{
  "hash": "8d6568c42923c5f81da0ea09f10326ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"時系列データ分析：ARIMA・介入分析・音声波形\"\nbibliography: references_timeseries.bib\nnocite: |\n  @hyndman2021, @shin2016, @shumway2017, @ortega2005, @verspoor2008, @gu2015, @debot2007, @turner2021, @bernal2017, @li2025, @fant1960, @boersma2023, @thomas2007, @cohen1988_ts\n---\n\n## はじめに\n\n言語の学習も、音声の産出も、**時間の中で**展開します。学習者のテストスコアは週ごとに変動しながら徐々に上昇し、教授法の変更は突然のジャンプや緩やかなカーブとして現れます。一方、人間の声は毎秒16,000回以上の振動として記録され、そこには声帯の周期的振動（ピッチ）や声道の共鳴（フォルマント）が時間的パターンとして埋め込まれています。\n\n本章では、このような**時間的パターン**を適切に分析するための枠組みとして、時系列分析 (time series analysis) を扱います。具体的には、以下の3つのリサーチクエスチョンを念頭に置きながら進めます。\n\n1. **介入の効果検証**：「ある高校で extensive reading プログラムを導入した。毎週の語彙テストの推移を見ると、導入後に成績が上がっているように見える。だが、それは介入の効果なのか、それとも元々の上昇傾向が続いただけなのか？」\n\n2. **スコアの予測と傾向の把握**：「ある語学学校のコホートが月次でTOEFL iBTを受験している。12ヶ月を過ぎたあたりでスコアが頭打ちになったように見える。これは本当の天井効果か、それとも単なるノイズか？今後のスコアはどう推移すると予測できるか？」\n\n3. **音声特徴の時間変動**：「学習者の音読データからF0（基本周波数）の時間変化を追いたい。流暢性が向上するにつれて、F0の変動パターンはどう変化するか？」\n\nこれらの問いに共通するのは、**データが時間順に並んでおり、隣接する観測値が互いに関連している**という性質です。第1章で学んだt検定や第2章のANOVAは、各データ点が**独立**であることを前提としています。しかし、時系列データではこの前提が成り立ちません。今週の語彙テストで85点を取った学生は、来週もおそらく85点前後を取るでしょう — クラス平均の75点にいきなり戻るわけではありません。この週と週の間の「粘り」を**自己相関** (autocorrelation) と呼びます。自己相関を無視すると、標準誤差が過小推定され、p値が楽観的になりすぎるという深刻な問題が生じます。\n\n時系列分析は、応用言語学において重要な研究手法でありながら、まだ十分に活用されていません。@ortega2005 は SLA における時系列研究デザインの重要性を早くから指摘し、@verspoor2008 は動的システム理論 (Dynamic Systems Theory) の観点から、第二言語発達が非線形で、進歩と後退、急激な変化と停滞を繰り返すことを示しました。こうした複雑な時間的パターンを捉えるには、前後比較のt検定ではなく、時系列に特化した手法が必要です。@gu2015 による TOEFL Junior の縦断的妥当性検証研究でも反復測定ANOVAが用いられましたが、ARIMA等の時系列モデルを適用すれば、自己相関やトレンドをより適切に扱えた可能性があります。\n\n::: {.callout-tip}\n\n本章は大きく4つのパートで構成されています。\n\n- **Part A（セクション2–5）**：テストスコアの時系列を題材に、時系列データの基本概念（定常性・自己相関・分解・階差）と ARIMA モデルの考え方を学びます。\n- **Part B（セクション6）**：**介入時系列分析 (ITS)** — 本章のハイライトです。教育介入の効果をARIMAXモデルで検証する方法を詳しく解説します。英語教育研究者にとって最も実用的なセクションです。\n- **Part C（セクション7–8）**：発展的な話題として、欠測値の処理、多変量時系列 (VAR)、dynamic time warping (DTW)、隠れマルコフモデル (HMM)、状態空間モデル (SSM)、ベイズ的時系列分析を扱います。\n- **Part D（セクション9–12）**：テストスコアの「マクロな時系列」から音声波形の「ミクロな時系列」へ橋渡しし、英語母音の合成・F0推定・スペクトル分析・wav処理・Praat連携を実演します。\n\n初学者は **Part A → Part B** を優先して読んでください。Part BのITS分析は、介入研究が主流の英語教育分野で直ちに活用できます。\n:::\n\n::: {.callout-important}\n### この章の到達目標\n\n本章を読み終えた後、以下のことができるようになることを目指します。\n\n1. 時系列データの**定常性**を視覚的・統計的（ADF/KPSS検定）に判断し、適切な差分回数を決定できる\n2. `auto.arima()` で ARIMA モデルを構築し、**残差診断**（ACF・Ljung-Box検定）でモデルの妥当性を評価できる\n3. **介入時系列分析（ITS / ARIMAX）**でステップ・ランプ効果を推定し、反事実プロットと標準化効果量を報告できる\n4. 研究目的に応じて ARIMA・ETS・SSM・VAR・ベイズ時系列を**使い分ける判断基準**を説明できる\n5. 音声波形から**自己相関法・ケプストラム法**でF0を推定する原理を理解し、テストスコアの自己相関分析との共通点を説明できる\n:::\n\n::: {.callout-note}\n### クイックリファレンス：研究目的別の分析手法\n\n| 研究の問い | データの種類 | まず試す手法 | 発展的な手法 |\n|---|---|---|---|\n| スコアの予測・傾向把握 | 単変量時系列 | `auto.arima()` / `ets()` | TBATS（複数季節性） |\n| 教育介入の効果検証 | 介入前後の時系列 | **ITS: ARIMAX**（本章のハイライト） | 統制群付きITS (CITS) |\n| 変数間の時間的因果 | 多変量時系列 | VAR + Granger因果性 | VECM（共和分） |\n| 学習曲線どうしの時間ずれ比較 | 2系列の軌跡比較 | DTW（`dtw::dtw()`） | DTWクラスタリング（`dtwclust`） |\n| 潜在状態（停滞期/伸長期）の推定 | レジーム切替を含む時系列 | HMM（`depmixS4`） | ベイズHMM / 状態空間HMM |\n| 欠測あり・測定誤差を分離 | ギャップのある時系列 | SSM (KFAS) | ベイズSSM (brms) |\n| 小標本＋事前知識あり | 短い時系列（<30時点） | brms（ベイズ推定） | GP による非線形トレンド |\n| F0・フォルマントの分析 | 高頻度音声信号 | ACF / ケプストラム / Praat | GAMM（トラジェクトリ比較） |\n\n初学者は **ITS: ARIMAX**（表の2行目）を最優先で習得してください。\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse,    # データ操作・可視化（dplyr, ggplot2, tidyr 等）\n\n  forecast,     # ARIMA, ETS, auto.arima, 予測, ACF/PACF\n  tseries,      # ADF検定（adf.test）\n  gt,           # 表の作成・整形\n  DT,           # インタラクティブデータテーブル\n  KFAS,         # 状態空間モデル（カルマンフィルタ）\n  brms,         # ベイズ時系列（Stan経由のARMA/GP）\n  vars,         # VARモデル（多変量時系列・Granger因果性）\n  dtw,          # Dynamic Time Warping（時間ずれを許容した系列整列）\n  depmixS4,     # 隠れマルコフモデル（HMM）\n  urca,         # KPSS検定, 共和分検定\n  strucchange,  # 構造変化点の検出（breakpoints）\n  imputeTS,     # 欠測値の補間（Kalmanフィルタ等）\n  tuneR,        # wav読み込み・書き出し・基本処理\n  seewave,      # 音声分析（スペクトログラム, F0, スペクトル特徴量）\n  rPraat,       # Praat TextGridの読み書き\n  phonTools     # LPC（線形予測符号化）によるフォルマント推定\n)\ntheme_set(theme_bw(base_size = 12))\ntheme_update(legend.position = \"bottom\")\nset.seed(2024)\n```\n:::\n\n\n## 分析の流れ\n\n時系列データを手にしたときは、「何を知りたいか」に応じて分析経路を分けます。将来予測が目的なら ARIMA / ETS / TBATS を候補にし、季節性がある場合は SARIMA や seasonal ETS を優先します。介入効果の検証が目的なら ITS（ARIMAX）に進み、残差診断と効果量報告を重視します。変数間の時間的因果を調べる場合は VAR / Granger 因果性検定を使います。最終的には AICc や時系列 CV（tsCV）でモデル比較を行い、予測と報告につなげます。\n\n::: {.callout-note}\n英語教育研究では、新しい教授法やカリキュラムの効果を検証する**介入研究**が多く行われます。そのため、多くの読者は「介入の効果検証」のパス（→ ITS / ARIMAX）に進むことになるでしょう。本章のセクション6で詳しく扱います。\n:::\n\n## データの作成：英語教育研究のシナリオ\n\n本章では、AirPassengers のような汎用データセットではなく、英語教育研究に直接関連する**3つのシミュレーションデータ**を使います。いずれも架空のデータですが、実際の研究で見られるパターンを反映しています。\n\n### Dataset 1: 週次語彙テストスコア（40週）\n\nある大学の英語プログラムで、20項目の語彙クイズを毎週実施しています。1年間（40週）にわたるクラス平均スコアを観察します。このデータには以下の特徴があります：\n\n- **緩やかな上昇トレンド**：学習が進むにつれてスコアが向上\n- **試験期間のディップ**：中間試験（第15–16週）と期末試験（第30–31週）の前後でスコアが一時的に低下（学生が語彙学習より試験対策を優先するため）\n- **自己相関**：先週のスコアが今週のスコアに影響する（AR(1)的な構造）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_weeks <- 40\ntrend <- seq(0, 6, length.out = n_weeks)           # 緩やかな上昇（6点分）\nexam_dip <- -2.5 * (dnorm(1:n_weeks, 15, 2) + dnorm(1:n_weeks, 31, 2)) / dnorm(0, 0, 2)\nar_noise <- as.numeric(arima.sim(n = n_weeks, list(ar = 0.55), sd = 1.2))\nvocab_scores <- 10 + trend + exam_dip + ar_noise    # ベースライン10点（/20）\nvocab_scores <- pmax(pmin(vocab_scores, 20), 0)     # 0–20に制限\nvocab_ts <- ts(vocab_scores, frequency = 1)\n\nautoplot(vocab_ts) +\n  labs(title = \"Weekly vocabulary quiz scores (40 weeks)\",\n       x = \"Week\", y = \"Score (/20)\") +\n  geom_vline(xintercept = c(15, 31), linetype = \"dashed\", alpha = 0.4) +\n  annotate(\"text\", x = 15, y = max(vocab_scores) - 0.5, label = \"Midterm\", size = 3) +\n  annotate(\"text\", x = 31, y = max(vocab_scores) - 0.5, label = \"Final\", size = 3)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/create-vocab-data-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**図の読み方**：\n\n- **y軸（Score /20）**：20点満点の語彙テストのクラス平均スコア。ベースラインは約10点。\n- **全体的な上昇トレンド**：左から右に向かってスコアが上がっており、40週間の学習効果を反映しています。\n- **破線（Midterm / Final）**：中間試験（第15週）と期末試験（第31週）の時期。この前後でスコアが一時的に下がっています（試験対策のため語彙学習の優先度が下がる）。\n- **ギザギザした変動**：AR(1)ノイズによるもの。先週のスコアが今週に影響する「自己相関」を反映しています。\n\n### Dataset 2: 月次TOEFL風スコア（24ヶ月、介入あり）\n\nある語学学校が、30名のコホートの平均TOEFL iBTスコアを24ヶ月間追跡しています。**12ヶ月目にカリキュラムを刷新**し、統合スキル重視の新プログラムに切り替えました。このデータは、介入時系列分析 (ITS) のデモンストレーションに使います。\n\n- **介入前（月1–12）**：ベースライン約65点、微増トレンド（+0.3点/月）、月次の自己相関\n- **介入後（月13–24）**：ステップ変化（即座に+5点）＋ 緩やかなランプ効果（+0.5点/月の追加上昇）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_months <- 24\nintervention_point <- 12\nmonths <- 1:n_months\n\n# 共通のAR(1)ノイズ\nar_toefl <- as.numeric(arima.sim(n = n_months, list(ar = 0.45), sd = 2))\n\n# 介入前後のスコア構築\nbaseline <- 65\npre_trend <- 0.3 * months\nstep_effect <- ifelse(months > intervention_point, 5, 0)\nramp_effect <- ifelse(months > intervention_point, 0.5 * (months - intervention_point), 0)\n\ntoefl_scores <- baseline + pre_trend + step_effect + ramp_effect + ar_toefl\ntoefl_ts <- ts(toefl_scores, frequency = 12, start = c(2022, 1))\n\nautoplot(toefl_ts) +\n  labs(title = \"Monthly TOEFL-like scores (24 months, intervention at month 12)\",\n       x = \"Time\", y = \"Score\") +\n  geom_vline(xintercept = 2022 + 12/12, linetype = \"dashed\", color = \"red\", linewidth = 0.8) +\n  annotate(\"text\", x = 2023.1, y = max(toefl_scores) - 1,\n           label = \"Curriculum change\", color = \"red\", size = 3.5)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/create-toefl-data-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**図の読み方**：\n\n- **赤い破線（Curriculum change）**：12ヶ月目のカリキュラム変更時点。ここを境にスコアの水準が変わっているかどうかが分析の焦点です。\n- **介入前（左半分）**：ベースライン約65点からの緩やかな上昇（+0.3点/月程度）。\n- **介入後（右半分）**：スコアが一段階ジャンプし（ステップ効果）、さらに上昇の傾きが急になっているように見えます（ランプ効果）。\n- **重要な注意**：このような視覚的パターンだけでは介入効果を確認できません。自己相関やトレンドの影響を統計的に切り分けるITS分析（セクション6）が必要です。\n\n### Dataset 3: 週次読解流暢性 WPM（30週、季節性あり）\n\nEFLプログラムで、学生の音読流暢性（words per minute, WPM）を毎週測定しています。30週間のデータには**周期的な低下パターン**が見られます：中間試験と期末試験の準備期間に音読練習が減り、WPMが一時的に下がります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_fluency <- 30\ntrend_f <- seq(0, 15, length.out = n_fluency)      # 全体的な上昇（15 WPM分）\n# 10週周期の季節的パターン（試験準備期間のディップ）\nseasonal_f <- -5 * sin(2 * pi * (1:n_fluency) / 10)\nar_f <- as.numeric(arima.sim(n = n_fluency, list(ar = 0.4), sd = 3))\nfluency_wpm <- 100 + trend_f + seasonal_f + ar_f   # ベースライン100 WPM\nfluency_ts <- ts(fluency_wpm, frequency = 10)       # 周期10\n\nautoplot(fluency_ts) +\n  labs(title = \"Weekly reading fluency (WPM, 30 weeks)\",\n       x = \"Week\", y = \"Words per Minute\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/create-fluency-data-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### 3つのデータセットの概要\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Dataset = c(\"Vocabulary quiz\", \"TOEFL-like scores\", \"Reading fluency (WPM)\"),\n  N = c(length(vocab_ts), length(toefl_ts), length(fluency_ts)),\n  Mean = round(c(mean(vocab_ts), mean(toefl_ts), mean(fluency_ts)), 1),\n  SD = round(c(sd(vocab_ts), sd(toefl_ts), sd(fluency_ts)), 1),\n  Min = round(c(min(vocab_ts), min(toefl_ts), min(fluency_ts)), 1),\n  Max = round(c(max(vocab_ts), max(toefl_ts), max(fluency_ts)), 1)\n) |>\n  gt() |>\n  tab_header(title = \"Descriptive statistics of simulated datasets\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Descriptive statistics of simulated datasets\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrr}\n\\toprule\nDataset & N & Mean & SD & Min & Max \\\\ \n\\midrule\\addlinespace[2.5pt]\nVocabulary quiz & 40 & 12.0 & 2.9 & 6.7 & 18.8 \\\\ \nTOEFL-like scores & 24 & 73.1 & 6.4 & 63.5 & 83.7 \\\\ \nReading fluency (WPM) & 30 & 107.2 & 7.8 & 90.9 & 121.1 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-important}\n#### `ts()` の `frequency` パラメータ設定ガイド\n\n`ts()` オブジェクトを作成する際の `frequency` は、**1年間あたりの観測回数**を指定します。教育データでは以下が一般的です：\n\n| データの頻度 | `frequency` | 例 |\n|---|---|---|\n| 年次（年1回テスト） | `1` | 各学年末の学力テスト |\n| 学期ごと（年2–3回） | `2` または `3` | 前期・後期テスト |\n| 月次 | `12` | 月次のTOEFLスコア推移 |\n| 隔週 | `26` | 隔週の小テスト |\n| 週次 | `52` | 週次の語彙テスト |\n| 日次（授業日のみ） | `5` ×学期週数 を年換算 | 毎日の出席・課題提出 |\n\n**注意**：週次データを `frequency = 1` で作成すると、季節性の検出・分解ができなくなります。学期内の周期パターン（例：10週ごとの試験サイクル）がある場合は、そのサイクル長を `frequency` に設定してください（上記 Dataset 3 では `frequency = 10`）。\n\n`frequency` がわからない場合は、`findfrequency(y)` で自動推定できます（`forecast`パッケージ）。\n:::\n\n::: {.callout-warning}\n#### 教育データ特有の注意点\n\n教育データを時系列として分析する際に、自然科学のデータにはない特有の問題があります。\n\n1. **学校暦による構造的欠測**：春休み・夏休みの期間はデータが存在しません。欠測として補間するか、休暇期間を除外して「授業週」で連番を振るかは研究目的に応じて判断してください。補間する場合は `imputeTS::na_kalman()` が推奨です（セクション7参照）。\n\n2. **天井・床効果 (ceiling/floor effects)**：満点20点のテストでは、上位の学生が天井に張り付き、トレンドが人工的に平坦化します。Box-Cox変換（`lambda` パラメータ）や、項目応答理論（第11章）で能力推定値を使うことで対処できます。\n\n3. **練習効果 (practice effects)**：同じテストを繰り返し使用すると、学習効果ではなくテスト慣れによるスコア上昇が混入します。パラレルフォーム（複数バージョン）の使用や、IRT等化でこの問題を軽減できます。\n\n4. **コホートの構成変化**：学生の転入・転出によりグループの構成が変化します。特に学年変わりでクラス替えがある場合、前後のスコアは異なる集団のものです。分析時には、同一学生の追跡データか集計データかを明確にしてください。\n\n5. **イベント的外れ値**：文化祭・体育祭の週、インフルエンザによる学級閉鎖、自然災害による休校など、教育特有のイベントでスコアが突然変動します。これらは外れ値として除外するのではなく、ITSの**パルスダミー**としてモデルに組み込むのが適切です。\n:::\n\n## 時系列データの特性と分解\n\n### なぜt検定や通常の回帰が使えないのか\n\n::: {.callout-important}\n#### 自己相関の問題\n\n通常の回帰分析（第4章）やt検定（第1章）は、各データ点が**独立に**抽出されていることを前提とします。しかし時系列データでは、今日の値は昨日の値に引きずられます。たとえば、ある学生が今週の語彙テストで高得点を取った場合、来週もおそらく高い点数を取るでしょう。\n\nこの**自己相関** (autocorrelation) を無視して通常の回帰を当てはめると：\n\n- **標準誤差が過小推定**される → p値が本来よりも小さくなる\n- **有意でないはずの効果が有意に見える**（第一種の過誤率の上昇）\n- 予測区間が狭すぎて実際の変動を捉えられない\n\n時系列分析の手法（ARIMA等）は、この自己相関を**明示的にモデルに組み込む**ことで正しい推論を可能にします。\n:::\n\n### 定常性 (stationarity)\n\n時系列分析で最も重要な概念の一つが**定常性**です。直感的に言えば、定常な時系列とは「統計的な性質が時間によって変わらない」系列のことです。\n\n比喩で考えてみましょう。弓道の射手を想像してください。\n\n- **定常**：熟練の射手が的を狙っている。矢は的の中心周辺に、一定の散らばりで集まる。100本目でも500本目でも、命中パターンは変わらない。\n- **非定常（トレンド）**：初心者が練習中。最初は的を外すが、徐々に上達して中心に近づいていく。矢の平均的な位置が時間とともに移動する。\n- **非定常（分散変化）**：射手の集中力が不安定。調子のいい日は集中して散らばりが小さく、悪い日は大きくばらつく。\n\nより正確には、**弱定常性** (weak stationarity) は以下を要求します：\n\n- 平均が時間に依らず一定\n- 分散が時間に依らず一定\n- 自己共分散が時点間の差（ラグ）のみに依存\n\n::: {.panel-tabset}\n#### 定常な系列\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AR(1)の定常的なノイズ（トレンドを除いた語彙テストの残差に相当）\nstationary_ex <- arima.sim(n = 100, list(ar = 0.5), sd = 1)\nautoplot(ts(stationary_ex)) +\n  labs(title = \"Stationary series (AR(1), constant mean & variance)\",\n       x = \"Time\", y = \"Value\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"blue\", alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/stationary-demo-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n#### 非定常（トレンドあり）\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 語彙テストの生データ（上昇トレンドがあるので非定常）\nautoplot(vocab_ts) +\n  labs(title = \"Non-stationary: vocabulary scores with upward trend\",\n       x = \"Week\", y = \"Score (/20)\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/nonstationary-trend-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n#### 非定常（分散変化）\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 分散が時間とともに増大する例\nchanging_var <- cumsum(rnorm(100)) * seq(0.5, 2, length.out = 100)\nautoplot(ts(changing_var)) +\n  labs(title = \"Non-stationary: increasing variance over time\",\n       x = \"Time\", y = \"Value\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/nonstationary-variance-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n:::\n\n### 単位根検定（ADF検定）\n\n系列が定常かどうかを統計的に検定するには、**拡張ディッキー＝フラー検定** (Augmented Dickey-Fuller test, ADF test) を使います。帰無仮説は「単位根が存在する（＝非定常である）」なので、p値が小さければ定常と判断します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 生データ（非定常が疑われる）\nadf_raw <- adf.test(vocab_ts)\n\n# 1階差分（トレンド除去後）\nadf_diff <- adf.test(diff(vocab_ts))\n\ntibble(\n  Series = c(\"Raw vocab scores\", \"Differenced (diff)\"),\n  ADF_statistic = round(c(adf_raw$statistic, adf_diff$statistic), 3),\n  p_value = round(c(adf_raw$p.value, adf_diff$p.value), 4),\n  Conclusion = c(\n    ifelse(adf_raw$p.value < 0.05, \"Stationary\", \"Non-stationary (unit root)\"),\n    ifelse(adf_diff$p.value < 0.05, \"Stationary\", \"Non-stationary (unit root)\")\n  )\n) |>\n  gt() |>\n  tab_header(title = \"ADF test: raw vs. differenced vocabulary scores\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ADF test: raw vs. differenced vocabulary scores\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrl}\n\\toprule\nSeries & ADF\\_statistic & p\\_value & Conclusion \\\\ \n\\midrule\\addlinespace[2.5pt]\nRaw vocab scores & -2.742 & 0.2821 & Non-stationary (unit root) \\\\ \nDifferenced (diff) & -3.284 & 0.0889 & Non-stationary (unit root) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-note}\nADF検定の結果を読むときの注意点：p値が小さい（例: < 0.05）→「単位根を棄却 → 定常と判断」。p値が大きい → 「非定常の可能性あり → 差分を取って再検定」。この検定は系列の長さや次数の設定に敏感なので、**視覚的な確認（プロット）と併用**するのが安全です。なお、ADF検定は小標本（$n < 30$ 程度）では検出力が低いため、教育データでは結果を過信しないことが重要です。\n:::\n\n#### KPSS検定との併用\n\nADF検定の帰無仮説は「非定常」ですが、**KPSS検定** (Kwiatkowski-Phillips-Schmidt-Shin) の帰無仮説は逆に「定常」です。FPP3 [@hyndman2021] は、両方を併用することを推奨しています。\n\n| ADF | KPSS | 結論 |\n|-----|------|------|\n| p < 0.05（定常）| p > 0.05（定常）| **定常** |\n| p > 0.05（非定常）| p < 0.05（非定常）| **非定常 → 差分が必要** |\n| 食い違う | 食い違う | より慎重な判断が必要 |\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# KPSS検定（帰無仮説：定常）\nkpss_raw <- urca::ur.kpss(as.numeric(vocab_ts), type = \"tau\")\n\n# ADF と KPSS の結果を並べて表示\ntibble(\n  Test = c(\"ADF (H0: non-stationary)\", \"KPSS (H0: stationary)\"),\n  Statistic = c(round(adf_raw$statistic, 3),\n                round(kpss_raw@teststat, 3)),\n  Conclusion = c(\n    ifelse(adf_raw$p.value < 0.05, \"Reject H0 → Stationary\", \"Fail to reject → possibly non-stationary\"),\n    ifelse(kpss_raw@teststat > kpss_raw@cval[2], \"Reject H0 → Non-stationary\", \"Fail to reject → Stationary\")\n  )\n) |>\n  gt() |>\n  tab_header(title = \"ADF vs KPSS: complementary stationarity tests\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ADF vs KPSS: complementary stationarity tests\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrl}\n\\toprule\nTest & Statistic & Conclusion \\\\ \n\\midrule\\addlinespace[2.5pt]\nADF (H0: non-stationary) & -2.742 & Fail to reject → possibly non-stationary \\\\ \nKPSS (H0: stationary) & 0.090 & Fail to reject → Stationary \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# ndiffs() で必要な差分回数を自動判定\ncat(\"Recommended differencing (KPSS-based):\", forecast::ndiffs(vocab_ts, test = \"kpss\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecommended differencing (KPSS-based): 1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ncat(\"Recommended differencing (ADF-based):\", forecast::ndiffs(vocab_ts, test = \"adf\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecommended differencing (ADF-based): 1 \n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n#### ADF検定とKPSS検定の結果が食い違う場合\n\n**症状**：ADF検定は「定常」と言うがKPSS検定は「非定常」と言う（あるいはその逆）。\n\n**原因**：系列が定常と非定常の境界領域にある場合、検出力の異なる2つの検定が異なる結論を出すことがあります。特に $n < 40$ の教育データではよく起こります。\n\n**対処法**：\n\n1. まず**プロットを目視**で確認（明らかなトレンドや分散変化があるか）\n2. `ndiffs()` の結果（自動判定）を参考にする\n3. 迷った場合は**差分を1回取る**のが安全（定常な系列を差分しても大きな問題は生じないが、非定常な系列をそのまま使うと推論が不正確になる）\n4. 過剰差分の兆候（ACFラグ1の大きな負のスパイク）がないかチェック\n:::\n\n### 時系列の分解\n\n時系列は、**トレンド** (trend)、**季節成分** (seasonal)、**残差** (remainder) に分解できます。これは「全体的な方向性」「繰り返しのパターン」「説明できないノイズ」を分離する操作です。\n\nDataset 3（読解流暢性）は試験周期に応じた季節的パターンがあるので、分解に適しています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstl_fluency <- stl(fluency_ts, s.window = \"periodic\")\nautoplot(stl_fluency) +\n  labs(title = \"STL decomposition: reading fluency (WPM)\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/stl-decompose-fluency-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-tip}\n#### STLのパラメータ\n\n`s.window = \"periodic\"` は季節パターンが全期間で同一であると仮定します。教育データでは試験日程が年度によって微妙にずれることがあるため、数値を指定する（例: `s.window = 7`）と季節パターンの緩やかな変化を許容できます。`t.window` はトレンドの平滑化の窓幅を制御します。\n:::\n\n**STL分解結果の読み方**：\n\n| パネル | 意味 | 確認ポイント | この例では |\n|--------|------|-------------|-----------|\n| **data** | 生の時系列 | 全体的な形状を把握 | 30週間のWPM。上昇しながら波打つ |\n| **trend** | 長期的な方向性 | 単調増加/減少/プラトー？ | 30週で約15 WPMの上昇（学習効果） |\n| **seasonal** | 繰り返しの周期パターン | 一貫した形状か？ | 約10週周期の上下動（試験ディップ） |\n| **remainder** | 説明できないランダム変動 | パターンがないこと、分散が一定であること | ゼロ付近でランダムに散在 |\n| **右側のスケールバー** | 各成分の相対的な大きさ | どの成分が支配的か比較 | バーが短い成分ほど変動が大きい |\n\n**スケールバーの読み方のコツ**：4つのパネルの右側にある灰色のバーの長さは、それぞれの成分の縦軸のスケールに対応しています。バーが短い（= 縦軸のレンジが広い）ほど、その成分の変動幅が大きいことを意味します。trend と seasonal のバーを比較して、どちらが支配的かを判断してください。\n\n::: {.callout-note}\n#### 加法分解と乗法分解\n\n季節変動の振幅が**一定**なら加法分解 ($y_t = T_t + S_t + R_t$)、振幅がトレンドに**比例**して大きくなるなら乗法分解（あるいは対数変換後に加法分解）が適します。教育データでは多くの場合、加法分解で十分です。`stl()` は加法分解を行います。\n:::\n\n### 階差（差分）\n\n**階差** (differencing) は、非定常な系列を定常化するための基本操作です。直感的には、「高度計の読み」を「上昇率」に変換する操作と同じです。実際のスコア（何点か？）ではなく、「先週からの変化量」（何点上がった/下がったか？）に注目します。\n\n$$\\Delta y_t = y_t - y_{t-1}$$\n\nこの操作でトレンドが除去されます。季節性がある場合は、**季節差** ($y_t - y_{t-s}$, sは周期) も取ります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- autoplot(vocab_ts) +\n  labs(title = \"Original: vocabulary scores\", x = \"Week\", y = \"Score\")\np2 <- autoplot(diff(vocab_ts)) +\n  labs(title = \"After 1st differencing (trend removed)\", x = \"Week\", y = \"Change in score\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"blue\", alpha = 0.5)\n\ngridExtra::grid.arrange(p1, p2, ncol = 1)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/differencing-demo-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n差分後の系列は**平均がほぼ0の周りで安定して振動**しており、定常に近いことが視覚的に確認できます。ARIMAの「I」(Integrated) は、この差分操作を何回行ったかを表します。\n\n::: {.callout-warning}\n#### 過剰差分 (over-differencing) に注意\n\n差分は1回で十分な場合がほとんどです。2回以上差分を取ると**人工的な負の自己相関**が導入され、モデルの推定を不安定にします。過剰差分の兆候は、差分後のACFのラグ1に**大きな負のスパイク**（-0.5前後）が現れることです。`forecast::ndiffs()` で適切な差分回数を自動判定できます。\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# 過剰差分のデモ\nd1 <- diff(vocab_ts)               # 1回差分（適切）\nd2 <- diff(vocab_ts, differences = 2)  # 2回差分（過剰の可能性）\n\np_d1 <- ggAcf(d1) + labs(title = \"ACF: 1st diff (appropriate)\")\np_d2 <- ggAcf(d2) + labs(title = \"ACF: 2nd diff (over-differenced?)\")\ngridExtra::grid.arrange(p_d1, p_d2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/overdiff-demo-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n\n### ACF/PACF と AR/MA の直感\n\nARIMAモデルの核心は、**AR** (Autoregressive) と **MA** (Moving Average) の2つの成分です。まず直感的に理解しましょう。\n\n::: {.callout-tip}\n#### AR と MA のアナロジー\n\n- **AR（自己回帰）**：**振り子**の動き。振り子の現在の位置は、直前の位置に引きずられる。スコアの文脈では、「先週85点だったから、今週も85点に近いだろう」という慣性。AR係数が大きいほど慣性が強く、過去の値に強く依存します。\n\n- **MA（移動平均）**：**サーモスタット**の動き。設定温度を目指して、直前の予測誤差を修正する。「先週のモデル予測が2点高すぎたから、今週はその分を差し引こう」という修正メカニズム。\n\n- **I（和分 / 積分）**：差分を取ってからAR+MAを当てはめる。ARIMA(1,1,0)は「1回差分してAR(1)を適用」の意味。\n\n- **ARIMA(p, d, q)**：p = AR次数（何ラグ前まで見るか）、d = 差分の回数、q = MA次数（何期前の誤差まで使うか）。\n:::\n\n**ACF** (自己相関関数) と **PACF** (偏自己相関関数) のプロットは、AR/MAの次数を見極める手がかりになります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_acf <- ggAcf(diff(vocab_ts)) + labs(title = \"ACF: differenced vocabulary scores\")\np_pacf <- ggPacf(diff(vocab_ts)) + labs(title = \"PACF: differenced vocabulary scores\")\ngridExtra::grid.arrange(p_acf, p_pacf, ncol = 1)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/acf-pacf-vocab-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-tip}\n#### ACF/PACF の読み方（次数同定のルール）\n\n| パターン | ACF | PACF | 示唆するモデル |\n|----------|-----|------|----------------|\n| ACFが指数的に減衰、PACFがラグpで打ち切り | 緩やかに減衰 | p期で急に0に | **AR(p)** |\n| ACFがラグqで打ち切り、PACFが指数的に減衰 | q期で急に0に | 緩やかに減衰 | **MA(q)** |\n| 両方とも緩やかに減衰 | — | — | **ARMA(p,q)** を検討 |\n\nただし、実務では `auto.arima()` による自動同定を基本とし、ACF/PACFは補助的な確認に使います。\n:::\n\n#### シミュレーションでAR/MAのパターンを体験\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AR(1): PACFがラグ1で切れる\nsim_ar1 <- arima.sim(n = 200, list(ar = 0.7))\n# MA(1): ACFがラグ1で切れる\nsim_ma1 <- arima.sim(n = 200, list(ma = 0.7))\n\npar(mfrow = c(2, 2))\nacf(sim_ar1, main = \"ACF of AR(1): gradual decay\")\npacf(sim_ar1, main = \"PACF of AR(1): cuts off at lag 1\")\nacf(sim_ma1, main = \"ACF of MA(1): cuts off at lag 1\")\npacf(sim_ma1, main = \"PACF of MA(1): gradual decay\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/simulate-ar-ma-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n## ARIMAモデルの基本実装\n\n### 手動同定 → 推定 → 診断\n\nDataset 1（語彙テスト）を使って、ARIMAモデルを手動で構築するプロセスを一歩ずつ進めます。\n\n**Step 1: 時系列をプロットして特徴を把握**\n\n上昇トレンドがあり、試験期間にディップがある。非定常の可能性が高い。\n\n**Step 2: 差分を取って定常化し、ADF検定**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1階差分\nd_vocab <- diff(vocab_ts)\nadf.test(d_vocab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  d_vocab\nDickey-Fuller = -3.2839, Lag order = 3, p-value = 0.08893\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n**Step 3: ACF/PACF で候補次数を確認**\n\n差分後の系列のACF/PACFを確認します（上のセクションで既に表示済み）。PACFがラグ1で有意 → AR(1)が候補。\n\n**Step 4: モデルの推定**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ARIMA(1,1,0): 1回差分してAR(1)を適用\nfit_vocab_manual <- Arima(vocab_ts, order = c(1, 1, 0))\nfit_vocab_manual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: vocab_ts \nARIMA(1,1,0) \n\nCoefficients:\n          ar1\n      -0.2309\ns.e.   0.1549\n\nsigma^2 = 2.244:  log likelihood = -70.62\nAIC=145.24   AICc=145.57   BIC=148.57\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n#### 出力の読み方\n\n`Arima()` の出力には以下の情報が含まれます。\n\n- **ar1**：AR(1)の係数推定値。0.55 なら「差分後のスコアの55%が1期前の値に引きずられる」ことを意味します。\n- **sigma^2**：残差の分散（モデルが説明しきれないランダムな変動の大きさ）。\n- **AIC / AICc / BIC**：モデル選択基準。**AICc**（小標本補正情報量基準）は $\\text{AICc} = \\text{AIC} + \\frac{2k(k+1)}{n-k-1}$ で定義され、パラメータ数 $k$ に対するサンプルサイズ $n$ が小さいほど補正が大きくなります。教育データ（$n < 100$）ではAICよりAICcを使うのが安全です。AICcが小さいモデルほど「データへの当てはまり」と「パラメータの節約」のバランスが良いと判断されます。**AICcの差が2未満**なら実質的に同等、**10以上**なら強い差と解釈するのが目安です。\n- **log likelihood**：対数尤度（モデルのデータへの当てはまりの良さ）。AICcは「-2×対数尤度 + 補正項」なので、対数尤度が大きいほどAICcは小さくなります。\n\nなお、`forecast::Arima()` は基本Rの `arima()` のラッパーで、`model` 引数によるモデルの再適用や `lambda` による Box-Cox 変換に対応しています。本章では `Arima()` を推奨します。\n:::\n\n**Step 5: 残差診断**\n\n残差が**白色雑音** (white noise) かどうかを確認します。残差に自己相関が残っていたら、次数の見直しが必要です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheckresiduals(fit_vocab_manual)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/arima-step5-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from ARIMA(1,1,0)\nQ* = 10.738, df = 7, p-value = 0.1505\n\nModel df: 1.   Total lags used: 8\n```\n\n\n:::\n:::\n\n\n::: {.panel-tabset}\n#### 残差の時系列プロット\n\n`checkresiduals()` の上段パネルは残差の時系列プロットです。\n\n- **確認ポイント**：系統的なパターン（上昇・下降・波打ち）がないこと\n- **OK**：残差がゼロ付近でランダムに散在し、分散が時間を通じてほぼ一定\n- **NG**：残差にトレンドや周期パターンが見える → モデルが構造を捉えきれていない → 次数の見直しが必要\n\n#### 残差のACF\n\n中段パネルは残差の自己相関関数（ACF）です。\n\n- **確認ポイント**：青い破線（95%信頼限界）を超えるバーがないこと\n- **OK**：すべてのラグが破線内に収まっている → 残差に有意な自己相関なし\n- **NG**：特定のラグが破線を超えている → そのラグに対応するAR/MA項の追加を検討\n- 5%有意水準では、20本中1本程度は偶然超えることがあるため、1本だけなら過度に心配する必要はありません\n\n#### Ljung-Box検定\n\n下段の検定結果は残差の自己相関を**まとめて**検定します。\n\n- **帰無仮説**：ラグ1～$h$の自己相関がすべて0\n- **統計量**：$Q = n(n+2) \\sum_{k=1}^{h} \\frac{\\hat{\\rho}_k^2}{n-k}$（カイ二乗分布に従う）\n- **判断基準**：**p > 0.05 なら「残差に有意な自己相関なし」** → モデルは適切\n- ラグの数 $h$ は `checkresiduals()` が自動設定。FPP3 は非季節データで $h = \\min(10, T/5)$ を推奨\n\n#### 正規性チェック\n\n残差の正規性も確認しておくと予測区間の信頼性が向上します。\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# 追加の残差診断\nresid_manual <- residuals(fit_vocab_manual)\nshapiro.test(resid_manual)  # 正規性検定（p > 0.05 なら正規と判断）\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid_manual\nW = 0.97851, p-value = 0.6342\n```\n\n\n:::\n:::\n\n\n- **Shapiro-Wilk検定**：帰無仮説は「残差が正規分布に従う」。**p > 0.05 なら正規性を仮定してOK**\n- 正規性が棄却された場合は `forecast(..., bootstrap = TRUE)` でブートストラップ予測区間を使用してください\n:::\n\n\n### 自動同定 `auto.arima()`\n\n手動同定は教育的ですが、実務では `auto.arima()` による自動選択が効率的です。この関数は AICc を最小化するモデルを探索します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_vocab_auto <- auto.arima(vocab_ts)\nfit_vocab_auto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: vocab_ts \nARIMA(0,1,0) \n\nsigma^2 = 2.314:  log likelihood = -71.7\nAIC=145.4   AICc=145.5   BIC=147.06\n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(fit_vocab_auto)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/auto-arima-vocab-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from ARIMA(0,1,0)\nQ* = 11.788, df = 8, p-value = 0.1609\n\nModel df: 0.   Total lags used: 8\n```\n\n\n:::\n:::\n\n\n#### `auto.arima()` の重要パラメータ\n\n教育データでは、以下のパラメータを意識的に調整することで精度が向上します。\n\n| パラメータ | デフォルト | 推奨 | 理由 |\n|-----------|----------|------|------|\n| `stepwise` | `TRUE` | **`FALSE`** | ヒューリスティック探索ではなく全探索。教育データは短いので計算コストは小さい |\n| `approximation` | 自動 | `FALSE` | 150点超で近似計算に切り替わる。短い系列では影響なし |\n| `lambda` | `NULL` | `\"auto\"` | Box-Cox 変換パラメータの自動推定。分散が時間とともに変化する場合に有効 |\n| `max.p`, `max.q` | 5 | **2** | 小標本では高次モデルの推定が不安定。$n < 50$ なら次数を制限 |\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# stepwise=TRUE（デフォルト）vs FALSE（全探索）の比較\nfit_step <- auto.arima(vocab_ts, stepwise = TRUE)\nfit_full <- auto.arima(vocab_ts, stepwise = FALSE)\n\ntibble(\n  Search = c(\"Stepwise (default)\", \"Exhaustive\"),\n  Model = c(paste0(fit_step), paste0(fit_full)),\n  AICc = round(c(fit_step$aicc, fit_full$aicc), 1)\n) |>\n  gt() |>\n  tab_header(title = \"Stepwise vs exhaustive model search\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Stepwise vs exhaustive model search\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llr}\n\\toprule\nSearch & Model & AICc \\\\ \n\\midrule\\addlinespace[2.5pt]\nStepwise (default) & ARIMA(0,1,0) & 145.5 \\\\ \nExhaustive & ARIMA(0,1,1) & 145.4 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-important}\n#### 小サンプル（$n < 50$ 時点）での推奨設定\n\n教育データでは時点数が20〜40と少ないことが多く、これはARIMAの世界では**非常に小さい**サンプルサイズです。以下の設定を推奨します。\n\n```r\n# 小サンプル時の推奨\nfit_small <- auto.arima(y,\n  stepwise = FALSE,     # 全探索\n  max.p = 2, max.q = 2, # 高次モデルを制限\n  max.P = 1, max.Q = 1  # 季節項も制限\n)\n\n# ブートストラップ予測区間（正規性を仮定しない）\nfc_boot <- forecast(fit_small, h = 10, bootstrap = TRUE)\n```\n\n`forecast(..., bootstrap = TRUE)` は残差のブートストラップに基づく予測区間を計算し、正規分布の仮定が怪しい小標本で特に有効です。\n:::\n\n::: {.callout-warning}\n#### `arima()` が収束しない場合\n\n**症状**：`auto.arima()` や `Arima()` の実行時に `\"non-stationary AR part\"` や `\"possible convergence problem\"` の警告が表示される。\n\n**原因**：差分の過不足、初期値の問題、またはサンプルサイズに対してモデルが複雑すぎる。教育データ（$n < 50$ 時点）で特に発生しやすい。\n\n**修正手順**：\n\n1. `auto.arima(stepwise = FALSE)` で全探索を試みる\n2. `max.p = 2, max.q = 2` で次数を制限する\n3. `lambda = \"auto\"` でBox-Cox変換を検討する\n4. `ndiffs()` と `nsdiffs()` で適切な差分回数を確認する\n5. それでも不安定なら `ets()` や SSM（KFAS）への切り替えを検討\n:::\n\n### 予測と可視化\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfc_vocab <- forecast(fit_vocab_auto, h = 10)\nautoplot(fc_vocab) +\n  labs(title = \"Vocabulary quiz score forecast (next 10 weeks)\",\n       x = \"Week\", y = \"Score (/20)\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/forecast-vocab-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n予測区間（青い帯）は将来のスコアの**不確実性**を表します。時間が経つほど広がるのは、遠い未来ほど予測が不確実になるためです。この情報は、教育プログラムの評価や計画を立てる際に重要です。\n\n### ETS（指数平滑：Holt–Winters）\n\n指数平滑モデル (`ets`) は、**レベル** (level)、**傾き** (trend)、**季節成分** (seasonal) を**指数重み**で逐次更新するモデルです。過去の観測値に対して、より新しいものほど大きな重みを与えます。\n\n`ets()` の出力には **ETS(X, Y, Z)** という表記が使われます。\n\n| 位置 | 意味 | 選択肢 |\n|------|------|--------|\n| **X** (Error) | 誤差の構造 | A = 加法的, M = 乗法的 |\n| **Y** (Trend) | トレンドの構造 | N = なし, A = 加法的, A_d = 減衰加法 |\n| **Z** (Seasonal) | 季節性の構造 | N = なし, A = 加法的, M = 乗法的 |\n\n例えば **ETS(A, A, N)** は「加法的誤差・加法的トレンド・季節性なし」で、Holtの線形トレンドモデルに相当します。`ets()` はこれらの組み合わせを自動で探索し、AICcが最小のモデルを選択します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ets <- ets(fluency_ts)\nfit_ets\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nETS(A,N,N) \n\nCall:\nets(y = fluency_ts)\n\n  Smoothing parameters:\n    alpha = 0.9999 \n\n  Initial states:\n    l = 97.8396 \n\n  sigma:  4.827\n\n     AIC     AICc      BIC \n200.4192 201.3423 204.6228 \n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(fit_ets)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/ets-fluency-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from ETS(A,N,N)\nQ* = 15.041, df = 6, p-value = 0.01994\n\nModel df: 0.   Total lags used: 6\n```\n\n\n:::\n\n```{.r .cell-code}\nfc_ets <- forecast(fit_ets, h = 10)\nautoplot(fc_ets) + labs(title = \"ETS forecast: reading fluency (WPM)\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/ets-fluency-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### ETS出力の読み方\n\n| 出力要素 | 意味 | 確認ポイント |\n|---------|------|-------------|\n| **ETS(X, Y, Z)** | 選択されたモデル型（Error, Trend, Seasonal） | 上のETS表記テーブルと照合。例：ETS(A, A, A) = 加法的誤差・加法的トレンド・加法的季節 |\n| **alpha（平滑パラメータ：レベル）** | レベルの更新速度 | 0に近い → 過去の情報を重視（滑らか）。1に近い → 直近の観測値に追随（敏感） |\n| **beta（平滑パラメータ：傾き）** | トレンドの更新速度 | 0に近い → 傾きが安定。1に近い → 傾きが急変しやすい |\n| **gamma（平滑パラメータ：季節）** | 季節パターンの更新速度 | 0に近い → 季節パターン固定。1に近い → 季節パターンが毎周期変化 |\n| **Initial states** | 初期レベル・傾き | モデルの出発点。通常は自動推定 |\n| **sigma^2** | 残差分散 | ARIMAと同義。小さいほど当てはまりが良い |\n| **AICc** | 小標本補正情報量基準 | ARIMAのAICcと**直接比較可能**（同じデータ・同じ変換であれば） |\n:::\n\n::: {.callout-note}\n#### ETS と ARIMA の違い\n- **ETS** はレベル・傾き・季節を指数重みで更新する「平滑」型のモデル。構造が直感的で解釈しやすい。\n- **ARIMA** は差分＋ARMA で記述する「確率過程」型のモデル。残差の自己相関構造を明示的にモデル化する。\n- 多くのケースで予測性能は同等。強い季節＋滑らかなトレンド → ETS、差分で定常化しやすい → ARIMA、のように使い分けるか、**両方当ててAICc/残差/tsCVで比較**するのが現実的です。\n:::\n\n### モデル比較（AICc / 精度指標）\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dataset 3 で ARIMA と ETS を比較\nfit_arima_f <- auto.arima(fluency_ts)\nfit_ets_f <- ets(fluency_ts)\n\ntibble(\n  Model = c(\"auto.arima\", \"ets\"),\n  AICc = round(c(fit_arima_f$aicc, fit_ets_f$aicc), 1)\n) |>\n  gt() |>\n  tab_header(title = \"AICc comparison: ARIMA vs ETS (reading fluency)\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  AICc comparison: ARIMA vs ETS (reading fluency)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nModel & AICc \\\\ \n\\midrule\\addlinespace[2.5pt]\nauto.arima & 128.2 \\\\ \nets & 201.3 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\naccuracy(fit_arima_f) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Set\") |>\n  gt() |>\n  tab_header(title = \"ARIMA: accuracy metrics\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ARIMA: accuracy metrics\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrrr}\n\\toprule\nSet & ME & RMSE & MAE & MPE & MAPE & MASE & ACF1 \\\\ \n\\midrule\\addlinespace[2.5pt]\nTraining set & -0.01621015 & 3.378965 & 2.295672 & -0.02466688 & 2.112799 & 0.3887052 & 0.04956701 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\naccuracy(fit_ets_f) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Set\") |>\n  gt() |>\n  tab_header(title = \"ETS: accuracy metrics\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ETS: accuracy metrics\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrrr}\n\\toprule\nSet & ME & RMSE & MAE & MPE & MAPE & MASE & ACF1 \\\\ \n\\midrule\\addlinespace[2.5pt]\nTraining set & 0.4304233 & 4.663291 & 3.809111 & 0.3168505 & 3.558039 & 0.644962 & 0.1845749 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-note}\n#### 精度指標の読み方\n\n| 指標 | 正式名称 | 意味 | 小さいほど良い？ |\n|------|---------|------|:---------------:|\n| **ME** | Mean Error | 平均誤差（バイアス）。正なら過大予測、負なら過小予測 | **0に近い** |\n| **RMSE** | Root Mean Squared Error | 典型的な予測誤差の大きさ（元の単位：WPM） | はい |\n| **MAE** | Mean Absolute Error | 平均絶対偏差。外れ値の影響がRMSEより小さい | はい |\n| **MAPE** | Mean Absolute Percentage Error | パーセント誤差。値が0に近いデータでは不安定 | はい |\n| **MASE** | Mean Absolute Scaled Error | ナイーブ予測と比較した相対誤差。**< 1 ならナイーブ予測より良い** | はい |\n\n**2つのモデルの比較方法**：同じデータに対するRMSEやMASEを比較し、小さいモデルが予測性能で優れます。ただし、訓練データでの精度（in-sample accuracy）は過学習の影響を受けるため、次のtsCVによる**アウトオブサンプル評価**がより信頼できます。\n:::\n\n### 時系列クロスバリデーション（tsCV）\n\n過学習を防ぎ、モデルの**真の予測性能**を評価するには、tsCV（時系列クロスバリデーション）が有効です。学習データを過去→未来の順に展開し、1ステップ先の予測誤差を繰り返し計算します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_arima <- function(y, h) forecast(auto.arima(y), h = h)\nf_ets   <- function(y, h) forecast(ets(y), h = h)\n\ne_arima <- tsCV(fluency_ts, f_arima, h = 1)\ne_ets   <- tsCV(fluency_ts, f_ets,   h = 1)\n\ntibble(\n  Model = c(\"auto.arima\", \"ets\"),\n  MSE = round(c(mean(e_arima^2, na.rm = TRUE), mean(e_ets^2, na.rm = TRUE)), 2)\n) |>\n  gt() |>\n  tab_header(title = \"tsCV: 1-step-ahead MSE comparison\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  tsCV: 1-step-ahead MSE comparison\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nModel & MSE \\\\ \n\\midrule\\addlinespace[2.5pt]\nauto.arima & 37.47 \\\\ \nets & 28.22 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**tsCV結果の読み方**：MSE（Mean Squared Error）は1ステップ先の予測誤差の平均二乗です。MSEが小さいモデルほど予測性能が優れています。上の `accuracy()` による訓練データ精度と異なり、tsCVは**アウトオブサンプル**（未見のデータ）に対する精度なので、過学習の影響を受けにくく、より信頼できる比較です。MSEの差がわずかであれば、よりシンプルなモデルを選ぶのが安全です（パラメータ数が少ないほど安定）。\n\n::: {.callout-tip}\n#### tsCV の注意点\n- **データ漏洩** (leakage) を避けるため、常に「過去のみで学習→未来を予測」の順序を守ります。\n- 比較するモデルには**同じ前処理**（変換・差分）を適用して公平に評価します。\n:::\n\n## 介入時系列分析（ITS）\n\n::: {.callout-important}\n### 本章のハイライト\n\n介入時系列分析 (Interrupted Time Series, ITS) は、教育介入の効果を検証するための強力なクウェーシ実験デザインです。ランダム化比較試験 (RCT) が実施困難な教育現場で、「新しいカリキュラムを導入したことでスコアが変わったか」を統計的に評価できます。\n\n@turner2021 の品質基準ガイドに基づく4ステップ:\n\n1. **データの可視化と前処理**（トレンド・分散の確認、必要なら変換）\n2. **モデルの選択**（ARIMA + 介入ダミーの外生変数 = ARIMAX）\n3. **モデルの推定**（係数の推定と信頼区間）\n4. **残差診断**（白色性の確認）\n:::\n\n### なぜITSが英語教育研究に重要か\n\n英語教育では、以下のような場面で介入効果の検証が必要になります：\n\n- 新しい教科書やカリキュラムの導入効果\n- CLIL（内容言語統合型学習）プログラムの評価\n- 反転授業やオンライン学習への移行効果\n- コロナ禍によるオンライン授業への突然の切り替えの影響\n\nしかし、教育現場では学生をランダムに介入群と統制群に割り当てることが倫理的・実務的に困難な場合が多くあります。ITSは、**同一の対象者を時間方向に追跡し、介入前後のトレンドの変化を検出する**ことで、この問題を回避します。PLOS ONE に掲載された @li2025 の研究では、プロジェクトベース学習がEFL学習者のライティングに与える効果をITSデザインで検証しています。\n\n::: {.callout-note}\n#### ITSに必要なデータ量\n\n介入前後に**最低8–10時点**のデータが必要です（Kontopantelis et al., 2015）。週次測定を1学期行えば約15時点が得られ、十分です。月次測定1年間では12時点で、やや少ないがギリギリ実行可能です。半期の月次データ（6時点のみ）では不十分です。\n:::\n\n### なぜ通常の回帰ではだめなのか：OLS vs ARIMAX\n\nITS分析でよくある誤りは、自己相関を無視して通常のOLS回帰（第4章）を当てはめることです。以下で「間違った方法」と「正しい方法」を比較します。\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# 「間違った方法」：OLS 回帰（自己相関を無視）\ndf_its_ols <- data.frame(\n  time = 1:n_months,\n  score = as.numeric(toefl_ts),\n  post = ifelse(1:n_months > intervention_point, 1, 0),\n  time_after = ifelse(1:n_months > intervention_point,\n                      1:n_months - intervention_point, 0)\n)\nfit_ols <- lm(score ~ time + post + time_after, data = df_its_ols)\n\n# Durbin-Watson 検定で自己相関を確認\ndw <- lmtest::dwtest(fit_ols)\n\n# 「正しい方法」：ARIMAX（OLSとの比較用に先にフィット）\nstep_dummy_pre <- ifelse(1:n_months > intervention_point, 1, 0)\nramp_dummy_pre <- ifelse(1:n_months > intervention_point,\n                         1:n_months - intervention_point, 0)\nxreg_pre <- cbind(step = step_dummy_pre, ramp = ramp_dummy_pre)\nfit_arimax_pre <- auto.arima(toefl_ts, xreg = xreg_pre)\n\ntibble(\n  Method = c(\"OLS (自己相関無視)\", \"ARIMAX (自己相関考慮)\"),\n  `Step SE` = c(\n    round(summary(fit_ols)$coefficients[\"post\", \"Std. Error\"], 2),\n    round(sqrt(diag(vcov(fit_arimax_pre)))[\"step\"], 2)\n  ),\n  Note = c(\n    paste0(\"DW = \", round(dw$statistic, 2), \", p = \", round(dw$p.value, 3),\n           ifelse(dw$p.value < 0.05, \" → 自己相関あり！\", \"\")),\n    \"自己相関をモデルに組み込み済み\"\n  )\n) |>\n  gt() |>\n  tab_header(title = \"OLS vs ARIMAX: standard errors comparison\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  OLS vs ARIMAX: standard errors comparison\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrl}\n\\toprule\nMethod & Step SE & Note \\\\ \n\\midrule\\addlinespace[2.5pt]\nOLS (自己相関無視) & 1.54 & DW = 2.45, p = 0.685 \\\\ \nARIMAX (自己相関考慮) & 1.19 & 自己相関をモデルに組み込み済み \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-warning}\n#### OLSの標準誤差は信用できない\n\nDurbin-Watson検定の結果が有意（p < 0.05）の場合、残差に自己相関があることを意味し、OLSの標準誤差は**過小推定**されています。つまり、本来有意でない効果が「有意」と判定されるリスクがあります。ARIMAXはこの自己相関を明示的にモデル化するため、正しい推論が可能です。\n\nなお、サンプルサイズが極めて小さく（10時点未満）ARIMA推定が不安定な場合は、**Newey-West補正**（`sandwich::NeweyWest()`）によるロバスト標準誤差が実用的な代替案となります。\n:::\n\n### 3つの介入効果のタイプ\n\n介入の効果は、時系列上でどのように現れるかによって3つに分類されます。\n\n介入効果の型は、(1) **ステップ（step）**: 介入直後に水準が恒常的に変化する型、(2) **パルス（pulse）**: 介入時点でのみ一時的に変化する型、(3) **ランプ（ramp）**: 介入後に効果が徐々に累積する型、の3つに整理できます。分析では研究デザインに合わせて適切な介入ダミー（step / pulse / ramp）を指定します。\n\n- **ステップ (step)**：介入直後にスコアが即座にジャンプし、その後もそのレベルが維持される。例：新しい教科書を採用した途端にテストの平均点が上がった。\n- **パルス (pulse)**：介入時点でのみ一時的に変化し、すぐ元に戻る。例：特別講師を1週だけ招いたときの一時的な成績向上。\n- **ランプ (ramp)**：介入後、効果が時間とともに徐々に蓄積される。例：タスクベース教授法の導入後、学生の習慣が徐々に変わり、数ヶ月かけてスコアが改善。\n\n### フルITS分析：Dataset 2（TOEFLスコア）\n\n#### ダミー変数の作成\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 介入ダミーの作成\nstep_dummy  <- ts(ifelse(months > intervention_point, 1, 0),\n                  start = c(2022, 1), frequency = 12)\nramp_dummy  <- ts(ifelse(months > intervention_point, months - intervention_point, 0),\n                  start = c(2022, 1), frequency = 12)\npulse_dummy <- ts(ifelse(months == intervention_point + 1, 1, 0),\n                  start = c(2022, 1), frequency = 12)\n\n# 可視化\ntibble(\n  Month = months,\n  TOEFL = as.numeric(toefl_ts),\n  Step = as.numeric(step_dummy),\n  Ramp = as.numeric(ramp_dummy) / max(ramp_dummy)  # スケーリング\n) |>\n  pivot_longer(-Month, names_to = \"Variable\", values_to = \"Value\") |>\n  ggplot(aes(Month, Value, color = Variable)) +\n  geom_line(linewidth = 0.8) +\n  geom_vline(xintercept = intervention_point, linetype = \"dashed\") +\n  labs(title = \"TOEFL scores with intervention dummies\",\n       x = \"Month\", y = \"Value (scaled)\") +\n  facet_wrap(~Variable, scales = \"free_y\", ncol = 1)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/its-create-dummies-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n#### ARIMAX モデルの推定\n\n外生変数（介入ダミー）をARIMAモデルに組み込んだモデルを**ARIMAX**（ARIMA with eXogenous regressors）と呼びます。数学的には以下のように表現されます。\n\n$$\ny_t = \\beta_0 + \\beta_{\\text{step}} \\cdot D_t^{\\text{step}} + \\beta_{\\text{ramp}} \\cdot D_t^{\\text{ramp}} + n_t, \\quad n_t \\sim \\text{ARIMA}(p, d, q)\n$$\n\nここで $D_t^{\\text{step}}$ は介入後に1となるステップダミー、$D_t^{\\text{ramp}}$ は介入後の経過時間を表すランプダミー、$n_t$ は自己相関を持つ誤差項（ARIMA過程）です。通常の回帰分析（第4章）との違いは、**誤差項 $n_t$ が独立ではなく ARIMA 構造を持つ**点です。これにより、時系列の自己相関を考慮した正しい標準誤差と p 値が得られます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxreg_its <- cbind(step = as.numeric(step_dummy),\n                  ramp = as.numeric(ramp_dummy))\n\nfit_its <- auto.arima(toefl_ts, xreg = xreg_its)\nbroom::tidy(fit_its) |>\n  gt() |>\n  tab_header(title = \"ARIMAX: Interrupted Time Series\") |>\n  fmt_number(columns = where(is.numeric), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ARIMAX: Interrupted Time Series\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nterm & estimate & std.error \\\\ \n\\midrule\\addlinespace[2.5pt]\nintercept & 67.338 & 0.504 \\\\ \nstep & 7.273 & 1.188 \\\\ \nramp & 0.652 & 0.146 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(fit_its)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/its-arimax-fit-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(0,0,0) errors\nQ* = 2.4748, df = 5, p-value = 0.7803\n\nModel df: 0.   Total lags used: 5\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n#### ARIMAX 出力の読み方\n\n| 出力要素 | 確認場所 | 意味 | この分析での注目点 |\n|---------|---------|------|------------------|\n| **ARIMA order** | 最初の行（例: ARIMA(1,0,0)） | 誤差項 $n_t$ の自己相関構造 | スコアの時間的依存を捉えている。介入効果とは独立 |\n| **`step` 係数** | xreg セクション | 介入直後の**即座の水準変化**（点） | 正で有意 → カリキュラム変更直後にスコアがジャンプ |\n| **`ramp` 係数** | xreg セクション | 介入後の**毎月の追加的変化**（点/月） | 正で有意 → 介入後もスコアが月々改善し続けている |\n| **ar1**（あれば） | Coefficients | 残差の自己回帰係数 | スコアの「粘り」の強さ |\n| **sigma^2** | Coefficients 下 | 残差分散 | 小さいほどモデルの当てはまりが良い |\n| **AICc** | Information criteria | モデル選択基準 | 代替モデル（step のみ、ramp のみ）と比較 |\n| **Ljung-Box p** | `checkresiduals()` | 残差の白色性検定 | **p > 0.05 なら残差に自己相関なし** → モデル適切 |\n\n**ITS分析の核心**：`step` と `ramp` の係数とその95%信頼区間が、この分析で最も報告すべき結果です。信頼区間が0を含まなければ、介入効果が統計的に有意と判断されます。\n:::\n\n#### 係数の解釈\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefs <- coef(fit_its)\nse <- sqrt(diag(vcov(fit_its)))\n\n# step と ramp の係数を抽出\nits_results <- tibble(\n  Effect = c(\"Step (immediate change)\", \"Ramp (gradual change per month)\"),\n  Estimate = round(coefs[c(\"step\", \"ramp\")], 2),\n  SE = round(se[c(\"step\", \"ramp\")], 2),\n  CI_lower = round(Estimate - 1.96 * SE, 2),\n  CI_upper = round(Estimate + 1.96 * SE, 2)\n)\n\nits_results |>\n  gt() |>\n  tab_header(title = \"ITS results: intervention effects on TOEFL scores\") |>\n  cols_label(CI_lower = \"95% CI lower\", CI_upper = \"95% CI upper\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ITS results: intervention effects on TOEFL scores\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nEffect & Estimate & SE & 95\\% CI lower & 95\\% CI upper \\\\ \n\\midrule\\addlinespace[2.5pt]\nStep (immediate change) & 7.27 & 1.19 & 4.94 & 9.60 \\\\ \nRamp (gradual change per month) & 0.65 & 0.15 & 0.36 & 0.94 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-note}\n#### 結果の読み方\n\n- **Step 係数**が正で有意 → カリキュラム変更直後にスコアが即座に上昇したことを示す\n- **Ramp 係数**が正で有意 → 変更後、毎月追加的にスコアが上昇し続けていることを示す\n- 両方が有意 → 即座の効果と漸進的な効果の両方が存在\n:::\n\n#### 反事実プロット（もし介入がなかったら？）\n\nITS分析の強みは、**反事実** (counterfactual) — 「介入がなかった場合に予想されるスコアの推移」を推定できることです。介入前のトレンドをそのまま延長し、実際のスコアと比較します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 反事実: 介入がなかったと仮定（step=0, ramp=0）\nxreg_counterfactual <- cbind(step = rep(0, n_months), ramp = rep(0, n_months))\ncounterfactual <- fitted(Arima(toefl_ts, model = fit_its, xreg = xreg_counterfactual))\n\n# プロット\ntibble(\n  Time = as.numeric(time(toefl_ts)),\n  Actual = as.numeric(toefl_ts),\n  Counterfactual = as.numeric(counterfactual)\n) |>\n  pivot_longer(-Time, names_to = \"Scenario\", values_to = \"Score\") |>\n  ggplot(aes(Time, Score, color = Scenario, linetype = Scenario)) +\n  geom_line(linewidth = 0.9) +\n  geom_vline(xintercept = 2022 + 12/12, linetype = \"dashed\", color = \"gray40\") +\n  annotate(\"text\", x = 2023.05, y = min(toefl_scores) + 2,\n           label = \"Intervention\", color = \"gray40\", size = 3.5) +\n  scale_color_manual(values = c(\"Actual\" = \"steelblue\", \"Counterfactual\" = \"tomato\")) +\n  labs(title = \"Actual vs. counterfactual TOEFL scores\",\n       x = \"Year\", y = \"TOEFL score\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/its-counterfactual-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n実線（Actual）と破線（Counterfactual）の差が、介入によって生じたと推定されるスコア変化です。\n\n#### 効果量の算出\n\nITS分析では、介入効果の**大きさ**を標準化して報告することが重要です（第1章のCohen's dと同様の発想）。介入前のSDで標準化することで、他の研究と比較可能な効果量が得られます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 介入前のSDで標準化した効果量\npre_sd <- sd(toefl_scores[1:intervention_point])\nfitted_vals <- fitted(fit_its)\ncounter_vals <- as.numeric(counterfactual)\n\n# 各時点での効果量（実測値 - 反事実）/ 介入前SD\neffect_trajectory <- (as.numeric(toefl_ts) - counter_vals) / pre_sd\npost_idx <- (intervention_point + 1):n_months\n\ntibble(\n  Metric = c(\"Pre-intervention SD\",\n             \"Step effect (raw points)\",\n             \"Effect at final time point (d)\",\n             \"Cumulative mean effect (d)\"),\n  Value = round(c(\n    pre_sd,\n    coefs[\"step\"],\n    effect_trajectory[n_months],\n    mean(effect_trajectory[post_idx], na.rm = TRUE)\n  ), 2)\n) |>\n  gt() |>\n  tab_header(title = \"ITS effect size summary\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ITS effect size summary\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nMetric & Value \\\\ \n\\midrule\\addlinespace[2.5pt]\nPre-intervention SD & 1.96 \\\\ \nStep effect (raw points) & 7.27 \\\\ \nEffect at final time point (d) & 7.66 \\\\ \nCumulative mean effect (d) & 5.87 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# 効果量の時間推移\ntibble(Month = post_idx, d = effect_trajectory[post_idx]) |>\n  ggplot(aes(Month, d)) +\n  geom_line(linewidth = 0.8, color = \"steelblue\") +\n  geom_hline(yintercept = c(0.2, 0.5, 0.8), linetype = \"dotted\", alpha = 0.4) +\n  annotate(\"text\", x = max(post_idx), y = c(0.2, 0.5, 0.8) + 0.05,\n           label = c(\"Small\", \"Medium\", \"Large\"), size = 2.8, hjust = 1) +\n  labs(title = \"Standardized effect size trajectory (Cohen's d equivalent)\",\n       x = \"Month\", y = \"Effect size (d)\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/its-effect-size-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**効果量プロットの読み方**：\n\n- **横軸**：介入後の各月。\n- **縦軸**：標準化効果量（Cohen's $d$ 相当）。介入前のSDで標準化した「実測値 - 反事実」の差です。\n- **点線の基準線**：$d$ = 0.2（小）、0.5（中）、0.8（大）は Cohen (1988) の目安です。教育研究では $d$ = 0.4 以上を実質的な効果と見なすことが多いです。\n- **軌跡の形状**：ステップ効果のみなら水平線、ランプ効果があれば右上がりの直線になります。両方あれば、初期ジャンプ + 上昇です。\n- **Summary table**：`Pre-intervention SD` は標準化の分母、`Step effect (raw points)` は即座の変化、`Effect at final time point (d)` は最終時点での累積効果量、`Cumulative mean effect (d)` は介入後全期間の平均効果量です。\n\n#### 予測（介入継続を仮定）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh <- 12\nnewx <- cbind(step = rep(1, h), ramp = (1:h) + max(ramp_dummy))\nfc_its <- forecast(fit_its, xreg = newx, h = h)\nautoplot(fc_its) +\n  labs(title = \"ARIMAX forecast (intervention continues)\",\n       x = \"Year\", y = \"TOEFL score\") +\n  geom_vline(xintercept = 2022 + 12/12, linetype = \"dashed\", color = \"red\", alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/its-forecast-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n### 構造変化の検出\n\n介入時点が既知でない場合、**統計的に変化点を検出**することも可能です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbp <- strucchange::breakpoints(as.numeric(toefl_ts) ~ 1)\nbp_summary <- summary(bp)\nbp_rss <- bp_summary$RSS\n# RSS table structure varies; convert to data frame safely\nif (is.matrix(bp_rss)) {\n  bp_df <- as.data.frame(bp_rss)\n  bp_df$n_breaks <- 0:(nrow(bp_df) - 1)\n  bp_df |>\n    dplyr::select(n_breaks, everything()) |>\n    gt() |>\n    tab_header(title = \"Breakpoint Analysis: Model Comparison\") |>\n    fmt_number(columns = where(is.numeric), decimals = 2)\n} else {\n  tibble(Info = \"No breakpoints detected by the model.\") |> gt()\n}\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Breakpoint Analysis: Model Comparison\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrrrrrr}\n\\toprule\nn\\_breaks & 0 & 1 & 2 & 3 & 4 & 5 & 6 \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.00 & 928.72 & 134.01 & 79.57 & 56.93 & 45.88 & 39.46 & 46.51 \\\\ \n1.00 & 162.20 & 122.10 & 115.94 & 114.27 & 115.44 & 118.18 & 128.48 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nplot(bp)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/breakpoints-toefl-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### breakpoints出力の読み方\n\n- **summary(bp)**：候補となる変化点の数（0個、1個、2個...）ごとのBIC（ベイズ情報量基準）とRSS（残差二乗和）を表示します。**BICが最小**となる変化点数が推奨されます。\n- **plot(bp)**：BIC/RSSの変化点数に対するプロット。最小値の位置が最適な変化点数です。\n- **推定された変化点の時点**：`breakpoints(bp)` で具体的な時点番号が返されます。月12の介入時点に近いかどうかを確認してください。\n:::\n\n::: {.callout-tip}\n自動検出された変化点と、既知の介入時点（月12）を比較してみてください。一致していれば、介入効果の証拠がより強固になります。不一致の場合は、介入以外の要因（教員の変更、試験形式の変更など）も検討すべきです。\n:::\n\n::: {.callout-warning}\n#### ITS分析で残差に自己相関が残る場合\n\n**症状**：`checkresiduals()` のLjung-Box検定で p < 0.05、またはACFに有意なラグが残っている。\n\n**原因**：ARIMA次数が不十分で、スコアの時間的依存を捉えきれていない。\n\n**修正手順**：\n\n1. `auto.arima(stepwise = FALSE)` で再度全探索\n2. ACFの有意なラグを確認し、そのラグに対応するAR/MA項を手動で追加（例：ラグ2が有意 → AR(2)を試す）\n3. 季節性がある場合は季節ARIMA (SARIMA) を検討\n4. それでも解決しない場合は、**季節ダミーやイベントダミー**を外生変数として追加\n5. 最終手段として **Newey-West補正**によるロバスト標準誤差を使用\n:::\n\n### ITSの脅威と限界\n\n::: {.callout-warning}\n#### ITS分析の内的妥当性への脅威\n\nITSは強力なデザインですが、以下の脅威に注意が必要です。\n\n1. **歴史的脅威 (history threat)**：介入と同時期に他の変化が起きた場合（例：カリキュラム変更と同時に教員が交代した）、効果の帰属が不明確になります。\n2. **測定の変化 (instrumentation)**：介入に合わせてテスト形式を改訂した場合、スコア変化は介入効果か測定の違いか区別できません。\n3. **成熟 (maturation)**：統制群がない場合、学生の自然な成長と介入効果を完全に分離できません。\n4. **平均への回帰 (regression to the mean)**：異常に低いスコアを契機に介入を実施した場合、その後の改善は部分的に統計的回帰の可能性があります。\n\n**対策**：可能であれば**統制群付きITS (Controlled ITS, CITS)** を設計し、差の差 (difference-in-differences) 的な解釈を行います。統制群がない場合は、上記の脅威を論文のLimitationsで明記してください。\n:::\n\n### ITS 報告テンプレート\n\nITSの結果を論文に記載する際の標準的なフォーマットです。\n\n**報告テンプレート（ITS / ARIMAX）**\n\n- **デザイン**：月次 / 週次の時系列（N = __ 時点、介入は第 __ 時点）\n- **前処理**：対数変換の有無、差分の回数\n- **モデル**：ARIMA(p, d, q) + step / ramp / pulse の外生変数\n- **選択基準**：AICc = __、残差 Ljung-Box p = __（白色性 OK / NG）\n- **介入効果**：\n  - ステップ変化：$\\hat{\\beta}_{\\text{step}}$ = __ (SE = __), 95% CI [__, __]\n  - 傾き変化：$\\hat{\\beta}_{\\text{ramp}}$ = __ (SE = __), 95% CI [__, __]\n- **効果の解釈**：介入後、スコアは即座に約__点上昇し、その後も月あたり約__点の追加的上昇が見られた\n- **限界**：交絡の可能性（同時期の他の変更）、データ点数の制約\n\n## 欠測値・外れ値・複数季節性\n\n### 教育データにおける欠測値の処理\n\n教育データには欠測が頻繁に発生します — 学校休暇、休校日、学生の欠席、テスト未実施の週など。時系列データの欠測補間は、**時間的順序を尊重**する必要があるため、単純な平均値代入は不適切です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 語彙テストデータに3週分の欠測を導入（学校休暇を想定）\nvocab_na <- vocab_ts\nvocab_na[c(8, 20, 35)] <- NA\n\n# 2つの補間法を比較\ninterp_linear <- na.interp(vocab_na)                 # 線形補間\ninterp_kalman <- imputeTS::na_kalman(vocab_na)       # 状態空間モデルに基づく補間\n\ntibble(\n  Week = 1:n_weeks,\n  Original = as.numeric(vocab_ts),\n  Linear = as.numeric(interp_linear),\n  Kalman = as.numeric(interp_kalman)\n) |>\n  pivot_longer(-Week, names_to = \"Method\", values_to = \"Score\") |>\n  ggplot(aes(Week, Score, color = Method)) +\n  geom_line(alpha = 0.8) +\n  geom_point(data = tibble(Week = c(8, 20, 35)),\n             aes(x = Week, y = vocab_ts[c(8, 20, 35)]),\n             color = \"red\", size = 3, shape = 4, inherit.aes = FALSE) +\n  labs(title = \"Missing value imputation: linear vs. Kalman\",\n       x = \"Week\", y = \"Score (/20)\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/missing-education-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n`na_kalman()` はカルマンフィルタに基づく補間で、系列の自己相関構造を考慮するため、一般に線形補間より正確です。ただし、補間・置換は**予測用途**では有効ですが、**因果推論**が目的なら欠測指示変数の導入やロバスト手法の検討が必要です。\n:::\n\n### 外れ値の検出と処理\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout <- tsoutliers(vocab_ts)\nout\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$index\ninteger(0)\n\n$replacements\nnumeric(0)\n```\n\n\n:::\n\n```{.r .cell-code}\nvocab_clean <- vocab_ts\nif (length(out$index) > 0) {\n  vocab_clean[out$index] <- out$replacements\n}\n```\n:::\n\n\n::: {.callout-tip}\n外れ値が検出されたとき、機械的に置換する前に**ドメイン知識**を確認してください。たとえば、第15週のスコア低下が「文化祭の週で授業が短縮された」ことによるものなら、外れ値ではなく**介入（パルス効果）**としてモデルに含めるべきです。\n:::\n\n### TBATS（複数季節性への対応）\n\n日次の出席データなど、**週次パターン**（月曜日に低い）と**年次パターン**（学期の始まりと終わり）が重なるデータには、TBATSが有効です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_tb <- tbats(fluency_ts)\nfit_tb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTBATS(1, {0,0}, -, {<10,1>})\n\nCall: tbats(y = fluency_ts)\n\nParameters\n  Alpha: 0.7438826\n  Gamma-1 Values: -0.02890015\n  Gamma-2 Values: 0.001244792\n\nSeed States:\n           [,1]\n[1,] 104.559699\n[2,]  -3.431484\n[3,]  -6.680820\n\nSigma: 3.460124\nAIC: 188.5142\n```\n\n\n:::\n\n```{.r .cell-code}\nfc_tb <- forecast(fit_tb, h = 10)\nautoplot(fc_tb) + labs(title = \"TBATS forecast: reading fluency\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/tbats-brief-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\nTBATSは**Box–Cox変換 + ARMA誤差 + Trigonometric な季節成分**を組み合わせたモデルで、複数の周期を同時にモデル化できます。名前はこれらの頭文字に由来します。教育データでは、日次の出席・学習ログデータなどで威力を発揮します。\n:::\n\n------------------------------------------------------------------------\n\n::: {.callout-important}\n#### モデル選択早見表：どの手法をいつ使うか\n\n| シナリオ | 推奨手法 | 理由 |\n|---------|---------|------|\n| 短い系列（<30点）、季節性なし | ARIMA or ETS | シンプルで診断が容易 |\n| 強い季節性 + 滑らかなトレンド | ETS (or SARIMA) | 季節更新が自然 |\n| 複数の季節周期が重なる | TBATS | 非整数・複数周期を同時処理 |\n| **介入効果の検証** | **ARIMAX (ITS)** | 外生変数で step/ramp/pulse を明示的にモデル化 |\n| 複数変数の時間的因果 | VAR + Granger | 変数間のクロスラグ効果を検定 |\n| 時間ずれのある2系列の類似度比較 | DTW | 時間軸の伸縮を許容して形状を対応づけ |\n| 潜在レジーム（停滞/伸長）の推定 | HMM | 観測値の背後にある状態遷移を推定 |\n| 欠測あり・測定誤差の分離 | SSM (KFAS) | カルマンフィルタが欠測を自然に処理 |\n| 小標本 + 事前情報あり | brms（ベイズ） | 事前分布が正則化の役割。確率的解釈 |\n| 非線形トレンド（プラトー/S字） | brms + GP | ガウス過程が柔軟な曲線をフィット |\n\n教育研究では**ITS (ARIMAX)** が最も頻出です。迷ったらまず `auto.arima()` を試し、次にITSの枠組みに進んでください。\n:::\n\n## 発展編：VAR・DTW・HMM・状態空間モデル・ベイズ時系列\n\n### 多変量時系列（VAR）：語彙力と読解力の相互関係\n\n「語彙力の伸びは、後の読解力の伸びを予測するか？」という問いは、**VARモデル** (Vector Autoregression) で検討できます。VARは複数の時系列を同時にモデル化し、変数間の**時間的先行関係**（Granger因果性）を検定します。\n\n以下のコードでは、語彙スコアと読解スコアの2変量時系列をシミュレーションし、VARモデルで分析します。シミュレーションには「語彙の1期前の値が読解に正の影響を与える」というクロスラグ効果（係数 = 0.3）を埋め込んでいます。これは「語彙指導が読解力に波及する」というSLAの理論的予測を統計的に検証するアプローチのデモンストレーションです。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 語彙スコアと読解スコアの2変量時系列をシミュレーション\nn_var <- 50\nset.seed(2024)\n# 語彙 → 読解 のクロスラグ効果を埋め込む\nvocab_var  <- numeric(n_var)\nreading_var <- numeric(n_var)\nvocab_var[1] <- 10; reading_var[1] <- 50\n\nfor (i in 2:n_var) {\n  vocab_var[i]   <- 0.6 * vocab_var[i-1] + rnorm(1, 0.2, 1)\n  reading_var[i] <- 0.5 * reading_var[i-1] + 0.3 * vocab_var[i-1] + rnorm(1, 0.3, 2)\n}\n\nedu_mts <- ts(cbind(Vocabulary = vocab_var, Reading = reading_var), frequency = 1)\nplot(edu_mts, main = \"Bivariate time series: Vocabulary & Reading scores\")\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/var-education-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# 差分で定常化\nd_edu <- diff(edu_mts)\nVARselect(d_edu, lag.max = 8)$selection\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAIC(n)  HQ(n)  SC(n) FPE(n) \n     1      1      1      1 \n```\n\n\n:::\n\n```{.r .cell-code}\nfit_var <- VAR(d_edu, p = 2, type = \"const\")\n\n# VAR model coefficients\npurrr::map_dfr(names(summary(fit_var)$varresult), function(eq) {\n  coefs <- coef(summary(fit_var)$varresult[[eq]])\n  tibble(\n    Equation = eq,\n    Term = rownames(coefs),\n    Estimate = coefs[, \"Estimate\"],\n    Std.Error = coefs[, \"Std. Error\"],\n    t = coefs[, \"t value\"],\n    p = coefs[, \"Pr(>|t|)\"]\n  )\n}) |>\n  gt() |>\n  tab_header(title = \"VAR Model Coefficients\") |>\n  fmt_number(columns = c(Estimate, Std.Error, t), decimals = 3) |>\n  fmt_number(columns = p, decimals = 4)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  VAR Model Coefficients\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrr}\n\\toprule\nEquation & Term & Estimate & Std.Error & t & p \\\\ \n\\midrule\\addlinespace[2.5pt]\nVocabulary & Vocabulary.l1 & -0.082 & 0.155 & -0.527 & 0.6010 \\\\ \nVocabulary & Reading.l1 & 0.001 & 0.072 & 0.017 & 0.9864 \\\\ \nVocabulary & Vocabulary.l2 & -0.019 & 0.164 & -0.117 & 0.9077 \\\\ \nVocabulary & Reading.l2 & 0.035 & 0.052 & 0.678 & 0.5013 \\\\ \nVocabulary & const & -0.092 & 0.194 & -0.476 & 0.6368 \\\\ \nReading & Vocabulary.l1 & 0.606 & 0.282 & 2.149 & 0.0375 \\\\ \nReading & Reading.l1 & -0.206 & 0.131 & -1.573 & 0.1233 \\\\ \nReading & Vocabulary.l2 & 0.464 & 0.299 & 1.549 & 0.1289 \\\\ \nReading & Reading.l2 & 0.164 & 0.095 & 1.727 & 0.0915 \\\\ \nReading & const & -0.206 & 0.353 & -0.584 & 0.5621 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# 安定性チェック：すべての固有値が1未満（= 単位円内）であること\nvar_roots <- roots(fit_var)\ncat(\"Eigenvalues:\", round(var_roots, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEigenvalues: 0.542 0.43 0.29 0.29 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"All stable (< 1)?\", all(var_roots < 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll stable (< 1)? TRUE \n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n#### VAR出力の読み方\n\n| 出力要素 | 確認場所 | 意味 | 判断基準 |\n|---------|---------|------|---------|\n| **VARselect** | `$selection` | 最適ラグ次数の推奨 | AIC/BICが一致すればそのラグ。不一致ならBIC（節約的）を優先 |\n| **Equation: Vocabulary** | `summary()` の第1方程式 | 語彙の変化を予測する因子 | Readingのラグ係数が有意 → 読解が語彙に先行影響 |\n| **Equation: Reading** | `summary()` の第2方程式 | 読解の変化を予測する因子 | **Vocabularyのラグ係数が有意** → 語彙が読解に先行影響（今回の関心） |\n| **roots()** | 固有値の一覧 | モデルの安定性 | **すべて < 1**（単位円内）なら安定。1以上があれば不安定 → ラグ次数を見直し |\n| **R-squared** | 各方程式の決定係数 | 予測力 | 時系列の説明力の目安。0.3以上なら相応の予測力 |\n\n**この分析での注目点**：Reading方程式において `Vocabulary.l1`（語彙の1ラグ前）の係数が正で有意であれば、「語彙力の向上が、次の時点の読解力に正の影響を与える」というクロスラグ効果を示唆します。\n:::\n\n\n#### Granger因果性検定\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 語彙 → 読解 のGranger因果性\ncausality(fit_var, cause = \"Vocabulary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Granger\n\n\tGranger causality H0: Vocabulary do not Granger-cause Reading\n\ndata:  VAR object fit_var\nF-Test = 3.1693, df1 = 2, df2 = 84, p-value = 0.0471\n\n\n$Instant\n\n\tH0: No instantaneous causality between: Vocabulary and Reading\n\ndata:  VAR object fit_var\nChi-squared = 1.0271, df = 1, p-value = 0.3108\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n#### Granger因果性検定の出力の読み方\n\n`causality()` は2種類の検定を返します。\n\n- **Granger causality** (F検定)：帰無仮説は「Vocabularyの過去の値は、Readingの予測に追加的な情報を持たない」。**p < 0.05 なら、語彙が読解をGranger因果する**（＝語彙のラグが読解の予測に有意に寄与する）と判断します。\n- **Instant causality** (χ²検定)：同時点での相関の有無を検定します。Granger因果性とは別の概念です。\n\n**重要な注意**：Granger因果性は**予測的先行関係**（temporal precedence in prediction）であり、真の因果関係を保証するものではありません。交絡変数の統制や理論的裏付けが別途必要です。論文では「Granger-causes」と記述し、「causes」とは書かないのが慣例です。\n:::\n\n#### インパルス応答関数（IRF）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nirf_result <- irf(fit_var, impulse = \"Vocabulary\", response = \"Reading\", n.ahead = 10)\nplot(irf_result)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/irf-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### IRFプロットの読み方\n\n- **横軸**：先行ラグ数（0, 1, 2, ...）。「語彙に1単位のショック（突然の変化）を与えた後、何期にわたって読解が影響を受けるか」を示します。\n- **縦軸**：読解スコアの応答の大きさ。正の値は正の影響、負の値は負の影響。\n- **信頼帯**（灰色の領域）：0を含まなければ、その時点での応答は統計的に有意です。\n- **減衰パターン**：安定なVARモデルでは、応答は時間とともに0に収束します。持続的に0から離れている場合は、語彙の変化が読解に長期的な影響を持つことを示唆します。\n:::\n\n::: {.callout-tip}\n#### VAR を一歩進める\n- 変数間に**共和分**（長期的均衡関係）が疑われるなら**VECM** (`urca` パッケージ) を検討。\n- IRF/FEVDは**ショックの識別順序**に依存します。教育研究のドメイン知識に基づいて変数の順序を決定してください。\n:::\n\n::: {.callout-warning}\n#### VARモデルが不安定（固有値 ≥ 1）の場合\n\n**症状**：`roots(fit_var)` の値に1以上のものがあり、`all(roots < 1)` が `FALSE` を返す。\n\n**原因**：ラグ次数が大きすぎるか、非定常な系列をそのまま投入している。\n\n**修正手順**：\n\n1. `VARselect()` で推奨ラグを再確認し、より小さいラグ次数を試す\n2. 差分を取ってから `VAR()` に投入する（`diff(edu_mts)` を使用）\n3. 変数間に共和分関係がある場合は `VECM`（`urca::ca.jo()`）に切り替え\n:::\n\n### dynamic time warping（DTW）：時間ずれを許容した軌跡比較\n\n学習者AとBで「似た伸び方」をしていても、伸びるタイミングが1〜2週ずれていることがあります。通常の時点合わせ（同じ週同士の比較）ではこのズレが過大評価されます。DTWは、時間軸を局所的に伸縮させながら2系列を最適に対応付ける手法です。**予測モデルではなく、軌跡の類似度評価**に向いています [@giorgino2009]。\n\n::: {.callout-important}\n#### DTWで答えられる問い / 答えにくい問い\n- **答えられる問い**：2つの学習軌跡は「時間ずれを許せば」どの程度似ているか\n- **答えにくい問い**：介入効果の因果推論、将来時点の予測、係数の統計的有意性\n- **実務上の位置づけ**：探索的な類似度評価・クラスタリング前処理・ケース比較に強い\n:::\n\n`dtw` の公式マニュアルでは、`dtw()` の挙動を主に次の4つで制御します。\n\n1. **`step.pattern`**：局所的な対応ルール（傾き制約）。標準は `symmetric2`\n2. **`window.type` + `window.size`**：大域的な探索幅（例：Sakoe-Chiba窓）\n3. **`open.begin` / `open.end`**：部分一致（サブシーケンス探索）を許容\n4. **`distance.only`**：距離のみを高速計算（バックトラック省略）\n\n::: {.callout-warning}\n#### 距離比較の前提（公式仕様に基づく注意）\n- `distance` と `normalizedDistance` は、`step.pattern` や `window.type` の設定に依存します\n- `normalizedDistance` は、選択したステップパターンで正規化が定義される場合にのみ解釈可能です\n- `open.begin` / `open.end` を使う場合は、`dtw::asymmetric` など正規化可能なステップパターンを選びます\n- 距離を研究間・条件間で比較する場合は、**DTW設定を固定**してから比較してください\n:::\n\n::: {.callout-note}\n#### DTW 公式ドキュメント（参照先）\n- `dtw()` リファレンス: <https://cran.r-project.org/web/packages/dtw/refman/dtw.html>\n- `stepPattern()` / 窓制約（Sakoe-Chibaなど）: 同上（`stepPattern`, `sakoeChibaWindow` 節）\n:::\n\n以下では、公式仕様どおりに「制約なし」と「窓制約あり」を比較し、`normalizedDistance` まで確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nweek <- 1:length(fluency_ts)\n\n# 2つの読解流暢性トラジェクトリ（BはAよりやや遅れて伸びる設定）\ndtw_curve_a <- as.numeric(scale(fluency_ts))\ndtw_curve_b_raw <- 100 + seq(0, 15, length.out = length(week)) -\n  5 * sin(2 * pi * (week - 2) / 10) +\n  as.numeric(arima.sim(n = length(week), list(ar = 0.3), sd = 2))\ndtw_curve_b <- as.numeric(scale(dtw_curve_b_raw))\n\nget_norm_dist <- function(x) {\n  if (is.null(x$normalizedDistance)) NA_real_ else x$normalizedDistance\n}\n\nfit_dtw_none <- dtw::dtw(\n  x = dtw_curve_a,\n  y = dtw_curve_b,\n  step.pattern = dtw::symmetric2\n)\n\nfit_dtw_sc <- dtw::dtw(\n  x = dtw_curve_a,\n  y = dtw_curve_b,\n  step.pattern = dtw::symmetric2,\n  window.type = \"sakoechiba\",\n  window.size = 4,\n  keep.internals = TRUE\n)\n\nfit_dtw_fast <- dtw::dtw(\n  x = dtw_curve_a,\n  y = dtw_curve_b,\n  step.pattern = dtw::symmetric2,\n  window.type = \"sakoechiba\",\n  window.size = 4,\n  distance.only = TRUE\n)\n\ntibble(\n  Model = c(\n    \"No window (symmetric2)\",\n    \"Sakoe-Chiba window (symmetric2)\",\n    \"Sakoe-Chiba + distance.only\"\n  ),\n  Distance = c(fit_dtw_none$distance, fit_dtw_sc$distance, fit_dtw_fast$distance),\n  NormalizedDistance = c(\n    get_norm_dist(fit_dtw_none),\n    get_norm_dist(fit_dtw_sc),\n    get_norm_dist(fit_dtw_fast)\n  )\n) |>\n  mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  gt() |>\n  tab_header(title = \"DTW comparison: constraints and distance definitions\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  DTW comparison: constraints and distance definitions\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nModel & Distance & NormalizedDistance \\\\ \n\\midrule\\addlinespace[2.5pt]\nNo window (symmetric2) & 17.081 & 0.285 \\\\ \nSakoe-Chiba window (symmetric2) & 17.081 & 0.285 \\\\ \nSakoe-Chiba + distance.only & 17.081 & 0.285 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nplot(\n  fit_dtw_sc,\n  type = \"twoway\",\n  main = \"DTW alignment with Sakoe-Chiba window\"\n)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/dtw-fluency-core-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**読み方**：\n\n- `distance` は総コスト、`normalizedDistance` はパス長で正規化した距離（`step.pattern` が正規化可能な場合）\n- `window.type = \"sakoechiba\"` を入れると、非現実的な大きい時間飛びを抑制できる\n- `distance.only = TRUE` は探索比較やグリッドサーチを速くしたいときに有効（対応経路は返らない）\n- 距離が小さいほど「時間ずれを許した形状類似性」が高いが、同時に設定依存性も高い\n\n#### open-begin / open-end による部分一致（サブシーケンス探索）\n\n公式ドキュメントにある `open.begin` / `open.end` を使うと、「短い系列が長い系列のどこに埋まっているか」を検出できます。ここでは、短いクエリ系列を長い参照系列に照合します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndtw_query_sub <- dtw_curve_a[8:24]\ndtw_ref_long <- c(rnorm(5, 0, 0.2), dtw_curve_b, rnorm(6, 0, 0.2))\n\nfit_dtw_open <- dtw::dtw(\n  x = dtw_query_sub,\n  y = dtw_ref_long,\n  step.pattern = dtw::asymmetric,\n  open.begin = TRUE,\n  open.end = TRUE,\n  keep.internals = TRUE\n)\n\nmatched_start <- min(fit_dtw_open$index2)\nmatched_end <- max(fit_dtw_open$index2)\n\ncat(\"Matched reference interval:\", matched_start, \"-\", matched_end, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMatched reference interval: 13 - 32 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Subsequence normalized distance:\", round(get_norm_dist(fit_dtw_open), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSubsequence normalized distance: 0.286 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(\n  fit_dtw_open,\n  type = \"twoway\",\n  main = \"Open-begin/open-end DTW (subsequence matching)\"\n)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/dtw-open-subsequence-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n`Matched reference interval` は、長い参照系列の中で「短いクエリと最も整合した区間」です。学習ログ分析では、ある学習者の特定期間が、別学習者のどの期間に対応するかを検出する用途に使えます。\n\n::: {.callout-tip}\n#### DTW の報告テンプレート（そのまま使える形）\n- 「`step.pattern = ...`, `window.type = ...`, `window.size = ...` を指定してDTW距離を算出した」\n- 「`distance = ...`, `normalizedDistance = ...`（利用可能な場合）であった」\n- 「`open.begin/open.end` を用いた部分一致では、参照系列の `...`〜`...` 区間が最適整列区間であった」\n:::\n\n### 隠れマルコフモデル（HMM）：見えない学習状態の推定\n\nテストスコア系列には、観測値だけでは見えない「停滞期」「伸長期」のような潜在状態があるかもしれません。HMMは、各時点の観測値がどの状態から生成されたかを推定し、さらに状態間の遷移確率（例：停滞 → 伸長）を推定します。基礎理論は @rabiner1989 のチュートリアル、R実装は `depmixS4` の解説 [@visser2010] を参照できます。\n\n::: {.callout-important}\n#### HMMを直感的に捉える3層構造\n- **隠れ状態（state）**：「停滞」「上昇」など、観測できない学習フェーズ\n- **遷移（transition）**：ある状態から次の状態へ移る確率（例：停滞が続く確率）\n- **出力分布（emission）**：各状態で観測スコアがどの分布に従うか（ここでは正規分布）\n:::\n\n`depmixS4` の公式設計は「**モデル指定 (`depmix`) → 推定 (`fit`)**」の2段階です。実務では次の順で進めると安定します。\n\n1. `nstates` を複数候補で試し、`BIC` で比較\n2. `em.control(random.start = TRUE)` で初期値依存を緩和\n3. 必要に応じて `multistart()` で多開始値推定\n4. `posterior(type = \"smoothing\")` を主に解釈（確率として解釈しやすい）\n\n::: {.callout-note}\n#### HMM 公式ドキュメント（参照先）\n- `depmix()` / `fit()` / `em.control()` / `multistart()` / `posterior()`: <https://cran.r-project.org/web/packages/depmixS4/refman/depmixS4.html>\n:::\n\n::: {.callout-note}\n#### `posterior(type = ...)` の使い分け（公式仕様）\n\n| `type` | 主な用途 | 返り値の解釈 |\n|---|---|---|\n| `\"global\"` | 系列全体で最も整合的な状態列（Viterbi） | 各時点の状態ラベル |\n| `\"local\"` | 各時点で最尤な状態ラベル | 各時点の状態ラベル |\n| `\"filtering\"` | 時点 $t$ までの情報での状態確率 | 状態確率（オンライン判断向け） |\n| `\"smoothing\"` | 全時点情報での状態確率 | 状態確率（事後解釈向け） |\n\n教育データの解釈では、確率として自然に読める `\"smoothing\"` を中心に報告するのが実務的です。\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\ndf_hmm <- tibble(\n  month = 1:length(toefl_ts),\n  score = as.numeric(toefl_ts)\n)\n\nfit_hmm_candidate <- function(k) {\n  mod <- depmixS4::depmix(\n    response = score ~ 1,\n    data = df_hmm,\n    nstates = k,\n    transition = ~1,\n    family = gaussian()\n  )\n  try_fit <- try(\n    depmixS4::fit(\n      mod,\n      verbose = FALSE,\n      emcontrol = depmixS4::em.control(\n        maxit = 500,\n        tol = 1e-8,\n        random.start = TRUE\n      )\n    ),\n    silent = TRUE\n  )\n\n  if (inherits(try_fit, \"try-error\")) {\n    depmixS4::fit(\n      mod,\n      verbose = FALSE,\n      emcontrol = depmixS4::em.control(maxit = 500, tol = 1e-8, random.start = FALSE)\n    )\n  } else {\n    try_fit\n  }\n}\n\nfit_hmm_candidates <- purrr::map(1:3, fit_hmm_candidate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nconverged at iteration 1 with logLik: -77.92361 \nconverged at iteration 7 with logLik: -57.24705 \nconverged at iteration 38 with logLik: -51.19237 \n```\n\n\n:::\n\n```{.r .cell-code}\nhmm_ic <- tibble(\n  nstates = 1:3,\n  logLik = purrr::map_dbl(fit_hmm_candidates, ~ as.numeric(logLik(.x))),\n  AIC = purrr::map_dbl(fit_hmm_candidates, AIC),\n  BIC = purrr::map_dbl(fit_hmm_candidates, BIC)\n)\n\nhmm_ic |>\n  mutate(across(c(logLik, AIC, BIC), ~ round(.x, 2))) |>\n  gt() |>\n  tab_header(title = \"HMM model selection (1-3 states)\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  HMM model selection (1-3 states)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\nnstates & logLik & AIC & BIC \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & -77.92 & 159.85 & 162.20 \\\\ \n2 & -57.25 & 128.49 & 136.74 \\\\ \n3 & -51.19 & 130.38 & 146.88 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nbest_k <- hmm_ic$nstates[which.min(hmm_ic$BIC)]\ncat(\"Selected by BIC:\", best_k, \"states\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSelected by BIC: 2 states\n```\n\n\n:::\n\n```{.r .cell-code}\nmod_hmm_best <- depmixS4::depmix(\n  response = score ~ 1,\n  data = df_hmm,\n  nstates = best_k,\n  transition = ~1,\n  family = gaussian()\n)\n\nfit_hmm <- try(\n  depmixS4::multistart(mod_hmm_best, nstart = 20, initIters = 20),\n  silent = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nconverged at iteration 12 with logLik: -57.24705 \nconverged at iteration 12 with logLik: -57.24705 \nconverged at iteration 10 with logLik: -57.24705 \nconverged at iteration 14 with logLik: -57.24705 \nconverged at iteration 18 with logLik: -57.24705 \nconverged at iteration 6 with logLik: -57.24705 \nconverged at iteration 11 with logLik: -57.24705 \nconverged at iteration 8 with logLik: -57.24705 \nconverged at iteration 10 with logLik: -57.24705 \nconverged at iteration 7 with logLik: -57.24705 \nconverged at iteration 10 with logLik: -57.24705 \nconverged at iteration 14 with logLik: -57.24705 \nconverged at iteration 17 with logLik: -57.24705 \nconverged at iteration 10 with logLik: -57.24705 \nconverged at iteration 9 with logLik: -57.24705 \nconverged at iteration 10 with logLik: -57.24705 \nconverged at iteration 12 with logLik: -57.24705 \n```\n\n\n:::\n\n```{.r .cell-code}\nif (inherits(fit_hmm, \"try-error\")) {\n  fit_hmm <- depmixS4::fit(\n    mod_hmm_best,\n    verbose = FALSE,\n    emcontrol = depmixS4::em.control(maxit = 500, tol = 1e-8, random.start = TRUE)\n  )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nconverged at iteration 10 with logLik: -57.24705 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npst_global <- depmixS4::posterior(fit_hmm, type = \"global\")\npst_local <- depmixS4::posterior(fit_hmm, type = \"local\")\npst_smooth <- depmixS4::posterior(fit_hmm, type = \"smoothing\")\npst_filter <- depmixS4::posterior(fit_hmm, type = \"filtering\")\n\nsmooth_mat <- as.matrix(pst_smooth)\nfilter_mat <- as.matrix(pst_filter)\ncolnames(smooth_mat) <- paste0(\"Pr_state\", seq_len(ncol(smooth_mat)))\nsmooth_tbl <- as_tibble(smooth_mat)\nstate_local_from_smooth <- max.col(smooth_mat, ties.method = \"first\")\n\ndf_hmm_decoded <- df_hmm |>\n  mutate(\n    state_global = factor(pst_global),\n    state_local = factor(pst_local),\n    state_local_from_smooth = factor(state_local_from_smooth),\n    decode_disagree = state_global != state_local\n  ) |>\n  bind_cols(smooth_tbl)\n\ncat(\n  \"Global vs local decoding disagreements:\",\n  sum(df_hmm_decoded$decode_disagree),\n  \"time points\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGlobal vs local decoding disagreements: 0 time points\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\n  \"Local decoding equals argmax(smoothing):\",\n  all(as.integer(pst_local) == state_local_from_smooth),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLocal decoding equals argmax(smoothing): TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ndf_hmm_decoded |>\n  group_by(state_global) |>\n  summarise(\n    n = n(),\n    mean_score = mean(score),\n    sd_score = sd(score),\n    .groups = \"drop\"\n  ) |>\n  gt() |>\n  tab_header(title = \"HMM decoded state summary (global decoding)\") |>\n  fmt_number(columns = c(mean_score, sd_score), decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  HMM decoded state summary (global decoding)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}crrr}\n\\toprule\nstate\\_global & n & mean\\_score & sd\\_score \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 12 & 78.85 & 2.89 \\\\ \n2 & 12 & 67.34 & 1.96 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nggplot(df_hmm_decoded, aes(x = month, y = score, color = state_global)) +\n  geom_line(color = \"grey60\", linewidth = 0.6) +\n  geom_point(size = 2) +\n  labs(\n    title = \"HMM: decoded latent states in TOEFL scores\",\n    x = \"Month\",\n    y = \"Score\",\n    color = \"Global state\"\n  )\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/hmm-toefl-decoding-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ndf_hmm_decoded |>\n  dplyr::select(month, starts_with(\"Pr_state\")) |>\n  pivot_longer(-month, names_to = \"state\", values_to = \"prob\") |>\n  ggplot(aes(x = month, y = prob, color = state)) +\n  geom_line(linewidth = 0.9) +\n  labs(\n    title = \"Posterior state probabilities (smoothing)\",\n    x = \"Month\",\n    y = \"Probability\",\n    color = \"\"\n  )\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/hmm-toefl-decoding-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ntibble(\n  month = df_hmm$month,\n  filtering = filter_mat[, 1],\n  smoothing = smooth_mat[, 1]\n) |>\n  pivot_longer(-month, names_to = \"type\", values_to = \"prob\") |>\n  ggplot(aes(x = month, y = prob, color = type)) +\n  geom_line(linewidth = 0.9) +\n  labs(\n    title = \"State 1 probability: filtering vs smoothing\",\n    x = \"Month\",\n    y = \"Probability\",\n    color = \"\"\n  )\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/hmm-toefl-decoding-3.pdf){fig-pos='H'}\n:::\n:::\n\n\n**読み方**：\n\n- BICが最小の状態数を第一候補にする（過剰状態数を避ける）\n- `posterior(type = \"smoothing\")` は各時点の状態確率として最も解釈しやすい\n- `filtering` は「その時点までの情報」に限定されるため、通常 `smoothing` より不安定になりやすい\n- `global` と `local` は一致しない場合があるため、報告時はどちらを使ったかを明記する\n- `viterbi` の付加確率（delta）は直感的な「事後確率」とは異なるため、主解析は smoothing を推奨\n\n::: {.callout-tip}\n#### HMM の報告テンプレート（そのまま使える形）\n- 「`nstates = 1..K` を比較し、BIC最小の `k = ...` を採用した」\n- 「`posterior(type = \"smoothing\")` を用いて状態確率を解釈した（global/local との差も確認）」\n- 「状態 `s` の平均スコアは `...` 点で、`...` 月付近で当該状態確率が上昇した」\n:::\n\n### 状態空間モデル（SSM）とカルマンフィルタ\n\n::: {.callout-note}\n#### ARIMA と SSM の比較\n\n| 特徴 | ARIMA | SSM（基本構造時系列） |\n|------|-------|--------------------|\n| **考え方** | 差分 + AR/MAで記述する確率過程 | 隠れ状態 + 測定誤差の分離 |\n| **欠測データ** | 事前に補間が必要 | カルマンフィルタが**自然に処理** |\n| **分解** | 事後的（STL等） | **モデル内蔵**（トレンド / 季節 / 不規則） |\n| **トレンドの柔軟性** | 差分で固定 | 時変（ローカルレベル / 線形トレンド） |\n| **診断** | ACF / PACF / Ljung-Box | 標準化予測誤差 |\n| **主なRパッケージ** | `forecast::auto.arima()` | `KFAS::fitSSM()` |\n| **教育データでの強み** | 短期予測、ITS分析 | 長期トレンドの解釈、欠測の多いデータ |\n:::\n\n状態空間モデル (SSM) は、**直接観測できない「真の状態」**と**ノイズを含む「観測値」**を分けて考える枠組みです。教育データの文脈で直感的に説明します。\n\n> **比喩**：学生の「真の英語力」は直接見えない（= 隠れた状態 $\\alpha_t$）。テストスコアは英語力に測定誤差が乗ったもの（= 観測値 $y_t$）。状態空間モデルは、ノイジーなテストスコアから真の英語力の推移を推定するモデルです。\n\n数学的には2つの方程式で表現されます。\n\n- **観測方程式**：$\\; y_t = Z_t\\,\\alpha_t + \\varepsilon_t,\\; \\varepsilon_t \\sim \\mathcal{N}(0, H_t)$ — 観測値 = 真の状態 × 観測行列 + 測定誤差\n- **状態方程式**：$\\; \\alpha_{t+1} = T_t\\,\\alpha_t + R_t\\,\\eta_t,\\; \\eta_t \\sim \\mathcal{N}(0, Q_t)$ — 真の状態がどう時間発展するか\n\nここで $H_t$ は測定誤差の分散、$Q_t$ は状態の変動（学習による英語力の変化）の分散です。**カルマンフィルタ**は時点 $t$ までの情報で状態を逐次推定し（リアルタイム予測）、**スムーザ**は系列全体を使って過去の状態を再推定します（事後的分析に適し、より滑らか）。`KFAS` の実装と推定手順は @helske2017 に基づきます。\n\n::: {.callout-note}\n#### 公式ドキュメント（実装参照先）\n- `dtw::dtw()`（引数仕様）: <https://cran.r-project.org/web/packages/dtw/refman/dtw.html>\n- `depmixS4::posterior()`（`global/local/filtering/smoothing`）: <https://cran.r-project.org/web/packages/depmixS4/refman/depmixS4.html>\n- `KFAS::KFS()`（`filtering` / `smoothing` 指定）: <https://cran.r-project.org/web/packages/KFAS/KFAS.pdf>\n- `fitted.KFS()`（`filtered = TRUE/FALSE`）: <https://cran.r-project.org/web/packages/KFAS/KFAS.pdf>\n:::\n\n#### カルマンフィルタの最小実行例（フィルタ vs スムーザ）\n\n以下は `KFAS` での最小例です。`filtered` は時点 $t$ までの情報で逐次推定、`smoothed` は全期間情報で再推定した系列です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_kf <- SSModel(toefl_ts ~ SSMtrend(1, Q = NA), H = NA)\nfit_kf <- fitSSM(model_kf, inits = c(log(var(toefl_ts)), 0))\n\nkfs_both <- KFS(\n  fit_kf$model,\n  filtering = c(\"state\", \"mean\"),\n  smoothing = c(\"state\", \"mean\")\n)\n\ndf_kf <- tibble(\n  time = as.numeric(time(toefl_ts)),\n  observed = as.numeric(toefl_ts),\n  filtered = as.numeric(fitted(kfs_both, filtered = TRUE)),\n  smoothed = as.numeric(fitted(kfs_both))\n)\n\nggplot(df_kf, aes(x = time)) +\n  geom_line(aes(y = observed, color = \"Observed\"), linewidth = 0.6, alpha = 0.7) +\n  geom_line(aes(y = filtered, color = \"Filtered\"), linewidth = 0.8) +\n  geom_line(aes(y = smoothed, color = \"Smoothed\"), linewidth = 0.9) +\n  scale_color_manual(values = c(Observed = \"grey50\", Filtered = \"#1b9e77\", Smoothed = \"#d95f02\")) +\n  labs(\n    title = \"Kalman filter vs smoother (TOEFL series)\",\n    x = \"Year\", y = \"Score\", color = \"\"\n  )\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/kalman-filter-minimal-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n`Filtered` がリアルタイム用途、`Smoothed` が事後分析用途です。教育データの報告では、通常は `Smoothed` の方が解釈しやすいトレンドになります。\n\n::: {.callout-important}\n#### フィルタとスムーザの実務的な使い分け\n- **進行中モニタリング**（今月までのデータで早期警戒したい）: `filtered`\n- **研究報告・事後分析**（全期間の傾向を解釈したい）: `smoothed`\n- 同一図に重ねると、終端付近で `filtered` が揺れやすい理由を視覚的に説明できます\n:::\n\n#### 欠測を含む系列の推定例（事前補間なし）\n\n状態空間モデルの強みは、欠測を `NA` のまま扱える点です。以下では、TOEFL系列に人工的な欠測を入れたうえで、`KFS` による平滑化推定を行います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntoefl_with_na <- toefl_ts\nmiss_idx <- sort(sample(4:(length(toefl_with_na) - 3), 4))\ntoefl_with_na[miss_idx] <- NA\n\nmodel_kf_na <- SSModel(toefl_with_na ~ SSMtrend(1, Q = NA), H = NA)\nfit_kf_na <- fitSSM(\n  model_kf_na,\n  inits = c(log(var(as.numeric(toefl_with_na), na.rm = TRUE)), 0)\n)\nkfs_na <- KFS(fit_kf_na$model, smoothing = c(\"state\", \"mean\"))\n\ndf_kf_na <- tibble(\n  time = as.numeric(time(toefl_with_na)),\n  observed = as.numeric(toefl_with_na),\n  smoothed = as.numeric(fitted(kfs_na)),\n  missing = is.na(observed)\n)\n\ncat(\"Artificial missing months:\", paste(miss_idx, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArtificial missing months: 4, 9, 16, 18 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(df_kf_na, aes(x = time)) +\n  geom_line(aes(y = smoothed, color = \"Smoothed\"), linewidth = 0.9) +\n  geom_point(aes(y = observed, color = \"Observed\"), size = 2, na.rm = TRUE) +\n  geom_point(\n    data = dplyr::filter(df_kf_na, missing),\n    aes(y = smoothed),\n    shape = 21,\n    fill = \"white\",\n    color = \"red\",\n    size = 2.8,\n    stroke = 1\n  ) +\n  scale_color_manual(values = c(Observed = \"grey45\", Smoothed = \"#0072B2\")) +\n  labs(\n    title = \"Kalman smoothing with missing observations (red circles = missing months)\",\n    x = \"Year\",\n    y = \"Score\",\n    color = \"\"\n  )\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/kalman-missing-demo-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n赤い丸は観測が欠けていた月で、その値はモデルが前後情報から推定した平滑値です。欠測率が高い場合は、`Q` と `H` の推定安定性（過度平滑化の有無）を必ず確認してください。\n\n#### KFAS による実装\n\n以下のコードでは、TOEFLスコアの時系列にローカルレベルの状態空間モデルを当てはめます。ARIMAが「差分によって定常化してから確率過程をモデル化する」のに対し、SSMは「**真の英語力**（隠れた状態 $\\alpha_t$）を直接推定し、テストスコアは測定誤差を含む観測値として扱う」アプローチです。カルマンスムーザにより、ノイズを除去した滑らかなトレンドを抽出します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ローカルレベル + トレンドの基本構造時系列\nmodel_ssm <- SSModel(toefl_ts ~ SSMtrend(1, Q = NA), H = NA)\nfit_ssm   <- fitSSM(model_ssm, inits = c(log(var(toefl_ts)), 0))\nkfs_ssm   <- KFS(fit_ssm$model, smoothing = c(\"state\", \"mean\", \"signal\"))\n\n# 平滑化されたシグナル\nsig_ssm <- as.numeric(fitted(kfs_ssm))\nsignal_ssm <- ts(sig_ssm, start = start(toefl_ts), frequency = frequency(toefl_ts))\n\nautoplot(toefl_ts) +\n  autolayer(signal_ssm, series = \"Smoothed signal\") +\n  labs(title = \"KFAS: smoothed TOEFL score trend\",\n       x = \"Year\", y = \"Score\") +\n  geom_vline(xintercept = 2022 + 12/12, linetype = \"dashed\", color = \"red\", alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/kfas-education-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### KFASプロットの読み方\n\n- **灰色の点/線（Data）**：観測されたTOEFLスコア（ノイズを含む生データ）\n- **色付きの線（Smoothed signal）**：カルマンスムーザが推定した「真のトレンド」。測定誤差を除去した滑らかな推移\n- **2つの線のギャップ**：観測値と平滑シグナルの差は推定された**測定誤差**に相当します。ギャップが大きいほど、モデルが「このデータ点はノイズが大きい」と判断しています\n- **介入時点（赤破線）での挙動**：平滑シグナルが介入時点付近でジャンプしていれば、SSMもレベル変化を検出しています\n\n**Q（状態分散）と H（観測分散）の関係**：\n- **Q >> H**（状態変動が大きく、測定誤差が小さい）：平滑線がデータに密着 → ほぼそのまま「真の値」として追跡\n- **H >> Q**（測定誤差が大きく、状態変動が小さい）：平滑線がデータからかなり離れた滑らかな曲線 → ノイズを強く平滑化\n:::\n\n::: {.callout-note}\n#### フィルタとスムーザの違い\n- **フィルタ**：時点tまでの情報のみで状態 $\\alpha_t$ を推定。リアルタイム用途（例：毎月のスコアをその都度予測）。\n- **スムーザ**：系列全体の情報を使って過去の状態 $\\alpha_t$ を再推定。事後的な分析（例：コホート全体のトレンドを振り返る）に適し、推定がより滑らか。\n\n行列 $Z, T, R, H, Q$ はそれぞれ観測 / 状態遷移 / 駆動ノイズ / 観測分散 / 状態分散に対応し、ローカルレベル / 線形トレンド / 季節は既定のブロックを組み合わせた特殊例です。\n\n#### SSM/カルマンの報告テンプレート（そのまま使える形）\n\n- 「`SSMtrend(...)` を含む状態空間モデルを `fitSSM()` で推定した」\n- 「`KFS(..., filtering = ..., smoothing = ...)` により filtered / smoothed series を取得した」\n- 「研究上の主解釈は `smoothed` を用い、欠測時点はモデル内で自然に推定した」\n:::\n\n#### ローカルレベル vs ローカル線形トレンド\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ローカルレベル\nm_ll  <- SSModel(toefl_ts ~ SSMtrend(1, Q = NA), H = NA)\nf_ll  <- fitSSM(m_ll, inits = c(0, 0))\n\n# ローカル線形トレンド（レベル＋傾き）\nm_llt  <- SSModel(toefl_ts ~ SSMtrend(2, Q = list(NA, NA)), H = NA)\nf_llt  <- fitSSM(m_llt, inits = c(0, 0, 0))\n\nAIC_ll  <- -2 * as.numeric(logLik(f_ll$model))  + 2 * length(f_ll$optim.out$par)\nAIC_llt <- -2 * as.numeric(logLik(f_llt$model)) + 2 * length(f_llt$optim.out$par)\n\ntibble(Model = c(\"Local Level\", \"Local Linear Trend\"),\n       AIC = round(c(AIC_ll, AIC_llt), 1)) |>\n  gt() |>\n  tab_header(title = \"AIC comparison: Local Level vs Local Linear Trend (KFAS)\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  AIC comparison: Local Level vs Local Linear Trend (KFAS)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nModel & AIC \\\\ \n\\midrule\\addlinespace[2.5pt]\nLocal Level & 118.3 \\\\ \nLocal Linear Trend & 118.2 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**AIC比較の読み方**：AICが小さいモデルが選好されます。ローカルレベル（状態 = レベルのみ）とローカル線形トレンド（状態 = レベル＋傾き）の差が2未満なら実質同等、10以上なら強い差です。TOEFLスコアには明確な上昇トレンドがあるため、ローカル線形トレンドが選択される可能性が高いです。\n\n::: {.callout-tip}\n#### 使い分けの目安\n- **ARIMA**：診断・同定が容易で、短期予測に強い。ACF/PACFによる構造把握が直感的。\n- **SSM（BSM）**：トレンド / 季節 / 不規則を「部品」ごとに推定・可視化。外れ値・欠測にも比較的頑健。教育データの長期的傾向の解釈にはSSMが適することが多い。\n:::\n\n::: {.callout-warning}\n#### KFASの `fitSSM` がNaNや最適化失敗を返す場合\n\n**症状**：`fitSSM()` が `NaN` を返す、または `optim.out$convergence` が0以外。\n\n**原因**：初期値が不適切、モデルが過度に複雑、またはデータのスケールが極端。\n\n**修正手順**：\n\n1. `inits` の初期値を変更して再実行（例：`c(0, 0)` → `c(log(var(y)/10), -1)`）\n2. より単純なモデルから始める（`SSMtrend(1, ...)` → `SSMtrend(2, ...)`の順に複雑化）\n3. データを標準化してからフィット（`scale(y)` を使用）\n4. `fitSSM(..., method = \"BFGS\")` でオプティマイザを変更\n:::\n\n### 季節ダミー vs 季節SSM（比較）\n\n季節性の扱いを**回帰ダミー変数**と**SSMの季節成分**で比較します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dataset 3（読解流暢性）で比較\ncycle_f <- factor(cycle(fluency_ts))\nX_seas  <- model.matrix(~ cycle_f)[, -1]\n\n# ダミー回帰 + ARIMA残差\nfit_seas_dummy <- auto.arima(fluency_ts, xreg = X_seas)\n\n# 季節SSM (KFAS)\nm_seas_ssm <- SSModel(fluency_ts ~ SSMtrend(1, Q = NA) + SSMseasonal(10, Q = NA), H = NA)\nf_seas_ssm <- fitSSM(m_seas_ssm, inits = c(0, 0, 0))\n\nAIC_dummy <- AIC(fit_seas_dummy)\nAIC_ssm_s <- -2 * as.numeric(logLik(f_seas_ssm$model)) + 2 * length(f_seas_ssm$optim.out$par)\n\ntibble(Model = c(\"Seasonal Dummies + ARIMA\", \"Seasonal SSM (KFAS)\"),\n       AIC = round(c(AIC_dummy, AIC_ssm_s), 1)) |>\n  gt() |>\n  tab_header(title = \"Seasonal dummies vs seasonal SSM: AIC comparison\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Seasonal dummies vs seasonal SSM: AIC comparison\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nModel & AIC \\\\ \n\\midrule\\addlinespace[2.5pt]\nSeasonal Dummies + ARIMA & 162.2 \\\\ \nSeasonal SSM (KFAS) & 133.5 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-tip}\nダミー回帰は**季節パターンが固定**の前提。SSM季節はパターンの緩やかな変化を許容するため、実務ではSSMが頑健なことが多い。\n:::\n\n### brms によるベイズ的時系列\n\nbrms は Stan を通じた**ベイズ推定**で、AR/MA 残差相関やガウス過程を柔軟に取り込めます。ベイズ的アプローチの利点は、係数の**不確実性を事後分布として**直接可視化・報告できることです。\n\n::: {.callout-tip}\n#### 第7章との接続\nbrmsの基礎（事前分布の設定、事後分布の解釈、MCMCの診断など）は**第7章「ベイズ推定」**で詳しく解説しています。ベイズの基本概念に不安がある場合は、先にそちらを参照してください。本セクションでは、第7章の知識を前提として、**時系列特有の拡張**（AR/MA残差相関、ガウス過程による平滑トレンド）に焦点を当てます。\n:::\n\nたとえば、「TOEFLスコアの月次上昇率は、先行研究から学期あたり2–5点程度と知られている」といった事前情報を**事前分布**として組み込むことも可能です。これは第7章で学んだ「ドメイン知識を事前分布に反映する」考え方の実践的な応用です。\n\n以下のコードでは、brmsを使ってTOEFLスコアにベイズ的なARMA(1,1)モデルを当てはめます。`cor_arma()` により残差の自己相関構造を明示的にモデル化します。ベイズ的アプローチの主な利点は、(1) **事前分布による正則化**で小標本でも安定した推定が可能、(2) 係数の**不確実性を事後分布として**直接可視化・報告できることです。`pp_check()` で事後予測分布が観測データとどの程度一致するかを確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_toefl <- tibble(time = 1:n_months, y = as.numeric(toefl_ts), id = 1)\n\nfit_brm_arma <- brm(\n  bf(y ~ 1),\n  data = df_toefl,\n  family = gaussian(),\n  autocor = cor_arma(~ time | id, p = 1, q = 1),\n  file = \"brms_arma_toefl\",\n  chains = 2, iter = 2000, cores = 2, seed = 2024\n)\nas_tibble(fixef(fit_brm_arma)) |>\n  tibble::rownames_to_column(\"Term\") |>\n  gt() |>\n  tab_header(title = \"Bayesian ARMA Model (brms)\") |>\n  fmt_number(columns = where(is.numeric), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Bayesian ARMA Model (brms)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\nTerm & Estimate & Est.Error & Q2.5 & Q97.5 \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 69.487 & 2.901 & 64.011 & 75.091 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\npp_check(fit_brm_arma)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/brms-arma-toefl-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### brms（ARMA）出力の読み方\n\n| 出力要素 | 意味 | 確認ポイント |\n|---------|------|-------------|\n| **Intercept** | 全体平均の事後推定（Estimate ± Est.Error） | 95% CI が0を含むかどうかは通常ここでは重要でない（切片なので） |\n| **ar[1]** | AR(1)係数の事後推定 | 正で大きいほどスコアの慣性が強い。95% CI が0を含まなければ有意な自己相関 |\n| **ma[1]** | MA(1)係数の事後推定 | 正なら正のショック修正。CI が0を含めばMAは不要かもしれない |\n| **sigma** | 残差の標準偏差 | 小さいほどモデルの当てはまりが良い |\n| **Rhat** | 収束診断 | **< 1.01** なら収束OK。1.1以上は非収束（チェーン数増加やイテレーション追加が必要） |\n| **Bulk_ESS / Tail_ESS** | 有効サンプルサイズ | **> 400**（理想は > 1000）。低すぎると事後分布の推定が不安定 |\n| **pp_check()** | 事後予測チェック | 薄い線（事後予測分布）が太い線（観測データ）を包んでいればOK |\n\n詳細な収束診断とpp_checkの解釈方法は**第7章**を参照してください。\n:::\n\nガウス過程を用いた**平滑トレンド**の例（`gp(time)`）。GPは非線形な学習曲線（プラトー、加速、S字カーブなど）を柔軟にモデル化できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_toefl <- df_toefl |>\n  mutate(time_sc = (time - min(time)) / (max(time) - min(time)))\n\nfit_brm_gp <- brm(\n  bf(y ~ gp(time_sc, k = 15)),\n  data = df_toefl,\n  family = gaussian(),\n  file = \"brm_gp_toefl\",\n  file_refit = \"always\",\n  chains = 2, iter = 2000, cores = 2, seed = 2024,\n  control = list(adapt_delta = 0.95, max_treedepth = 12),\n  save_pars = save_pars(all = TRUE)\n)\nas_tibble(fixef(fit_brm_gp)) |>\n  tibble::rownames_to_column(\"Term\") |>\n  gt() |>\n  tab_header(title = \"Bayesian GP Model (brms)\") |>\n  fmt_number(columns = where(is.numeric), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Bayesian GP Model (brms)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\nTerm & Estimate & Est.Error & Q2.5 & Q97.5 \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 73.441 & 3.963 & 65.737 & 81.893 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nce <- conditional_effects(fit_brm_gp, effects = \"time_sc\", nug = 1e-3)\nplot(ce, points = TRUE)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/brms-gp-toefl-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### GP出力の読み方\n\n- **conditional_effects プロット**：横軸が正規化された時間（0–1）、縦軸が予測スコア。黒い点が観測値、線が事後平均、帯が95%信頼区間。帯が狭いほどモデルの確信度が高い。\n- **GPの長さスケール (length-scale)**：GPがどの程度「滑らか」にフィットするかを制御するパラメータ。値が大きいほど滑らかで大域的なトレンドを捉え、小さいほど局所的な変動に追随します。\n- **プラトーの検出**：conditional_effectsのプロットで線が水平に近づく区間があれば、スコアの頭打ち（天井効果やプラトー）を示唆します。\n- `k = 15` は基底関数の数で、GPの近似精度を制御します。データ点数（24点）より大きくする必要はありません。\n:::\n\n::: {.callout-note}\n#### brms を選ぶ場面と利点\n\n**こんな場面で brms が威力を発揮します：**\n\n1. **小サンプル**（<30時点）：頻度論的ARIMA は推定が不安定になりがちですが、brmsでは事前分布が正則化の役割を果たし、**過適合を防ぎ**ます。\n2. **事前情報がある**：先行研究のメタ分析から「介入のステップ効果は3–7点」と分かっている場合、`prior(normal(5, 2), class = \"b\")` のように組み込めます。\n3. **不確実性の報告**：p値ではなく「効果が0.2以上である確率は92%」のような**直感的な確率報告**が可能です。\n4. **非線形トレンド**：`gp()` や `s()` を使った平滑トレンドで、学習曲線の**プラトー**（頭打ち）や**加速**を柔軟にモデル化できます。\n\n**注意**：brmsのコンパイル・サンプリングには時間がかかります（`file =` 引数でキャッシュを活用してください）。`pp_check()` による事後予測チェックと、`rhat` / `ess_bulk` による収束診断は必須です（詳細は第7章参照）。\n:::\n\n::: {.callout-warning}\n#### brmsのコンパイルが遅い / チェーンが収束しない場合\n\n**症状①（コンパイルが遅い）**：初回実行時にStanモデルのコンパイルに数分かかる。\n\n**対処**：`file =` 引数を必ず指定し、2回目以降はキャッシュから読み込む。`backend = \"cmdstanr\"` に切り替えるとコンパイルが高速化される場合がある。\n\n**症状②（収束しない）**：Rhat > 1.01、divergent transitions の警告、tree depth exceeded。\n\n**対処**：\n\n1. `control = list(adapt_delta = 0.95, max_treedepth = 12)` で探索を丁寧にする\n2. 事前分布を明示的に指定し、パラメータ空間を制約する\n3. `iter` を増やす（4000以上）\n4. データのスケーリング（標準化）を確認する\n5. モデルを簡素化する（例：ARMA(1,1) → AR(1) のみ）\n:::\n\n\ntsibble（整然時系列）＋ fable（モデリング）＋ feasts（特徴量・診断）による、tidyverse スタイルの時系列分析パイプラインです。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ts -> tsibble へ\nlibrary(fable); library(tsibble); library(feasts)\nvocab_tbl <- as_tsibble(vocab_ts)\n\n# モデリング（ARIMA/ETS）と予測\nfit_tbl <- vocab_tbl |> model(ARIMA = ARIMA(value), ETS = ETS(value))\nfc_tbl  <- fit_tbl |> forecast(h = 10)\nautoplot(fc_tbl, vocab_tbl)\n\n# 残差診断\nfit_tbl |> dplyr::select(ARIMA) |> gg_tsresiduals()\n```\n:::\n\n\n::: {.callout-note}\nfable系は複数系列・キー（グループ）の同時処理に強く、**再現可能なパイプライン**を組みやすいのが特長です。たとえば、複数クラスの語彙テストスコアを同時にモデル化し、クラスごとに最適なモデルを自動選択できます。\n:::\n\n------------------------------------------------------------------------\n\n## マクロ時系列からミクロ時系列へ：テストスコアから音声波形へ\n\nここまでのセクション（Part A–C）では、**週単位・月単位**のテストスコアという「マクロな時系列」を分析してきました。ここからは、**毎秒16,000回**でサンプリングされる音声波形という「ミクロな時系列」に目を向けます。\n\n一見まったく異なるデータに見えますが、実は**同じ数学的原理**が貫いています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Feature = c(\"Sampling rate\", \"Autocorrelation reveals...\",\n              \"Periodicity\", \"Decomposition\",\n              \"Stationarity needed for...\"),\n  `Macro (test scores)` = c(\"1/week or 1/month\", \"Score dependency (AR structure)\",\n                              \"Academic calendar (exams)\", \"Trend + seasonal + remainder\",\n                              \"ARIMA modeling\"),\n  `Micro (speech)` = c(\"16,000/second\", \"F0: fundamental frequency (pitch)\",\n                         \"Vocal fold vibration\", \"Source (F0) + filter (formants) + noise\",\n                         \"Spectral analysis within a frame\")\n) |>\n  gt() |>\n  tab_header(title = \"Macro vs. micro time series: conceptual parallels\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Macro vs. micro time series: conceptual parallels\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lll}\n\\toprule\nFeature & Macro (test scores) & Micro (speech) \\\\ \n\\midrule\\addlinespace[2.5pt]\nSampling rate & 1/week or 1/month & 16,000/second \\\\ \nAutocorrelation reveals... & Score dependency (AR structure) & F0: fundamental frequency (pitch) \\\\ \nPeriodicity & Academic calendar (exams) & Vocal fold vibration \\\\ \nDecomposition & Trend + seasonal + remainder & Source (F0) + filter (formants) + noise \\\\ \nStationarity needed for... & ARIMA modeling & Spectral analysis within a frame \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n具体的な対応関係：\n\n- テストスコアの**自己相関**（今週の点数は先週に依存）→ 音声波形の**自己相関**でF0（声帯振動の周期）を推定する（セクション10で実演）\n- テストスコアの**周期性**（試験サイクル）→ 音声の**周期性**（声帯振動の繰り返し）\n- STLによる**トレンド＋季節＋残差の分解** → 音声の**ソース（声帯振動）＋フィルタ（声道の共鳴 = フォルマント）＋ノイズ**への分離\n- テストスコアの**定常化**（差分を取ってARIMAを適用）→ 音声フレーム内の**定常性**を仮定したスペクトル分析\n\n英語教育研究者にとって、音声分析は以下の場面で重要です：\n\n1. **L2発音研究**：学習者と母語話者の母音空間（F1/F2散布図）を比較\n2. **韻律研究**：F0のcontour（抑揚パターン）を流暢性の指標として分析\n3. **縦断的研究**：学習者の音響特徴を時間経過で追跡 — これはまさに「マクロな時系列」と「ミクロな時系列」の交差点\n\n------------------------------------------------------------------------\n\n## 音声波形の時系列分析（英語母音の例）\n\n英語教育・応用言語学では、英語母音の産出に関する研究で**基本周波数（F0）**や**ホルマント（F1/F2/F3）**が頻繁に分析されます。母音はおおむね**周期的な声帯振動**（F0）と、**声道の共鳴**（ホルマント）によってスペクトル上に調波列＋ピーク（F1/F2/…）として現れます。\n\nここでは、**ソース–フィルタ・モデル**で母音ライクな波形を合成し、F0を**自己相関**・**ケプストラム**で推定し、スペクトルから**調波構造**を確認する例を示します。合成データを用いることで、完全に再現可能な環境で音声分析の基礎を体験できます。\n\n::: {.callout-note}\n### ソース–フィルタ・モデルとは\n\n音声の生成は、**ソース**（声帯振動 → 倍音列を生成）と**フィルタ**（声道 → 特定の周波数を増幅・減衰）の2段階で近似できます。これは @fant1960 による古典的モデルです。\n\n- **ソース**：声帯が開閉する振動の基本周波数がF0。男性は約100–150 Hz、女性は約200–250 Hz、子供は約250–350 Hz。この振動から F0 の整数倍（倍音, harmonics: f0, 2f0, 3f0, ...）のエネルギーが生成されます。\n- **フィルタ**：声道（口腔・鼻腔・咽頭）の共鳴特性。倍音列のうち、共鳴周波数（= フォルマント）に近い成分が増幅されます。\n\nこのモデルのおかげで、F0（ピッチ、話者の声の高さ）とフォルマント（母音の音色）を**独立に**分析できます。たとえば、同じ/a/を高い声で言っても低い声で言っても、F1/F2パターンは大きく変わりません。\n:::\n\n::: {.callout-note}\n### フォルマントとは？\n\nフォルマントは声道の**共鳴周波数**です。瓶の口に息を吹き込むと特定の音が鳴るように、声道の形状に応じた周波数で音が増幅されます。舌の位置や口の開き具合を変えることで声道の形が変わり、異なる母音が産出されます。第1フォルマント（F1）は口の開き、第2フォルマント（F2）は舌の前後位置に主に対応します。\n:::\n\n### 合成母音の作成（/i/ と /a/ の典型的フォルマントを参考）\n\n以下のコードでは、ソース-フィルタ・モデルに基づいて英語母音 /i/（\"beat\"の母音）と /a/（\"father\"の母音）の合成波形を作成します。F0 = 120 Hz（男性の典型値）の調波列をソースとして生成し、各母音の典型的なフォルマント周波数でフィルタリングします。合成データを使うことで、**既知のF0とフォルマント周波数に対する推定精度を検証**でき、音声分析の原理を再現可能な形で体験できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 合成関数：基本周波数f0の調波を合成し、フォルマントで包絡を付ける\nvowel_synth <- function(f0 = 120, dur = 0.5, fs = 16000,\n                        formants = c(300, 2200, 3000),\n                        bandwidths = c(60, 90, 150)){\n  t  <- seq(0, dur, by = 1/fs)\n  nh <- floor((fs/2)/f0)  # ナイキストまでの調波数\n  sig <- rep(0, length(t))\n  # 各調波の振幅をフォルマントのガウス包絡で整形\n  for(h in 1:nh){\n    f   <- h * f0\n    env <- prod(exp(-0.5 * ((f - formants)/bandwidths)^2))\n    sig <- sig + env * sin(2*pi*f*t)\n  }\n  # 窓＆正規化\n  w   <- 0.5 - 0.5*cos(2*pi*(0:(length(t)-1))/(length(t)-1))\n  sig <- sig * w\n  sig <- sig / max(abs(sig))\n  ts(sig, frequency = fs)\n}\n\nfs <- 16000\n# 参考フォルマント（典型値）：/i/ と /a/（学術報告に見られる範囲の例）\nvw_i <- vowel_synth(f0 = 120, fs = fs, formants = c(300, 2200, 3000), bandwidths = c(60,90,150))\nvw_a <- vowel_synth(f0 = 120, fs = fs, formants = c(730, 1100, 2440), bandwidths = c(80,90,130))\n\nautoplot(vw_i) + labs(title = 'Synthetic vowel /i/ (waveform)', x = 'Time', y = 'Amplitude')\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/synth_vowels-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nautoplot(vw_a) + labs(title = 'Synthetic vowel /a/ (waveform)', x = 'Time', y = 'Amplitude')\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/synth_vowels-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-tip}\nフォルマント値（F1/F2）は**性別・年齢・話速**で大きく異なります。本節の合成は教育目的の近似で、実測にはPraat等で**安定区間**を注釈し、LPCや反射法での推定を推奨します。\n:::\n\n### Create a .wav file for downstream examples\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preferred: generate via Python utility\n#   python3 audio_generation.py --emit-vowels i --outdir data/audio --sample-rate 16000 --duration-ms 2000\n# Fallback: show an instruction if the file is missing\nif (!file.exists('data/audio/vowel_i.wav')) {\n  if (!dir.exists('data/audio')) dir.create('data/audio', recursive = TRUE)\n  message(\"Missing data/audio/vowel_i.wav. Run: python3 audio_generation.py --emit-vowels i --outdir data/audio --sample-rate 16000 --duration-ms 2000\")\n} else {\n  message(\"Found data/audio/vowel_i.wav\")\n}\n```\n:::\n\n\n### F0推定：自己相関とケプストラム\n\n以下のコードでは、合成母音波形から2つの方法（**自己相関法**と**ケプストラム法**）でF0を推定します。自己相関法は、セクション4でテストスコアのACFからAR次数を同定したときと**まったく同じ原理**を応用しています — 信号の中の「繰り返しの周期」を検出するという点で共通です。\n\nF0（基本周波数）は自己相関の**主要ピーク**（ラグ）や、ケプストラムの**主要ピーク**（ケフレンシ）で推定できます。ここで使う自己相関法は、セクション4でテストスコアのAR次数を同定したときと**まったく同じ原理**です — 信号の中の「繰り返しの周期」を検出しています。\n\n::: {.callout-note}\n#### ケプストラムの直感的理解\n\nケプストラム（cepstrum）は「spectrum」の前半を逆にした造語で、**スペクトルのスペクトル**とも呼ばれます。\n\n処理の流れ：`信号 → FFT → |X(f)|² → log → 逆FFT → ケプストラム`\n\n音声信号のスペクトルには、F0の**倍音列**（f0, 2f0, 3f0, ...）が**等間隔**に並んでいます。この等間隔パターンは、対数スペクトル上では**周期的な成分**になります。逆FFTを取ることで、この周期性に対応するピークが「ケフレンシ」（quefrency, 単位は秒）軸上に現れます。そのピーク位置の逆数がF0です。\n\nケプストラムの利点は、声帯振動（ソース）と声道の共鳴（フィルタ）を**分離**できることです。低ケフレンシ成分はフォルマント（声道の形状）に対応し、高ケフレンシのピークがF0（声帯振動の周期）に対応します。\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest_f0_ac <- function(x, fs, fmin=60, fmax=300){\n  xr  <- as.numeric(scale(x, center = TRUE, scale = FALSE))\n  ac  <- stats::acf(xr, lag.max = floor(fs/fmin), plot = FALSE)$acf[-1]\n  lags<- 1:length(ac)\n  # 許容範囲内の最大ピーク\n  idx <- which(lags >= floor(fs/fmax) & lags <= floor(fs/fmin))\n  lag0<- lags[idx][which.max(ac[idx])]\n  fs/lag0\n}\n\nest_f0_cep <- function(x, fs, fmin=60, fmax=300){\n  X   <- stats::fft(x)\n  logS<- log(pmax(Mod(X), 1e-6))\n  cep <- Re(stats::fft(logS, inverse = TRUE))\n  q   <- 0:(length(cep)-1) / fs            # ケフレンシ（秒）\n  # 1/fmax 〜 1/fmin の範囲で最大を取る\n  idx <- which(q >= 1/fmax & q <= 1/fmin)\n  q0  <- q[idx][which.max(cep[idx])]\n  1/q0\n}\n\nf0_i_ac  <- est_f0_ac(vw_i, fs)\nf0_i_cep <- est_f0_cep(as.numeric(vw_i), fs)\nf0_a_ac  <- est_f0_ac(vw_a, fs)\nf0_a_cep <- est_f0_cep(as.numeric(vw_a), fs)\n\ngt(tibble(Vowel=c('/i/','/i/','/a/','/a/'), Method=c('ACF','Cepstrum','ACF','Cepstrum'),\n          F0 = round(c(f0_i_ac, f0_i_cep, f0_a_ac, f0_a_cep),1))) |>\n  tab_header(title = 'F0 estimates (Hz)')\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  F0 estimates (Hz)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llr}\n\\toprule\nVowel & Method & F0 \\\\ \n\\midrule\\addlinespace[2.5pt]\n/i/ & ACF & 108.1 \\\\ \n/i/ & Cepstrum & 120.3 \\\\ \n/a/ & ACF & 120.3 \\\\ \n/a/ & Cepstrum & 120.3 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**F0推定結果の読み方**：合成母音のF0は 120 Hz に設定しました。ACF法とケプストラム法の推定値が両方とも 120 Hz に近ければ、推定が正しく機能しています。もし値が 240 Hz（2倍）や 60 Hz（半分）に跳んでいる場合は、**倍音跳躍** (octave jump) が発生しています（後述の callout-warning を参照）。/i/ と /a/ で同じF0が推定されるべきです — F0は声帯振動の周期であり、母音の種類には依存しません。\n\n::: {.callout-note}\n#### ACF法とケプストラム法の比較\n\n| 方法 | 原理 | 長所 | 短所 |\n|------|------|------|------|\n| ACF法 | 信号の周期ピークを検出 | 直感的、実装が簡単 | 無声区間で誤推定、振幅変動に敏感 |\n| ケプストラム法 | 畳み込み分離（スペクトルの対数→逆FFT） | ソースとフィルタを分離でき頑健 | 短窓では分解能が低下 |\n\nしきい値・探索帯域（`fmin`/`fmax`）は対象話者に合わせて調整します。男性は80–200 Hz、女性は150–350 Hz、子供は200–500 Hz が一般的な範囲です。\n:::\n\n::: {.callout-warning}\n#### F0の倍音跳躍 (octave jump) に注意\n\nF0推定で最も頻出するエラーが**倍音跳躍**（octave jump）です。アルゴリズムがF0を2倍（1オクターブ上）や半分（1オクターブ下）の値で検出してしまう現象です。\n\n**検出方法**：連続するフレーム間でF0が急に2倍や半分になっていないかチェックします。\n\n```\n# 倍音跳躍の簡易検出・修正（概念コード）\nfix_octave_jumps <- function(f0_track, threshold = 0.4) {\n  for (i in 2:length(f0_track)) {\n    if (!is.na(f0_track[i]) && !is.na(f0_track[i-1])) {\n      ratio <- f0_track[i] / f0_track[i-1]\n      if (ratio > (2 - threshold)) f0_track[i] <- f0_track[i] / 2\n      else if (ratio < (0.5 + threshold/2)) f0_track[i] <- f0_track[i] * 2\n    }\n  }\n  f0_track\n}\n```\n\n**対策**：(1) Praatの`To Pitch (ac)...`は倍音跳躍の自動修正を内蔵しています。(2) R で独自実装する場合は、メディアンフィルタで平滑化してから外れ値を検出します。(3) `fmin`/`fmax` の範囲を話者の実際のF0範囲に合わせて狭くすると、誤推定を減らせます。\n:::\n\n### スペクトルと調波・ホルマントの概観\n\n以下のコードでは、合成母音のスペクトル（周波数ごとの振幅分布）を可視化します。FFT（高速フーリエ変換）で時間領域の波形を周波数領域に変換し、F0の整数倍に現れる**調波列** (harmonics) と、フォルマント周波数付近で振幅が増幅された**スペクトル包絡のピーク**を確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_spectrum <- function(x, fs, nfft=4096){\n  X <- fft(as.numeric(x)[1:min(length(x), nfft)])\n  f <- (0:(length(X)-1)) * fs/length(X)\n  amp <- 20*log10(pmax(Mod(X), 1e-6))\n  tibble(f=f, amp=amp) |>\n    filter(f <= fs/2) |>\n    ggplot(aes(f, amp)) + geom_line() +\n    labs(x='Frequency (Hz)', y='Amplitude (dB)') + theme_bw(base_size = 12) + theme(legend.position = \"bottom\")\n}\n\nplot_spectrum(vw_i, fs) + labs(title='Spectrum of synthetic /i/')\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/spectrum_helpers-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nplot_spectrum(vw_a, fs) + labs(title='Spectrum of synthetic /a/')\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/spectrum_helpers-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### スペクトルの読み方\n\n- **横軸**（Frequency, Hz）：周波数。左が低音、右が高音。\n- **縦軸**（Amplitude, dB）：各周波数のエネルギー。dBスケールは対数的なので、20 dBの差は振幅で約10倍に相当します。\n- **等間隔のピーク（調波列）**：F0の整数倍（f0, 2f0, 3f0, ...）に対応。ピーク間の間隔がF0です。合成母音ではF0 = 120 Hzなので、120 Hz, 240 Hz, 360 Hz, ... にピークが並びます。\n- **包絡の山（フォルマント）**：調波列全体を滑らかに結ぶ包絡線に注目すると、特定の周波数帯でエネルギーが特に強くなっています。これがフォルマント（F1, F2, F3）です。\n- **/i/ と /a/ の違い**：/i/ はF1が低く（~300 Hz）F2が高い（~2200 Hz）のに対し、/a/ はF1が高く（~730 Hz）F2が低い（~1100 Hz）。このパターンの違いが母音の音色を決定します。\n:::\n\n::: {.callout-tip}\n窓長（`wl`）は**時間分解能–周波数分解能のトレードオフ**。音声では 20–40 ms 程度が目安。**プリエンファシス**（高域強調）で包絡が見やすくなることもあります。\n:::\n\n::: {.callout-tip}\n厳密なホルマント推定には**LPC**や専用ツール（例：Praat、`seewave::lpc` など）が有用です。本稿ではベースRでの**概観**に留め、再現性を重視しました。実データ計測では**録音条件・マイク・話速**の影響も考慮してください。\n:::\n\n### 実データ（.wav）への応用（概念；eval=FALSE）\n\n録音データの母音部分を切り出して、F0とホルマントを推定します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use the generated vowel (see the preparation chunk below)\nw <- readWave('data/audio/vowel_i.wav')            # mono / sample rate\nseewave::oscillo(w)                      # 波形\nf0 <- seewave::fund(w, f = w@samp.rate, ovlp = 50, from = 0.2, to = 0.3, plot = TRUE)\n# Approximate LPC envelope (phonTools)\nphonTools::lpc(as.numeric(w@left), fs = w@samp.rate, show = TRUE)\n```\n:::\n\n\n::: {.callout-note}\n研究例（概要）：学習者の**英語/i/と/ɪ/** のF1/F2空間がネイティブの分布と異なる、ピッチ変動（F0の周期性）が母語のイントネーション転移を示す、など。実践では、単語/文コンテキスト、ピッチ範囲正規化、共変量（性別/年齢）を含めてGLMMや階層ベイズで分析します。\n:::\n\n------------------------------------------------------------------------\n\n## Rでwav処理入門（tuneR・seewave）\n\n\n::: {.callout-important}\n### 録音品質チェックリスト\n\n音声分析の信頼性は**録音品質**に大きく依存します。分析を始める前に以下を確認してください。\n\n| チェック項目 | 基準 | 確認方法 |\n|---|---|---|\n| **サンプリングレート** | 16 kHz以上（フォルマント分析には最低8 kHz） | `w@samp.rate` |\n| **ビット深度** | 16-bit以上 | `w@bit` |\n| **クリッピング** | 波形が±1.0で平坦化していないこと | `max(abs(w@left))` が0.95以下 |\n| **SNR（信号対雑音比）** | 30 dB以上が望ましい | 無音区間と発話区間のRMS比 |\n| **モノラル** | 分析はモノラルで行う | `w@stereo` が `FALSE` |\n| **背景ノイズ** | 一定レベルの定常ノイズであること | スペクトログラムの目視確認 |\n\n**よくある問題と対策**：\n\n- **クリッピング**：マイク入力レベルが高すぎると波形が「切り取られ」、F0やフォルマントの推定精度が著しく低下します。録音時のゲイン設定で防止します。\n- **部屋の反響**：反射音がフォルマントのピークを歪めます。吸音材のある部屋やヘッドセットマイクの使用を推奨します。\n- **圧縮音声**：MP3等の非可逆圧縮はスペクトル構造を変化させます。必ず**WAV（無圧縮）**で録音してください。\n:::\n\n\n### 1) ファイルを読む・基本情報を確認\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (file.exists('data/audio/vowel_i.wav')) {\n  w <- readWave('data/audio/vowel_i.wav')  # パスは適宜\n  w                                     # bit数・サンプリングレートなど\n  w@stereo                               # TRUEならステレオ\n\n  # モノラル化（左チャンネル）/ 正規化 / ダウンサンプリング（16 kHz）\n  w_mono <- mono(w, which = 'left')\n  w_norm <- tuneR::normalize(w_mono, unit = '16', center = TRUE)\n  w_ds   <- downsample(w_norm, samp.rate = 16000)\n} else {\n  message('data/audio/vowel_i.wav not found. See the Python command above to generate it.')\n}\n```\n:::\n\n\n### 2) 可視化（波形・スペクトログラム）\n\n以下のコードでは、音声データを2つの方法で可視化します。**波形** (oscillogram) は時間軸に沿った振幅の変化を示し、発話区間や無音区間の特定に使います。**スペクトログラム**は時間×周波数の2次元表現で、色の濃さがエネルギーの強さを表します。フォルマントは横に連なる暗い帯として現れます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists('w_ds')) {\n  oscillo(w_ds)                                            # 時間波形\n  spectro(w_ds, wl = 512, ovlp = 75, wn = 'hanning',       # スペクトログラム\n          flim = c(0, 5))                                  # 0–5 kHz を表示\n\n  # スペクトルの平均（スペクトル包絡の概観）\n  meanspec(w_ds, f = w_ds@samp.rate, wl = 1024)\n} else {\n  message('Skip viz: w_ds not available')\n}\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_viz-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_viz-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_viz-3.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-note}\n#### スペクトログラムの読み方\n\n| 要素 | 意味 | 確認ポイント |\n|------|------|-------------|\n| **横軸** | 時間（秒） | 発話の開始・終了、母音・子音の境界を確認 |\n| **縦軸** | 周波数（kHz） | フォルマント分析では 0–5 kHz の範囲に注目 |\n| **色の濃さ** | エネルギーの強さ（dB） | 暗い帯＝フォルマント（声道の共鳴） |\n| **横に連なる暗い帯** | フォルマント（F1, F2, F3...） | 下から順にF1、F2、F3 |\n| **縦の縞模様** | 声帯振動の各パルス | 有声区間で見られる。縞の間隔がF0の逆数 |\n| **均一な高周波ノイズ** | 無声摩擦音（/s/, /f/など） | 高周波帯に広がるエネルギー |\n\n`wl = 512` は窓長（サンプル数）で、16 kHzサンプリングなら約32 msに相当します。窓長を長くすると周波数分解能が上がり（フォルマントが鮮明に）、短くすると時間分解能が上がります（過渡的な変化が見やすく）。\n:::\n\n### 3) 記述統計（長さ・RMS・ZCR・スペクトル特徴）\n\n以下のコードでは、音声ファイルの基本的な記述統計を算出します。これらの指標は、録音品質の確認やデータセット全体の概観把握に使います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists('w_ds')) {\n  dur_sec <- length(w_ds@left) / w_ds@samp.rate            # 長さ（秒）\n  rms_amp <- seewave::rms(w_ds)                            # 振幅RMS\n  zcr_val <- seewave::zcr(w_ds)                            # ゼロ交差率\n\n  # スペクトル特徴（重心・スプレッドなど）\n  sp   <- meanspec(w_ds, f = w_ds@samp.rate, wl = 1024, plot = FALSE)\n  prop <- seewave::specprop(sp, f = w_ds@samp.rate)\n  prop$cent                     # スペクトル重心（Hz）\n\n  data.frame(duration = dur_sec, rms = rms_amp, zcr = zcr_val, centroid = prop$cent)\n} else {\n  message('Skip stats: w_ds not available')\n}\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_stats-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    duration rms   zcr.time   zcr.zcr centroid\n1  0.5000625  NA 0.00000000 0.1328125 1088.806\n2  0.5000625  NA 0.03571875 0.1347656 1088.806\n3  0.5000625  NA 0.07143750 0.1347656 1088.806\n4  0.5000625  NA 0.10715625 0.1347656 1088.806\n5  0.5000625  NA 0.14287500 0.1347656 1088.806\n6  0.5000625  NA 0.17859375 0.1347656 1088.806\n7  0.5000625  NA 0.21431250 0.1347656 1088.806\n8  0.5000625  NA 0.25003125 0.1347656 1088.806\n9  0.5000625  NA 0.28575000 0.1347656 1088.806\n10 0.5000625  NA 0.32146875 0.1347656 1088.806\n11 0.5000625  NA 0.35718750 0.1347656 1088.806\n12 0.5000625  NA 0.39290625 0.1347656 1088.806\n13 0.5000625  NA 0.42862500 0.1347656 1088.806\n14 0.5000625  NA 0.46434375 0.1347656 1088.806\n15 0.5000625  NA 0.50006250 0.1347656 1088.806\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n#### 音響記述統計の読み方\n\n| 指標 | 意味 | 典型的な値の目安 |\n|------|------|----------------|\n| **duration** | 音声の長さ（秒） | 持続母音: 0.5–2秒、単語: 0.3–1秒 |\n| **RMS** (Root Mean Square) | 振幅の実効値（音量の指標） | 正規化後は 0–1 の範囲。0.01未満は無音に近い |\n| **ZCR** (Zero Crossing Rate) | 波形がゼロを横切る頻度 | 有声音（母音）で低く、無声摩擦音（/s/）で高い |\n| **Spectral centroid** | スペクトルの「重心」周波数（Hz） | 明るい音色ほど高い。母音 /i/ > /a/ が一般的 |\n\nこれらの値は**録音品質の異常検出**にも使えます。たとえば、RMSが極端に低いファイルはマイク設定のミス、ZCRが異常に高いファイルはノイズ混入の可能性を示します。\n:::\n\n### 4) ピッチトラック（F0）とフォルマント概観\n\n以下のコードでは、`seewave::fund()` でF0トラック（時間に沿ったF0の変化）を推定し、`phonTools::lpc()` でLPC（線形予測符号化）によるスペクトル包絡を算出します。F0トラッキングの結果自体が**時系列データ**であり、Part A–Cで学んだ手法を直接適用できます。\n\n::: {.callout-tip}\n#### F0トラックへの時系列分析の応用\n\n- **STL分解**：文全体のF0 contourからトレンド（declination：文末に向かってF0が下がる傾向）と局所変動を分離\n- **自己相関（ACF）**：F0の周期性を検出 — 流暢な発話ではリズミカルなF0パターンが見られることがある\n- **ARIMAモデル**：学習者のF0変動パターンが経時的にどう変化するかを定量化\n- **変化点検出（`strucchange`）**：音読の途中で韻律パターンが変化した時点を自動検出\n\nたとえば、学習者を毎月録音し、各録音からF0の変動係数（CV）を算出すれば、それは「マクロな時系列」になり、ITS分析で発音訓練の効果を評価できます。\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists('w_ds')) {\n  fund(w_ds, f = w_ds@samp.rate, ovlp = 50,                     # F0トラック\n       threshold = 5, fmax = 400, plot = TRUE)\n\n  # Show LPC spectral envelope using phonTools\n  phonTools::lpc(as.numeric(w_ds@left), fs = w_ds@samp.rate, show = TRUE)\n} else {\n  message('Skip pitch/formants: w_ds not available')\n}\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_pitch_formants-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_pitch_formants-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1.00000000 -1.11542774 -0.55861177  0.47037460  0.75032055  0.30696682\n [7] -0.17081469 -0.39523382 -0.24516647 -0.03868762  0.36289110  0.31817672\n[13]  0.11851563 -0.01379901 -0.16889925 -0.11970438  0.03246043  0.11949892\n[19]  0.10778764 -0.02178952\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n#### F0トラック・LPCスペクトルの読み方\n\n- **F0トラックプロット**：横軸が時間（秒）、縦軸がF0（Hz）。安定した有声区間ではF0が一定の帯域に集中します。急な跳躍や欠損は無声区間や推定エラーの可能性があります。\n- **LPCスペクトル包絡**：横軸が周波数（Hz）、縦軸が振幅（dB）。包絡のピーク（山）がフォルマント周波数に対応します。最初の山がF1（口の開き）、次がF2（舌の前後位置）です。\n- **F0とフォルマントの独立性**：ソース-フィルタ・モデルにより、F0（声の高さ）とフォルマント（母音の音色）は独立に分析できます。高い声で /a/ を言っても、F1/F2パターンは大きく変わりません。\n:::\n\n### 5) トリミング・フィルタリング・保存\n\n以下のコードでは、音声ファイルの不要な部分（無音区間・ノイズ区間）をトリミングし、バンドパスフィルタで分析に不要な周波数帯を除去してから保存します。フォルマント分析では 300–8000 Hz 程度のバンドパスが一般的です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (exists('w_ds')) {\n  # Compute duration and choose a safe cut window\n  dur <- length(w_ds@left) / w_ds@samp.rate\n  start_t <- 0.2\n  end_t   <- 0.6\n  # Clamp to available duration\n  start_t <- max(0, min(start_t, dur))\n  end_t   <- max(start_t + 1e-3, min(end_t, dur))\n  # If still too short, fall back to [0, min(0.4, dur)]\n  if (end_t - start_t < 0.02) {\n    start_t <- 0\n    end_t   <- min(0.4, dur)\n  }\n  # Final guard: ensure positive window\n  if (end_t <= start_t) {\n    start_t <- 0\n    end_t   <- dur\n  }\n\n  # Cut and filter\n  w_cut <- cutw(w_ds, from = start_t, to = end_t, output = 'Wave')\n  w_bp <- ffilter(w_cut, f = w_ds@samp.rate, from = 300, to = 8000,\n                  bandpass = TRUE, output = 'Wave')\n\n  writeWave(w_bp, 'data/audio/vowel_i_proc.wav')\n} else {\n  message('Skip edit/save: w_ds not available')\n}\n```\n:::\n\n\n::: {.callout-note}\n#### サンプリングとビット深度\n- 16–48 kHz, 16-bit mono で十分な解析が可能（フォルマントは〜5 kHz程度）。\n- 24-bitは**ダイナミックレンジ**が広がるが、ファイルサイズ増に注意。解析では**正規化**と**クリップ回避**が肝要です。\n:::\n\n### 6) 複数ファイルのバッチ処理（記述統計をCSVに）\n\n以下のコードでは、`data/audio/` フォルダ内のすべての .wav ファイルに対して、前処理（モノラル化・正規化）→ 記述統計（duration / ZCR / RMS / スペクトル重心）の算出を自動化し、結果をCSVに保存します。複数話者・複数項目のデータを一括処理するパイプラインの雛形です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiles <- list.files('data/audio', pattern = '\\\\.(wav|WAV)$', full.names = TRUE)\n\nsummarise_wav <- function(path){\n  w <- readWave(path) |> mono('left') |> tuneR::normalize(unit='16', center=TRUE)\n  dur <- length(w@left)/w@samp.rate\n  zcr <- zcr(w); rmsv <- rms(w)\n  sp  <- meanspec(w, f = w@samp.rate, wl=1024, plot=FALSE)\n  cen <- specprop(sp, f = w@samp.rate)$cent\n  data.frame(file = basename(path), duration = dur, zcr = zcr, rms = rmsv, centroid = cen)\n}\n\ntbl <- map_dfr(files, summarise_wav)\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_batch-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_batch-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nwrite.csv(tbl, 'audio_summary.csv', row.names = FALSE)\ntbl |> DT::datatable(caption = 'Audio files: descriptive stats')\n```\n\n::: {.cell-output-display}\n![](13_時系列データ分析_ARIMA_files/figure-pdf/wav_batch-3.pdf){fig-pos='H'}\n:::\n:::\n\n\n::: {.callout-tip}\nPraatやELANなどの標準ツールとRを組み合わせると、**特徴量抽出 → 統計解析（GLMM/ベイズ）**を一貫して再現可能にできます。Rでは`tidyverse`で表整形、`lme4`/`brms`で推定、`emmeans`/`ggeffects`で解釈・図示が定番です。\n:::\n\n------------------------------------------------------------------------\n\n## 生成データ（audio_generation.py）をRで一括解析（ネイティブパイプ）\n\n以下は、Pythonの`audio_generation.py`で作成された最小データセット（`./audio_dataset`）を、Rで読み込み→記述統計→F0推定→集約保存する最小パイプラインです。R 4.1+ のネイティブパイプ（`|>`）を使用しています。\n\n### ステップ\n\n- メタデータCSVの読み込み（ファイルパスを取得）\n- wavの標準前処理（モノラル化・正規化）\n- 記述統計（duration/RMS/ZCR/スペクトル重心）\n- F0（fund）を持続母音は中央区間、文は全区間で中央値推定\n- テーブルを保存して後続（GLMMなど）へ\n\n以下のパイプラインでは、Pythonの `audio_generation.py` で生成した最小データセットをRで一括処理します。メタデータCSVの読み込み → wavの前処理（モノラル化・正規化）→ 記述統計の算出 → F0の中央値推定 → テーブルの保存、という流れを R 4.1+ のネイティブパイプ（`|>`）で記述しています。保存した特徴量テーブルは、そのまま GLMM や階層ベイズの入力データとして使えます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# このコードは存在チェックを行うため、ビルド環境に音声がなくても安全に動きます\nif (file.exists(\"audio_dataset/metadata/metadata.csv\")) {\n\n  # 1) メタデータ読み込み\n  md <- read.csv(\"audio_dataset/metadata/metadata.csv\", stringsAsFactors = FALSE)\n\n  # 2) 前処理：モノラル化→正規化\n  read_mono_norm <- function(path) {\n    w <- readWave(path)\n    if (w@stereo) w <- mono(w, which = \"left\")\n    tuneR::normalize(w, unit = \"16\", center = TRUE)\n  }\n\n  # 3) 記述統計：長さ・RMS・ZCR・スペクトル重心\n  describe_wav <- function(w) {\n    dur_sec <- length(w@left) / w@samp.rate\n    rms_amp <- seewave::rms(w)\n    zcr_val <- seewave::zcr(w)\n    sp      <- meanspec(w, f = w@samp.rate, wl = 1024, plot = FALSE)\n    cent    <- specprop(sp, f = w@samp.rate)$cent\n    tibble(duration = dur_sec, rms = as.numeric(rms_amp),\n           zcr = as.numeric(zcr_val), centroid = as.numeric(cent))\n  }\n\n  # 4) F0中央値（fund）：持続母音は中央50%区間、文は全区間\n  f0_median <- function(w, from = 0, to = NULL, fmax = 350) {\n    s   <- w@samp.rate\n    dur <- length(w@left) / s\n    if (is.null(to)) { from <- 0; to <- dur }\n    out <- tryCatch(\n      seewave::fund(w, f = s, ovlp = 50, from = from, to = to,\n                    threshold = 5, fmax = fmax, plot = FALSE),\n      error = function(e) NULL\n    )\n    if (is.null(out)) return(NA_real_)\n    # 出力構造に依存せず中央値を取得\n    vals <- tryCatch({\n      if (is.data.frame(out) || is.matrix(out)) as.numeric(out[, ncol(out)])\n      else if (is.list(out) && !is.null(out$ff)) as.numeric(out$ff)\n      else numeric(0)\n    }, error = function(e) numeric(0))\n    if (length(vals)) stats::median(vals, na.rm = TRUE) else NA_real_\n  }\n\n  # 5) 1レコードの特徴抽出\n  extract_features <- function(rec) {\n    w <- read_mono_norm(rec$filepath)\n    s <- w@samp.rate\n    dur <- length(w@left) / s\n    stats <- describe_wav(w)\n    f0 <- if (rec$task == \"sustained_vowel\")\n      f0_median(w, from = dur*0.25, to = dur*0.75, fmax = 350) else f0_median(w, fmax = 350)\n    dplyr::bind_cols(as_tibble(rec), stats, tibble(f0 = f0))\n  }\n\n  # 6) すべての行に適用（ネイティブパイプ＋baseのlapply）\n  features <- (\n    md |>\n      (\n        function(df) lapply(seq_len(nrow(df)), function(i) extract_features(df[i, , drop = FALSE]))\n      )() |>\n      dplyr::bind_rows()\n  )\n\n  # 7) 持続母音の概要（例）\n  features |>\n    dplyr::filter(task == \"sustained_vowel\") |>\n    dplyr::group_by(item) |>\n    dplyr::summarise(n = dplyr::n(),\n                     mean_f0 = mean(f0, na.rm = TRUE),\n                     sd_f0   = sd(f0, na.rm = TRUE),\n                     mean_centroid = mean(centroid, na.rm = TRUE), .groups = \"drop\") |>\n    gt() |>\n    tab_header(title = \"Sustained vowels: F0/spectral centroid summary\")\n\n  # 8) 文タイプのF0（例）\n  features |>\n    dplyr::filter(task == \"sentence\") |>\n    dplyr::mutate(type = dplyr::coalesce(sentence_type, \"unknown\")) |>\n    dplyr::group_by(type) |>\n    dplyr::summarise(n = dplyr::n(),\n                     mean_f0 = mean(f0, na.rm = TRUE),\n                     sd_f0   = sd(f0, na.rm = TRUE), .groups = \"drop\") |>\n    gt() |>\n    tab_header(title = \"Sentence: F0 summary (by type)\")\n\n  # 9) 保存\n  write.csv(features, \"audio_dataset/metadata/audio_features.csv\", row.names = FALSE)\n\n} else {\n  message(\"audio_dataset が見つかりませんでした。先に Python の audio_generation.py を実行してください。\")\n}\n```\n:::\n\n\n::: {.callout-tip}\n#### GLMM への橋渡し\n保存した `audio_features.csv` を `metadata.csv` と結合し、話者（Participant）やアイテム（Item）を乱効果にしてGLMM/階層ベイズへ展開できます。F0やフォルマントは**連続**、正誤は**二値**として第6章のレシピがそのまま適用できます。\n:::\n\n------------------------------------------------------------------------\n\n## Praat TextGrid と LPC による F1/F2 抽出（実データ連携）\n\nPraatのTextGridで注釈した母音区間から、Rで**F1/F2**を抽出して可視化・混合効果分析へ繋げる最小レシピです。TextGridは `rPraat` で読み、区間を `tuneR/seewave` で切り出し、**LPC**またはスペクトルピークで近似的に求めます。\n\n### 準備（ファイル配置）\n\n- `data/audio/` に `spk001_word_bit_rep01.wav` と `spk001_word_bit_rep01.TextGrid` のように**同名**（拡張子だけ異なる）で置いておきます。\n- TextGridの tier には、母音区間を含む `Vowel`（例）を用意（`label` に母音記号やターゲット名）。\n\n### 読み込みと切り出し（eval=FALSE）\n\n以下のコードでは、Praatで作成したTextGridファイルを `rPraat::tg.read()` で読み込み、母音ラベルが付与された区間の開始・終了時刻を取得します。その後、対応する .wav ファイルから `seewave::cutw()` で母音区間を切り出します。TextGridとwavファイルは**同じファイル名**（拡張子のみ異なる）で配置しておく必要があります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntg <- tg.read(\"data/audio/spk001_word_bit_rep01.TextGrid\")\ntiers <- tg.tierNames(tg)\nprint(tiers)\n\n# 例：'Vowel' tier の intervalをdata.frame化\niv <- tg.getTier(tg, \"Vowel\")\nann <- tibble(\n  t1 = iv$t1, t2 = iv$t2, label = iv$label\n) |>\n  filter(nchar(label) > 0)\n\n# wav読み込み→目的区間を切り出し（中心±25msなど）\nw <- readWave(\"data/audio/spk001_word_bit_rep01.wav\") |> mono(\"left\") |> tuneR::normalize(unit='16', center=TRUE)\nfs <- w@samp.rate\n\nextract_segment <- function(w, from, to, pad_ms = 0){\n  cutw(w, from = max(0, from - pad_ms/1000), to = to + pad_ms/1000, output = 'Wave')\n}\n\nsegments <- ann |>\n  mutate(mid = (t1 + t2)/2,\n         seg = pmap(list(t1, t2), ~extract_segment(w, ..1, ..2, pad_ms = 0)))\n```\n:::\n\n\n### LPCとピーク抽出（近似）\n\n以下のコードでは、切り出した母音区間のスペクトルから**F1/F2**を近似的に推定します。`meanspec()` で平均スペクトルを算出し、`fpeaks()` でピーク周波数を検出して、低周波側から順にF1、F2として採用します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_formants <- function(seg, f = fs, nform = 2, flim = c(200, 3500)){\n  # スペクトルを計算し、声道の共鳴付近のピークを検出\n  sp <- meanspec(seg, f = f, wl = 1024, plot = FALSE)\n  # fpeaks: 主要ピークを抽出（nmax=6程度）\n  pk <- seewave::fpeaks(sp, f = f, nmax = 6)\n  if (is.null(pk) || nrow(pk) == 0) return(c(NA, NA))\n  # 音声領域のピークを絞り込み、低周波からnform個を採用\n  cand <- pk[,1]\n  cand <- cand[cand >= flim[1] & cand <= flim[2]]\n  sort(cand)[1:min(nform, length(cand))]\n}\n\nformant_tbl <- segments |>\n  mutate(F = map(seg, estimate_formants)) |>\n  mutate(F1 = map_dbl(F, ~ .x[1] %||% NA_real_),\n         F2 = map_dbl(F, ~ .x[2] %||% NA_real_)) |>\n  select(label, t1, t2, F1, F2)\nformant_tbl\n```\n:::\n\n\n::: {.callout-note}\nLPCのモデル次数や窓長によって推定は大きく変わります。実データでは、**Praat（FormantTask）**でF1/F2を抽出し、TextGridと揃えてRで集約・統計化するのが一般的です。`phonTools::formanttrack`等のR実装を使う方法もあります。\n:::\n\n### F1–F2散布図（楕円つき）\n\n以下のコードでは、推定したF1/F2を散布図にプロットし、母音カテゴリごとに68%信頼楕円を重ねて**母音空間** (vowel space) を可視化します。音声学では慣例としてF2を横軸（左→右を**反転**）、F1を縦軸（上→下を**反転**）に取ります。これにより、図の配置が調音位置（舌の前後・上下）に対応します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformant_tbl |>\n  mutate(Vowel = label) |>\n  ggplot(aes(F2, F1, color = Vowel, label = Vowel)) +\n  geom_point(alpha = .6) +\n  stat_ellipse(level = .68, linewidth = .6) +\n  scale_x_reverse() + scale_y_reverse() +\n  labs(title = 'Vowel space (F1–F2)', x = 'F2 (Hz)', y = 'F1 (Hz)') +\n  theme_bw(base_size = 12) + theme(legend.position = \"bottom\")\n```\n:::\n\n\n::: {.callout-tip}\n#### 母音の正規化（Lobanov法）\n\n複数の話者（異なる性別・年齢）のフォルマントを比較する場合、声道の物理的な長さの違いを補正する**正規化**が必要です。最も広く使われているのが**Lobanov法**（z-score正規化）です。\n\n```\n# Lobanov正規化：話者ごとにz-scoreに変換\nlobanov_norm <- function(df, speaker_col = \"Speaker\") {\n  df |>\n    group_by(.data[[speaker_col]]) |>\n    mutate(\n      F1_z = (F1 - mean(F1, na.rm = TRUE)) / sd(F1, na.rm = TRUE),\n      F2_z = (F2 - mean(F2, na.rm = TRUE)) / sd(F2, na.rm = TRUE)\n    ) |>\n    ungroup()\n}\n```\n\n正規化後のF1_z/F2_zを使うことで、「話者の個人差を除いた母音カテゴリの違い」を比較できます。Rパッケージ `vowels` や `phonR` も正規化機能を提供しています。\n:::\n\n### GLMM か？ 時系列か？（考え方）\n\n::: {.callout-tip}\n**Steady-state 母音**：各トークンから1点（F1/F2）を抽出する場合、**LMM/GLMM**（交差乱効果：話者×項目）で群差や条件効果を評価するのが標準です（第6章参照）。\n\n**トラジェクトリ（F0/フォルマントの時間変化）**：時点をそろえて曲線を比較するなら、**GAM/GAMM**（`mgcv`）や**状態空間**（KFAS）が適します。例：`gam(F0 ~ s(time, by = condition) + s(time, speaker, bs='fs'), method='REML')`。\n\n**縦断的発達研究**：学習者を月ごとに録音し、F0やフォルマントの変化を追跡する場合、各時点の音響特徴を集約した値は「マクロな時系列」になります。ここで Part A–C の ARIMA / STL / SSM が再び適用できます。\n:::\n\n### 混合効果モデル（LMM）の最小例\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 例：F1 ~ Vowel * Group + (1|Speaker) + (1|Item)\ndf <- formant_tbl |>\n  mutate(Speaker = 'spk001', Item = row_number(), Group = 'G1')  # 実際はメタデータと結合\n\nfit_f1 <- lmer(F1 ~ Vowel * Group + (1|Speaker) + (1|Item), data = df)\nsummary(fit_f1)\n```\n:::\n\n\n### トラジェクトリ比較（GAMM）の最小例\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# F0曲線を time in [0,1] に正規化し、各トークンでサンプル（要事前整形）\n# df_track: columns = c(Speaker, Item, Condition, time, F0)\nfit_gamm <- gam(F0 ~ s(time, by = Condition) + s(time, Speaker, bs='fs'),\n                data = df_track, method = 'REML')\nsummary(fit_gamm)\nplot(fit_gamm, pages = 1)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n\n### 報告テンプレート集\n\n#### テンプレート①：基本ARIMA（worked example: Dataset 1 語彙テスト）\n\n> 週次語彙テストスコア（N = 40 時点、20点満点）に対し、ARIMA モデルを `auto.arima()` により最大尤度推定で当てはめた。モデル選択は AICc に基づき、`stepwise = FALSE` の全探索を実施した。選択されたモデルは ARIMA(1,1,0) であり、AICc = [値] であった。差分は通常差 d = 1（トレンド除去）、季節差 D = 0。Box-Cox 変換は適用しなかった（`lambda = NULL`）。AR(1)係数は [値]（SE = [値]）であり、差分後のスコアの [値]% が1期前の値に依存することを示す。残差診断では Ljung-Box 検定の p = [値]（> 0.05）であり、残差に有意な自己相関は認められなかった。Shapiro-Wilk 検定（p = [値]）でも残差の正規性は棄却されなかった。10週先の予測では、スコアは [値] 点（95% PI: [[値], [値]]）と推定された。\n\n::: {.callout-tip collapse=\"true\"}\n#### 査読者チェックリスト（基本ARIMA）\n\n- [ ] ADF / KPSS による定常性検定の結果を報告したか\n- [ ] `ndiffs()` による差分回数の根拠を示したか\n- [ ] 残差診断（ACF + Ljung-Box）の結果を報告したか\n- [ ] AICcの値と、代替モデルとの比較を示したか\n- [ ] 予測区間の幅を報告し、その意味を解釈したか\n- [ ] 小標本の場合、`bootstrap = TRUE` を検討したか\n:::\n\n#### テンプレート②：ITS / ARIMAX（worked example: Dataset 2 TOEFLスコア）\n\n> 月次TOEFL風スコア（N = 24 時点）に対し、介入時系列分析（ITS）を実施した。介入は第12時点（2023年1月）のカリキュラム刷新（統合スキル重視プログラムへの移行）である。外生変数として step ダミー（介入後 = 1）と ramp ダミー（介入後の経過月数）を ARIMAX モデルに組み込んだ。`auto.arima()` により選択されたモデルは ARIMA([p],[d],[q]) + step + ramp であり、AICc = [値] であった。\n>\n> **介入効果の推定**：\n>\n> - ステップ変化（即座の効果）：$\\hat{\\beta}_{\\text{step}}$ = [値]（SE = [値]）、95% CI [[値], [値]]。カリキュラム変更直後にTOEFLスコアが約 [値] 点上昇した。\n> - 傾き変化（漸進的効果）：$\\hat{\\beta}_{\\text{ramp}}$ = [値]（SE = [値]）、95% CI [[値], [値]]。変更後、毎月さらに約 [値] 点の追加的上昇が見られた。\n>\n> 残差診断では Ljung-Box p = [値]（> 0.05）であり、残差の白色性が確認された。Durbin-Watson 検定により、OLS 回帰の残差には有意な自己相関（DW = [値], p = [値]）が検出され、ARIMAX の使用が妥当であることが支持された。標準化効果量は最終時点で d = [値] であった。反事実プロットにより、介入がなかった場合のスコア推移との差を可視化した。\n>\n> **限界**：統制群を設定していないため、同時期の他の変更（教員の異動等）による交絡を完全には排除できない。24時点は ARIMA 推定の下限に近く、推定値の不確実性が大きい可能性がある。\n\n::: {.callout-tip collapse=\"true\"}\n#### 査読者チェックリスト（ITS / ARIMAX）\n\n- [ ] 介入前後の最低時点数（各8–10以上）を満たしているか\n- [ ] ADF / KPSS による定常性検定を報告したか\n- [ ] OLS との比較（Durbin-Watson 検定）で ARIMAX の必要性を示したか\n- [ ] step と ramp の両方をテスト（有意でなくても報告）したか\n- [ ] 反事実 (counterfactual) プロットを提示したか\n- [ ] 標準化効果量（Cohen's d 相当）を算出・報告したか\n- [ ] 残差診断（Ljung-Box）でモデルの妥当性を確認したか\n- [ ] 内的妥当性への脅威（history, maturation, instrumentation）を Limitations に記載したか\n:::\n\n#### テンプレート③：音響時系列（worked example: 合成母音 /i/ /a/）\n\n> 合成母音データ（f0 = 120 Hz、サンプリングレート 16 kHz、モノラル 16 bit、持続時間 0.5 秒）を用いて F0 推定の精度を検証した。F0 は自己相関法（ACF）とケプストラム法の2手法で推定し、それぞれ /i/: ACF = [値] Hz / Cepstrum = [値] Hz、/a/: ACF = [値] Hz / Cepstrum = [値] Hz であった（真値 120 Hz）。両手法とも真値に近い推定を示し、母音の種類（フォルマント構造の違い）にかかわらず F0 推定が安定していることが確認された。\n>\n> スペクトル分析では、/i/ の F1 ≈ 300 Hz / F2 ≈ 2200 Hz、/a/ の F1 ≈ 730 Hz / F2 ≈ 1100 Hz の近傍にスペクトル包絡のピークが確認され、合成パラメータと一致した。\n>\n> **実データへの適用時の注意**：実録音データでは話者間変動（性別・年齢による声道長の違い）があるため、Lobanov法等による正規化が必要。統計モデルは LMM（F1 ~ Vowel * Group + (1|Speaker) + (1|Item)）を基本とし、F0トラジェクトリの比較には GAMM を使用する。\n\n::: {.callout-tip collapse=\"true\"}\n#### 査読者チェックリスト（音響時系列）\n\n- [ ] 録音条件（サンプリングレート、ビット深度、マイク、環境）を報告したか\n- [ ] クリッピング・SNR のチェックを行ったか\n- [ ] F0 推定の `fmin` / `fmax` パラメータを話者の範囲に合わせたか\n- [ ] フォルマント推定法（LPC / Praat）と設定を明記したか\n- [ ] 複数話者の比較では正規化（Lobanov等）を実施したか\n- [ ] 統計モデルに話者・項目の乱効果を含めたか\n- [ ] 母音空間図（F1–F2）を提示したか\n:::\n\n### トラブルシューティング（よくあるつまずき）\n\n主要なトラブルシューティングは各セクション内の `.callout-warning` ボックスに記載しています。ここでは、セクション横断的な補足事項をまとめます。\n\n| 問題 | 対処 | 関連セクション |\n|------|------|-------------|\n| 季節差が効かない | `frequency(ts_object)` で `frequency` の設定を確認 | セクション3（`ts()` の frequency ガイド） |\n| 外れ値の影響が大きい | `tsclean()` またはパルスダミーで対処 | セクション7（外れ値の検出と処理） |\n| 週次 vs 月次で結果が異なる | 週次はノイズが多いがITSの検出力が高い。月次は滑らかだが時点数が少ない | セクション6（ITS） |\n| 複数クラスのデータ | 階層時系列（乱効果付きモデル）を検討 | 第6章の混合効果モデル参照 |\n| 天井・床効果でARIMAが不安定 | Box-Cox変換（`lambda`）でデータを変換。IRT能力値の使用も検討 | セクション3（教育データ注意点） |\n\n## 参考文献\n\n::: {#refs}\n:::\n\n### 推奨リソース\n\n- R Documentation: `forecast`, `arima`, `stl`, `decompose` — Rの公式ヘルプ。`?forecast::auto.arima` で引数の全一覧を確認できます。\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}