---
title: "統計モデルについての概略"
---

## はじめに

プラモデルは本物の車や飛行機などの実際の重さや材質、機能などを無視して、形や色を模倣しています。つまり、モデルとは不必要な性質を大胆に無視して、必要なエッセンスだけを取り上げたものを指します。統計モデルは確率分布とパラメータを使ってデータの特徴を模倣するものです。このページでは伝統的な統計モデルではどのような手法が用いられているのかを概観していきましょう。

### 尺度水準

統計モデルを理解する上で、データにはいくつかの種類があることを押さえておきましょう。例えば、身長は150センチよりも160センチの方が高く、この10センチの差は170センチと180センチの差と同じです。また、小学生の頃は140センチだった身長が大学生で180センチになった際には、身長が約1.3倍になったと言えます。さらに、長さの単位となっているセンチメートルの長さには原点となる0があります。このように、原点があり、間隔や比率に意味があるデータは比率尺度と呼ばれます。

気温の5度から10度への変化と15度から20度への変化は、どちらも同じ5度の変化であることから間隔は等しいと言えます。しかし、5度が10度へと変化しても、気温が2倍になったとは言えません。このように、目盛が等間隔となるデータは間隔尺度と呼ばれます。

データの情報量としては、比率尺度の方が間隔尺度よりも多いと言われています。間隔尺度以上のデータでは平均値や標準偏差などを計算することができます。特に、比率尺度は平均値を標準偏差で割った変動係数を計算することができ、平均値に対する相対的なばらつきの大きさを検討することができます。

英語教育の分野で用いるデータとしては、テストの点数のような間隔尺度だけでなく、名義尺度と順序尺度があります。

名義尺度とは、学習条件A・B・Cのように、他と区別するだけのラベルのことを指します。例えば、母語が日本語である場合を1、中国語である場合を2としても、1より2の方が大きいとは言えません。この順序が仮定されるデータ（例：英検の級、CEFRレベル）は順序尺度と呼ばれます。名義尺度の場合は数を数え上げるのみですが、順序尺度は中央値を検討することができます。名義尺度と順序尺度は質的変数やカテゴリカル変数と呼ばれます。一方、間隔尺度や比率尺度は量的変数や連続変数と呼ばれます。

### 変数の種類

英語教育の分野では目に見えない変数を扱うことが多いです。例えば、「コミュニケーションで使える語彙知識」とはいったい何を指しているのでしょうか。スピーキングで使われる語彙知識なのでしょうか、ダイアローグにおいて相手が英語で言っていることを理解するためのリスニングで使われる語彙知識も含むのでしょうか、メールの「確かに承りました」を英語で伝える際にcertainlyを使うと嫌味に聞こえてしまうような語用論的知識なのでしょうか、"make"を使えることは作成動詞と使役動詞の2種類があると知っていることなのでしょうか、使役動詞のmakeは受動態では原形不定詞ではなくto不定詞を伴うと知っていることなのでしょうか、使える語彙知識と使える文法知識に違いはあるのでしょうか。

目に見えない概念を扱うには測定具が必要です。語彙知識の測定には一般的に「語彙サイズテスト」が用いられることがあります。日本語を母語とする英語学習者が英語の語彙知識をどのくらい知っているかを検討する測定具としては、Hamada et al. (2021) のVST-NJ8や相澤・望月 (2010) の望月語彙サイズテストなどがあります。このように、測定具を用いて目に見えるようなデータが得られると、英語学習者の熟達度を検討することができます。目に見える変数を観測変数、目に見えない変数を潜在変数と呼びます。

### 相関関係・回帰関係・因果関係

「風が吹けば桶屋が儲かる」という日本の諺を聞いたことはありますか？以下はWikipediaによる説明です。

1. 大風が吹けば土埃が立ち、眼病疾患者が増加する
2. 盲人などが三味線を生業とし、演奏方法を指導したり、門付で三味線を演奏するので、三味線の需要が増える
3. 三味線製造に猫の皮が欠かせないため、猫が多数減り、鼠が増加する
4. 鼠は箱の類（桶など）をかじる
5. 桶の需要も増加して桶屋が儲かるだろう

この関係性の説明は相当に無理がありますが、気温とアイスクリームの売り上げの関係性はどうでしょうか？夏のような暑い気温ではアイスクリームを購入する人が多くなりそうです。ではアイスクリームの売り上げと溺死の件数の関係はどうでしょうか。夏になると海水浴に行く人が増え、溺死の件数も増えると予想されます。このように、どちらが原因でどちらが結果であるかがはっきりとしない関係性は相関関係と呼ばれます。なお「相関がある」「相関がない」という表現は不適切で、「強い相関がある」「弱い相関がある」「正の相関がある」「負の相関がある」のようなコロケーションを用います。どちらかが高くなればどちらかも高くなるような気温とアイスクリームの売り上げは正の相関、どちらかが高くなればどちらかが低くなるような気温とおでんの売り上げは負の相関と言います。

変数間の関係には相関以外に回帰関係と因果関係があります。例えば、中間テストが終わった高校生に対して、土曜日補講を行う効果を検討してみましょう。補講への参加は任意とすると、参加する生徒と参加しない生徒が出てきます。補講に参加する生徒を1、参加しない生徒を0という名義尺度で考えてみましょう。補講の効果は英語の期末テストで測定することとします。この期末テストの結果は観測変数となります。補講が期末テストに与える影響を考える時、影響を受けると考える側（期末テスト）を目的変数・応答変数・従属変数と呼び、影響を与えると考える側（補講への参加生徒1、0）を説明変数・予測変数・独立変数・共変量・特徴量と呼びます。目的変数と説明変数によって、「目的変数 = 傾き × 説明変数 + 切片 + 誤差」のような式で表す関係を回帰関係と呼びます。

上記の土曜日補講と期末テストの回帰関係は「ナイーブな」比較と言えます。なぜなら、生徒Aが補講を受けた際の影響は目的変数として得られる一方で、生徒Aが補講を受けない影響は目的変数として得られません。つまり、潜在的な結果が生じてしまいます。また、土曜日補講に参加しようとする生徒は学習に対する動機づけが高いと考えられ、平日も自主学習を行っていたり、授業に真面目に参加していると考えられます。そのため、補講以外の交絡要因を検討する必要もあります。

なお、因果関係を検討する上では、性別や動機づけのような属性変数を統計モデルに組み入れ、あたかも原因のように扱うことは不適切です。因果関係を検討する際には、何が操作されており、観測変数は何かを考えることが重要です。

## 構造方程式モデリング

上記で述べてきた「説明変数」および「目的変数」が「観測変数」か「潜在変数」かによって、統計モデルの名前は変わります。しかし、最終的には構造方程式モデリングと呼ばれる手法が全ての統計モデルを扱うことができます。構造方程式モデリングでは、目的変数が名義尺度でも順序尺度でもよく、ある目的変数が説明変数になるモデル（例えば、語彙サイズがリスニング能力に影響を与え、リスニング能力がリテリングの結果に影響を与えるなど）も分析可能です。つまり、回帰分析も因子分析も構造方程式モデリングの一種であると言えます。以下では主な統計モデルを紹介します。

### 説明変数・目的変数が観測変数の場合

まずは説明変数も目的変数も観測変数の場合を考えてみましょう。例えば、上記の土曜日補講が期末テストに与える影響を与えるかを検討するt検定がこの統計モデルに含まれます。繰り返しになりますが、これらのモデルはすべて構造方程式モデリングの特殊な例です。例えば、回帰分析における目的変数が別の目的変数に影響を与える説明変数となる場合の分析はパス解析と呼ばれますが、パス解析は潜在変数が組み込まれていない構造方程式モデリングです。

| 統計モデルの名前 | 説明変数（観測） | 目的変数（観測） |
|---|---|---|
| 回帰分析 | 連続・カテゴリカル | 連続 |
| 判別分析 | 連続 | 名義 |
| 名義ロジスティック回帰分析 | 連続 | 名義 |
| 順序ロジスティック回帰分析 | 連続 | 順序 |
| 数量化Ⅰ類 | カテゴリカル | 連続 |
| 数量化Ⅱ類 | カテゴリカル | 名義 |

### 説明変数が潜在変数、目的変数が観測変数の場合

潜在変数とは目に見えない変数、観測変数とは目に見える変数のことを指します。

| 統計モデルの名前 | 説明変数（潜在） | 目的変数（観測） |
|---|---|---|
| 因子分析 | 連続 | 連続 |
| 段階反応モデル | 連続 | 順序 |
| 2値ラッシュモデル | 連続 | 名義（2値） |
| 潜在プロフィール分析 | カテゴリカル | 連続 |
| 潜在クラス分析 | カテゴリカル | 名義 |
| 潜在ランク分析 | 順序 | カテゴリカル |

### 説明変数が観測変数、目的変数が潜在変数の場合

| 統計モデルの名前 | 説明変数（観測） | 目的変数（潜在） |
|---|---|---|
| 主成分分析 | 連続 | 連続 |
| コレスポンデンス分析、多重コレスポンデンス分析 | カテゴリカル | 連続 |

### モデルの評価指標

作成した統計モデルがどの程度データと一致しているのかを検討する方法として、モデルの適合度指標があります。構造方程式モデリングでは複数の指標が出力されます。

#### 情報量基準

情報量基準とは尤度に-2をかけたもので、Akaike Information Criteria (AIC) やBayesian Information Criteria (BIC) があります。情報量基準はモデルがデータにどの程度よくフィットしているかを示します。つまり、複数のモデルA、モデルB、モデルCを同じデータに当てはめた時、これらの情報量基準が低いほど、データによく適合していると判断できます。

#### Root Mean Square Error of Approximation (RMSEA)

モデルがデータとどの程度乖離しているかを直接表現した指標です。一般に、0.05より小さければ、そのモデルは当てはまりが良く、0.1以上であれば当てはまりが悪いと判断できます。

#### Comparative Fit Index (CFI) / Tucker-Lewis Index (TLI)

観測変数間に全く相関がないという非現実的なモデルに比べ、当該のモデルがどの程度良いかを標準化したものです。1.0に近いほど良いモデルとされます。

#### Standardized Root Mean square Residual (SRMR)

標準化された残差平方平均平方根のことで、モデルで説明できなかったデータの分散がどれほどあったかを表します。0に近ければ近いほど当てはまりが良いことを表します。

## 統計モデリングと回帰分析

回帰分析は1つの目的変数（従属変数・応答変数とも）を説明変数（独立変数・固定効果とも）から予測する統計手法です。大きく以下の3つに分けることができます。

- 線形モデル：t検定、ANOVA、単回帰分析、重回帰分析など
- 一般化線形モデル：ロジスティック回帰、ポアソン回帰、ガンマ回帰、ベータ回帰など
- 一般化線形混合効果モデル：ロジスティック混合回帰モデル、ポアソン回帰混合効果モデルなど

### 線型モデル

線形モデルは目的変数が[正規分布](https://ai-trend.jp/basic-study/normal-distribution/normal-distribution/)であることを分析の前提としています。この正規性の前提は[ルビーン検定](http://data-science.gr.jp/implementation/ist_r_levene_test.html)や[コルモゴロフ・スミルノフ検定](https://data-science.gr.jp/implementation/ist_r_kolmogorov_smirnov_test.html)、[Q-Qプロット](https://qiita.com/TSeri/items/e0228f877ccb22f5dbc9)などで確認することができます。つまり、線型モデルで扱うことができるデータの種類は連続変数と呼ばれる間隔尺度以上の変数となります。具体的には、テストの点数（0〜100点）や反応時間（ミリ秒）などが連続値として扱われることから、線型モデルで検討することができます。

線型モデルの中で最も典型的なモデルが単回帰分析です。こちらは1つの連続値を目的変数、1つの連続値を説明変数とするモデルで、主に目的変数の予測に使われることが多いです。例えば、期末テストの得点を予測する際、テスト期間中の勉強時間を説明変数とするなどが考えられます。

単回帰分析では説明変数として1つの変数のみが含まれていました。複数の説明変数を含む統計モデルは重回帰分析と呼ばれます。例えば、英語の期末テストの得点を目的変数として、中間テストの英語の得点や小テストの点数などを追加で含めるモデルが考えられます。重回帰分析に含まれる複数の説明変数は相関が低いことが前提となります。この説明変数同士の相関が高いことはモデルの作成において、[多重共線性](https://best-biostatistics.com/correlation_regression/multi-co.html)と呼ばれる問題を引き起こしてしまいます。複数の説明変数をモデルに組み込むことができる一方で、理論的に適切な説明変数を選択することができるかが鍵となります。

重回帰分析における説明変数は、連続変数でもカテゴリカル変数でも問題なく目的変数を推定することができます。連続変数とは、テストの得点のように数字で大小を比べることができ、平均値などを計算することに意味を持つ変数のことです。一方、カテゴリカル変数は性別や正解・不正解のように平均値を計算することに意味を持たない変数のことです。正解・不正解のように2水準となる場合もあれば、母語が日本語・韓国語・中国語・英語など多水準になる場合もあります。なお、Rのようなプログラミング言語では正解を1、不正解を0とするようにダミーコーディングされます。この0や1の値に大小関係が存在しないため、Rではfactor型にしておくことが必要です。

説明変数が2つでいずれも2水準のカテゴリカルである重回帰分析は2 way ANOVAと呼ばれます。つまり、分散分析は重回帰分析の特殊な場合ということになります。t検定も同様に、目的変数が1つで、説明変数が2水準の1つのカテゴリカル変数である回帰分析であると言えます。

線型モデルの概要については[こちらの動画](https://youtu.be/7ArmBVF2dCs?si=XLdwV4zUDIYZLCa9)がとても参考になります。

### 一般化線型モデル

線型モデル (linear model) は目的変数が連続値で正規分布に従うことが前提です。しかし、試験の合格・不合格や思考発話の中で現れる特定の方略の数などの特殊なデータを扱うことができません。このような目的変数の確率分布に応じて回帰分析を行う手法が一般化線型モデル (generalized linear model; GLM) です。

コインの表・裏、成功・失敗、合格・不合格のように、2つの値だけを取るデータは「2値データ」と呼ばれます。このようなデータは[二項分布](https://bellcurve.jp/statistics/course/6979.html)と呼ばれる確率分布に従っています。二項分布に従う2値データは正規性を満たしません。そのため、重回帰分析やt検定で分析することは不適切です。そこで[ロジスティック回帰](https://cacco.co.jp/datascience/blog/data-analysis/1274/)という分析方法を用いることとなります。ロジスティック回帰分析は重回帰分析のように複数の説明変数をモデルに組み込むことができます。具体例としては、中間テストのリスニングの点数とリーディングの点数の2つを説明変数として、試験に合格するかどうかを目的変数として予測するなどがあります。

一般化線型モデルには2値データ以外にもカウントデータを扱う統計モデルも存在します。カウントデータは出現頻度のことを表しており、例えば、英文の要約で書き手のパラフレーズが何回登場するか、思考発話のプロトコルに特定の方略が何回登場するか、視線計測による読み戻り回数などがカウントデータに該当します。このカウントデータの平均はλ（ラムダ）と呼ばれ、「平均と分散が等しい」という前提に基づいた[ポアソン回帰](http://www.snap-tck.com/room04/c01/stat/stat15/stat1501.html)や、出現頻度0が多い・過分散に対応した[負の二項回帰](https://best-biostatistics.com/correlation_regression/negative-binomial.html)などがあります。

先行研究ではたまに「正規性が満たされなかったため、[ノンパラメトリック検定](https://www.ibm.com/support/pages/ノンパラメトリック検定)を用いた」という表記があります。ノンパラメトリック検定は母集団の確率分布が事前にわからないものを推定する際に有用ですが、事前に二項分布やポアソン分布に従うデータであることがわかる場合には、ノンパラメトリック検定よりもGLMを用いる方が適切です。具体的には以下のようなGLMを用いることができます。

- 目的変数が2値データ：ロジスティック回帰 (e.g., 正解 vs. 不正解，成功 vs. 失敗)
- 目的変数が確率データ：2値ロジスティック回帰 (e.g., 10回の施行で3回起きる確率)
- 目的変数が順序データ：順序ロジスティック回帰 (e.g., リッカートスケール)
- 目的変数がカウントデータ：ポアソン回帰、負の二項回帰 (e.g., 思考発話の各カテゴリに関する発話回数)
- 目的変数が非負の連続データ：重回帰分析、ガンマ回帰 (e.g., 0〜10点のテスト)
- 目的変数が連続データ：t検定、ANOVA、重回帰分析 (e.g., 反応時間)

目的変数が連続データの場合は正規分布に従うため、線型モデルで分析できます。つまり、一般化線型モデルは線型モデルを包含した概念であると言えます。

### 一般化線型混合効果モデル

一般化線型混合効果モデル (Generalized Linear Mixed effect Model; GLMM) は、マルチレベルモデルや階層線型モデルとも呼ばれ、階層性のあるデータ (e.g., 自治体 - 学校 - 生徒) を分析することができます。GLMMの文脈では説明変数は固定効果、階層性のレベルはランダム効果と呼ばれており、これらを混合させて分析することから混合効果モデルという名前がついています。

ランダム効果の関係性はいくつかのパターンがあります。例えば、3つの学校から30人の生徒の実力テストの結果が得られたとします。この時、学校Aの生徒と学校Bの生徒は別の生徒であり、生徒は学校の中にネストされています。表にすると以下のようになります。

| 学校 | 生徒 | テスト得点 |
|---|---|---|
| A | A1 | 70 |
| A | A2 | 75 |
| A | A3 | 60 |
| … | … | … |
| A | A29 | 95 |
| A | A30 | 80 |
| B | B1 | 80 |
| B | B2 | 65 |
| … | … |  |
| B | B30 | 90 |
| C | C1 | 40 |
| … | … | … |
| C | C30 | 35 |

一方、30人の実験参加者に20語の単語を学習してもらう場合は、単語は参加者ごとに共通しているため、クロスしたランダム効果と言えます。

| 参加者 | 単語 |
|---|---|
| 1 | A |
| 1 | B |
| 1 | … |
| 1 | S |
| 1 | T |
| 2 | A |
| 2 | B |
| 2 | … |
| 2 | S |
| 2 | T |
| … | … |
| 30 | A |
| 30 | … |
| 30 | T |

GLMでは参加者や単語を分析の単位として扱っていなかったことから、データセット作成の際には20点満点のテストとして扱い、以下のような表を作成しました。

| 参加者 | テスト |
|---|---|
| 1 | 15 |
| 2 | 10 |
| … | … |
| 30 | 20 |

GLMで考慮しなかった参加者や単語などのランダム効果を考慮するのがGLMMであると言えます。GLMMはGLMにランダム効果を組み込んだ統計モデルであるため、ロジスティック回帰やポアソン回帰などを包括した呼び方となります。先行研究で「分析にはGLMMを用いた」と書かれていた場合、目的変数が何かを踏まえて分析手法にはどの回帰分析を用いたのかを確認することが必要です。

## 回帰分析における重要な用語

### 切片と傾き

回帰分析は基本的に$y = a + β_1x_1 + error$という形で表現されます。aは切片、βは傾きと呼ばれます。切片は説明変数$x = 0$の時の目的変数yの値を指しており、傾きは説明変数xが1単位増えた際の目的変数yの増加率を指しています。説明変数の数が増えれば係数である傾きの値も変化します。

回帰式は関数であるとみなせるため、$f(y_i) = β_1 + β_2x_i+β_3f_i +...$と表すことができます。左辺は目的変数はリンク関数、右辺は線形予測子と呼ばれます。

切片と傾きは観測データから回帰線との差（誤差）を最小とするように設定されます。これが最小二乗法と呼ばれる方法です。

### ポアソン分布

ポアソン回帰分析は頻度データの分析に使える回帰分析です。発生頻度は負の値を取らない整数であるという特徴があります。ポアソン分布の確率分布は$p(y|λ)=\frac{λ^yexp(-λ)}{y!}$と表すことができます。このλ（ラムダ）はポアソン回帰における唯一の変数で、$λ = exp(β_1 + β_2x_1)$で表されます。正規分布では平均$μ$と分散$σ$がパラメータとなっていました。今回のポアソン回帰分析は平均も分散も同じλで表されます。

ポアソン分布における特徴は以下の通りです。

- 目的変数$y$は自然数を取る
- 全ての$y$の発生確率を足し合わせると1となる
- 確率分布のλは平均を表す
- 平均と分散は等しい：λ = 平均 = 分散

母集団のλを推定する際、得られたデータからその値を推定することとなります。その推定の際、得られたデータが真の値にどのくらい当てはまっているのかは尤度と呼ばれるパラメータの関数で推定されます。尤度は手元のデータで得られた確率の条件付き確率であることから、その計算には掛け算が用いられます。尤度はそのままでは扱いづらいため、対数が取られます。この対数尤度を最大とする推定方法が最尤法です。

### ロジスティック回帰

ポアソン回帰分析では頻度データを扱っていますが、上限がないデータを扱っています。ロジスティック回帰分析では上限があるデータに加え、二項分布による2値データを扱えます。上限があるデータのように「N個のうち、y個で事象が生じる確率」はオフセット項とみなして扱うことができます。二項分布の確率分布は$p(y|N,q)= \begin{pmatrix}N\\y\\\end{pmatrix}q^y(1-q)^{N-y}$と定義されます。

ロジスティック回帰分析を理解・解釈する上で「オッズ」という概念を理解することが重要です。オッズとは、ある事象が起こる確率の怒らない確率に対する割合のことをさします。$odds = \frac{probability}{1-probability}$となります。例えば、4択問題にランダムに解答して正解する確率は$1/4$であるため、正解するオッズは$odds =\frac{\frac{1}{4}}{1-\frac{1}{4}}=\frac{1}{3}$となります。つまり、確率が「全体の中でのその事象の起こりやすさの割合」であるのに対し、オッズは「起こらない確率に対する、起こる確率の割合」です。オッズから確率を計算するには以下を使います：$probability = \frac{odds}{1+odds}$

オッズが1の時は確率がちょうど0.5になります。もし生じる機会が生じない機会よりも小さいなら、オッズは1よりも小さくなります（確率0.5よりも小さい）。生じる確率が等しいのあればオッズはちょうど1となります。確率が上限が1であるのに対し、オッズは無限大となり、オッズに上限はありません。そのため、非対称性があることから関係性の強さの尺度として使いにくく、オッズ比の対数（ロジット）を用いることが多いです。ロジットは1よりも大きなオッズ比（50%より大きい）の際に正の値、1よりも小さなオッズ比の際に負の値（50%より小さい）、オッズ比が1の際に0となります。

（対数について補足です）ある数値の常用対数とは、10を何乗すればその数と等しくなるのかという数のことです。例えば100は10を2乗するため、2は100の対数です。0乗した数は1に等しいため、1の対数は0、1よりも大きな数の対数は0よりも大きくなり、0より大き1よりも小さな値の対数は0よりも小さくなります。

オッズという概念は条件付きオッズ比の解釈が効果的であるため、複数の説明変数間の関係性について検討できます。さらに、ロジットを使う利点は2つあります。1つはオッズ比に比べてタイプSエラーが起こりにくいという点です。タイプSエラーは係数の解釈に関わるもので、統計的に有意差があり、解釈の際にどちらが高い値であるかの符号が逆になってしまうという誤りです。オッズ比は1を基準としていますが、ロジットは0を基準として正か負かで判断することができます。ロジットを使う利点の2つ目は、

ロジスティック回帰ではロジットリンク関数をリンク関数として用いています。ロジットリンク関数は$log(q_i) = log\frac{q_i}{1-q_i}$と表されます。ロジット関数はロジスティック関数$q_i = logistic(z_i) = \frac{1}{1+exp(-z_i)}$で表されます。

### 情報量基準

統計モデルの当てはまりの良さを表す指標にはいくつかあります。上記の対数尤度を変形した統計量である逸脱度 (deviance) は「当てはまりの悪さ」を表します。つまり、この値が高いほど悪いモデルであると言えます。対数尤度とχ二乗分布との対応関係が良くなるため、逸脱度Dは最大対数尤度logL\*に-2をかけて算出されます：$D = -2logL^*$。また、Dから最小逸脱度を引いた値は残差逸脱度と呼ばれます。残差逸脱度は統計モデルに含まれるパラメータの数が多くなるほど小さくなる（当てはまりがよい）という傾向にあります。

パラメータの数が多くなるほど、モデルの当てはまりが良くなるのであれば、目的変数に関係のない変数をたくさん含めればよくなってしまいます（つまり、過学習に陥ってしまうこととなります）。Akaike Information Criteria (AIC) を使うと、予測の良さを検討することができます。最尤推定したパラメータの個数がkであるときにAICは以下のように定義される：

$AIC = -2{(最大対数尤度) - (最尤推定したパラメータ数)} = -2(logL^* -k) = D +2k$。

AICをはじめとした情報量基準は、モデルの当てはまりの良さを表す指標であり、複数のモデルを比較する相対的な値です。パラメータの数が多いモデルよりも、パラメータの数が少ないモデルのAICが低い場合、多重共線性を回避できたと言えます。

モデル選択については[こちら](https://logics-of-blue.com/モデル選択_理論編/)を参照。

## 統計モデリングに関する参考文献

久保拓弥. (2012). データ解析のための統計モデリング入門――一般化線形モデル・階層ベイズモデル・MCMC (確率と情報の科学). 岩波書店.

小杉考司, 清水裕士, 押江隆, 山根嵩史, 平川真, 浅野良輔, 竹林由武, 藤原翔, 大谷和大, 森敦広, 林真広. (2014). M-plusとRによる構造方程式モデリング入門. 北大路書房.

馬場真哉. (2019). 実践Data Scienceシリーズ　RとStanではじめる　ベイズ統計モデリングによるデータ分析入門 (ＫＳ情報科学専門書). 講談社

松浦健太郎. (2016). StanとRでベイズ統計モデリング (Wonderful R 2). 共立出版.
