{
  "hash": "60fb3444a67232c58b1a91c7b64cd422",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MANOVA・判別分析\"\nbibliography:\n  - references_manova_discriminant.bib\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequired_packages <- c(\n  \"GGally\",\n  \"MVN\",\n  \"WebPower\",\n  \"biotools\",\n  \"broom\",\n  \"candisc\",\n  \"dplyr\",\n  \"effectsize\",\n  \"emmeans\",\n  \"forcats\",\n  \"heplots\",\n  \"MASS\",\n  \"patchwork\",\n  \"purrr\",\n  \"rlang\",\n  \"scales\",\n  \"tidyr\",\n  \"tidyverse\"\n)\n\nmissing_packages <- setdiff(required_packages, rownames(installed.packages()))\nif (length(missing_packages) > 0) {\n  install.packages(missing_packages, repos = \"https://cloud.r-project.org\")\n}\n```\n:::\n\n\n\n## セットアップ {.unnumbered}\n\nここでは、本章で必要なパッケージを一括で読み込みます。`heplots` はMANOVAのH行列とE行列を楕円として可視化するためのパッケージ、`candisc` は正準判別分析のプロットに使用します。`WebPower` はMANOVAの検定力分析に使います。\n\n### 主なパッケージの役割\n\n- `MASS` / `candisc`: 線形判別分析と正準判別分析を扱う。\n- `MVN` / `biotools` / `heplots`: 多変量正規性、Box's M、HE プロットなど MANOVA の前提確認と可視化を支える。\n- `effectsize` / `emmeans` / `broom`: 効果量、追跡比較、結果の整形を担当する。\n- `tidyverse` / `GGally` / `patchwork` / `WebPower`: データ整形、探索図、図の合成、表、検定力分析を補助する。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSys.setenv(RGL_USE_NULL = TRUE)\n\npackages_to_load <- c(\n  \"tidyverse\",\n  \"MASS\",\n  \"MVN\",\n  \"biotools\",\n  \"effectsize\",\n  \"emmeans\",\n  \"GGally\",\n  \"broom\",\n  \"patchwork\",\n  \"heplots\",\n  \"candisc\",\n  \"WebPower\"\n)\n\nmissing_packages <- packages_to_load[!vapply(packages_to_load, requireNamespace, logical(1), quietly = TRUE)]\nif (length(missing_packages) > 0) {\n  stop(\n    \"Install the following packages before rendering this chapter: \",\n    paste(missing_packages, collapse = \", \")\n  )\n}\n\ninvisible(lapply(packages_to_load, library, character.only = TRUE))\n\noptions(rgl.useNULL = TRUE)\nset.seed(2024)\ntheme_set(theme_bw(base_size = 12, base_family = \"sans\") +\n  theme(\n    plot.title.position = \"plot\",\n    plot.title = element_text(\n      face = \"bold\",\n      size = rel(1.0),\n      lineheight = 1.04,\n      margin = margin(b = 6)\n    ),\n    plot.subtitle = element_text(\n      size = rel(0.92),\n      lineheight = 1.04,\n      margin = margin(b = 8)\n    ),\n    plot.margin = margin(t = 10, r = 14, b = 10, l = 10)\n  ))\ntheme_update(legend.position = \"bottom\")\n```\n:::\n\n\n## はじめに {.unnumbered}\n\n本章へようこそ。ここでは **英語語彙学習研究**を想定して、2つの目的変数（MANOVA の文脈では従属変数 [DV] とも呼ばれます）（`Recall`, `Recognition`）を同時に扱う **MANOVA（多変量分散分析）** と、群の分離構造を評価する **判別分析** を、「実装できる」だけでなく「論文結果節として説明できる」水準まで整理します。ここでの DDA（descriptive discriminant analysis）は追跡分析の**考え方**であり、実装としては主に LDA（linear discriminant analysis）を使い、QDA（quadratic discriminant analysis）は分類目的の感度分析として扱います。\n\n回帰分析の既習者向けに、以下の対応関係を明示して進めます。\n\n- **単回帰・重回帰**: 1つの目的変数に対する線形モデル\n- **MANOVA**: 複数の目的変数を**同時に**扱う多変量線形モデル\n- **DDA（記述的判別分析）**: MANOVAの追跡枠組みとして、群分離の方向と構造を明らかにする\n- **LDA / QDA**: DDAを実装するための分類モデル。LDAは共通共分散、QDAは群別共分散を仮定する\n\n### この章の到達目標\n\n以下は **本章を一通り咀嚼したあとの最終ゴール**です。一読目では「**MANOVA は複数 DV の同時検定**」「**Pillai と DDA が主役**」の 2 点だけ掴めれば十分で、残りは必要に応じて戻ってくる読み方を推奨します。\n\n- MANOVAの前提を、設計上の論点と統計検定の論点に分けて説明できる。\n- H行列とE行列の意味を直感的に説明し、HEプロットを読むことができる。\n- Pillai / Wilks / Hotelling-Lawley / Roy の読み分けと選択根拠を説明できる。\n- DDA（判別分析）をMANOVAの主要追跡法として実装・解釈できる。\n- 構造係数（structure coefficients）を用いてDVの寄与を評価できる。\n- 有意性だけでなく、効果量・分類性能・検定力まで一貫して報告できる。\n- `WebPower` を用いた検定力分析でサンプルサイズ計画ができる。\n\n### なぜ個別ANOVAの繰り返しでは不適切なのか\n\n目的変数が複数ある場合、「DVごとにANOVAを繰り返す」アプローチは不適切です。このアプローチには2つの根本的な問題があります。\n\n1. **Type Iエラーの膨張**: DV が $p$ 個あれば、各 $\\alpha = .05$ で検定を繰り返すと、族全体での偽陽性率の **上限**は $1 - (1 - .05)^p$ に達します(これは **DV 同士が独立な場合**の値で、$p = 2$ なら 9.75%、$p = 5$ なら 22.6%)。実際の偽陽性率は DV 間相関の構造に依存し、相関が高いほど低くなりますが、依然として無補正よりは膨張します。Smith et al. [-@smith2020] は英才教育研究の 56 本を体系的にレビューし、ほぼすべての論文が MANOVA 後に単変量 ANOVA のみで追跡しており、**最悪ケースでは Type I エラー率が 76% に達しうる**シミュレーション結果を報告しています(76% は特定条件下のシミュレーション値であり、すべての研究で観測される率ではない点に注意)。\n\n2. **DV間の相関構造の無視**: 個別ANOVAは各DVを独立に扱うため、DV間の共変動パターンに埋め込まれた群差を検出できません。MANOVAが有意でも、すべてのANOVAが非有意になるケースは珍しくありません。Warne [-@warne2014] はMANOVAの58本の実証論文をレビューし、「MANOVAを実施しながらも追跡分析で多変量構造を適切に考慮した論文はほとんどない」と指摘しています。\n\n#### 「MANOVA = 同時ANOVA」という誤解\n\nMANOVAは単にANOVAを同時に実行するものではありません。MANOVAは**DV間の共分散構造を考慮した上で群差を検定**します。これは、H行列（群間変動）とE行列（群内変動）の相対的な大きさを多変量的に評価するものであり、個別ANOVAにはこの情報がありません [@warne2014; @huberty2006]。Huberty & Olejnik [-@huberty2006] は、MANOVAの本質を「DVの最適な重み付け線形結合に対する検定」と定義しており、これは個別ANOVAでは原理的にアクセスできない情報です。\n\nでは、MANOVAが常に最善かというと、DV間の相関の程度によって判断が変わります。\n\n| DV間相関の範囲 | MANOVAへの適合性 | 推奨 |\n|:---:|:---|:---|\n| .00 -- .30 | DVがほぼ独立。MANOVAの付加価値は小さい | 研究質問がDV別なら補正付き個別ANOVAも候補 |\n| **.30 -- .70** | **経験的に扱いやすい範囲。MANOVAの利点が出やすい** | **MANOVA推奨** |\n| .70 以上 | 多重共線性の懸念。推定が不安定になりうる | DVの統合・再検討を検討 |\n\n: DV間相関とMANOVAの適合性 {.striped}\n\n### 回帰分析との接続\n\n行列表記では、MANOVAは\n\n$$\n\\mathbf{Y} = \\mathbf{X}\\mathbf{B} + \\mathbf{E}\n$$\n\nと書けます。ここで、$\\mathbf{Y}$ は $n \\times p$ の目的変数行列（$p$ 個のDVを列に持つ）、$\\mathbf{X}$ は計画行列、$\\mathbf{B}$ は係数行列、$\\mathbf{E}$ は誤差行列です。つまり「回帰式を同時に推定し、**誤差の共分散構造も含めて**効果を検定する」という理解が、回帰既習者には最も自然です [@warne2014; @huberty2006]。R の公式ドキュメントでも `manova()` は `aov()` を呼び出して `manova` クラスを付ける設計だと説明されており、**モデル適合そのものより、要約の読み方が多変量化されている**と捉えると理解しやすくなります [@r_manova_doc]。\n\n### MANOVAとSEMの接続\n\nここで一歩進めて考えると、MANOVA は **SEM と対立する方法**というより、**観測変数ベースの簡潔な多変量モデル**として理解すると整理しやすくなります。Cole et al. [-@cole1993] は、群間比較の問題を「観測変数の平均ベクトルを比べるか」「潜在変数を含む変数システム全体を比べるか」という連続体として捉えています。Rosseel [-@rosseel2012] の `lavaan` 論文に沿って言えば、SEM はこの枠組みをさらに拡張して、**測定誤差・潜在変数・平均構造・群間等値制約**まで扱えるようにしたものです。\n\n#### MANOVA = 飽和(saturated)モデルとしての SEM\n\n実は MANOVA と多母集団 SEM は、**特殊条件下で数学的に等価**になります。具体的には:\n\n1. DV を**観測変数のまま**(潜在因子に置き換えない)\n2. 平均構造を含み(`meanstructure = TRUE`)、各群で平均ベクトルを自由推定\n3. 共分散行列を**全群等値**(または等値制約なし)に設定\n4. すべての観測変数間の共分散を**飽和**(saturated)に推定\n\nこのとき、多母集団 SEM の **likelihood ratio test (LRT)** は MANOVA の **Wilks' Λ 検定**と漸近的に同じ p 値を返します [@cole1993]。つまり MANOVA は **「観測変数ベースの飽和多群 SEM」の特別な場合**として位置付けられます。\n\n#### `lavaan` で MANOVA と等価な多群 SEM を組む\n\n```r\nlibrary(lavaan)\n\n# 平均構造を持つ飽和多群 SEM(MANOVA と等価)\nmanova_as_sem <- '\n  Recall ~~ Recognition       # DV 間共分散\n  Recall ~ 1                  # Recall の平均\n  Recognition ~ 1             # Recognition の平均\n'\n\nfit_unconstrained <- sem(manova_as_sem, data = simulated,\n                         group = \"Group\", meanstructure = TRUE)\n\n# 群間で平均ベクトルを等値に制約 → 帰無仮説モデル\nfit_means_equal <- sem(manova_as_sem, data = simulated,\n                       group = \"Group\", meanstructure = TRUE,\n                       group.equal = \"intercepts\")\n\n# LRT は MANOVA の Wilks' Λ 検定と漸近的に同等\nanova(fit_means_equal, fit_unconstrained)\n```\n\nこの等価性は理論的には重要ですが、**実用的には MANOVA の方がシンプル**です。SEM の本領は次のような状況で発揮されます。\n\n#### SEM が MANOVA を超える 4 つの場面\n\n1. **DV が複数項目の合成スコア**:`Recall` が 15 項目、`Recognition` が 20 項目の合計得点なら、各項目を指標として **潜在因子 (latent factor)** を作ると測定誤差を分離できます。MANOVA では合成スコアの信頼性を 1 と仮定しているのに対し、SEM では信頼性に応じた減衰補正(disattenuation)が入ります\n2. **測定不変性 (measurement invariance) の検証**:群間で「同じ構成概念を同じように測れているか」を `configural → metric → scalar` の順に検定。**スカラー不変性が成立しない限り、潜在平均の比較は意味を失います**[@vandenberg2000measurement]。MANOVA は測定不変性を仮定したまま走らせてしまう点に注意\n3. **媒介・調整変数を含む理論モデル**:「指導法 → 認知負荷 → テスト得点」のような媒介経路、または交互作用を含む構造モデル。MANOVA は単純な群差検定にとどまる\n4. **欠測 + ML 推定**:SEM は **完全情報最尤推定 (FIML)** で MAR(missing at random)欠測を扱えます。MANOVA はリストワイズ削除が基本なので、欠測が多い縦断データで力を発揮しにくい\n\n実務的な使い分けの目安は次の通りです。\n\n| 問い | MANOVA が向く場面 | SEM が向く場面 |\n|:---|:---|:---|\n| 目的変数は何か | 観測された得点そのものを比較したい | 潜在構成概念を比較したい |\n| 誤差の扱い | 測定誤差は明示的には分離しない | 測定誤差をモデル化できる |\n| 群間等値性 | 暗黙に仮定する | 段階的に検定する(measurement invariance) |\n| 欠測の扱い | リストワイズ削除が基本 | FIML で MAR 欠測に対応 |\n| 研究目的 | 群差の omnibus test と追跡 | 測定モデル・媒介・群間等値性まで含めた理論モデル |\n| 典型例 | `Recall` と `Recognition` の平均ベクトル差 | 「語彙知識」や「処理効率」などの潜在因子の群差 |\n\nこの章のデータのように、**少数の観測得点をそのまま目的変数として比較する**なら MANOVA が自然です。一方、もし `Recall` と `Recognition` がそれぞれ複数項目から成る下位尺度で、測定不変性や潜在平均差まで問題にしたいなら、**多母集団 SEM** の方が適切です [@cole1993; @rosseel2012; @vandenberg2000measurement]。詳細な SEM の扱いは第 9 章「潜在変数モデリングと次元縮約」を参照してください。\n\n### H行列とE行列: MANOVAの核心\n\n::: {.callout-tip}\n#### 初読では飛ばして OK\n本サブセクション(H/E 行列・4 つの多変量統計量・固有値分解)は MANOVA の数学的基盤ですが、**初読では「Pillai を読めば足りる」**だけ覚えれば、@sec-manova-execution(MANOVAの実行)以降を読み進められます。後で戻ってきても理解できる構成にしています。\n:::\n\nMANOVAを理解する鍵は、**H行列**（Hypothesis SSCP）と**E行列**（Error SSCP）の関係です [@huberty2006; @psu505_lesson08]。これは、単変量ANOVAにおける群間平方和（$SS_B$）と群内平方和（$SS_W$）の多変量版です。Warne [-@warne2014] はMANOVAの理解において「H行列とE行列の比が全統計量の基盤であることを把握することが最も重要」と述べています。\n\n| 単変量ANOVA | MANOVA | 意味 |\n|:---:|:---:|:---|\n| $SS_B$（群間平方和） | **H行列**（Hypothesis SSCP） | 群平均の散らばり（効果の大きさ） |\n| $SS_W$（群内平方和） | **E行列**（Error SSCP） | 群内のばらつき（ノイズ） |\n| $F = MS_B / MS_W$ | $\\mathbf{H}\\mathbf{E}^{-1}$ の固有値 | 効果がノイズに比べてどれだけ大きいか |\n\n: ANOVAとMANOVAの対応関係 {.striped}\n\n単変量ANOVAでは $F$ 値が1つだけですが、MANOVAでは $\\mathbf{H}\\mathbf{E}^{-1}$ の**固有値**が $s = \\min(p, h)$ 個($p$ = DV 数、$h$ = その効果の仮説自由度)得られます。1 要因 $k$ 群の主効果なら $h = k - 1$ なので $s = \\min(p, k-1)$ になりますが、**交互作用や複雑な対比では $h$ がそのコントラストの自由度として変わる**ため、より一般的には $h$ で書きます。各固有値 $\\lambda_i$ は、多変量空間における群分離の「次元」ごとの大きさを表します。\n\n#### 固有値の直感的理解\n\n固有値 $\\lambda_i$ は「$i$ 番目に重要な群分離の方向で、群差がノイズの何倍あるか」を示します。\n\n- $\\lambda_1$ が大きく $\\lambda_2$ が小さければ、群分離はほぼ1次元で説明できます。\n- 複数の $\\lambda_i$ が大きければ、群分離は多次元的です。\n- 4つの検定統計量（Pillai, Wilks, Hotelling-Lawley, Roy）は、これらの固有値を**異なる方法で要約**したものです。\n\n### 4つの検定統計量の比較\n\n4つの検定統計量はいずれもH行列とE行列の関係を要約しますが、要約の仕方が異なります [@olson1974; @r_summary_manova; @psu505_lesson08]。\n\n| 統計量 | 数式の直感 | 有意の方向 | 頑健性 | 推奨場面 |\n|:---|:---|:---:|:---:|:---|\n| **Pillai's Trace** | $\\sum \\frac{\\lambda_i}{1 + \\lambda_i}$ | 大きい = 効果大 | **最も頑健** | **デフォルト推奨** |\n| Wilks' $\\Lambda$ | $\\prod \\frac{1}{1 + \\lambda_i}$ | 小さい = 効果大 | 中程度 | 等共分散・大標本 |\n| Hotelling-Lawley | $\\sum \\lambda_i$ | 大きい = 効果大 | 中程度 | 等共分散・大標本 |\n| Roy's Largest Root | $\\max(\\lambda_i)$ | 大きい = 効果大 | **最も脆弱** | **非推奨** |\n\n: 4つのMANOVA検定統計量の比較 [@olson1974; @psu505_lesson08] {.striped}\n\nOlson [-@olson1974] は6つの多変量検定統計量をモンテカルロ・シミュレーションで比較し、以下の実務的な結論を導いています。\n\n- **正規性違反のみ**の場合: すべての統計量が比較的頑健であり、結果は大きく変わらない。\n- **共分散行列の不等質性（等共分散の違反）**: Pillai のトレースが最も頑健。Wilks や Hotelling-Lawley は保守的になりすぎるか、リベラル（第I種過誤率が高い状態）になるリスクがある。\n- **不等質性 + サンプルサイズの不均衡**: 最も実務的に危険な条件。このとき、Pillai のみが名義 $\\alpha$ 水準を比較的よく維持する。\n- **Roy の最大根**: F 近似は **F 値の下限(p 値の上限)** を与える形になっており、実際の Type I エラー率は近似の良し悪しに依存します。一般にすべての条件で最も Type I エラー率が高く、群数や DV 数が多い場合に特に問題が大きくなります。\n\nPenn State STAT 505 [-@psu505_lesson08] も同様に、実務でまず確認すべきはPillaiであると明記しています。R の `summary.manova()` のデフォルトがPillaiであるのもこの根拠に基づいています [@r_summary_manova]。加えて公式ドキュメントは、**目的変数が非常に高く相関するとランク判定が不安定になりうる**ため、`tol` で実効ランクを制御する設計になっていることも明記しています [@r_summary_manova]。これは、本章で DV 間相関を先に確認する理由とも整合しています。\n\n#### 実務上の結論: Roy's Largest Root は主報告にしない\n\nRoy の最大根は最大の固有値のみに基づくため、多変量的な群差の全体像を反映しません。さらに、F 近似が **F 値の下限**(p 値の上限)を与える形になっているため、実際の有意性に対して保守的にならず Type I エラーが膨張しやすいことが知られています。Olson [-@olson1974] のモンテカルロ研究では、正規性・等共分散の両方が違反し、かつ群サイズが不均衡な条件で、Roy のType Iエラー率が名義水準の2倍以上に達する場合があることが示されています。本章では **Pillai を主報告**とし、他の統計量は一貫性確認のために併記します。\n\n### MANOVAとDDA（判別分析）の関係\n\nMANOVAと判別分析は、同じ数学的構造の「表と裏」です [@finch2013; @huberty2006]。\n\n- **MANOVA**: 「群間に多変量的な差があるか？」を検定する（有意性の判定）\n- **DDA（Descriptive Discriminant Analysis）**: 「どのDVが、どの方向に群分離に寄与しているか？」を明らかにする（効果の解釈）\n\n両者はともに $\\mathbf{H}\\mathbf{E}^{-1}$ の固有値分解に基づきますが、MANOVAは固有値の大きさを検定し、DDAは対応する固有ベクトル（＝判別関数の係数）を解釈します。このため、**DDAはMANOVAの最も自然な追跡法**であり、単変量ANOVAよりも理論的に一貫した追跡分析を提供します [@smith2020; @sherry2005]。\n\nにもかかわらず、実証研究の実態はDDAの使用率が極めて低いことを示しています。\n\n- **Warne [-@warne2014]** はMANOVAを用いた58本の実証論文をレビューし、DDAを追跡法として適切に使用した論文は**1本もなかった**と報告しています。ほぼすべてが単変量ANOVAのみで追跡しており、多変量構造の解釈が放棄されていました。\n- **Smith et al. [-@smith2020]** は英才教育研究の56本をレビューし、同様の傾向を確認しています。さらに、DDAを使用しないことでType Iエラーが深刻に膨張するリスクを定量的に示しました。\n- **Finch & French [-@finch2013]** は、DDAの判別関数がMANOVAの検定統計量と数学的に同一の情報源（$\\mathbf{H}\\mathbf{E}^{-1}$ の固有値・固有ベクトル）に基づくことを示し、追跡法としての理論的一貫性を強調しています。\n\n本章では、これらのレビューの知見を踏まえ、**DDAを主要追跡法として一貫して使用する**方針を採ります。\n\n#### 本章の分析デザイン上の前提\n\nここでは、**群間（between-subjects）設計**として説明します。同一参加者の反復測定や項目反復を主対象にする場合は、混合効果モデル（第6章）に接続する方が妥当です。\n\n#### 反復測定データにそのまま適用しない\n\n- 本章のデータ構造は **1参加者1行** を前提にしています。\n- 同一参加者を複数時点で追跡したデータ（within-subjects）に、そのまま本章のMANOVA/判別分析を当てると、独立性仮定を損ねる可能性があります。\n- 反復測定デザインでは、反復測定MANOVAまたは混合効果モデルを優先してください。\n\n::: {.callout-important}\n### `Time` という変数名を使う場面\n\n`Time` は、同じ参加者を複数時点で測る場合や、系列上の観測位置を表す場合に使う方が混乱が少なくなります。本章のような between-subjects MANOVA では、直後/遅延テストのような時点名を群要因として置くのではなく、`LearningMode`、`PracticeFormat`、`FeedbackTiming` など、各参加者が1条件だけ経験する実験条件名を使います。\n:::\n\n### 統計チュートリアル文献との接続\n\n::: {.callout-tip}\n#### 初読では飛ばして OK\n本サブセクション以下の文献レビューは、本章の方針(Pillai 主、DDA 主、Sherry & Henson 構造係数 .30 基準など)が**現代の文献的合意**にどう支えられているかをまとめたものです。**初読では飛ばし**、論文を書くときに **どの文献を引用するか**を確認するために戻ってきてください。\n:::\n\n\n### 主要ソースの要点\n\n本章は以下の文献を統合しています。\n\n**MANOVAの設計と解釈**\n\n- **Warne [-@warne2014]**: MANOVAの実証論文58本をレビュー。DDAを追跡に使った論文は0本。推奨手順は「(1) 前提確認 → (2) 多変量検定 → (3) 効果量 → (4) DDAによる追跡」の4段階。\n- **Penn State STAT 505 [-@psu505_lesson08]**: 4統計量はH行列とE行列の比を異なる視点で要約するもの。フローは「前提確認→MANOVA→追跡」。各統計量の数式的導出も掲載。\n\n**検定統計量とR docs**\n\n- **Olson [-@olson1974]**: モンテカルロ・シミュレーションで6統計量を比較。正規性違反・共分散不等質性・群サイズ不均衡の3条件を組み合わせた結果、Pillaiが最も名義 $\\alpha$ 水準を維持。Royは全条件で最も脆弱。\n- **R公式ドキュメント [-@r_manova_doc]**: `manova()` は `aov()` を呼び出し、`manova` クラスを付けて多変量用 summary に渡す入口関数。\n- **R公式ドキュメント [-@r_summary_manova]**: `summary.manova()` でPillaiがデフォルト。\n\n**前提チェック**\n\n- **Korkmaz et al. [-@korkmaz2014]**: MVNパッケージ。HZ検定はアフィン変換不変で、次元数と標本サイズに依存しにくい。Mardia の歪度・尖度検定やRoyston検定も提供。\n- **Tabachnick & Fidell [-@tabachnick2019]**: Box's M は過敏であるため $p < .001$ を実務基準とする。DV間相関が .90 を超える場合は多重共線性を疑い、DV の統合を検討。\n\n**判別分析（DDA）**\n\n- **Smith et al. [-@smith2020]**: 英才教育研究56本をレビュー。ほぼ全論文が単変量ANOVAのみで追跡。Type Iエラー率は最大76%に達しうることをシミュレーションで示す。DDAの使用を強く推奨。\n- **Sherry & Henson [-@sherry2005]**: 構造係数の解釈基準（$|r_s| \\geq .30$ で実質的寄与）。標準化係数は多重共線性に敏感であるため、構造係数を優先すべきことを具体例で示す。\n- **Finch & French [-@finch2013]**: DDAとMANOVAが数学的に同一の固有値分解に基づくことの厳密な証明。DVが5個以上の場合でもDDAが安定していることを示す。\n- **Penn State STAT 505 [-@psu505_lesson10]**: 7段階の判別分析手順を提示。(1) 前提確認 → (2) 判別関数推定 → (3) 有意性検定 → (4) 構造係数 → (5) 分類規則 → (6) LOOCV → (7) 結果の解釈。\n\n**HEプロット**\n\n- **Friendly [-@friendly2007]**: H行列とE行列を楕円として可視化する方法論。H楕円がE楕円からはみ出す方向が、Roy の最大根の検定で有意な方向と対応するという幾何学的解釈を提供。\n\n**教科書的参照**\n\n- **Tabachnick & Fidell [-@tabachnick2019]**: 各群のN > DV数が最低条件。構造係数 $|r_s| \\geq .30$ を実質的寄与の閾値とする。DV間相関の適正範囲は .30-.70。\n- **Stevens [-@stevens2009]**: 社会科学向け。検定力の観点から、各群20名以上を推奨。効果量小（$f = .10$）の検出には各群50名以上が必要。\n- **Hahs-Vaughn [-@hahs2017]**: MANOVA の前提条件を段階的に解説。段階的な判断フローチャートを提供。\n\n### 分析の全体像\n\n本章の分析パイプラインは以下の順で進みます。\n\nまず前提条件（多変量正規性・Box's M など）を確認し、次に MANOVA を実行して主報告は Pillai 統計量で行います。続いて HE プロットで H/E 行列を可視化し、追跡分析として DDA を主軸に、必要に応じて単変量 ANOVA を補助的に実施します。最後に効果量・分類精度・検定力を整理して APA 形式で報告します。\n\nまた、MANOVA の適用可否は次の判断基準で決めます。まず目的変数（DV）が2つ以上あるかを確認し、1つだけなら ANOVA/t 検定で十分です。DV が複数ある場合は DV 間相関を確認し、`.30-.70` 程度の中程度相関なら MANOVA の利点が出ます。一方、相関が低すぎる場合は個別 ANOVA で十分、高すぎる場合は多重共線性を疑って DV の再設計を検討します。MANOVA を実施した後に Pillai が有意なら追跡分析へ進み、非有意なら検定力不足の可能性を確認します。\n\n### R公式ドキュメントとの対応\n\nこの章で使う主要関数は、R の公式ドキュメントや各パッケージの公式マニュアルで次のように位置づけられています。ここを理解しておくと、「なぜこの関数をこの場面で使うのか」がかなり明確になります。\n\n| 関数 | 公式ドキュメントで重要な点 | 本章での使い方 |\n|:---|:---|:---|\n| `stats::manova()` | `aov()` を呼び出して `manova` クラスを付与し、**多変量用の要約メソッド**で読む設計 [@r_manova_doc] | 多変量線形モデルをまず適合する入口 |\n| `summary.manova()` | デフォルトは **Pillai**。さらに docs は**非常に高い残差相関**に注意し、`tol` で実効ランクを制御できると説明 [@r_summary_manova] | 4統計量を併記しつつ、Pillai を主報告とする根拠 |\n| `MASS::lda()` | 共通共分散を仮定し、`prior` が2群超では**判別軸の向きにも影響**する。`CV = TRUE` では LOOCV 分類を返す [@mass_lda_doc] | DDA の主追跡法として、構造係数と分類精度を確認 |\n| `MASS::qda()` | 群別共分散を許容するが、群内共分散が特異だと不安定・失敗しやすい [@mass_qda_doc] | 分類目的の感度分析としてLDAと比較 |\n| `candisc::candisc()` | 多変量線形モデルを**正準判別空間**へ写して可視化する公式パッケージ docs を持つ [@friendly2021candisc] | 群分離の方向を図で読む |\n| `WebPower::wp.kanova()` | 近似的な power 計算ツールであり、複雑な factorial MANOVA の各効果別 power を厳密に与える関数ではない [@zhang2018] | omnibus な目安として使う |\n\n要するに、**`manova()` で適合し、`summary.manova()` で多変量検定を読み、`lda()` / `candisc()` で群分離の方向を解釈し、`qda()` は分類目的の感度分析、`wp.kanova()` は近似的な計画支援**という役割分担です。\n\n## 分析課題とフロー\n\n想定する研究課題は次の2点です。\n\n1. `Instruction`（Glossing vs Writing）と`LearningMode`（Individual vs Collaborative）は、`Recall`と`Recognition`の**組**に影響するか。\n2. 4群（Instruction×LearningMode）は、`Recall`と`Recognition`でどの程度判別できるか。\n\n分析フローは以下の順で進めます。\n\n1. データ設計と記述統計\n2. 前提チェック（独立性、多変量正規性、共分散等質性）\n3. MANOVA（4統計量を併記、主報告はPillai）\n4. HEプロット（H行列とE行列の可視化）\n5. DDA（判別分析を主要追跡法として）\n6. 単変量追跡分析（補助的、多重性調整つき）\n7. 検定力分析\n8. 論文結果節向けの要約\n\n### 中核となる読み筋\n\n論文・報告書で MANOVA の主要結果を提示する際の最低限の流れは以下です。\n\n1. 実行順は前提チェック→MANOVA→HEプロット。結果を読むときは、HEプロットで群分離の全体像を視覚的に把握する。\n2. MANOVA統計量表のPillai列だけを読む。\n3. DDAの構造係数で、どのDVが群分離に寄与しているかを確認する。\n4. 最後の報告テンプレートを自分のデータに置き換える。\n\n## データ作成（語彙学習研究を想定）\n\nここでは、2（Instruction: Glossing vs Writing）× 2（LearningMode: Individual vs Collaborative）の4群・各群45名のシミュレーションデータを作成します。`LearningMode` は「個人で語彙活動に取り組むか、ペア/小グループで協同的に取り組むか」を表す **参加者間要因** です。各学生は1つの学習モードだけに割り当てられるため、本章の「1参加者1行」の前提と整合します。`Recall` と `Recognition` には中程度の相関（$r \\approx .40$）を持たせます。この相関水準では、MANOVAの利点が出やすくなります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_per_group <- 45\n\nmu_tbl <- tibble(\n  Group = c(\n    \"Glossing_Individual\",\n    \"Glossing_Collaborative\",\n    \"Writing_Individual\",\n    \"Writing_Collaborative\"\n  ),\n  Recall_mu = c(12.0, 13.5, 16.0, 17.5),\n  Recognition_mu = c(18.0, 19.5, 23.0, 24.5)\n)\n\n# 2つの従属変数の共分散（中程度の相関を想定）\nSigma <- matrix(\n  c(16, 6,\n    6, 20),\n  nrow = 2,\n  byrow = TRUE\n)\n\nsimulated <- mu_tbl |>\n  mutate(\n    sim = purrr::map2(\n      Recall_mu,\n      Recognition_mu,\n      ~ MASS::mvrnorm(\n          n = n_per_group,\n          mu = c(.x, .y),\n          Sigma = Sigma\n        ) |>\n        as_tibble(.name_repair = \"minimal\") |>\n        setNames(c(\"Recall\", \"Recognition\"))\n    )\n  ) |>\n  dplyr::select(Group, sim) |>\n  tidyr::unnest(sim) |>\n  mutate(\n    Instruction = if_else(str_detect(Group, \"^Glossing\"), \"Glossing\", \"Writing\"),\n    LearningMode = if_else(str_detect(Group, \"Individual$\"), \"Individual\", \"Collaborative\"),\n    ID = row_number(),\n    Recall = pmin(pmax(Recall, 0), 30),\n    Recognition = pmin(pmax(Recognition, 0), 30)\n  ) |>\n  mutate(across(c(Instruction, LearningMode, Group), as.factor)) |>\n  dplyr::select(ID, Instruction, LearningMode, Group, Recall, Recognition)\n\nsimulated |>\n  group_by(Instruction, LearningMode) |>\n  summarise(\n    n = n(),\n    Recall_Mean = mean(Recall),\n    Recognition_Mean = mean(Recognition),\n    .groups = \"drop\"\n  ) |>\n    mutate(across(where(is.numeric), ~ round(.x, 2))) |>\n  knitr::kable(caption = \"シミュレーションデザインの概要（simulated design overview）: Instruction × LearningMode 別のサンプルサイズと平均\")\n```\n\n::: {.cell-output-display}\n\n\nTable: シミュレーションデザインの概要（simulated design overview）: Instruction × LearningMode 別のサンプルサイズと平均\n\n|Instruction |LearningMode  |  n| Recall_Mean| Recognition_Mean|\n|:-----------|:-------------|--:|-----------:|----------------:|\n|Glossing    |Collaborative | 45|       12.40|            19.30|\n|Glossing    |Individual    | 45|       11.30|            17.49|\n|Writing     |Collaborative | 45|       18.12|            24.68|\n|Writing     |Individual    | 45|       16.17|            23.68|\n\n\n:::\n:::\n\n\n**出力の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `n` | 各群のサンプルサイズ（45 = バランスド・デザイン） |\n| `Recall_Mean` | 再生テストの群平均。Writing 群が Glossing 群より高い傾向 |\n| `Recognition_Mean` | 再認テストの群平均。同様に Writing 群が高い傾向 |\n\n## 記述統計と可視化\n\nここでは、群ごとの記述統計量（平均・標準偏差）を算出し、プロファイルプロットで群パターンを視覚化します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesc_tbl <- simulated |>\n  group_by(Instruction, LearningMode) |>\n  summarise(\n    n = n(),\n    Recall_Mean = mean(Recall),\n    Recall_SD = sd(Recall),\n    Recognition_Mean = mean(Recognition),\n    Recognition_SD = sd(Recognition),\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    Recall_SE = Recall_SD / sqrt(n),\n    Recall_CI = qt(0.975, df = n - 1) * Recall_SE,\n    Recognition_SE = Recognition_SD / sqrt(n),\n    Recognition_CI = qt(0.975, df = n - 1) * Recognition_SE\n  )\n\nprofile_plot_tbl <- bind_rows(\n  desc_tbl |>\n    transmute(\n      Instruction,\n      LearningMode,\n      Outcome = \"Recall\",\n      Mean = Recall_Mean,\n      CI = Recall_CI\n    ),\n  desc_tbl |>\n    transmute(\n      Instruction,\n      LearningMode,\n      Outcome = \"Recognition\",\n      Mean = Recognition_Mean,\n      CI = Recognition_CI\n    )\n)\n\ngroup_centers <- simulated |>\n  group_by(Group) |>\n  summarise(\n    Recall = mean(Recall),\n    Recognition = mean(Recognition),\n    .groups = \"drop\"\n  ) |>\n  mutate(Group_label = str_replace(Group, \"_\", \"\\n\"))\n\ndesc_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 2))) |>\n  knitr::kable(caption = \"記述統計（descriptive statistics）: 群別の目的変数（dependent variables）\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 記述統計（descriptive statistics）: 群別の目的変数（dependent variables）\n\n|Instruction |LearningMode  |  n| Recall_Mean| Recall_SD| Recognition_Mean| Recognition_SD| Recall_SE| Recall_CI| Recognition_SE| Recognition_CI|\n|:-----------|:-------------|--:|-----------:|---------:|----------------:|--------------:|---------:|---------:|--------------:|--------------:|\n|Glossing    |Collaborative | 45|       12.40|      3.76|            19.30|           4.80|      0.56|      1.13|           0.71|           1.44|\n|Glossing    |Individual    | 45|       11.30|      4.24|            17.49|           4.52|      0.63|      1.28|           0.67|           1.36|\n|Writing     |Collaborative | 45|       18.12|      4.60|            24.68|           3.56|      0.69|      1.38|           0.53|           1.07|\n|Writing     |Individual    | 45|       16.17|      3.55|            23.68|           3.82|      0.53|      1.07|           0.57|           1.15|\n\n\n:::\n\n```{.r .cell-code}\np_recall <- ggplot(desc_tbl, aes(x = LearningMode, y = Recall_Mean, group = Instruction, color = Instruction)) +\n  geom_errorbar(aes(ymin = Recall_Mean - Recall_CI, ymax = Recall_Mean + Recall_CI), width = 0.08) +\n  geom_line(linewidth = 1.1) +\n  geom_point(size = 2.8) +\n  labs(title = \"Recall（再生）\", y = \"平均得点\", x = \"LearningMode\")\n\np_recog <- ggplot(desc_tbl, aes(x = LearningMode, y = Recognition_Mean, group = Instruction, color = Instruction)) +\n  geom_errorbar(aes(ymin = Recognition_Mean - Recognition_CI, ymax = Recognition_Mean + Recognition_CI), width = 0.08) +\n  geom_line(linewidth = 1.1) +\n  geom_point(size = 2.8) +\n  labs(title = \"Recognition（再認）\", y = \"平均得点\", x = \"LearningMode\")\n\np_recall + p_recog +\n  plot_annotation(\n    title = \"群平均プロファイル\",\n    subtitle = \"Instruction × LearningMode のパターンを2つの目的変数で比較\"\n  )\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-html/descriptives-profile-1.png){width=2100}\n:::\n:::\n\n\n**プロファイルプロットの読み方**:\n\n- 2本の線（Instruction: Glossing vs Writing）がほぼ平行 → 交互作用は小さい\n- 線の上下差が大きい → Instruction 主効果が大きい\n- Individual → Collaborative の傾き → LearningMode 主効果の方向\n- エラーバーは各群平均の 95% 信頼区間であり、平均推定の不確実性を示す\n- 2つのDVで似た形が繰り返されていれば、多変量空間でも一貫した群差がありそうだと予想できる\n\n### DV間相関の確認\n\nMANOVAを実施する前に、DV間の相関が適切な範囲（.30-.70）にあるかを確認します。Tabachnick & Fidell [-@tabachnick2019] は、DV間相関が .90 を超える場合は「深刻な多重共線性」と判断し、DVの統合または一方の除外を推奨しています。一方、相関が .30 未満の場合はDVがほぼ独立であるため、MANOVAの付加価値は小さく、研究質問がDV別に定義されているなら補正付き個別ANOVAも候補になります。\n\nここで注意すべきなのは、全体相関には群平均差による共変動が混ざることです。MANOVAの前提やDVの冗長性を判断するには、全体相関に加えて、群要因を取り除いた**残差相関**も確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_overall <- cor(simulated[, c(\"Recall\", \"Recognition\")])\nresid_dvs <- residuals(lm(cbind(Recall, Recognition) ~ Instruction * LearningMode, data = simulated))\ncor_residual <- cor(resid_dvs)\n\ntibble(\n  Scope = c(\"Overall\", \"Residual after Instruction × LearningMode\"),\n  DV_Pair = \"Recall -- Recognition\",\n  Correlation = c(cor_overall[1, 2], cor_residual[1, 2]),\n  Judgment = case_when(\n    abs(Correlation) < 0.30 ~ \"低い: 補正付き個別ANOVAも候補\",\n    abs(Correlation) <= 0.70 ~ \"扱いやすい範囲: MANOVA推奨\",\n    TRUE ~ \"高すぎる: 多重共線性の懸念\"\n  )\n) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"DV間相関の確認（DV correlation check）: MANOVAに適した相関構造か\")\n```\n\n::: {.cell-output-display}\n\n\nTable: DV間相関の確認（DV correlation check）: MANOVAに適した相関構造か\n\n|Scope                                     |DV_Pair               | Correlation|Judgment                   |\n|:-----------------------------------------|:---------------------|-----------:|:--------------------------|\n|Overall                                   |Recall -- Recognition |       0.555|扱いやすい範囲: MANOVA推奨 |\n|Residual after Instruction × LearningMode |Recall -- Recognition |       0.341|扱いやすい範囲: MANOVA推奨 |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGGally::ggpairs(\n  simulated,\n  columns = c(\"Recall\", \"Recognition\"),\n  mapping = aes(color = Group, alpha = 0.6),\n  title = \"群別の2変量構造\"\n)\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-html/bivariate-ggpairs-1.png){width=2100}\n:::\n:::\n\n\n**`ggpairs` の読み方**:\n\n- 対角成分は各DVの分布の形を示す。大きな歪みや極端な裾がないかを見る\n- 非対角成分は Recall と Recognition の共変動を見る。右上がりなら正の相関である\n- 色ごとの点群が重なりすぎていなければ、群分離の可能性がある\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(simulated, aes(x = Recall, y = Recognition, color = Group)) +\n  geom_point(alpha = 0.45, size = 1.8) +\n  stat_ellipse(level = 0.68, linewidth = 0.8) +\n  geom_point(\n    data = group_centers,\n    aes(x = Recall, y = Recognition, fill = Group),\n    shape = 21,\n    color = \"black\",\n    size = 3.6,\n    stroke = 0.6,\n    show.legend = FALSE\n  ) +\n  geom_label(\n    data = group_centers,\n    aes(x = Recall, y = Recognition, label = Group_label, fill = Group),\n    color = \"black\",\n    size = 3,\n    alpha = 0.85,\n    linewidth = 0.15,\n    show.legend = FALSE\n  ) +\n  labs(\n    title = \"生得点空間における群楕円と群重心\",\n    subtitle = \"楕円は各群の中心付近の典型的な範囲を示す\",\n    x = \"Recall（再生得点）\",\n    y = \"Recognition（再認得点）\"\n  )\n```\n\n::: {.cell-output-display}\n![2つの目的変数空間（two-DV space）における4群構造。楕円（ellipse）は各群の中心付近の散らばり、ラベル付き点は群重心（centroid）を示す。](3_MANOVA_判別分析_files/figure-html/bivariate-group-ellipses-1.png){fig-alt='Recallを横軸、Recognitionを縦軸にした散布図。4群の点、68%楕円、群重心が描かれており、Writing群がGlossing群より右上に位置する。' width=2250}\n:::\n:::\n\n\n**楕円と重心の読み方**:\n\n- 楕円は各群の「中心付近の典型的な散らばり方」（ここでは68%楕円）を示す。楕円が大きく重なるほど群分離は弱い\n- 重心は各群の平均的位置であり、重心どうしが離れていれば群差の方向が明確である\n- 4群が主に右上がり方向で並ぶなら、2つのDVが同じ方向に群差を支えている\n- 楕円の向きが似ていれば、群内共分散の構造も大きくは異なっていない可能性がある\n\n### プロファイル・プロット:平行性・水準・平坦性の視覚化\n\nMANOVA を **profile analysis** の枠組みで読むと、群差は次の 3 つの観点に分解できます [@tabachnick2019]。SLA・教育研究の論文では、この 3 観点を一枚の図で示すことが一般的です。\n\n| 観点 | 帰無仮説 | 視覚的な見え方 |\n|:---|:---|:---|\n| **平行性 (parallelism)** | 群のプロファイル形状が同じ(交互作用なし) | 群間で線が平行 |\n| **水準 (level)** | 群間の全体平均が等しい | 群間で線の高さが揃う |\n| **平坦性 (flatness)** | DV の平均が等しい | 線が水平 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofile_dat <- simulated |>\n  tidyr::pivot_longer(c(Recall, Recognition),\n                      names_to = \"Outcome\", values_to = \"Score\") |>\n  dplyr::group_by(Group, Outcome) |>\n  dplyr::summarise(\n    M  = mean(Score),\n    SE = sd(Score) / sqrt(dplyr::n()),\n    .groups = \"drop\"\n  ) |>\n  dplyr::mutate(\n    Outcome = factor(Outcome, levels = c(\"Recall\", \"Recognition\")),\n    LB = M - 1.96 * SE,\n    UB = M + 1.96 * SE\n  )\n\nggplot(profile_dat,\n       aes(x = Outcome, y = M, color = Group, group = Group)) +\n  geom_line(linewidth = 1.0, alpha = 0.85) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = LB, ymax = UB), width = 0.08, linewidth = 0.6) +\n  labs(\n    title = \"Group Profiles Across Outcomes\",\n    subtitle = \"Parallel lines = no Group × Outcome interaction; vertical gap = Group main effect; flat lines = Outcome main effect\",\n    x = NULL,\n    y = \"Mean Score (with 95% CI)\"\n  )\n```\n\n::: {.cell-output-display}\n![プロファイル・プロット(profile plot):4 群の DV 別平均値と 95% 信頼区間。線が平行 = 平行性成立(交互作用弱)、線の高さが揃う = 水準性成立(群差弱)、線が水平 = 平坦性成立(DV 間差弱)。](3_MANOVA_判別分析_files/figure-html/fig-profile-plot-1.png){#fig-profile-plot fig-alt='横軸に Recall と Recognition の 2 つの DV、縦軸に得点を取り、4 群(Glossing-Imm、Glossing-Del、Writing-Imm、Writing-Del)のプロファイルを線で示した図。各点には 95% CI のエラーバーが付いている。' width=2250}\n:::\n:::\n\n\n**プロファイル・プロットの読み方**:\n\n- **線が平行に近いか?** → 平行なら「群と DV の交互作用は小さい」(**DV を共通尺度で読む前提のもと**、Pillai/Wilks の交互作用検定が非有意になりやすい。本章の Recall と Recognition は近い尺度ですが、厳密な解釈には z 標準化など共通尺度化が望ましい — Tabachnick & Fidell, 2019)\n- **線の高さが群間で揃っているか?** → 揃っていなければ「群主効果あり」(線が上下にずれている)\n- **線が水平か?** → 水平でなければ「DV 主効果あり」(`Recall` と `Recognition` の平均が異なる)\n- **線が交差しているか?** → 交差は強い交互作用を示唆。本章のように Group が複数水準なら、平行でない方向(prep/post 反転、強弱反転など)が DDA の構造係数で読み取れる方向と対応します\n\n::: {.callout-tip}\n#### Profile plot は MANOVA の最初の一枚に最適\n英語教育・SLA のメタ分析的レビュー(Plonsky 2014 系)でも、MANOVA を報告する論文の多くがこの形式を採用しています。HE プロットや正準判別プロットが「多変量空間での技術的解析」の図であるのに対し、profile plot は **「読者(査読者・実践者)に研究結果の構造を即座に伝える」** ための第一の図として機能します。論文では、最初の Results 図として profile plot、補足図として HE / 正準判別プロットを置く構成が王道です。\n:::\n\n## MANOVAの前提\n\n### 独立性（設計で担保する前提）\n\n独立性は、検定結果だけで担保するよりも、**研究計画段階（割り付け・測定手順）で保証する**ことが原則です。ここでは「1参加者1行」であることをデータ構造から確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_check <- simulated |>\n  count(ID, name = \"rows_per_id\")\n\ntable(id_check$rows_per_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1 \n180 \n```\n\n\n:::\n:::\n\n\n**出力の読み方**: すべてのIDに対して行数が1であれば、1参加者1行のデータ構造が確認できます。\n\n### 多変量正規性（群ごと）\n\nMANOVAで確認したいのは、**各群における目的変数ベクトルの多変量正規性**です。全体ではなく群ごとに検定することが重要です。なぜなら、MANOVAの仮定は「各群内の残差が多変量正規分布に従う」ことだからです。\n\n本章では Henze-Zirkler（HZ）検定を用います。HZ 検定は **アフィン変換に不変**(affine invariant、つまり変数の線形変換 = 尺度変更や平行移動・回転を行っても結果が変わらない性質)という望ましい性質を持ちます [@korkmaz2014]。\n\n#### HZ検定をRで実施する最小コード\n\nまずは、全データを一括で検定する最小コードです（動作確認用）。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhz_overall <- MVN::mvn(\n  data = simulated |> dplyr::select(Recall, Recognition),\n  mvn_test = \"hz\",\n  tidy = TRUE\n)\n\nhz_overall$multivariate_normality |>\n  transmute(\n    Scope = \"All groups combined\",\n    Test,\n    Statistic,\n    p_value = p.value,\n    Decision = if_else(p.value < 0.05, \"MVNからの逸脱を示唆\", \"MVNを棄却せず\")\n  ) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"HZ検定（Henze-Zirkler test）の最小例: Rでの1ステップ実装\")\n```\n\n::: {.cell-output-display}\n\n\nTable: HZ検定（Henze-Zirkler test）の最小例: Rでの1ステップ実装\n\n|Scope               |Test          | Statistic| p_value|Decision      |\n|:-------------------|:-------------|---------:|-------:|:-------------|\n|All groups combined |Henze-Zirkler |     0.749|    0.25|MVNを棄却せず |\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n#### Mardia の歪度・尖度検定も併用すると診断的\nHZ 検定は単一の総合的な統計量ですが、**Mardia の歪度・尖度検定** [@mardia1970] を併用すると、**逸脱が「歪み由来」か「裾の重さ由来」か**を切り分けられます。`MVN::mvn(..., mvn_test = \"mardia\")` で得られ、SLA の小サンプル(n < 30/cell)での診断に有効です。なお `MVN` パッケージは v6.x 以降で API がやや再構成されているため、最新版での引数名は `?MVN::mvn` で確認してください。\n\n```r\nmardia <- MVN::mvn(\n  data = simulated |> dplyr::select(Recall, Recognition),\n  mvn_test = \"mardia\",\n  tidy = TRUE\n)\nmardia$multivariate_normality\n```\n\n歪度が問題なら変数変換、尖度が問題ならトリム平均ベースのロバスト法、というように対処方針が分かれます。\n:::\n\n**`MVN::mvn()` の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Test` | 使用した検定名（Henze-Zirkler） |\n| `Statistic` | HZ検定統計量。大きいほど正規性からの逸脱が大きい |\n| `p_value` | $p < .05$ なら「MVNからの逸脱が示唆される」。ただし即中止ではない |\n\n#### 群ごとのHZ検定を自動化する\n\n実務では「全体」より「群ごと」の確認が重要なので、再利用しやすい関数化を行います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_hz_test <- function(df, vars = c(\"Recall\", \"Recognition\"), alpha = 0.05) {\n  hz_out <- MVN::mvn(\n    data = df |> dplyr::select(all_of(vars)),\n    mvn_test = \"hz\",\n    tidy = TRUE\n  )\n\n  hz_out$multivariate_normality |>\n    transmute(\n      Test,\n      Statistic,\n      p_value = p.value,\n      alpha = alpha,\n      Decision = if_else(p.value < alpha, \"MVNからの逸脱を示唆\", \"MVNを棄却せず\")\n    )\n}\n\nalpha_level <- 0.05\n\nmvn_tbl <- simulated |>\n  group_by(Group) |>\n  group_modify(~ run_hz_test(.x, alpha = alpha_level)) |>\n  ungroup()\n\nmvn_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"群別の多変量正規性（multivariate normality）: Henze-Zirkler検定\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 群別の多変量正規性（multivariate normality）: Henze-Zirkler検定\n\n|Group                  |Test          | Statistic| p_value| alpha|Decision      |\n|:----------------------|:-------------|---------:|-------:|-----:|:-------------|\n|Glossing_Collaborative |Henze-Zirkler |     0.343|   0.790|  0.05|MVNを棄却せず |\n|Glossing_Individual    |Henze-Zirkler |     0.675|   0.160|  0.05|MVNを棄却せず |\n|Writing_Collaborative  |Henze-Zirkler |     0.408|   0.635|  0.05|MVNを棄却せず |\n|Writing_Individual     |Henze-Zirkler |     0.474|   0.480|  0.05|MVNを棄却せず |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhz_action_tbl <- mvn_tbl |>\n  mutate(\n    Action = if_else(\n      p_value < alpha,\n      \"外れ値・分布形状を確認し、Pillai中心で慎重に解釈\",\n      \"正規性の観点では通常どおりMANOVAを実行可能\"\n    )\n  ) |>\n  dplyr::select(Group, Statistic, p_value, Decision, Action)\n\nhz_action_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"HZ検定（Henze-Zirkler test）の解釈ガイド: 判定と次の対応\")\n```\n\n::: {.cell-output-display}\n\n\nTable: HZ検定（Henze-Zirkler test）の解釈ガイド: 判定と次の対応\n\n|Group                  | Statistic| p_value|Decision      |Action                                     |\n|:----------------------|---------:|-------:|:-------------|:------------------------------------------|\n|Glossing_Collaborative |     0.343|   0.790|MVNを棄却せず |正規性の観点では通常どおりMANOVAを実行可能 |\n|Glossing_Individual    |     0.675|   0.160|MVNを棄却せず |正規性の観点では通常どおりMANOVAを実行可能 |\n|Writing_Collaborative  |     0.408|   0.635|MVNを棄却せず |正規性の観点では通常どおりMANOVAを実行可能 |\n|Writing_Individual     |     0.474|   0.480|MVNを棄却せず |正規性の観点では通常どおりMANOVAを実行可能 |\n\n\n:::\n:::\n\n\n#### HZ検定の補助: マハラノビス距離による外れ値診断\n\nHZ検定だけでは「どの群で逸脱が起きているか」が見えにくい場合があります。そこで、群ごとにマハラノビス距離を計算し、$\\chi^2_{0.975, p}$ を超える比率を確認します。マハラノビス距離は、多変量空間における「中心からの距離」であり、単変量の外れ値検出では見逃す多変量的な外れ値を検出できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise_mahal_outliers <- function(df, vars = c(\"Recall\", \"Recognition\"), cutoff_prob = 0.975) {\n  x <- df |> dplyr::select(all_of(vars)) |> as.matrix()\n  p <- ncol(x)\n  d2 <- mahalanobis(x, colMeans(x), cov(x))\n  cutoff <- qchisq(cutoff_prob, df = p)\n\n  tibble(\n    N = nrow(x),\n    p = p,\n    Cutoff = cutoff,\n    Outlier_N = sum(d2 > cutoff),\n    Outlier_Rate = mean(d2 > cutoff)\n  )\n}\n\nmahal_tbl <- simulated |>\n  group_by(Group) |>\n  group_modify(~ summarise_mahal_outliers(.x)) |>\n  ungroup()\n\nmahal_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"マハラノビス距離（Mahalanobis distance）による外れ値確認: 群別外れ値率と97.5%カットオフ\")\n```\n\n::: {.cell-output-display}\n\n\nTable: マハラノビス距離（Mahalanobis distance）による外れ値確認: 群別外れ値率と97.5%カットオフ\n\n|Group                  |  N|  p| Cutoff| Outlier_N| Outlier_Rate|\n|:----------------------|--:|--:|------:|---------:|------------:|\n|Glossing_Collaborative | 45|  2|  7.378|         1|        0.022|\n|Glossing_Individual    | 45|  2|  7.378|         1|        0.022|\n|Writing_Collaborative  | 45|  2|  7.378|         1|        0.022|\n|Writing_Individual     | 45|  2|  7.378|         2|        0.044|\n\n\n:::\n:::\n\n\n**マハラノビス距離の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Cutoff` | $\\chi^2_{0.975, p=2} \\approx 7.38$。これを超える観測が多変量的外れ値の候補 |\n| `Outlier_N` | カットオフを超えた観測数 |\n| `Outlier_Rate` | 外れ値率。正規分布なら約2.5%が期待値。10%を超えると要注意 |\n\n次に、$\\chi^2$ Q-Qプロットで多変量正規性を視覚的に確認します。点が対角線に沿っていれば、マハラノビス距離が $\\chi^2$ 分布に従っている（＝多変量正規性が妥当）ことを示します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmahal_qq_tbl <- simulated |>\n  group_by(Group) |>\n  group_modify(~ {\n    x <- .x |> dplyr::select(Recall, Recognition) |> as.matrix()\n    d2 <- sort(mahalanobis(x, colMeans(x), cov(x)))\n    tibble(\n      theoretical = qchisq(ppoints(length(d2)), df = ncol(x)),\n      observed = d2\n    )\n  }) |>\n  ungroup()\n\nggplot(mahal_qq_tbl, aes(x = theoretical, y = observed)) +\n  geom_point(alpha = 0.7, size = 1.5) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\") +\n  facet_wrap(~ Group, scales = \"free\") +\n  labs(\n    title = \"群別のカイ二乗Q-Qプロット\",\n    subtitle = \"マハラノビス距離と理論分位点の比較\",\n    x = \"理論分位点\",\n    y = \"観測マハラノビス距離\"\n  )\n```\n\n::: {.cell-output-display}\n![群別のマハラノビス距離Q-Qプロット（Mahalanobis distance Q-Q plot）。点が破線に沿うほど多変量正規性（multivariate normality）の仮定を置きやすい。](3_MANOVA_判別分析_files/figure-html/fig-mahalanobis-qq-1.png){#fig-mahalanobis-qq width=2100}\n:::\n:::\n\n\n**Q-Qプロットの読み方**:\n\n- 点が対角線（破線）に沿っていれば → 多変量正規性は妥当\n- 右上で対角線から上方に逸脱 → 裾が重い（外れ値が多い）\n- 系統的なS字カーブ → 歪度の問題\n\n### HZ検定の読み方（実務まとめ）\n\n- `p >= .05`: 「MVNを棄却しない」。通常どおりMANOVAへ進む。\n- `p < .05`: 「逸脱の示唆」。即中止ではなく、外れ値確認・図示・Pillai中心報告で対応する。\n- 群ごとに判定し、どの群で逸脱が強いかを先に把握すると解釈が安定する。\n- Pillai の Trace は MVN 逸脱に最も頑健な検定統計量である [@olson1974]。\n\n#### 前提チェックを一括実行する関数\n\n以下の関数は他章でも再利用できます。`dv` と `group` を変えるだけで同じ流れを適用できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_manova_assumptions <- function(\n  data,\n  dv,\n  group,\n  id = NULL,\n  alpha = 0.05,\n  box_alpha = 0.001,\n  cutoff_prob = 0.975\n) {\n  group_sym <- rlang::sym(group)\n\n  hz <- data |>\n    group_by(!!group_sym) |>\n    group_modify(~ run_hz_test(.x, vars = dv, alpha = alpha)) |>\n    ungroup()\n\n  mahal <- data |>\n    group_by(!!group_sym) |>\n    group_modify(~ summarise_mahal_outliers(.x, vars = dv, cutoff_prob = cutoff_prob)) |>\n    ungroup()\n\n  box <- biotools::boxM(\n    data |> dplyr::select(all_of(dv)),\n    grouping = dplyr::pull(data, !!group_sym)\n  )\n\n  id_evidence <- if (!is.null(id) && id %in% names(data)) {\n    id_counts <- data |> count(.data[[id]], name = \"rows_per_id\")\n    if (all(id_counts$rows_per_id == 1)) {\n      \"One row per participant ID\"\n    } else {\n      paste0(\"Repeated IDs detected (max rows per ID = \", max(id_counts$rows_per_id), \")\")\n    }\n  } else {\n    \"No ID variable supplied (design-based judgment required)\"\n  }\n\n  summary <- tibble(\n    Assumption = c(\n      \"Independence\",\n      \"Multivariate normality (HZ)\",\n      \"Mahalanobis outlier burden\",\n      \"Homogeneity of covariance (Box's M)\"\n    ),\n    Evidence = c(\n      id_evidence,\n      paste0(sum(hz$p_value < alpha), \" / \", nrow(hz), \" groups flagged\"),\n      paste0(sum(mahal$Outlier_N), \" flagged obs across groups\"),\n      paste0(\"p = \", signif(box$p.value, 4))\n    ),\n    Practical_Decision = c(\n      if_else(str_detect(id_evidence, \"Repeated\"), \"Re-check design / consider mixed model\", \"Proceed\"),\n      if_else(any(hz$p_value < alpha), \"Proceed with caution (Pillai-priority)\", \"Proceed\"),\n      if_else(mean(mahal$Outlier_Rate) > 0.10, \"Inspect influential cases\", \"Proceed\"),\n      if_else(box$p.value < box_alpha, \"Proceed with caution (covariance mismatch)\", \"Proceed\")\n    )\n  )\n\n  list(hz = hz, mahal = mahal, box = box, summary = summary)\n}\n\nassump_obj <- check_manova_assumptions(\n  data = simulated,\n  dv = c(\"Recall\", \"Recognition\"),\n  group = \"Group\",\n  id = \"ID\"\n)\n\nassump_obj$summary |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"前提チェック（assumption checks）の一括診断: 1回の実行で得る要約\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 前提チェック（assumption checks）の一括診断: 1回の実行で得る要約\n\n|Assumption                          |Evidence                    |Practical_Decision |\n|:-----------------------------------|:---------------------------|:------------------|\n|Independence                        |One row per participant ID  |Proceed            |\n|Multivariate normality (HZ)         |0 / 4 groups flagged        |Proceed            |\n|Mahalanobis outlier burden          |5 flagged obs across groups |Proceed            |\n|Homogeneity of covariance (Box's M) |p = 0.2714                  |Proceed            |\n\n\n:::\n:::\n\n\n**一括チェック結果の読み方**:\n\n| Assumption | Proceed の条件 | 要注意の対応 |\n|:---|:---|:---|\n| Independence | 1参加者1行 | 反復あり → 混合モデルを検討 |\n| MVN (HZ) | 全群で p > .05 | フラグ群あり → Pillai優先 |\n| Outlier burden | 外れ値率 < 10% | 高い → 感度分析 |\n| Box's M | p > .001 | p < .001 → Pillai優先、群サイズの均衡を確認 |\n\n### 共分散行列の等質性（Box's M）\n\nBox's M検定は「群間で共分散行列が等しい」という帰無仮説を検定します [@box1949]。MANOVAの検定統計量（特にWilks' $\\Lambda$）は等共分散を仮定するため、この前提の確認が必要です。\n\nただし、Box's M は **(1) 多変量正規性を仮定する**ため、それ自体が MVN 違反に対して非頑健であり、**(2) 標本サイズに対しても過敏で**、大標本では実質的に無視できる程度の違いでも有意になることがあります。このため、Tabachnick & Fidell [-@tabachnick2019] および Huberty & Olejnik [-@huberty2006] は、$p < .05$ ではなく **$p < .001$ を実務的な基準**として採用することを推奨しています。Box's M は機械的な合否判定ではなく、**HE プロットによる群別共分散楕円の視覚的確認**と併せて判断するのが妥当です。\n\nさらに、Olson [-@olson1974] のモンテカルロ研究は、等共分散の違反があっても**群サイズが均衡していればPillaiのトレースは比較的頑健**であることを示しています。最も危険なのは「共分散不等質 + 群サイズ不均衡」の組み合わせであり、この条件ではすべての検定統計量が影響を受けますが、Pillaiが最も安定しています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbox_m <- biotools::boxM(\n  simulated |>\n    dplyr::select(Recall, Recognition),\n  grouping = simulated$Group\n)\n\nbox_tbl <- tibble(\n  Test = \"Box's M\",\n  Statistic = as.numeric(box_m$statistic),\n  df = as.numeric(box_m$parameter),\n  p_value = box_m$p.value,\n  Decision = if_else(box_m$p.value < 0.001, \"共分散等質性に注意\", \"重大な逸脱は示されず\")\n)\n\nbox_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"共分散行列の等質性（homogeneity of covariance matrices）: Box's M検定\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 共分散行列の等質性（homogeneity of covariance matrices）: Box's M検定\n\n|Test    | Statistic| df| p_value|Decision             |\n|:-------|---------:|--:|-------:|:--------------------|\n|Box's M |    11.063|  9|   0.271|重大な逸脱は示されず |\n\n\n:::\n:::\n\n\n**`Box's M` の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Statistic` | Box の M 統計量。大きいほど群間の共分散行列の差が大きい |\n| `df` | 近似 $\\chi^2$ の自由度（群数とDV数に依存） |\n| `p_value` | $p < .001$ なら共分散等質性に注意。$p < .05$ でも即問題ではない |\n| `Decision` | 判定結果。注意の場合は Pillai を優先し、群サイズの均衡を確認 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nassumption_summary <- tibble(\n  Assumption = c(\n    \"Independence (between-subject design)\",\n    \"Multivariate normality (HZ by group)\",\n    \"Homogeneity of covariance (Box's M)\"\n  ),\n  Evidence = c(\n    \"One row per participant ID\",\n    paste0(sum(mvn_tbl$p_value < alpha_level), \" / \", nrow(mvn_tbl), \" groups flagged\"),\n    paste0(\"p = \", round(box_tbl$p_value[[1]], 4))\n  ),\n  Practical_Decision = c(\n    \"Proceed (design-based check)\",\n    if_else(any(mvn_tbl$p_value < alpha_level), \"Proceed with caution (Pillai-priority)\", \"Proceed\"),\n    if_else(box_tbl$p_value[[1]] < 0.001, \"Proceed with caution (covariance mismatch)\", \"Proceed\")\n  )\n)\n\nassumption_summary |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"前提チェックリスト（assumption checklist; 実務要約）: MANOVA前に確認する項目\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 前提チェックリスト（assumption checklist; 実務要約）: MANOVA前に確認する項目\n\n|Assumption                            |Evidence                   |Practical_Decision           |\n|:-------------------------------------|:--------------------------|:----------------------------|\n|Independence (between-subject design) |One row per participant ID |Proceed (design-based check) |\n|Multivariate normality (HZ by group)  |0 / 4 groups flagged       |Proceed                      |\n|Homogeneity of covariance (Box's M)   |p = 0.2714                 |Proceed                      |\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n#### 前提が大きく崩れたときの代替手法\nHZ / Box's M で深刻な違反が確認され、Pillai の頑健性だけでは安心できない場合、次の代替手法が候補になります。\n\n| 手法 | パッケージ・関数 | 適する場面 |\n|---|---|---|\n| **順列 MANOVA(PERMANOVA)** [@anderson2001permanova] | `vegan::adonis2()` | MVN を仮定せず、距離行列から順列ベースで p 値算出。生態学起源だが SLA でも有用 |\n| **トリム平均ベースの頑健 MANOVA** | `WRS2::mulrank()` 等 | 重い裾、外れ値に頑健 |\n| **ノンパラメトリック MANOVA** | `npmv::nonpartest()` | 順位ベース、極端な非正規性に対応 |\n| **ベイズ多変量回帰** | `brms::brm(mvbind(Recall, Recognition) ~ ...)` | 複数 DV を同時にベイズ推定、残差相関も推定。詳細は第 7 章 |\n\nこれらは本章の主軸ではありませんが、「HZ で逸脱が大きい」「Box's M で群サイズも不均衡」といった条件で **感度分析として並走させる**価値があります。\n:::\n\n::: {.callout-tip}\n#### PERMANOVA の companion viz:NMDS / PCoA 順序付け\nPERMANOVA を使う場合、結果を**距離ベースの 2 次元順序付け図** (`vegan::metaMDS()` または `cmdscale()`) と一緒に提示するのが標準です。生態学では `NMDS + PERMANOVA` が定番のセットで、SLA でも DV が多い高次元ケースでは群分離パターンを直感的に伝えられます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vegan)\n\n# Bray-Curtis(または Euclidean)距離で順序付け\ndvs_mat <- as.matrix(simulated[, c(\"Recall\", \"Recognition\")])\nnmds_fit <- vegan::metaMDS(dvs_mat, distance = \"euclidean\", k = 2, trace = 0)\n\nnmds_dat <- as.data.frame(vegan::scores(nmds_fit, display = \"sites\")) |>\n  dplyr::bind_cols(simulated[, c(\"Group\", \"Instruction\", \"LearningMode\")])\n\n# PERMANOVA(同じ距離行列で)\npermanova_fit <- vegan::adonis2(dvs_mat ~ Instruction * LearningMode,\n                                 data = simulated, method = \"euclidean\",\n                                 permutations = 999)\n\nggplot(nmds_dat, aes(x = NMDS1, y = NMDS2, color = Group)) +\n  geom_point(alpha = 0.7, size = 2.5) +\n  stat_ellipse(level = 0.68, linewidth = 0.8) +\n  labs(\n    title = \"NMDS Ordination of Multivariate Data\",\n    subtitle = paste0(\"PERMANOVA: F = \",\n                       round(permanova_fit$F[1], 2),\n                       \", p = \", format.pval(permanova_fit$`Pr(>F)`[1], digits = 3)),\n    x = \"NMDS Axis 1\",\n    y = \"NMDS Axis 2\"\n  )\n```\n:::\n\n\n**読み方**:NMDS は元の DV 距離をできるだけ忠実に 2 次元に圧縮した「形状」を示します。PERMANOVA の F 値・p 値は本章の Pillai/Wilks と同じ役割(群差の総合検定)ですが、**MVN を仮定しない**点が違います。点群が色別に固まっていれば、PERMANOVA で検出した群差がどんな形をしているかが一目でわかります。DV が 2 つ程度なら HE プロットで十分ですが、**DV が 5 個以上**(複数下位スコアや項目反応データ)の高次元ケースで NMDS が真価を発揮します。\n:::\n\n## MANOVAの実行 {#sec-manova-execution}\n\n### 4つの統計量を併記して確認\n\nここでは、`manova()` 関数を用いて多変量分散分析を実行します。`cbind(Recall, Recognition)` で2つの目的変数を同時に指定し、Instruction と LearningMode の主効果および交互作用を検定します。R の公式ドキュメントでは `manova()` 自体はモデル適合の入口で、**多変量的な読みは `summary.manova()` 側で与えられる**と説明されています [@r_manova_doc; @r_summary_manova]。4つの検定統計量を併記しますが、**Pillai のトレースを主報告**とします [@olson1974; @r_summary_manova]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_manova <- manova(\n  cbind(Recall, Recognition) ~ Instruction * LearningMode,\n  data = simulated\n)\n\nextract_manova <- function(test_name) {\n  stats <- summary(fit_manova, test = test_name)$stats\n  statistic_col <- if (test_name %in% colnames(stats)) {\n    test_name\n  } else {\n    setdiff(colnames(stats), c(\"Df\", \"approx F\", \"num Df\", \"den Df\", \"Pr(>F)\"))[[1]]\n  }\n\n  tibble(\n    Test = test_name,\n    Effect = rownames(stats),\n    Hypothesis_df = stats[, \"Df\"],\n    Statistic = stats[, statistic_col],\n    Approx_F = stats[, \"approx F\"],\n    df1 = stats[, \"num Df\"],\n    df2 = stats[, \"den Df\"],\n    p_value = stats[, \"Pr(>F)\"]\n  ) |>\n    dplyr::filter(Effect != \"Residuals\")\n}\n\nmanova_tbl <- purrr::map(\n  c(\"Pillai\", \"Wilks\", \"Hotelling-Lawley\", \"Roy\"),\n  extract_manova\n) |>\n  purrr::list_rbind()\n\nmanova_tbl |>\n  mutate(\n    p = if_else(\n      p_value < .001,\n      \"< .001\",\n      sub(\"^0\", \"\", sprintf(\"%.3f\", p_value))\n    )\n  ) |>\n  mutate(across(c(Statistic, Approx_F), ~ round(.x, 3))) |>\n  mutate(across(c(Hypothesis_df, df1, df2), ~ round(.x, 0))) |>\n  dplyr::select(Test, Effect, Hypothesis_df, Statistic, Approx_F, df1, df2, p) |>\n  knitr::kable(caption = \"MANOVA検定統計量（MANOVA test statistics）: Instruction、LearningMode、交互作用\")\n```\n\n::: {.cell-output-display}\n\n\nTable: MANOVA検定統計量（MANOVA test statistics）: Instruction、LearningMode、交互作用\n\n|Test             |Effect                   | Hypothesis_df| Statistic| Approx_F| df1| df2|p      |\n|:----------------|:------------------------|-------------:|---------:|--------:|---:|---:|:------|\n|Pillai           |Instruction              |             1|     0.407|   59.975|   2| 175|< .001 |\n|Pillai           |LearningMode             |             1|     0.046|    4.222|   2| 175|.016   |\n|Pillai           |Instruction:LearningMode |             1|     0.008|    0.694|   2| 175|.501   |\n|Wilks            |Instruction              |             1|     0.593|   59.975|   2| 175|< .001 |\n|Wilks            |LearningMode             |             1|     0.954|    4.222|   2| 175|.016   |\n|Wilks            |Instruction:LearningMode |             1|     0.992|    0.694|   2| 175|.501   |\n|Hotelling-Lawley |Instruction              |             1|     0.685|   59.975|   2| 175|< .001 |\n|Hotelling-Lawley |LearningMode             |             1|     0.048|    4.222|   2| 175|.016   |\n|Hotelling-Lawley |Instruction:LearningMode |             1|     0.008|    0.694|   2| 175|.501   |\n|Roy              |Instruction              |             1|     0.685|   59.975|   2| 175|< .001 |\n|Roy              |LearningMode             |             1|     0.048|    4.222|   2| 175|.016   |\n|Roy              |Instruction:LearningMode |             1|     0.008|    0.694|   2| 175|.501   |\n\n\n:::\n:::\n\n\n**MANOVA出力の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Test` | 使用した検定統計量（Pillai を主報告） |\n| `Effect` | Instruction（主効果）、LearningMode（主効果）、Instruction:LearningMode（交互作用） |\n| `Hypothesis_df` | その効果の仮説自由度。2水準要因では通常1 |\n| `Statistic` | 検定統計量の値。Pillai は効果のランクに依存して最大値が決まる。本章の各効果では最大1 |\n| `Approx_F` | F 近似値。大きいほど効果が強い |\n| `df1, df2` | 仮説自由度と誤差自由度 |\n| `p` | APA形式に整えたp値。$p < .05$ なら多変量的に有意 |\n\n### 主報告（Pillai）を抽出\n\n\n::: {.cell}\n\n```{.r .cell-code}\npillai_focus <- manova_tbl |>\n  dplyr::filter(Test == \"Pillai\") |>\n  mutate(\n    Interpretation = if_else(p_value < 0.05, \"有意\", \"非有意\"),\n    Effect = factor(Effect, levels = c(\"Instruction\", \"LearningMode\", \"Instruction:LearningMode\")),\n    p_label = if_else(\n      p_value < .001,\n      \"p < .001\",\n      paste0(\"p = \", sub(\"^0\", \"\", sprintf(\"%.3f\", p_value)))\n    )\n  )\n\npillai_focus |>\n  mutate(across(c(Statistic, Approx_F), ~ round(.x, 3))) |>\n  dplyr::select(Test, Effect, Hypothesis_df, Statistic, Approx_F, df1, df2, p_label, Interpretation) |>\n  knitr::kable(caption = \"主推論（primary inference; Pillai's trace）: 推奨する多変量主検定\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 主推論（primary inference; Pillai's trace）: 推奨する多変量主検定\n\n|Test   |Effect                   | Hypothesis_df| Statistic| Approx_F| df1| df2|p_label  |Interpretation |\n|:------|:------------------------|-------------:|---------:|--------:|---:|---:|:--------|:--------------|\n|Pillai |Instruction              |             1|     0.407|   59.975|   2| 175|p < .001 |有意           |\n|Pillai |LearningMode             |             1|     0.046|    4.222|   2| 175|p = .016 |有意           |\n|Pillai |Instruction:LearningMode |             1|     0.008|    0.694|   2| 175|p = .501 |非有意         |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pillai_focus, aes(x = Statistic, y = forcats::fct_rev(Effect), color = Interpretation)) +\n  geom_segment(\n    aes(x = 0, xend = Statistic, yend = forcats::fct_rev(Effect)),\n    linewidth = 1.1,\n    show.legend = FALSE\n  ) +\n  geom_point(size = 3.4, show.legend = FALSE) +\n  geom_text(aes(label = p_label), nudge_x = 0.015, hjust = 0, size = 3.4, show.legend = FALSE) +\n  scale_color_manual(values = c(\"有意\" = \"#1b7837\", \"非有意\" = \"#762a83\")) +\n  expand_limits(x = max(pillai_focus$Statistic) + 0.07) +\n  labs(\n    title = \"Pillaiのトレースによる主検定\",\n    x = \"Pillaiのトレース\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![効果ごとのPillaiのトレース（Pillai's trace）。線分が長いほど多変量的な信号（multivariate signal）が強い。](3_MANOVA_判別分析_files/figure-html/pillai-effect-plot-1.png){fig-alt='Instruction、LearningMode、交互作用のPillai値を横棒状に示す図。Instructionが最も大きく、交互作用が最も小さい。' width=2100}\n:::\n:::\n\n\n**Pillaiプロットの読み方**:\n\n- 線分が長いほど、その効果が多変量空間で大きいことを示す\n- `Instruction` と `LearningMode` の線分が長く、`Instruction:LearningMode` が短ければ、「主効果が中心で交互作用は弱い」という図式になる\n- 色は有意性、長さは効果の大きさの目安なので、**有意かどうか**と**どれくらい大きいか**を分けて読める\n- 表を読む前にこの図を見ると、どの効果から解釈を始めるべきかが分かる\n\n### 多変量効果量\n\nMANOVA の効果量にはいくつかの正式な定義があります。本章で主報告する Pillai のトレースに加えて、研究間比較や多変量η²との対応で次の指標がよく用いられます [@kim2010multieta; @tatsuoka1988multivariate; @cohen1988]。\n\n| 指標 | 定義 | 由来 | 値域 |\n|:---|:---|:---|:---|\n| **Pillai η²** | $\\eta^2_{\\text{Pillai}} = V / s$($V$ = Pillai のトレース、$s = \\min(p, h)$) | Pillai のトレースの正規化 | $[0, 1]$ |\n| **Wilks η²** | $\\eta^2_{\\text{Wilks}} = 1 - \\Lambda^{1/s}$($\\Lambda$ = Wilks の Λ) | Wilks のΛから派生する代表的な多変量η² | $[0, 1]$ |\n| **Hotelling η²** | $\\eta^2_{HL} = (T/s)/(1 + T/s)$($T$ = Hotelling-Lawley トレース) | Hotelling のトレースから | $[0, 1]$ |\n| **Roy η²** | $\\eta^2_{\\text{Roy}} = \\theta = \\lambda_1 / (1 + \\lambda_1)$($\\lambda_1$ = 最大固有値) | 最大固有値方向の説明分散割合 | $[0, 1]$ |\n\nこれらは正式な**多変量効果量**であり、単変量の偏η²の自然な多変量拡張に対応します(Kim & Olejnik, 2010; Tatsuoka, 1988)。本章では Pillai を主報告するため、$\\eta^2_{\\text{Pillai}} = V/s$ を補助的に提示します。\n\n::: {.callout-tip}\n#### Pillai η² と単変量偏η²の関係\nDV が 1 つ($p=1$)のとき、Pillai η² は単変量偏 η² と一致します。複数 DV のときは、**多変量空間での「説明分散割合」**を表す自然な拡張です。`effectsize::eta_squared(fit_manova)` でも計算できますが、ランク $s$ の扱いにより僅かに値が異なる場合があります。\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pillai η² = V/s の算出\np_dvs <- 2  # DV数\n\npillai_index_tbl <- pillai_focus |>\n  mutate(\n    s = pmin(p_dvs, Hypothesis_df),\n    Pillai_eta2 = Statistic / s,\n    Comment = \"多変量η²(Pillai 由来)\"\n  ) |>\n  dplyr::select(Effect, Hypothesis_df, Statistic, s, Pillai_eta2, Comment)\n\npillai_index_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"Pillai 由来の多変量 η²($\\\\eta^2_{\\\\text{Pillai}} = V/s$)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Pillai 由来の多変量 η²($\\eta^2_{\\text{Pillai}} = V/s$)\n\n|Effect                   | Hypothesis_df| Statistic|  s| Pillai_eta2|Comment               |\n|:------------------------|-------------:|---------:|--:|-----------:|:---------------------|\n|Instruction              |             1|     0.407|  1|       0.407|多変量η²(Pillai 由来) |\n|LearningMode             |             1|     0.046|  1|       0.046|多変量η²(Pillai 由来) |\n|Instruction:LearningMode |             1|     0.008|  1|       0.008|多変量η²(Pillai 由来) |\n\n\n:::\n:::\n\n\n**指標の読み方**:\n\n| 指標 | 読み方 |\n|:---|:---|\n| `Statistic` | Pillai のトレース本体 *V*。APA 報告ではこれを使う |\n| `s` | $s = \\min(p, h)$。$p$ = DV 数、$h$ = その効果の仮説自由度 |\n| `Pillai_eta2` | Pillai η² = $V/s$。多変量空間での説明分散割合(0〜1) |\n\n`Pillai_eta2` は単変量の偏 η² と直接比較するものではありませんが、**効果間の相対比較**および**多変量効果の大きさの目安**として有用です。\n\n::: {.callout-warning}\n**多変量 η² に対する Cohen 慣例値の準用は推奨されません。** Cohen の小・中・大(.01 / .06 / .14)は**単変量分散説明割合**から導出された目安であり、$V/s$ や $1-\\Lambda^{1/s}$ のような **多変量** η² 系列に直接適用できる根拠はありません。Pillai η² の解釈は **当該分野の先行研究の効果量レンジ**(SLA なら Plonsky & Oswald のメタ分析的基準を多変量に拡張するなど)を基準にしてください。\n:::\n\n#### 多変量効果量フォレストプロット\n\n`effectsize::eta_squared(fit_manova, ci = 0.95)` で各効果の Pillai η² と 95% CI を取得し、フォレストプロット形式で並べると効果サイズの相対比較が一目で分かります。これは Fernández-Castilla et al. [-@fernandezcastilla2021forest] らが推奨する **多変量フォレストプロットの応用形**で、複数効果を一枚で対比する際に有効です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanova_eta <- effectsize::eta_squared(\n  fit_manova,\n  partial = TRUE,\n  ci = 0.95,\n  alternative = \"two.sided\",\n  generalized = FALSE\n)\n\nmanova_eta_tbl <- as.data.frame(manova_eta) |>\n  dplyr::mutate(\n    Effect = factor(Parameter, levels = rev(Parameter)),\n    is_signif = CI_low > 0\n  )\n\nggplot(manova_eta_tbl,\n       aes(x = Eta2_partial, y = Effect, color = is_signif)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_errorbarh(aes(xmin = CI_low, xmax = CI_high),\n                 height = 0.18, linewidth = 0.7) +\n  geom_point(size = 3.2) +\n  scale_color_manual(values = c(`TRUE` = \"#1b7837\", `FALSE` = \"#762a83\"),\n                     labels = c(`TRUE` = \"CI が 0 を含まない\", `FALSE` = \"CI が 0 を含む\"),\n                     name = NULL) +\n  labs(\n    title = \"Multivariate Effect Sizes (Pillai η²) with 95% CI\",\n    subtitle = \"効果間の相対比較と推定の不確実性を同時に提示\",\n    x = expression(Pillai~eta^2~(95*\"%\"~CI)),\n    y = NULL\n  ) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![多変量効果量フォレストプロット:各効果の Pillai η² と 95% 信頼区間。点は推定値、横棒は信頼区間、縦破線は「効果なし」基準(η² = 0)。](3_MANOVA_判別分析_files/figure-html/fig-multivariate-forest-1.png){#fig-multivariate-forest fig-alt='Instruction、LearningMode、Instruction:LearningMode の 3 効果について、Pillai η² の点推定と 95% 信頼区間を横方向に並べたフォレストプロット。' width=2250}\n:::\n:::\n\n\n**フォレストプロットの読み方**:\n\n- **点**は Pillai η² の点推定値、**横棒**は 95% CI\n- **CI が 0 を含まなければ**、F 検定で有意と整合(両側 CI は η² が 0 で有界なため F 有意でも CI 下限が 0 に張り付くことがある — 片側 CI `alternative = \"greater\"` を併用すると非対称性が解消される)\n- **棒の長さ**は推定の不確実性。サンプルサイズが小さい効果や DV 数が多い効果では棒が長くなりやすい\n- 効果間の **相対比較**を一枚で示せるため、論文の Results セクションでは Pillai 表に加えてこの図を載せると視認性が大きく上がります\n\n#### MANOVAの有意性と追跡検定のType Iエラー\n\n「MANOVAが有意なら、追跡ANOVAのType Iエラーは制御されている」と書かれることがありますが、これは**誤り**です。MANOVAの有意性は多変量空間での検定結果であり、個々のDVに対する保護効果は提供しません。追跡分析では依然として多重性調整（Holm法など）が必要です [@huberty2006]。\n\nSmith et al. [-@smith2020] は56本のレビューにより、この誤解に基づく慣行が広く定着していることを実証しました。さらに重要なことに、単変量ANOVAによる追跡は**多変量パターンを見逃す**可能性があります。Warne [-@warne2014] は58本のレビューでDDAを使った論文がゼロであったことを示し、DDAこそがMANOVAの数学的構造と整合した追跡法であると強調しています。\n\n## HEプロット: H行列とE行列の可視化\n\nHEプロットは、MANOVA のH行列（群間変動）とE行列（群内変動）を**楕円として可視化**する手法です [@friendly2007]。Friendly [-@friendly2007] はこの手法を体系的に定式化し、多変量一般線形モデルの効果を2次元散布図上で幾何学的に解釈する方法を示しました。\n\nHEプロットの核心的な読み方は次のとおりです。\n\n- **E楕円**は群内変動（誤差）の大きさと方向を表す。E楕円は全効果で共通です。\n- **H楕円**は各効果の群間変動を表す。効果ごとに1つずつ描かれます。\n- **H楕円がE楕円からはみ出す方向**は、その効果が強く現れている方向を読むための視覚的手がかりです。Friendly [-@friendly2007] はこれが**Roy の最大根の検定方向と幾何学的に対応する**ことを示しています。\n- H楕円がE楕円に完全に収まる場合、その2DV平面では効果が小さいと読む。ただし最終的な有意性判断は、MANOVA表の検定結果と併せて行う。\n\nこの幾何学的対応は、数値だけでは把握しにくい多変量的な群差のパターンを直感的に読み取ることを可能にします。\n\n### H行列とE行列の確認\n\nまず、H行列とE行列を数値で確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Instruction × LearningMode の2要因MANOVAフィット（再利用）\nH_matrices <- summary(fit_manova)$SS\nE_matrix <- H_matrices$Residuals\nH_instruction <- H_matrices$Instruction\nH_mode <- H_matrices$LearningMode\nH_interaction <- H_matrices$`Instruction:LearningMode`\n\n# H行列の表示\ntibble(\n  Effect = c(\"Instruction\", \"LearningMode\", \"Interaction\"),\n  H_Recall_Recall = c(H_instruction[1,1], H_mode[1,1], H_interaction[1,1]),\n  H_Recall_Recog = c(H_instruction[1,2], H_mode[1,2], H_interaction[1,2]),\n  H_Recog_Recog = c(H_instruction[2,2], H_mode[2,2], H_interaction[2,2])\n) |>\n    mutate(across(where(is.numeric), ~ round(.x, 2))) |>\n  knitr::kable(caption = \"仮説SSCP行列（hypothesis SSCP matrix; H）: 各効果における群間変動\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 仮説SSCP行列（hypothesis SSCP matrix; H）: 各効果における群間変動\n\n|Effect       | H_Recall_Recall| H_Recall_Recog| H_Recog_Recog|\n|:------------|---------------:|--------------:|-------------:|\n|Instruction  |         1259.33|        1377.84|       1507.52|\n|LearningMode |          104.60|          96.15|         88.39|\n|Interaction  |            8.22|          -7.83|          7.45|\n\n\n:::\n:::\n\n\n**H行列の読み方**:\n\n| 要素 | 意味 |\n|:---|:---|\n| `H_Recall_Recall` | Recall における群間変動（対角要素 = 分散成分） |\n| `H_Recog_Recog` | Recognition における群間変動 |\n| `H_Recall_Recog` | Recall と Recognition の群間共変動（非対角要素）。正なら両DVが同方向に群差を持つ |\n\n### 2要因MANOVAのHEプロット\n\nここでは、`heplots::heplot()` を用いて各効果のH楕円とE楕円を重ねてプロットします。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lm() オブジェクトが必要（heplot は lm を受け付ける）\nfit_lm_mv <- lm(cbind(Recall, Recognition) ~ Instruction * LearningMode, data = simulated)\n\nheplots::heplot(\n  fit_lm_mv,\n  fill = TRUE,\n  fill.alpha = 0.1,\n  main = \"HE Plot: Instruction × LearningMode Effects on Recall and Recognition\",\n  xlab = \"Recall\",\n  ylab = \"Recognition\"\n)\n```\n\n::: {.cell-output-display}\n![2要因MANOVAのHEプロット（HE plot）。E楕円（error ellipse）は群内変動、H楕円（hypothesis ellipse）は各効果の群間変動を示す。](3_MANOVA_判別分析_files/figure-html/fig-heplot-two-way-1.png){#fig-heplot-two-way fig-alt='RecallとRecognitionの2次元平面上に、Instruction、LearningMode、交互作用のH楕円とE楕円が重ねて描かれている。' width=2400}\n:::\n:::\n\n\n**HEプロットの読み方**:\n\n| プロット要素 | 意味 |\n|:---|:---|\n| **E楕円**（最も大きい楕円） | 群内のばらつき（誤差）の大きさと形状 |\n| **H楕円**（効果ごとの小さい楕円） | 各効果（Instruction, LearningMode, 交互作用）の群間変動 |\n| H楕円がE楕円を**超える方向** | その方向に群差の視覚的手がかりがある |\n| H楕円がE楕円に**収まる** | その2DV平面では効果が小さい可能性が高い |\n| 楕円の**傾き** | DV間の相関の方向（正の相関なら右上がり） |\n\n#### HEプロットの実務的な読み方\n\nHEプロットでは「H楕円がE楕円からはみ出す方向」に注目してください [@friendly2007]。\n\n1. **はみ出す方向**: H楕円がE楕円の外に出る方向は、群差が強く現れている方向を読むための手がかりです。これはRoyの最大根の検定方向と幾何学的に対応しますが、図だけで有意性を判断せず、MANOVA表と併せて確認します。\n2. **楕円の大きさ**: H楕円が大きいほど群間変動が大きい。E楕円に完全に収まるH楕円は、その効果が（その平面では）小さいことを示します。\n3. **楕円の傾き**: DV間に正の相関がある場合、楕円は右上がりに傾きます。この傾きの方向は DV 間の共分散構造を反映しています。\n4. **複数の効果の比較**: Instruction のH楕円が大きく、Interaction のH楕円が小さければ、主効果が支配的で交互作用は弱いことが一目でわかります。\n\nFriendly [-@friendly2007] は、HEプロットの最大の利点を「数表だけでは見えない多変量的パターンを、研究者が直感的に把握できること」と述べています。特に、MANOVAが有意なのに全ANOVAが非有意なケース（DVの組み合わせが群差を担う場合）では、HEプロットが唯一の視覚的手がかりを提供します。\n\n### 1要因（Group）でのHEプロット\n\n4群をまとめた1要因モデルでのHEプロットも確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm_oneway <- lm(cbind(Recall, Recognition) ~ Group, data = simulated)\n\nheplots::heplot(\n  fit_lm_oneway,\n  fill = TRUE,\n  fill.alpha = 0.1,\n  main = \"HE Plot: Group Effect (One-way)\",\n  xlab = \"Recall\",\n  ylab = \"Recognition\"\n)\n```\n\n::: {.cell-output-display}\n![4セルを1要因Groupとして見たHEプロット（HE plot）。4群全体の分離構造（group separation）を確認する。](3_MANOVA_判別分析_files/figure-html/fig-heplot-one-way-1.png){#fig-heplot-one-way fig-alt='RecallとRecognitionの平面上に、Group効果のH楕円とE楕円が描かれている。' width=2400}\n:::\n:::\n\n\n### 正準判別プロット\n\n正準判別分析は、群分離を最大化する線形結合（正準判別関数）を求め、その空間にデータを射影します。`candisc` の公式マニュアルでも、これは多変量線形モデルを**canonical discriminant space** へ写して可視化する手順として説明されています [@friendly2021candisc]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncan_fit <- candisc::candisc(fit_lm_oneway)\nplot(can_fit,\n     main = \"Canonical Discriminant Plot\")\n```\n\n::: {.cell-output-display}\n![4群全体の正準判別プロット（canonical discriminant plot）。群重心（centroid）と変数ベクトル（variable vectors）から分離方向を読む。](3_MANOVA_判別分析_files/figure-html/fig-canonical-discriminant-plot-1.png){#fig-canonical-discriminant-plot fig-alt='正準判別空間に4群の位置とRecall、Recognitionの変数ベクトルが表示される。' width=2400}\n:::\n:::\n\n\n**正準判別プロットの読み方**:\n\n| 要素 | 意味 |\n|:---|:---|\n| Can1（横軸） | 第1正準判別関数。群分離を最も多く説明する方向 |\n| Can2（縦軸） | 第2正準判別関数。Can1 に直交する方向での追加的な群分離 |\n| 各群の点と楕円 | 群の分布。楕円が離れているほど群分離が大きい |\n| 矢印（ベクトル） | 各DVが正準空間でどの方向に寄与しているか |\n\n## 判別分析による追跡（DDA）: 4セル全体の群分離\n\nMANOVAは「群間に多変量的な差があるか？」を検定しますが、**どのDVが、どの方向に群分離に寄与しているか**は明らかにしません。DDA（Descriptive Discriminant Analysis）は、MANOVAと同じ固有値分解を逆方向から解釈することで、この問いに答えます [@smith2020; @finch2013; @sherry2005]。\n\nただし、本節の LDA は `Instruction`、`LearningMode`、交互作用を個別に追跡するものではなく、`Instruction × LearningMode` から作った**4セル全体**（`Group`）の分離を記述する分析です。主効果や交互作用ごとの正準方向を直接見たい場合は、`candisc()` でモデル項ごとに正準判別分析を行う必要があります。本章では、初心者にとって読みやすい「4群が2つのDV空間でどう分かれるか」を中心に説明します。\n\nPenn State STAT 505 [-@psu505_lesson10] は、判別分析を以下の7段階で体系化しています。本章もこの流れに沿って進めます。\n\n1. **前提の確認**: 多変量正規性、共分散行列の等質性（Box's M）\n2. **判別関数の推定**: $\\mathbf{H}\\mathbf{E}^{-1}$ の固有値分解から判別関数を導出\n3. **有意性の検定**: 各判別関数のWilks' $\\Lambda$ 検定（MANOVAと等価）\n4. **構造係数の評価**: DVと判別関数の相関（$|r_s| \\geq .30$ を実質的寄与の目安にする）\n5. **分類規則の構築**: 事前確率と誤分類コストに基づく判別境界\n6. **交差検証**: LOOCVによる分類精度の評価\n7. **結果の解釈**: 構造係数・分散説明割合・分類精度を統合的に報告\n\n### DDAとANOVA追跡の比較\n\n| 追跡法 | 利点 | 限界 |\n|:---|:---|:---|\n| **DDA（判別分析）** | 多変量構造を保持し、DV間の相関を考慮。4セル全体の群分離を説明しやすい [@finch2013] | 効果別の追跡とは区別が必要。英語教育研究では馴染みが薄い場合がある |\n| 個別ANOVA | 直感的に理解しやすい。個々のDVの効果量が明確 | DV間の相関を無視。Type Iエラー膨張のリスクがある。多変量パターンを見逃す |\n\n構造係数の .30 基準は、もともと因子分析における loading の解釈基準として広く流通していた経験則を、Sherry & Henson [-@sherry2005] が判別関数の構造係数解釈に **適用・推奨**したものです。Tabachnick & Fidell [-@tabachnick2019] もこの基準を教科書的に採用しています(Sherry & Henson は一次出典ではなく、先行する経験則の判別分析への適用)。また Smith et al. [-@smith2020] は、無補正の単変量追跡では Type I エラー率が大きく膨張しうることを示しています。\n\nWarne [-@warne2014] のレビューでは、MANOVAを使った58本中DDAを適切に使った論文は0本でした。本章では **DDAを多変量構造の主要な記述的追跡法**とし、個別ANOVAは補助的な追跡法として後に報告します。\n\n### LDAの推定と係数\n\nここでは、`MASS::lda()` を用いて線形判別分析を実行します [@venables2002; @mass_lda_doc]。公式ドキュメントに沿うと、`lda()` は**群ごとの平均と、全群で共通の群内共分散（within-class covariance）**を使って判別軸を推定します。また `prior` は単に事前確率を変えるだけでなく、**2群を超える場合には判別軸の回転にも影響**します [@mass_lda_doc]。DDAとして使う場合、分類精度よりも**判別関数の係数**と**構造係数**に注目します。\n\nFinch & French [-@finch2013] が示したように、LDAの判別関数は $\\mathbf{H}\\mathbf{E}^{-1}$ の固有ベクトルに対応しており、MANOVAの固有値と同一の情報源です。つまり、LDAの結果を解釈することは、MANOVAの結果を「群分離の方向と構造」という観点から補完することに相当します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_fit <- MASS::lda(\n  Group ~ Recall + Recognition,\n  data = simulated,\n  CV = FALSE\n)\n\nlda_coef <- as.data.frame(lda_fit$scaling) |>\n  rownames_to_column(\"Variable\")\n\nlda_coef |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA係数（LDA coefficients）: 元尺度の正準判別係数（raw canonical discriminant coefficients）\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA係数（LDA coefficients）: 元尺度の正準判別係数（raw canonical discriminant coefficients）\n\n|Variable    |   LD1|    LD2|\n|:-----------|-----:|------:|\n|Recall      | 0.144| -0.219|\n|Recognition | 0.151|  0.203|\n\n\n:::\n\n```{.r .cell-code}\ncentroid_tbl <- as_tibble(lda_fit$means, rownames = \"Group\")\ncentroid_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 2))) |>\n  knitr::kable(caption = \"群重心（group centroids）: 群別の予測変数平均\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 群重心（group centroids）: 群別の予測変数平均\n\n|Group                  | Recall| Recognition|\n|:----------------------|------:|-----------:|\n|Glossing_Collaborative |  12.40|       19.30|\n|Glossing_Individual    |  11.30|       17.49|\n|Writing_Collaborative  |  18.12|       24.68|\n|Writing_Individual     |  16.17|       23.68|\n\n\n:::\n:::\n\n\n**LDA係数の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `LD1`, `LD2`, ... | 判別関数の係数。各DVにどの重みをかけて線形結合を作るか |\n| 群重心 | 各群がLD空間のどこに位置するか。重心が離れているほど群分離が良い |\n\n### 構造係数（Structure Coefficients）\n\n構造係数は、各DVと判別関数の相関であり、**各DVが判別関数にどれだけ寄与しているか**を示します。Sherry & Henson [-@sherry2005] は構造係数を「判別関数が捉える多変量的パターンの中で、各DVがどの程度そのパターンを共有しているか」と定義しています。\n\n`MASS::lda()` の係数は、ここでは元尺度上の正準判別係数です。変数を標準化していない限り「標準化係数」ではありません。これらの係数は回帰分析の $\\beta$ 係数と同様にDV間相関の影響を受けますが、構造係数は**DVと判別関数スコアの相関**なので解釈が安定しやすいです。Tabachnick & Fidell [-@tabachnick2019] は、DV間相関が .40 を超える場合、係数と構造係数の乖離が大きくなりうることを示しており、そのような場合に構造係数の優先使用を推奨しています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_pred <- predict(lda_fit, newdata = simulated)\n\n# 構造係数 = 各DVと判別関数スコアの相関\nstructure_coefs <- cor(\n  simulated[, c(\"Recall\", \"Recognition\")],\n  lda_pred$x\n)\n\nstructure_tbl <- as.data.frame(structure_coefs) |>\n  rownames_to_column(\"Variable\") |>\n  as_tibble()\n\nstructure_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"構造係数（structure coefficients）: DVと判別関数（discriminant functions）の相関\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 構造係数（structure coefficients）: DVと判別関数（discriminant functions）の相関\n\n|Variable    |   LD1|    LD2|\n|:-----------|-----:|------:|\n|Recall      | 0.869| -0.495|\n|Recognition | 0.894|  0.448|\n\n\n:::\n\n```{.r .cell-code}\ncoef_compare_plot_tbl <- bind_rows(\n  lda_coef |>\n    pivot_longer(-Variable, names_to = \"Function\", values_to = \"Value\") |>\n    mutate(Metric = \"Raw canonical coefficient\"),\n  structure_tbl |>\n    pivot_longer(-Variable, names_to = \"Function\", values_to = \"Value\") |>\n    mutate(Metric = \"Structure coefficient\")\n) |>\n  mutate(\n    Metric = factor(Metric, levels = c(\"Raw canonical coefficient\", \"Structure coefficient\"))\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(coef_compare_plot_tbl, aes(x = Function, y = Variable, fill = Value)) +\n  geom_tile(color = \"white\", linewidth = 0.8) +\n  geom_text(aes(label = sprintf(\"%.2f\", Value)), size = 4) +\n  facet_wrap(~ Metric) +\n  scale_fill_gradient2(\n    low = \"#b2182b\",\n    mid = \"white\",\n    high = \"#2166ac\",\n    midpoint = 0\n  ) +\n  labs(\n    title = \"どの目的変数が判別関数を支えているか\",\n    x = NULL,\n    y = NULL,\n    fill = \"Value\"\n  )\n```\n\n::: {.cell-output-display}\n![元尺度の正準判別係数（raw canonical discriminant coefficients）と構造係数（structure coefficients）。解釈は通常、構造係数を優先する。](3_MANOVA_判別分析_files/figure-html/dda-loading-heatmap-1.png){fig-alt='2つの目的変数と判別関数の関係をヒートマップで示す図。元尺度係数と構造係数が別パネルで表示される。' width=2250}\n:::\n:::\n\n\n**構造係数の解釈基準** [@sherry2005; @tabachnick2019]:\n\n| 構造係数の絶対値 | 解釈 |\n|:---:|:---|\n| $\\geq .30$ | **実質的な寄与**。その判別関数への重要な貢献 |\n| .15 -- .30 | 中程度の寄与。補助的に解釈 |\n| $< .15$ | 寄与はわずか。その判別関数には実質的に貢献していない |\n\n**係数ヒートマップの読み方**:\n\n- 上段の元尺度係数は「モデルがどの重みで線形結合を作ったか」を示す\n- 下段の構造係数は「各DVがその判別関数とどれだけ強く相関しているか」を示す\n- 2つがほぼ同じなら、解釈は安定している\n- 2つがずれるなら、多重共線性や抑圧効果を疑い、**下段の構造係数を優先**して読む\n\n#### 判別係数 vs 構造係数: どちらを報告すべきか\n\nLDA の判別係数は回帰分析の係数と同様に、多重共線性の影響を受けます。DV間の相関が高い場合、一方のDVの係数が不安定になったり、符号が反転したりすることがあります。\n\nSherry & Henson [-@sherry2005] は以下の指針を示しています。\n\n1. **構造係数を常に報告する**。標準化係数のみの報告は、多変量構造の解釈を歪める。\n2. **両者が一致する場合**: DV間の多重共線性が低い。判別係数も参考にできる。\n3. **両者が乖離する場合**: DV間の多重共線性が高い。構造係数を優先し、判別係数は参考として報告する。\n4. **構造係数の符号が逆転する場合**: そのDVは他のDVを通じて間接的に判別関数に関与している（抑圧効果の可能性）。\n\nTabachnick & Fidell [-@tabachnick2019] も同じ立場をとり、「構造係数 $\\geq .30$ を実質的寄与の閾値とする」という基準を広く普及させています。\n\n### 分散説明割合（Proportion of Trace）\n\n各判別関数が群間分散のどれだけを説明するかを確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_trace <- lda_fit$svd^2 / sum(lda_fit$svd^2)\n\nprop_trace_tbl <- tibble(\n  Function = paste0(\"LD\", seq_along(prop_trace)),\n  Eigenvalue = lda_fit$svd^2,\n  Proportion = prop_trace,\n  Cumulative = cumsum(prop_trace)\n)\n\nprop_trace_tbl |>\n  mutate(\n    Proportion = scales::percent(Proportion, accuracy = 0.1),\n    Cumulative = scales::percent(Cumulative, accuracy = 0.1)\n  ) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"Trace割合（proportion of trace）: 各判別関数が説明する群間分散\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Trace割合（proportion of trace）: 各判別関数が説明する群間分散\n\n|Function | Eigenvalue|Proportion |Cumulative |\n|:--------|----------:|:----------|:----------|\n|LD1      |     43.002|98.8%      |98.8%      |\n|LD2      |      0.505|1.2%       |100.0%     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(prop_trace_tbl, aes(x = Function, y = Proportion)) +\n  geom_col(fill = \"#3182bd\", width = 0.6) +\n  geom_text(aes(label = scales::percent(Proportion, accuracy = 0.1)), vjust = -0.5, size = 3.7) +\n  geom_line(aes(y = Cumulative, group = 1), color = \"#e6550d\", linewidth = 0.9) +\n  geom_point(aes(y = Cumulative), color = \"#e6550d\", size = 2.6) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1.05)) +\n  labs(\n    title = \"判別関数ごとのTrace割合\",\n    x = NULL,\n    y = \"群間分散の割合\"\n  )\n```\n\n::: {.cell-output-display}\n![各判別関数（discriminant function）が説明する群間分散。LD1が支配的なら、群分離（group separation）はほぼ1次元で要約できる。](3_MANOVA_判別分析_files/figure-html/proportion-trace-plot-1.png){width=2100}\n:::\n:::\n\n\n**Proportion of Trace の読み方**:\n\n- LD1 の Proportion が 90% 以上 → 群分離はほぼ1次元で説明できる\n- 複数のLDが大きな割合を占める → 群分離は多次元的（DVの役割が異なる方向で発揮される）\n- 累積割合が早く 100% に近づくなら、少数の判別関数だけで全体像を十分に要約できる\n\n### LOOCVによる分類精度\n\nDDAの分類性能を Leave-One-Out Cross-Validation（LOOCV）で評価します [@psu505_lesson10]。LOOCVは各観測を1つずつ除外して残りで判別関数を推定し、除外した観測の群を予測します。これにより、過学習を軽減した分類精度が得られます。`MASS::lda()` の公式ドキュメントでも、`CV = TRUE` を指定すると交差検証ベースの `class` と posterior が返る設計になっています [@mass_lda_doc]。\n\nPenn State STAT 505 [-@psu505_lesson10] の7段階手順では、LOOCVは第6段階に位置づけられます。これは完全な外部検証ではなく、未知データでの性能を近似的に見積もる**内部交差検証**です。再代入精度（学習データ自体での正解率）は過大評価されるため、LOOCVまたはk分割交差検証を使います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_cv <- MASS::lda(\n  Group ~ Recall + Recognition,\n  data = simulated,\n  CV = TRUE\n)\n\ncm_lda <- table(\n  Actual = simulated$Group,\n  Predicted = lda_cv$class\n)\n\nlda_overall <- sum(diag(cm_lda)) / sum(cm_lda)\nlda_balanced <- mean(diag(cm_lda) / rowSums(cm_lda))\nchance_level <- max(prop.table(table(simulated$Group)))\n\nlda_metric_tbl <- tibble(\n  Metric = c(\"Overall accuracy\", \"Balanced accuracy\", \"Chance level\"),\n  Value = c(lda_overall, lda_balanced, chance_level)\n)\n\ncm_lda_plot_tbl <- as.data.frame(cm_lda) |>\n  mutate(\n    Actual = factor(Actual, levels = rownames(cm_lda)),\n    Predicted = factor(Predicted, levels = colnames(cm_lda))\n  )\n\nas.data.frame.matrix(cm_lda) |>\n  rownames_to_column(\"Actual\") |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA混同行列（confusion matrix; LOOCV）: 行 = 実際の群、列 = 予測群\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA混同行列（confusion matrix; LOOCV）: 行 = 実際の群、列 = 予測群\n\n|Actual                 | Glossing_Collaborative| Glossing_Individual| Writing_Collaborative| Writing_Individual|\n|:----------------------|----------------------:|-------------------:|---------------------:|------------------:|\n|Glossing_Collaborative |                     10|                  21|                     3|                 11|\n|Glossing_Individual    |                     14|                  24|                     2|                  5|\n|Writing_Collaborative  |                      8|                   0|                    24|                 13|\n|Writing_Individual     |                     11|                   2|                    20|                 12|\n\n\n:::\n\n```{.r .cell-code}\nlda_metric_tbl |>\n  mutate(Value = scales::percent(Value, accuracy = 0.1)) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA分類指標（classification metrics）: LOOCVに基づく性能\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA分類指標（classification metrics）: LOOCVに基づく性能\n\n|Metric            |Value |\n|:-----------------|:-----|\n|Overall accuracy  |38.9% |\n|Balanced accuracy |38.9% |\n|Chance level      |25.0% |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cm_lda_plot_tbl, aes(x = Predicted, y = Actual, fill = Freq)) +\n  geom_tile(color = \"white\", linewidth = 0.8) +\n  geom_text(aes(label = Freq), size = 4.1, color = \"black\") +\n  scale_fill_gradient(low = \"#f7fbff\", high = \"#2171b5\") +\n  labs(\n    title = \"LDAモデルはどこで正しく分類し、どこで誤分類するか\",\n    x = \"予測群\",\n    y = \"実際の群\",\n    fill = \"度数\"\n  )\n```\n\n::: {.cell-output-display}\n![LDA混同行列（confusion matrix）のヒートマップ。対角セルが濃いほど分類が成功している。](3_MANOVA_判別分析_files/figure-html/lda-confusion-heatmap-1.png){fig-alt='実際の群を縦軸、予測群を横軸にしたヒートマップ。対角セルは正分類、非対角セルは誤分類を表す。' width=2040}\n:::\n:::\n\n\n**混同行列の読み方**:\n\n| 指標 | 意味 |\n|:---|:---|\n| 対角線 | 正しく分類された数。大きいほど良い |\n| 非対角線 | 誤分類。どの群がどの群に間違われやすいかを示す |\n| Overall accuracy | 全体正解率。チャンス水準（25.0%、4群均等の場合）と置換チェックを併せて確認 |\n| Balanced accuracy | 群サイズの不均衡を補正した正解率 |\n\n**混同行列ヒートマップの読み方**:\n\n- 濃い対角線セルが多いほど、分類は安定している\n- 特定の2群の非対角セルだけが濃いなら、その2群は判別空間で混同されやすい\n- `Overall accuracy` が高くても、1群だけ極端に苦手なら balanced accuracy と群別指標も併せて見る\n- 二項信頼区間は全体正解率の不確実性を見る近似であり、LOOCV予測の完全な独立性を仮定しない置換チェックも併記する\n\n#### 群別指標（Precision / Sensitivity / F1）\n\n分類精度は全体正解率だけでなく、**群ごとの感度（classification recall）と適合率**も確認します。ここでの recall は分類指標名であり、語彙テストの `Recall` 得点とは別物です。混同を避けるため、表では `Sensitivity` と表記します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalc_class_metrics <- function(cm) {\n  tp <- diag(cm)\n  support <- rowSums(cm)\n  predicted <- colSums(cm)\n\n  recall <- tp / support\n  precision <- tp / predicted\n  f1 <- ifelse(\n    (precision + recall) == 0,\n    NA_real_,\n    2 * precision * recall / (precision + recall)\n  )\n\n  tibble(\n    Group = rownames(cm),\n    Support = as.numeric(support),\n    Sensitivity = as.numeric(recall),\n    Precision = as.numeric(precision),\n    F1 = as.numeric(f1)\n  )\n}\n\ncalc_accuracy_ci <- function(cm, conf_level = 0.95) {\n  correct <- sum(diag(cm))\n  total <- sum(cm)\n  ci <- binom.test(correct, total, conf.level = conf_level)$conf.int\n\n  tibble(\n    Correct = correct,\n    Total = total,\n    Accuracy = correct / total,\n    CI_low = ci[1],\n    CI_high = ci[2]\n  )\n}\n\nlda_class_tbl <- calc_class_metrics(cm_lda)\nlda_acc_ci <- calc_accuracy_ci(cm_lda)\n\nset.seed(2025)\nn_perm <- 199\nperm_accuracy <- purrr::map_dbl(seq_len(n_perm), ~ {\n  perm_data <- simulated |>\n    mutate(Group_perm = sample(Group))\n  perm_cv <- MASS::lda(\n    Group_perm ~ Recall + Recognition,\n    data = perm_data,\n    CV = TRUE\n  )\n  mean(perm_cv$class == perm_data$Group_perm)\n})\n\nlda_perm_p <- (sum(perm_accuracy >= lda_overall) + 1) / (n_perm + 1)\n\nlda_chance_tbl <- tibble(\n  Observed_Accuracy = lda_overall,\n  Mean_Permuted_Accuracy = mean(perm_accuracy),\n  Permutation_p = lda_perm_p,\n  Permutations = n_perm\n)\n\nlda_class_tbl |>\n  mutate(across(c(Sensitivity, Precision, F1), ~ scales::percent(.x, accuracy = 0.1))) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDAの群別性能（class-wise performance）: sensitivity、precision、F1\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDAの群別性能（class-wise performance）: sensitivity、precision、F1\n\n|Group                  | Support|Sensitivity |Precision |F1    |\n|:----------------------|-------:|:-----------|:---------|:-----|\n|Glossing_Collaborative |      45|22.2%       |23.3%     |22.7% |\n|Glossing_Individual    |      45|53.3%       |51.1%     |52.2% |\n|Writing_Collaborative  |      45|53.3%       |49.0%     |51.1% |\n|Writing_Individual     |      45|26.7%       |29.3%     |27.9% |\n\n\n:::\n\n```{.r .cell-code}\nlda_acc_ci |>\n  mutate(across(c(Accuracy, CI_low, CI_high), ~ scales::percent(.x, accuracy = 0.1))) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA正解率（accuracy）と95% CI: 二項信頼区間による近似\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA正解率（accuracy）と95% CI: 二項信頼区間による近似\n\n| Correct| Total|Accuracy |CI_low |CI_high |\n|-------:|-----:|:--------|:------|:-------|\n|      70|   180|38.9%    |31.7%  |46.4%   |\n\n\n:::\n\n```{.r .cell-code}\nlda_chance_tbl |>\n  mutate(\n    across(c(Observed_Accuracy, Mean_Permuted_Accuracy), ~ scales::percent(.x, accuracy = 0.1)),\n    Permutation_p = if_else(\n      Permutation_p < .001,\n      \"< .001\",\n      sub(\"^0\", \"\", sprintf(\"%.3f\", Permutation_p))\n    )\n  ) |>\n  knitr::kable(caption = \"LDA正解率（accuracy）と置換チャンス水準（permuted chance）: LOOCV置換チェック\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA正解率（accuracy）と置換チャンス水準（permuted chance）: LOOCV置換チェック\n\n|Observed_Accuracy |Mean_Permuted_Accuracy |Permutation_p | Permutations|\n|:-----------------|:----------------------|:-------------|------------:|\n|38.9%             |24.8%                  |.005          |          199|\n\n\n:::\n:::\n\n\n### LDA判別空間の可視化\n\n判別関数スコアの散布図で、4群がどの程度分離しているかを視覚的に確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_scores <- as_tibble(lda_pred$x) |>\n  mutate(Group = simulated$Group)\n\nif (!\"LD2\" %in% colnames(lda_scores)) {\n  lda_scores <- lda_scores |>\n    mutate(LD2 = 0)\n}\n\nlda_centers <- lda_scores |>\n  group_by(Group) |>\n  summarise(LD1 = mean(LD1), LD2 = mean(LD2), .groups = \"drop\")\n\nld1_label <- paste0(\"LD1 (\", scales::percent(prop_trace[1], accuracy = 0.1), \")\")\nld2_label <- if (length(prop_trace) >= 2) {\n  paste0(\"LD2 (\", scales::percent(prop_trace[2], accuracy = 0.1), \")\")\n} else {\n  \"LD2\"\n}\n\nggplot(lda_scores, aes(x = LD1, y = LD2, color = Group)) +\n  geom_point(alpha = 0.7, size = 2.5) +\n  stat_ellipse(level = 0.95, linewidth = 0.7, linetype = \"dashed\") +\n  geom_label(\n    data = lda_centers,\n    aes(label = Group),\n    size = 3,\n    show.legend = FALSE\n  ) +\n  labs(\n    title = \"LDA判別空間\",\n    subtitle = \"点は個人、ラベルは群重心、破線楕円は95%楕円\",\n    x = ld1_label,\n    y = ld2_label\n  )\n```\n\n::: {.cell-output-display}\n![LDA判別空間（discriminant space）における4群の分布。軸ラベルの括弧内はtrace割合（proportion of trace）を示す。](3_MANOVA_判別分析_files/figure-html/fig-lda-discriminant-space-1.png){#fig-lda-discriminant-space fig-alt='LD1とLD2の散布図。4群の点、95%楕円、群重心ラベルが表示される。' width=2160}\n:::\n:::\n\n\n**判別空間の読み方**:\n\n- 楕円が重なりが少ないほど → 群分離が良好\n- LD1 方向で分離 → 第1判別関数が支配的\n- LD2 方向でも分離 → 2次元的な群差がある\n\n### QDAとの比較\n\nLDAは**全群で共通の共分散行列を仮定**しますが、QDA（Quadratic Discriminant Analysis）は**群ごとに異なる共分散行列を許容**します [@venables2002; @mass_lda_doc; @mass_qda_doc]。ただし、QDAは分類器であり、Box's M 検定が有意なMANOVAを「修復する」方法ではありません。本章では、QDAを主推論ではなく、分類性能を見るための感度分析として扱います。公式ドキュメントでも `qda()` は群別分散構造を推定するぶん、**群内共分散が特異だとランク落ち（rank deficiency）や小標本問題に弱い**ことが示唆されています [@mass_qda_doc]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqda_cv <- MASS::qda(\n  Group ~ Recall + Recognition,\n  data = simulated,\n  CV = TRUE\n)\n\ncm_qda <- table(\n  Actual = simulated$Group,\n  Predicted = qda_cv$class\n)\n\nqda_overall <- sum(diag(cm_qda)) / sum(cm_qda)\nqda_balanced <- mean(diag(cm_qda) / rowSums(cm_qda))\n\ncomparison_tbl <- tibble(\n  Method = c(\"LDA (LOOCV)\", \"QDA (LOOCV)\", \"Chance level\"),\n  Overall_Accuracy = c(lda_overall, qda_overall, chance_level),\n  Balanced_Accuracy = c(lda_balanced, qda_balanced, chance_level)\n)\n\ncomparison_tbl |>\n  mutate(across(c(Overall_Accuracy, Balanced_Accuracy), ~ scales::percent(.x, accuracy = 0.1))) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA vs QDA: 交差検証（cross-validation）に基づく分類性能\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA vs QDA: 交差検証（cross-validation）に基づく分類性能\n\n|Method       |Overall_Accuracy |Balanced_Accuracy |\n|:------------|:----------------|:-----------------|\n|LDA (LOOCV)  |38.9%            |38.9%             |\n|QDA (LOOCV)  |40.6%            |40.6%             |\n|Chance level |25.0%            |25.0%             |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqda_class_tbl <- calc_class_metrics(cm_qda)\nqda_acc_ci <- calc_accuracy_ci(cm_qda)\n\nbind_rows(\n  lda_class_tbl |> mutate(Method = \"LDA\"),\n  qda_class_tbl |> mutate(Method = \"QDA\")\n) |>\n  dplyr::select(Method, Group, Support, Sensitivity, Precision, F1) |>\n  mutate(across(c(Sensitivity, Precision, F1), ~ scales::percent(.x, accuracy = 0.1))) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA/QDAの群別比較（class-wise comparison）: 群ごとの分類品質\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA/QDAの群別比較（class-wise comparison）: 群ごとの分類品質\n\n|Method |Group                  | Support|Sensitivity |Precision |F1    |\n|:------|:----------------------|-------:|:-----------|:---------|:-----|\n|LDA    |Glossing_Collaborative |      45|22.2%       |23.3%     |22.7% |\n|LDA    |Glossing_Individual    |      45|53.3%       |51.1%     |52.2% |\n|LDA    |Writing_Collaborative  |      45|53.3%       |49.0%     |51.1% |\n|LDA    |Writing_Individual     |      45|26.7%       |29.3%     |27.9% |\n|QDA    |Glossing_Collaborative |      45|28.9%       |27.7%     |28.3% |\n|QDA    |Glossing_Individual    |      45|46.7%       |48.8%     |47.7% |\n|QDA    |Writing_Collaborative  |      45|40.0%       |54.5%     |46.2% |\n|QDA    |Writing_Individual     |      45|46.7%       |36.8%     |41.2% |\n\n\n:::\n\n```{.r .cell-code}\nbind_rows(\n  lda_acc_ci |> mutate(Method = \"LDA\"),\n  qda_acc_ci |> mutate(Method = \"QDA\")\n) |>\n  dplyr::select(Method, Correct, Total, Accuracy, CI_low, CI_high) |>\n  mutate(across(c(Accuracy, CI_low, CI_high), ~ scales::percent(.x, accuracy = 0.1))) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"LDA/QDA正解率（accuracy）と95% CI: 全体正解率の不確実性\")\n```\n\n::: {.cell-output-display}\n\n\nTable: LDA/QDA正解率（accuracy）と95% CI: 全体正解率の不確実性\n\n|Method | Correct| Total|Accuracy |CI_low |CI_high |\n|:------|-------:|-----:|:--------|:------|:-------|\n|LDA    |      70|   180|38.9%    |31.7%  |46.4%   |\n|QDA    |      73|   180|40.6%    |33.3%  |48.1%   |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccuracy_compare_plot_tbl <- bind_rows(\n  lda_acc_ci |> mutate(Method = \"LDA\", Balanced_Accuracy = lda_balanced),\n  qda_acc_ci |> mutate(Method = \"QDA\", Balanced_Accuracy = qda_balanced)\n)\n\nggplot(accuracy_compare_plot_tbl, aes(x = Method, y = Accuracy, color = Method)) +\n  geom_hline(yintercept = chance_level, linetype = \"dashed\", color = \"gray40\") +\n  geom_linerange(aes(ymin = CI_low, ymax = CI_high), linewidth = 1) +\n  geom_point(size = 3.4) +\n  geom_point(aes(y = Balanced_Accuracy), shape = 17, size = 3, color = \"black\") +\n  annotate(\"text\", x = 1.5, y = chance_level + 0.03, label = \"Chance level\", color = \"gray35\", size = 3.4) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1)) +\n  labs(\n    title = \"LDAとQDAの分類正解率\",\n    subtitle = \"丸 = overall accuracy、三角 = balanced accuracy\",\n    x = NULL,\n    y = \"正解率\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![LDAとQDAの全体正解率（overall accuracy）と95% CI。破線はチャンス水準（chance level）を表す。](3_MANOVA_判別分析_files/figure-html/lda-qda-accuracy-plot-1.png){fig-alt='LDAとQDAの正解率を点と信頼区間で比較する図。横破線はチャンス水準、三角点はbalanced accuracyを示す。' width=2040}\n:::\n:::\n\n\n**LDA vs QDA の選択基準**:\n\n| 条件 | 推奨 |\n|:---|:---|\n| Box's M が非有意（$p > .001$） | LDA（よりパーシモニアス） |\n| Box's M が有意（$p < .001$）かつ各群の $n \\gg p+1$ | 予測目的の感度分析として QDA を検討(各群の共分散行列を独立に推定するため、ある程度の n が必要) |\n| 各群の $n$ が $p+1$ をかろうじて超える程度 | **正則化判別分析(`klaR::rda`)**を検討。LDA と QDA の中間で、各群共分散と共通共分散をシュリンクで混合するため、小サンプルで安定 |\n| LDA と QDA の精度がほぼ同じ | LDA を選択（より安定） |\n| QDA が明らかに優れる | 分類目的に限ってQDAを報告。MANOVAの主推論とは分けて書く |\n\n::: {.callout-note}\n**$n > p + 1$ は QDA の必要条件であり、十分条件ではありません。** $n$ が $p+1$ ぎりぎりだと群別共分散の推定が不安定になります。実用上は $n \\gtrsim 5(p+1)$ 程度が目安で、それを下回る場合は **正則化判別分析** [@friedman1989rda; `klaR::rda()` で実装] で LDA と QDA を λ パラメータで補間するのが現実的です。\n:::\n\n**精度比較プロットの読み方**:\n\n- 丸印は overall accuracy、三角は balanced accuracy を表す\n- 95% CI が大きく重なるなら、LDA と QDA の差は実務上かなり小さいと考えてよい\n- chance level を大きく超えているかどうかで、「統計的に分離可能」だけでなく「実際に使える程度に分離できるか」を判断する。ただし、チャンス超えを推論として主張する場合は置換チェックや外部検証も併記する\n\n## 単変量追跡分析（Follow-up）: 補助的追跡法\n\n前節でDDAを主要追跡法として実施しました。ここでは、**補助的な追跡法**として単変量ANOVAを実行します。Warne [-@warne2014] の推奨手順に沿いつつも、個々のDVについて効果量を確認するために補助的に報告します。DV間の相関構造は考慮されない点に留意してください。\n\n### 単変量追跡の限界\n\n**注意**: 単変量ANOVAを追跡法として使う場合、以下の2つの問題があります [@smith2020; @finch2013]。\n\n1. **Type Iエラーの膨張**: 2 DV × 3 効果 = 6検定。Holm補正が必要。Smith et al. [-@smith2020] は、無補正の単変量追跡でType Iエラー率が最大76%に達しうることをシミュレーションで示しています。\n2. **多変量パターンの見逃し**: DV間の相関を無視するため、個々のANOVAでは非有意でもMANOVAでは有意になるケースを説明できない。Finch & French [-@finch2013] はこのケースをDDAでのみ解釈できることを示しています。\n\nWarne [-@warne2014] の58本レビューでは、ほぼすべてがANOVAのみで追跡しDDAを使っていませんでした。本章では**DDAを主要追跡法**とし、ANOVAは補助的に使います。\n\nMANOVAで有意な効果が見られた場合、どの目的変数が効果を担っているかを単変量で追跡します。ここでは6つの検定（2 DV × 3効果）に対して Holm 補正を適用します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_recall <- aov(Recall ~ Instruction * LearningMode, data = simulated)\naov_recognition <- aov(Recognition ~ Instruction * LearningMode, data = simulated)\n\nfollowup_tbl <- bind_rows(\n  broom::tidy(aov_recall) |>\n    mutate(Outcome = \"Recall\"),\n  broom::tidy(aov_recognition) |>\n    mutate(Outcome = \"Recognition\")\n) |>\n  dplyr::filter(term != \"Residuals\") |>\n  mutate(\n    p_holm = p.adjust(p.value, method = \"holm\")\n  ) |>\n  dplyr::select(Outcome, term, df, statistic, p.value, p_holm)\n\nfollowup_tbl |>\n  mutate(\n    p = if_else(p.value < .001, \"< .001\", sub(\"^0\", \"\", sprintf(\"%.3f\", p.value))),\n    p_Holm = if_else(p_holm < .001, \"< .001\", sub(\"^0\", \"\", sprintf(\"%.3f\", p_holm)))\n  ) |>\n  mutate(across(c(statistic), ~ round(.x, 3))) |>\n  mutate(across(df, ~ round(.x, 0))) |>\n  dplyr::select(Outcome, term, df, statistic, p, p_Holm) |>\n  knitr::kable(caption = \"単変量追跡検定（univariate follow-up tests）: Holm補正つきANOVA\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 単変量追跡検定（univariate follow-up tests）: Holm補正つきANOVA\n\n|Outcome     |term                     | df| statistic|p      |p_Holm |\n|:-----------|:------------------------|--:|---------:|:------|:------|\n|Recall      |Instruction              |  1|    76.450|< .001 |< .001 |\n|Recall      |LearningMode             |  1|     6.350|.013   |.051   |\n|Recall      |Instruction:LearningMode |  1|     0.499|.481   |.962   |\n|Recognition |Instruction              |  1|    85.203|< .001 |< .001 |\n|Recognition |LearningMode             |  1|     4.996|.027   |.080   |\n|Recognition |Instruction:LearningMode |  1|     0.421|.517   |.962   |\n\n\n:::\n:::\n\n\n**追跡ANOVAの読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Outcome` | どのDVの結果か |\n| `term` | 効果名（Instruction, LearningMode, 交互作用） |\n| `statistic` | F値 |\n| `p` | 補正前のp値 |\n| `p_Holm` | Holm補正後のp値。**こちらを報告に使用する** |\n\n### 効果量（偏η²）\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_tbl <- bind_rows(\n  as.data.frame(effectsize::eta_squared(aov_recall, partial = TRUE, alternative = \"two.sided\")) |>\n    mutate(Outcome = \"Recall\"),\n  as.data.frame(effectsize::eta_squared(aov_recognition, partial = TRUE, alternative = \"two.sided\")) |>\n    mutate(Outcome = \"Recognition\")\n) |>\n  dplyr::select(Outcome, Parameter, Eta2_partial, CI_low, CI_high)\n\neta_tbl |>\n  mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"効果量（effect size）: 追跡ANOVAの偏η²（partial eta-squared）\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 効果量（effect size）: 追跡ANOVAの偏η²（partial eta-squared）\n\n|Outcome     |Parameter                | Eta2_partial| CI_low| CI_high|\n|:-----------|:------------------------|------------:|------:|-------:|\n|Recall      |Instruction              |        0.303|  0.197|   0.403|\n|Recall      |LearningMode             |        0.035|  0.002|   0.103|\n|Recall      |Instruction:LearningMode |        0.003|  0.000|   0.039|\n|Recognition |Instruction              |        0.326|  0.220|   0.425|\n|Recognition |LearningMode             |        0.028|  0.000|   0.091|\n|Recognition |Instruction:LearningMode |        0.002|  0.000|   0.037|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_plot_tbl <- eta_tbl |>\n  mutate(\n    Effect = paste(Outcome, Parameter, sep = \" | \"),\n    Effect = factor(Effect, levels = rev(unique(Effect)))\n  )\n\nggplot(eta_plot_tbl, aes(x = Eta2_partial, y = Effect, color = Outcome)) +\n  geom_vline(xintercept = c(0.01, 0.06, 0.14), linetype = \"dotted\", color = \"gray60\") +\n  geom_segment(aes(x = CI_low, xend = CI_high, yend = Effect), linewidth = 0.9) +\n  geom_point(size = 3) +\n  labs(\n    title = \"どの単変量効果が大きいか\",\n    subtitle = \".01、.06、.14 の縦線は解釈の目安\",\n    x = \"偏η²\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![追跡ANOVAの偏η²（partial eta-squared）と信頼区間（confidence interval）。](3_MANOVA_判別分析_files/figure-html/followup-effectsize-plot-1.png){fig-alt='各目的変数と効果ごとの偏η²を点、信頼区間を横線で示す図。' width=2160}\n:::\n:::\n\n\n**偏η²の解釈基準**:\n\n| 偏η² | 効果の大きさ |\n|:---:|:---|\n| .01 | 小さい効果 |\n| .06 | 中程度の効果 |\n| .14 | 大きい効果 |\n\n**効果量プロットの読み方**:\n\n- 点が右へ行くほど、その効果は単変量的に大きい\n- 区間が短いほど、効果量推定の不確実性が小さい\n- 破線は「小・中・大」の目安であり、厳密な境界というより解釈補助として使う\n- 同じ `Outcome` 内で比較すると、どの効果が主役かが見えやすい\n\n### 事後比較（セル平均の比較）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_recall <- lm(Recall ~ Instruction * LearningMode, data = simulated)\nlm_recognition <- lm(Recognition ~ Instruction * LearningMode, data = simulated)\n\npairs_recall <- emmeans::emmeans(lm_recall, ~ Instruction * LearningMode) |>\n  pairs(adjust = \"holm\") |>\n  summary(infer = c(TRUE, TRUE)) |>\n  as.data.frame() |>\n  mutate(Outcome = \"Recall\")\n\npairs_recognition <- emmeans::emmeans(lm_recognition, ~ Instruction * LearningMode) |>\n  pairs(adjust = \"holm\") |>\n  summary(infer = c(TRUE, TRUE)) |>\n  as.data.frame() |>\n  mutate(Outcome = \"Recognition\")\n\npairwise_tbl <- bind_rows(pairs_recall, pairs_recognition)\n\npairwise_tbl |>\n  dplyr::select(Outcome, contrast, estimate, SE, df, t.ratio, p.value) |>\n  mutate(\n    estimate = round(estimate, 4),\n    SE = round(SE, 4),\n    df = round(df, 0),\n    t.ratio = round(t.ratio, 4),\n    p = if_else(p.value < .001, \"< .001\", sub(\"^0\", \"\", sprintf(\"%.3f\", p.value)))\n  ) |>\n  dplyr::select(-p.value) |>\n  knitr::kable(\n    caption = \"Post hocペア比較（post hoc pairwise comparisons）: 推定周辺平均の差（estimated marginal mean differences; Holm補正）\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Post hocペア比較（post hoc pairwise comparisons）: 推定周辺平均の差（estimated marginal mean differences; Holm補正）\n\n|Outcome     |contrast                                       | estimate|     SE|  df| t.ratio|p      |\n|:-----------|:----------------------------------------------|--------:|------:|---:|-------:|:------|\n|Recall      |Glossing Collaborative - Writing Collaborative |  -5.7175| 0.8556| 176| -6.6821|< .001 |\n|Recall      |Glossing Collaborative - Glossing Individual   |   1.0972| 0.8556| 176|  1.2823|.201   |\n|Recall      |Glossing Collaborative - Writing Individual    |  -3.7655| 0.8556| 176| -4.4008|< .001 |\n|Recall      |Writing Collaborative - Glossing Individual    |   6.8147| 0.8556| 176|  7.9645|< .001 |\n|Recall      |Writing Collaborative - Writing Individual     |   1.9520| 0.8556| 176|  2.2813|.047   |\n|Recall      |Glossing Individual - Writing Individual       |  -4.8627| 0.8556| 176| -5.6831|< .001 |\n|Recognition |Glossing Collaborative - Writing Collaborative |  -5.3810| 0.8868| 176| -6.0680|< .001 |\n|Recognition |Glossing Collaborative - Glossing Individual   |   1.8085| 0.8868| 176|  2.0394|.086   |\n|Recognition |Glossing Collaborative - Writing Individual    |  -4.3864| 0.8868| 176| -4.9465|< .001 |\n|Recognition |Writing Collaborative - Glossing Individual    |   7.1895| 0.8868| 176|  8.1075|< .001 |\n|Recognition |Writing Collaborative - Writing Individual     |   0.9946| 0.8868| 176|  1.1215|.264   |\n|Recognition |Glossing Individual - Writing Individual       |  -6.1949| 0.8868| 176| -6.9859|< .001 |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise_plot_tbl <- pairwise_tbl |>\n  mutate(\n    contrast = factor(contrast, levels = rev(unique(contrast))),\n    Significant = if_else(p.value < 0.05, \"Holm-adjusted p < .05\", \"ns\")\n  )\n\nggplot(pairwise_plot_tbl, aes(x = estimate, y = contrast, color = Significant)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_segment(aes(x = lower.CL, xend = upper.CL, yend = contrast), linewidth = 0.85) +\n  geom_point(size = 2.8) +\n  facet_wrap(~ Outcome, scales = \"free_y\") +\n  scale_color_manual(values = c(\"Holm-adjusted p < .05\" = \"#1b7837\", \"ns\" = \"#636363\")) +\n  labs(\n    title = \"各アウトカムでどのセル平均が異なるか\",\n    x = \"推定平均差\",\n    y = NULL,\n    color = NULL\n  )\n```\n\n::: {.cell-output-display}\n![各アウトカムにおけるペア比較（pairwise comparisons）の平均差と95%信頼区間（95% confidence intervals）。](3_MANOVA_判別分析_files/figure-html/followup-pairwise-plot-1.png){fig-alt='RecallとRecognitionの2パネルで、条件ペアごとの平均差と95%信頼区間を横線で示す図。' width=2400}\n:::\n:::\n\n\n**事後比較プロットの読み方**:\n\n- 0 の縦線をまたがない比較は、その outcome で安定した差がある\n- 点の符号は「最初の条件が高いか、低いか」を示す。正負だけでなく、区間の広さも必ず見る\n- `Recall` と `Recognition` を横に並べると、多変量効果がどちらのDVで強く現れているかが分かる\n- MANOVA で有意でも、この図では一部の比較しか明瞭でないことがある。それが「多変量では有意、単変量では限定的」という状況である\n\n## 拡張: 共変量を含む場合のMANCOVA\n\nここまでは、すべての予測変数がカテゴリカルである標準的な MANOVA を扱ってきました。実務ではここに **連続共変量**が加わることが多く、これが **MANCOVA** です。R では特別な別関数を使うわけではなく、`manova()` の右辺に連続変数を加えます。つまり、式は\n\n$$\n\\mathbf{Y} = \\mathbf{X}\\mathbf{B} + \\mathbf{z}\\boldsymbol{\\gamma} + \\mathbf{E}\n$$\n\nの形になり、群要因に加えて共変量 $\\mathbf{z}$ の線形効果を同時に調整します。Huberty & Olejnik [-@huberty2006] や Tabachnick & Fidell [-@tabachnick2019] が強調する通り、ここで重要なのは「共変量を入れたから自動的に厳密になる」のではなく、**傾きの等質性**が成り立っているかを先に見ることです。\n\n### 共変量つきデータの用意\n\nここでは、アウトカムとは別に観測された事前能力指標 `Proficiency` を想定します。教育研究で MANCOVA を使う場合、共変量は原則として介入後アウトカムから作るのではなく、介入前または独立した測定から得られる変数である必要があります。ここではまず外生的な `Proficiency` を生成し、その後で `Recall` と `Recognition` に弱く反映させます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nsimulated_cov <- simulated |>\n  mutate(\n    Proficiency = round(rnorm(n(), mean = 50, sd = 7), 1),\n    Proficiency_c = Proficiency - mean(Proficiency),\n    Recall = pmin(pmax(Recall + 0.16 * Proficiency_c, 0), 30),\n    Recognition = pmin(pmax(Recognition + 0.14 * Proficiency_c, 0), 30)\n  ) |>\n  dplyr::select(-Proficiency_c)\n\nsimulated_cov |>\n  group_by(Instruction, LearningMode) |>\n  summarise(\n    Proficiency_Mean = mean(Proficiency),\n    Proficiency_SD = sd(Proficiency),\n    .groups = \"drop\"\n  ) |>\n    mutate(across(where(is.numeric), ~ round(.x, 2))) |>\n  knitr::kable(caption = \"共変量の概要（covariate overview）: Instruction × LearningMode 別のProficiency\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 共変量の概要（covariate overview）: Instruction × LearningMode 別のProficiency\n\n|Instruction |LearningMode  | Proficiency_Mean| Proficiency_SD|\n|:-----------|:-------------|----------------:|--------------:|\n|Glossing    |Collaborative |            49.72|           7.02|\n|Glossing    |Individual    |            49.41|           6.90|\n|Writing     |Collaborative |            50.25|           5.52|\n|Writing     |Individual    |            50.20|           8.06|\n\n\n:::\n:::\n\n\n### 傾きの等質性を図で確認する\n\nMANCOVA で最初に見るべきなのは、**共変量と各DVの関係が群ごとに大きく変わっていないか**です。もし群ごとに回帰線の傾きが大きく異なるなら、「全群で同じ調整をかける」という標準的な MANCOVA の前提が弱くなります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovariate_plot_tbl <- simulated_cov |>\n  pivot_longer(\n    cols = c(Recall, Recognition),\n    names_to = \"Outcome\",\n    values_to = \"Score\"\n  )\n\nggplot(covariate_plot_tbl, aes(x = Proficiency, y = Score, color = Group)) +\n  geom_point(alpha = 0.35, size = 1.6) +\n  geom_smooth(method = \"lm\", se = TRUE, linewidth = 0.8, alpha = 0.12) +\n  facet_wrap(~ Outcome, scales = \"free_y\") +\n  labs(\n    title = \"共変量スロープは群間で似ているか\",\n    subtitle = \"傾きが大きく異なる場合は単純な共変量調整を避ける\",\n    x = \"Proficiency\",\n    y = \"アウトカム得点\"\n  )\n```\n\n::: {.cell-output-display}\n![共変量（covariate）と各アウトカムの関係を群別に確認する図。線が概ね平行なら傾きの等質性（homogeneity of slopes）を置きやすい。](3_MANOVA_判別分析_files/figure-html/covariate-slope-plot-1.png){fig-alt='Proficiencyを横軸、得点を縦軸にした散布図。RecallとRecognitionの2パネルで群別の回帰線と信頼帯が表示される。' width=2400}\n:::\n:::\n\n\n**共変量スロープ図の読み方**:\n\n- 群ごとの回帰線がおおむね平行であれば、標準的な MANCOVA の前提は大きく崩れていない\n- 1群だけ極端に傾きが急なら、その群では共変量の作用が別物かもしれない\n- `Recall` と `Recognition` の両方で同じ傾向が出るかを見ると、共変量が多変量的にどう関連しているかが掴みやすい\n\n### 傾きの等質性を多変量的に検定する\n\n図だけでなく、`Instruction:Proficiency` や `LearningMode:Proficiency` の交互作用を含むモデルで、**共変量と群要因の交互作用が有意でないか**も確認します。ここが有意なら、「単純な MANCOVA ではなく、共変量効果の群差そのものをモデル化する」方向へ進むべきです。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmancova_slope_fit <- manova(\n  cbind(Recall, Recognition) ~ Proficiency * Instruction * LearningMode,\n  data = simulated_cov\n)\n\nslope_stats <- summary(mancova_slope_fit, test = \"Pillai\")$stats\n\nslope_tbl <- tibble(\n  Effect = rownames(slope_stats),\n  Hypothesis_df = slope_stats[, \"Df\"],\n  Statistic = slope_stats[, \"Pillai\"],\n  Approx_F = slope_stats[, \"approx F\"],\n  df1 = slope_stats[, \"num Df\"],\n  df2 = slope_stats[, \"den Df\"],\n  p_value = slope_stats[, \"Pr(>F)\"]\n) |>\n  dplyr::filter(str_detect(Effect, \"Proficiency\"), Effect != \"Proficiency\") |>\n  mutate(\n    across(c(Statistic, Approx_F, p_value), ~ round(.x, 3)),\n    across(c(Hypothesis_df, df1, df2), ~ round(.x, 0))\n  )\n\nslope_tbl |>\n  mutate(\n    p = if_else(p_value < .001, \"< .001\", sub(\"^0\", \"\", sprintf(\"%.3f\", p_value)))\n  ) |>\n  mutate(\n    across(c(Statistic, Approx_F), ~ round(.x, 3)),\n    across(c(Hypothesis_df, df1, df2), ~ round(.x, 0))\n  ) |>\n  dplyr::select(Effect, Hypothesis_df, Statistic, Approx_F, df1, df2, p) |>\n  knitr::kable(caption = \"傾きの等質性チェック（homogeneity-of-slopes check）: 共変量を含む交互作用\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 傾きの等質性チェック（homogeneity-of-slopes check）: 共変量を含む交互作用\n\n|Effect                               | Hypothesis_df| Statistic| Approx_F| df1| df2|p    |\n|:------------------------------------|-------------:|---------:|--------:|---:|---:|:----|\n|Proficiency:Instruction              |             1|     0.003|    0.291|   2| 171|.748 |\n|Proficiency:LearningMode             |             1|     0.004|    0.380|   2| 171|.684 |\n|Proficiency:Instruction:LearningMode |             1|     0.010|    0.850|   2| 171|.429 |\n\n\n:::\n:::\n\n\n### 共変量を調整した MANCOVA\n\n傾きが概ね平行と判断できたら、通常の MANCOVA を適用します。R の `summary.manova()` は **逐次平方和(Type I SS)** に基づくため、項の順序が結果に影響します。ここでは `Proficiency` を式の先頭に置き、共変量を先に調整した後で `Instruction`、`LearningMode`、交互作用を評価します。\n\n::: {.callout-warning}\n**不均衡データや交互作用を含む MANCOVA では Type III SS を推奨**:項の順序に依存しない検定が必要な場合は、`car::Manova(model, type = \"III\")` を用いてください。第 2 章「不均衡デザインでの Type I / II / III SS」と同じ論点が多変量にも適用されます。Type III を使うときは Sum coding(`afex::set_sum_contrasts()` 等)とセットで使うのが原則です。\n:::\n\n```r\n# 不均衡データ + Type III SS の MANCOVA 例\nafex::set_sum_contrasts()\nmancova_lm <- lm(\n  cbind(Recall, Recognition) ~ Proficiency + Instruction * LearningMode,\n  data = simulated_cov\n)\ncar::Manova(mancova_lm, type = \"III\", test.statistic = \"Pillai\")\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmancova_fit <- manova(\n  cbind(Recall, Recognition) ~ Proficiency + Instruction * LearningMode,\n  data = simulated_cov\n)\n\nmancova_stats <- summary(mancova_fit, test = \"Pillai\")$stats\n\nmancova_tbl <- tibble(\n  Effect = rownames(mancova_stats),\n  Hypothesis_df = mancova_stats[, \"Df\"],\n  Statistic = mancova_stats[, \"Pillai\"],\n  Approx_F = mancova_stats[, \"approx F\"],\n  df1 = mancova_stats[, \"num Df\"],\n  df2 = mancova_stats[, \"den Df\"],\n  p_value = mancova_stats[, \"Pr(>F)\"]\n) |>\n  dplyr::filter(Effect != \"Residuals\") |>\n  mutate(\n    across(c(Statistic, Approx_F, p_value), ~ round(.x, 3)),\n    across(c(Hypothesis_df, df1, df2), ~ round(.x, 0))\n  )\n\nmancova_tbl |>\n  mutate(\n    p = if_else(p_value < .001, \"< .001\", sub(\"^0\", \"\", sprintf(\"%.3f\", p_value)))\n  ) |>\n  mutate(\n    across(c(Statistic, Approx_F), ~ round(.x, 3)),\n    across(c(Hypothesis_df, df1, df2), ~ round(.x, 0))\n  ) |>\n  dplyr::select(Effect, Hypothesis_df, Statistic, Approx_F, df1, df2, p) |>\n  knitr::kable(caption = \"MANCOVA（Pillai's trace）: Proficiency調整後の多変量効果\")\n```\n\n::: {.cell-output-display}\n\n\nTable: MANCOVA（Pillai's trace）: Proficiency調整後の多変量効果\n\n|Effect                   | Hypothesis_df| Statistic| Approx_F| df1| df2|p      |\n|:------------------------|-------------:|---------:|--------:|---:|---:|:------|\n|Proficiency              |             1|     0.108|   10.550|   2| 174|< .001 |\n|Instruction              |             1|     0.406|   59.491|   2| 174|< .001 |\n|LearningMode             |             1|     0.046|    4.178|   2| 174|.017   |\n|Instruction:LearningMode |             1|     0.008|    0.720|   2| 174|.488   |\n\n\n:::\n:::\n\n\n### 調整後平均を図で読む\n\nMANCOVA の数表だけでは、「共変量を入れたことで何が変わったのか」が見えにくいことがあります。そこで、各 outcome について `Proficiency` を平均値に固定した**調整後平均**を描きます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadj_means_tbl <- bind_rows(\n  as.data.frame(emmeans::emmeans(\n    lm(Recall ~ Instruction * LearningMode + Proficiency, data = simulated_cov),\n    ~ Instruction * LearningMode,\n    cov.reduce = mean\n  )) |>\n    transmute(\n      Instruction, LearningMode,\n      Outcome = \"Recall\",\n      emmean, lower.CL, upper.CL\n    ),\n  as.data.frame(emmeans::emmeans(\n    lm(Recognition ~ Instruction * LearningMode + Proficiency, data = simulated_cov),\n    ~ Instruction * LearningMode,\n    cov.reduce = mean\n  )) |>\n    transmute(\n      Instruction, LearningMode,\n      Outcome = \"Recognition\",\n      emmean, lower.CL, upper.CL\n    )\n)\n\nggplot(adj_means_tbl, aes(x = LearningMode, y = emmean, color = Instruction, group = Instruction)) +\n  geom_pointrange(aes(ymin = lower.CL, ymax = upper.CL), position = position_dodge(width = 0.15)) +\n  geom_line(position = position_dodge(width = 0.15), linewidth = 0.9) +\n  facet_wrap(~ Outcome, scales = \"free_y\") +\n  labs(\n    title = \"Proficiency調整後の平均\",\n    subtitle = \"共変量調整モデルから得た推定周辺平均\",\n    x = \"LearningMode\",\n    y = \"調整後平均\"\n  )\n```\n\n::: {.cell-output-display}\n![平均的なProficiency水準における調整後平均（adjusted means）。MANCOVAの調整を単変量的に確認する図。](3_MANOVA_判別分析_files/figure-html/adjusted-means-plot-1.png){fig-alt='RecallとRecognitionの2パネルで、InstructionとLearningMode別の調整後平均と信頼区間を示す図。' width=2400}\n:::\n:::\n\n\n**MANCOVA をどう読むか**:\n\n- `Proficiency` の行は、「共変量自体が outcome の組と関連しているか」を示す\n- `Instruction` や `LearningMode` がなお有意なら、「事前能力を調整しても群差が残る」と解釈できる\n- 逆に群効果が弱まるなら、「見えていた群差の一部は共変量と共有されていた」可能性がある\n- ただし、ここでの解釈はあくまで**線形調整後の条件付き比較**であり、因果的な統制が自動で保証されるわけではない\n\n### MANCOVA と SEM の接点\n\n共変量が入った時点で、MANOVA 系と SEM 系の距離はさらに近づきます。観測変数レベルでは MANCOVA は「複数 outcome に対する多変量回帰」であり、SEM ではこれを **潜在変数に対する回帰**へ拡張できます。もし `Proficiency` 自体が測定誤差を含むテスト得点で、さらに `Recall` や `Recognition` も複数指標から成るなら、**MANCOVA 的な調整を latent regression として SEM で実装する**方が理にかないます [@cole1993; @rosseel2012]。\n\n要するに、拡張の方向は次のように整理できます。\n\n- **観測得点 + 少数の共変量**: MANCOVA で十分なことが多い\n- **潜在因子 + 測定誤差 + 群間等値性**: 多母集団 SEM / latent mean analysis の方が自然\n- **共変量と群要因の交互作用が大きい**: 単純な MANCOVA ではなく、より一般的な多変量回帰や SEM を検討する\n\n## 検定力分析 {#sec-manova-power}\n\nMANOVAは多変量検定であるため、推定すべきパラメータが単変量ANOVAよりも多くなります。十分な検定力（通常 $\\geq .80$）を確保するには、サンプルサイズの事前計画が不可欠です。\n\nTabachnick & Fidell [-@tabachnick2019] は、MANOVAにおけるサンプルサイズの基本ルールとして以下を示しています。\n\n| ルール | 内容 | 根拠 |\n|:---|:---|:---|\n| **最低条件** | 各セルの $n >$ DV数 | 群内共分散行列が非特異であるために必要 |\n| **推奨条件** | 各セルの $n \\geq 20$ | 検定統計量のF近似が安定するために推奨 [@stevens2009] |\n| **DDA用の追加条件** | 各セルの $n \\geq$ DV数 + 1（QDA使用時は特に重要） | QDAの群別共分散推定に必要 |\n| **検定力の確保** | 総N に対して検定力計算で .80 以上 | 事前のパワー分析で確認 [@zhang2018] |\n\n: MANOVAのサンプルサイズに関する基本ルール {.striped}\n\nここでは `WebPower` パッケージの `wp.kanova()` を用いて、MANOVA効果に対する**近似的な事前検定力・感度分析**を行います [@zhang2018]。本章の2要因MANOVAでは、`Instruction`、`LearningMode`、`Instruction:LearningMode` の各効果は2水準要因に由来するため、Pillai表の分子自由度は概ね `ndf = 2` です。4セル全体を1要因として扱う omnibus 計画なら `ndf = 6` も考えられますが、ここでは本章の主検定に合わせて `ndf = 2` を使います。\n\n重要なのは、観測後に「本データの事後検定力」を結論の根拠にしないことです。非有意結果を解釈する場合は、事後検定力よりも、事前計画、最小検出可能効果、信頼区間の幅、または次回研究の必要サンプルサイズを報告します。\n\n### 現在の標本サイズで検出しやすい効果\n\n\n::: {.cell}\n\n```{.r .cell-code}\nndf_effect <- 2\nng_design <- 4\n\nwp_result <- WebPower::wp.kanova(\n  n = nrow(simulated),\n  ndf = ndf_effect,\n  f = 0.25,\n  ng = ng_design,\n  alpha = 0.05,\n  power = NULL\n)\n\ntibble(\n  Parameter = c(\"Total N\", \"Groups (ng)\", \"Numerator df (ndf)\", \"Effect size (f)\", \"Alpha\", \"Power\"),\n  Value = c(\n    wp_result$n,\n    wp_result$ng,\n    wp_result$ndf,\n    wp_result$f,\n    wp_result$alpha,\n    round(wp_result$power, 3)\n  )\n) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"現在の標本サイズでの検定力（statistical power）: WebPower::wp.kanova() によるMANOVA近似\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 現在の標本サイズでの検定力（statistical power）: WebPower::wp.kanova() によるMANOVA近似\n\n|Parameter          |   Value|\n|:------------------|-------:|\n|Total N            | 180.000|\n|Groups (ng)        |   4.000|\n|Numerator df (ndf) |   2.000|\n|Effect size (f)    |   0.250|\n|Alpha              |   0.050|\n|Power              |   0.855|\n\n\n:::\n:::\n\n\n**検定力分析の読み方**:\n\n| パラメータ | 意味 |\n|:---|:---|\n| `n` | 総サンプルサイズ |\n| `ng` | 群数 |\n| `ndf` | 分子自由度。本章の各2水準効果では概ね2 |\n| `f` | Cohen の f（中程度 = 0.25） |\n| `power` | 近似的な検定力。.80以上が計画上の目安 |\n\n### サンプルサイズと検定力の関係\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_seq <- seq(40, 300, by = 20)\npower_curve <- purrr::map(n_seq, \\(n_total) {\n  res <- WebPower::wp.kanova(\n    n = n_total, ndf = ndf_effect, f = 0.25,\n    ng = ng_design, alpha = 0.05, power = NULL\n  )\n  tibble(n = n_total, power = res$power)\n}) |>\n  purrr::list_rbind()\n\nggplot(power_curve, aes(x = n, y = power)) +\n  geom_line(linewidth = 1.1, color = \"#2c3e50\") +\n  geom_hline(yintercept = 0.80, linetype = \"dashed\", color = \"red\") +\n  annotate(\"text\", x = 250, y = 0.82, label = \"Power = .80 threshold\", color = \"red\") +\n  labs(\n    title = \"MANOVA効果に対する近似的な検定力曲線\",\n    subtitle = \"4 groups, Cohen's f = 0.25, ndf = 2\",\n    x = \"総サンプルサイズ\",\n    y = \"検定力\"\n  )\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-html/power-curve-1.png){width=2100}\n:::\n:::\n\n\n### 必要サンプルサイズの算出\n\n目標検定力 .80 に必要な総サンプルサイズを逆算します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwp_n <- WebPower::wp.kanova(\n  n = NULL,\n  ndf = ndf_effect,\n  f = 0.25,\n  ng = ng_design,\n  alpha = 0.05,\n  power = 0.80\n)\n\ntibble(\n  Target_Power = 0.80,\n  Required_N = ceiling(wp_n$n),\n  Per_Group = ceiling(wp_n$n / ng_design)\n) |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"必要サンプルサイズ（required sample size）: f = 0.25、power = .80 を目標にした近似計画\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 必要サンプルサイズ（required sample size）: f = 0.25、power = .80 を目標にした近似計画\n\n| Target_Power| Required_N| Per_Group|\n|------------:|----------:|---------:|\n|          0.8|        158|        40|\n\n\n:::\n:::\n\n\n#### 英語教育研究における効果量の目安\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffect_size_plan <- tibble(\n  f = c(0.10, 0.25, 0.40),\n  Interpretation = c(\"語彙学習法間の微差\", \"指導法間の一般的な差\", \"介入の顕著な効果\")\n) |>\n  mutate(\n    Required_N = purrr::map_dbl(f, ~ WebPower::wp.kanova(\n      n = NULL,\n      ndf = ndf_effect,\n      f = .x,\n      ng = ng_design,\n      alpha = 0.05,\n      power = 0.80\n    )$n),\n    Required_N = ceiling(Required_N),\n    Per_Group = ceiling(Required_N / ng_design)\n  )\n\neffect_size_plan |>\n  knitr::kable(caption = \"効果量別の感度分析（effect-size sensitivity）: 目標効果量ごとの近似必要N\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 効果量別の感度分析（effect-size sensitivity）: 目標効果量ごとの近似必要N\n\n|    f|Interpretation       | Required_N| Per_Group|\n|----:|:--------------------|----------:|---------:|\n| 0.10|語彙学習法間の微差   |        967|       242|\n| 0.25|指導法間の一般的な差 |        158|        40|\n| 0.40|介入の顕著な効果     |         64|        16|\n\n\n:::\n:::\n\n\n先行研究の効果量を参照してサンプルサイズを計画することが重要です。英語教育研究では $f = 0.25$ 前後が現実的な目安となることが多いです [@stevens2009; @hahs2017]。\n\n**実務上のポイント**:\n\n- Stevens [-@stevens2009] は、効果量が小さい（$f = .10$）場合の検出には各群50名以上が必要であると指摘しており、教育研究で典型的な30名前後のクラスサイズでは検出が困難であることを示唆しています。\n- 英語教育研究では1クラス20-30名が現実的な制約であるため、**2-3クラスをまとめて1群40-60名**を確保するか、効果量が中程度以上の介入に焦点を絞る戦略が必要です。\n- Tabachnick & Fidell [-@tabachnick2019] は「各セルの $n >$ DV数」を最低条件としていますが、これはあくまで行列演算上の最低限であり、検定力の観点ではさらに大きなNが必要です。\n\n## 効果量・メタ分析との接続 {#sec-manova-meta}\n\n研究を **将来のメタ分析の素材として残す**ためには、MANOVA の結果を「再利用可能な形」で報告する必要があります。MANOVA は本質的に多変量ですが、メタ分析は伝統的に**単変量効果量**(Cohen's *d*、Hedges' *g*、Pearson の *r*、偏 η²)を主指標として蓄積してきました。両者を橋渡しする報告戦略を整理します。\n\n### 多変量効果量の選択肢\n\nMANOVA に対応する効果量には次の階層があります。\n\n| 効果量 | 計算 | 性質 | メタ分析での扱い |\n|---|---|---|---|\n| **Mahalanobis $D^2$** | $D^2 = (\\bar{\\mathbf{x}}_1 - \\bar{\\mathbf{x}}_2)' \\mathbf{S}^{-1}_{\\text{pooled}} (\\bar{\\mathbf{x}}_1 - \\bar{\\mathbf{x}}_2)$ | 2 群比較の多変量距離。単変量 Cohen's *d* の自然な拡張(Cohen, 1988, 第 11 章) | 多変量メタ分析の主指標 |\n| **Pillai η² = $V/s$** | Pillai のトレースを正規化 | 多変量説明分散割合。3 群以上にも対応 | $\\eta^2_{\\text{multi}}$ として報告 |\n| **Wilks η² = $1 - \\Lambda^{1/s}$** | Wilks のΛから派生 | 同上(Wilks 経由) | 同上 |\n| **DV 別の Cohen's $d_j$ または偏 η²$_j$** | 各 DV を個別に計算 | 単変量。標準的なメタ分析に含めやすい | **単変量メタ分析の主指標** |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mahalanobis D²(2 群比較版):群平均ベクトルの差をプール内共分散で標準化\ndvs <- c(\"Recall\", \"Recognition\")\ndiff_mean <- colMeans(subset(simulated_2groups, Group == \"A\")[, dvs]) -\n             colMeans(subset(simulated_2groups, Group == \"B\")[, dvs])\n\n# プール内共分散行列(各群の共分散をサンプルサイズで重み付け平均)\nn_a <- sum(simulated_2groups$Group == \"A\")\nn_b <- sum(simulated_2groups$Group == \"B\")\nS_a <- cov(subset(simulated_2groups, Group == \"A\")[, dvs])\nS_b <- cov(subset(simulated_2groups, Group == \"B\")[, dvs])\npooled_S <- ((n_a - 1) * S_a + (n_b - 1) * S_b) / (n_a + n_b - 2)\n\nmahal_d2 <- as.numeric(t(diff_mean) %*% solve(pooled_S) %*% diff_mean)\n\n# 各 DV 別の Cohen's d(メタ分析投入用)\nlibrary(effectsize)\n\ndv_effects <- simulated_2groups |>\n  tidyr::pivot_longer(c(Recall, Recognition), names_to = \"DV\") |>\n  dplyr::group_by(DV) |>\n  dplyr::group_modify(\\(x, key) {\n    res <- effectsize::cohens_d(value ~ Group, data = x, ci = 0.95)\n    tibble::as_tibble(res)\n  })\n```\n:::\n\n\n### メタ分析投入のためのチェックリスト\n\n将来 **誰かがあなたの結果をメタ分析する**(あるいは自分で続報研究と統合する)とき、以下の情報がすべて揃っていると貢献度が大きく上がります。\n\n| 必要情報 | 形式 | 用途 |\n|---|---|---|\n| 群別 *M*, *SD*, *n*, DV 間相関 | 表(本文または付表) | 任意の効果量を再計算可能にする最重要情報 |\n| 多変量検定統計量(Pillai または Wilks)+ F + df + p | APA 報告 | 多変量メタ分析の入力 |\n| **DV 別の Cohen's *d* / 偏 η² + 95% CI** | DV ごと一行 | 単変量メタ分析の入力 |\n| Mahalanobis $D^2$ または Pillai η² | 数値 + 信頼区間 | 多変量効果量メタ分析の入力 |\n| サンプリング設計(クラスタ・無作為割付・除外基準) | 方法節 | 異質性評価とサブグループ分析 |\n| 共変量の有無 + 調整前/調整後の効果量 | 補足 | MANCOVA 含む研究の比較 |\n\n### 多変量メタ分析(MVMA)へのパス\n\n**多変量メタ分析(multivariate meta-analysis、MVMA)** は、複数の関連する DV の効果量を**同時に**統合する手法で、単変量メタ分析を独立に走らせるより**統計的精度と一貫性が高い**ことが知られています [@berkey1998multivariate; @riley2017]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# metafor::rma.mv() による MVMA の最小例\nlibrary(metafor)\n\n# 複数研究から各研究の Cohen's d(Recall, Recognition)を抽出した想定\nmeta_dat <- tibble(\n  study   = rep(1:5, each = 2),\n  outcome = rep(c(\"Recall\", \"Recognition\"), 5),\n  yi = c(0.45, 0.38, 0.52, 0.41, 0.38, 0.30, 0.61, 0.55, 0.42, 0.36),  # 各研究×DV の効果量\n  vi = c(0.04, 0.04, 0.05, 0.05, 0.06, 0.06, 0.04, 0.04, 0.05, 0.05)   # サンプリング分散\n)\n\n# DV 内・DV 間の相関構造を含めた多変量メタ分析\nmvma_fit <- rma.mv(\n  yi, vi,\n  mods   = ~ outcome - 1,                  # DV 別の平均効果量\n  random = ~ outcome | study,              # 研究内 DV 相関\n  struct = \"UN\",                           # 非構造的(自由推定)\n  data   = meta_dat\n)\nsummary(mvma_fit)\n```\n:::\n\n\nこの手法は研究内の DV 間相関構造を尊重するため、**「Recall は強い効果、Recognition は弱い効果」のような DV 間の効果プロファイル**を保ったまま統合できます。詳細は第 17 章「メタ分析」を参照してください。\n\n### 検定力分析と先行効果量の循環\n\n新規研究の検定力分析(@sec-manova-power 相当)は、**先行研究のメタ分析結果**を入力に使うのが現代的です。\n\n1. **既存メタ分析を引く**:Plonsky & Oswald [-@plonsky2014] のような分野メタ分析から、典型的な効果量レンジを取得\n2. **保守的な値で検定力分析**:メタ分析の効果量が中央値で $d = 0.5$ ないし $f = 0.25$ なら、それを下回る `f = 0.20` 程度で `WebPower::wp.kanova()` を回す\n3. **自分の研究を投稿** → 結果を**メタ分析に再利用可能な形で報告**(上記チェックリスト)\n4. **次世代の検定力分析の入力**になる\n\nこの **「メタ分析 → 検定力分析 → 新規研究 → メタ分析」のサイクル**が、再現可能な研究プログラムの基盤です。\n\n::: {.callout-tip}\n#### 単一研究で必ず報告すべき最小セット\n仮にメタ分析を意図しない場合でも、上の表のうち **群別 *M*, *SD*, *n*** と **DV 別の Cohen's *d* + CI** は**必ず報告**してください。これだけで誰でも独立に効果量を再計算でき、研究の透明性が大きく上がります。多変量検定だけ報告して終わると、後の系統的レビューで貴方の研究は**含めにくくなります**。\n:::\n\n## よくある誤解\n\n### 誤解1: 「MANOVAが有意なら追跡ANOVAのType Iエラーは制御される」\n\n**事実**: MANOVAの有意性は多変量空間全体での検定結果であり、個々のDVへの追跡ANOVAに対する「保護的ゲートキーパー」機能は限定的です。Huberty & Olejnik [-@huberty2006] はこの点を明確に指摘し、追跡ANOVAにはHolm法などの多重性補正が依然として必要であると述べています。\n\nSmith et al. [-@smith2020] は英才教育研究の56論文を体系的にレビューし、ほぼすべてがMANOVA後に無補正の単変量ANOVAのみで追跡していることを発見しました。シミュレーションにより、DV数が増えるとこの慣行のType Iエラー率が最大76%に達しうることを示しています。\n\n### 誤解2: 「MANOVAが非有意なら群差はない」\n\n**事実**: 非有意の結果は「差がない」ことの証拠ではなく、「差を検出できなかった」可能性があります。検定力が不足している場合（N不足、効果量が小さい場合）、真の差があっても検出できません。ただし、観測後の事後検定力を結論の根拠にするのではなく、効果量推定値と信頼区間、事前の検定力計画、または次回研究に必要なサンプルサイズを報告します [@stevens2009]。\n\n### 誤解3: 「追跡ANOVAのみで十分」\n\n**事実**: 追跡ANOVAは各DVを個別に検定するため、DV間の相関構造を無視します。MANOVAが有意でも全てのANOVAが非有意になるケースがあります（DVの組み合わせが群差のパターンを担う場合）。\n\nWarne [-@warne2014] は58本のMANOVA論文をレビューし、DDAを適切に使った論文が**1本もなかった**ことを報告しています。このことは、追跡ANOVAのみに頼る慣行がいかに根深いかを示しています。Finch & French [-@finch2013] は、DDAがMANOVAと数学的に同一の情報源（$\\mathbf{H}\\mathbf{E}^{-1}$ の固有値分解）に基づくことを示し、追跡法としての理論的一貫性を強調しています。DDAを併用することで、単変量では見えない多変量的パターンを捉えることが可能になります。\n\n### 誤解4: 「MANOVAは同時ANOVAにすぎない」\n\n**事実**: MANOVAはDV間の共分散構造を考慮した上で群差を検定します。H行列とE行列の比がMANOVAの検定統計量の基盤であり、DVを個別に検定するANOVAにはこの情報がありません。Huberty & Olejnik [-@huberty2006] はMANOVAの本質を「DVの最適な重み付け線形結合に対する検定」と定義しています。\n\nこの違いは、HEプロットで視覚的に確認できます。Friendly [-@friendly2007] のHEプロット手法では、H楕円がE楕円からはみ出す方向が多変量的な群差の方向を示しますが、この方向は個々のDV軸とは異なる場合があります。つまり、MANOVAは個別ANOVAでは原理的にアクセスできない「DV間の組み合わせに基づく群差」を検出する能力を持ちます。\n\n## トラブルシューティング（実務で詰まりやすい点）\n\nMANOVA / 判別分析で実際に解析を進めるとき、誰もが一度は遭遇しやすい 8 つのつまずきポイントを取り上げます。該当する項目だけ参照する形でも構いません。\n\n### 多変量正規性（MVN）が逸脱したときは?\n\n**症状**: HZ検定で $p < .05$。Q-Qプロットが対角線から乖離。\n\n**原因**: 外れ値、床効果・天井効果、本質的に非正規な変数。\n\n**修正**:\n\n1. マハラノビス距離で外れ値を特定し、感度分析（含む/除く）を行う。\n2. Pillai統計量を主報告にする。Olson [-@olson1974] のモンテカルロ研究で、正規性違反に最も頑健であることが確認されている。\n3. 逸脱が著しい場合、変数変換（log, sqrt）を検討。\n4. 大標本（各群 $n > 30$）であれば中心極限定理により頑健性が高まる [@tabachnick2019]。\n5. 論文には「HZ検定の結果と対応策」を明記する。\n\n### Box's M 検定が有意になってしまったら?\n\n**症状**: Box's M が $p < .001$。\n\n**原因**: 群間で共分散行列の構造が異なる。群サイズの不均衡があるとさらに影響が大きい。Box's M は標本サイズに過敏であるため、$p < .05$ ではなく $p < .001$ を実務基準とすることが推奨されます [@tabachnick2019; @huberty2006]。\n\n**修正**:\n\n1. 群サイズがバランスしていれば、Pillai統計量は比較的頑健。Olson [-@olson1974] はこの条件でPillaiが名義 $\\alpha$ 水準を維持することを示している。\n2. 群サイズが不均衡なら、最も危険な条件（共分散不等質 + 不均衡N）に該当するため、結果の解釈に特に慎重になる。\n3. 群ごとの共分散楕円を可視化し（HEプロットで確認可能）、逸脱の程度を確認する。\n4. 予測目的の感度分析としてQDAを検討する（群別共分散を許容）。ただし各群の $n >$ DV数 + 1 が必要で、MANOVAの主推論とは分けて扱う [@tabachnick2019]。\n\n### DV 間に強い多重共線性があるときは?\n\n**症状**: DV間相関が .70 を超える。判別関数の係数が不安定。Tabachnick & Fidell [-@tabachnick2019] は .90 以上を「深刻な多重共線性」として警告している。\n\n**原因**: DVが測定している構成概念がほぼ同一。\n\n**修正**:\n\n1. 一方のDVを除外するか、複合スコアに統合することを検討。\n2. 構造係数を優先して解釈する。Sherry & Henson [-@sherry2005] は、DV間相関が高い場合に標準化係数が不安定になることを示しており、構造係数のみでの解釈を推奨している。\n3. 理論的にDVが異なる構成概念であることを再確認する。\n4. DV間相関が .30-.70 程度の「扱いやすい範囲」に収まるようDVの選択を見直す。\n\n### サンプルサイズが不足しているときは?\n\n**症状**: MANOVAが非有意だが、記述統計では明らかな群差がある。\n\n**原因**: 検定力不足。MANOVAは推定パラメータが多いため、ANOVAより大きなNが必要。\n\n**修正**:\n\n1. 効果量推定値と信頼区間を確認し、推定の不確実性を明記する。\n2. `WebPower::wp.kanova()` などで、次回研究に必要なサンプルサイズや最小検出可能効果を計画する。\n3. 事後検定力ではなく、「検出力不足の可能性」と「次回研究の設計案」を報告する。\n\n### MANOVA は有意だが全ての追跡 ANOVA が非有意のときは?\n\n**症状**: Pillai が $p < .05$ だが、追跡ANOVAでは全DVが $p > .05$。\n\n**原因**: 群差がDV間の相関パターンに埋め込まれており、個々のDVでは表面化しない。これは「矛盾」ではなく、**MANOVAの利点が発揮された場面**です。Warne [-@warne2014] はこの状況を「MANOVAの存在意義を最もよく示すケース」と述べています。\n\n**修正**:\n\n1. DDA（判別分析）で多変量的な群分離パターンを確認する。構造係数を読むことで、DVの組み合わせがどの方向に群差を形成しているかがわかります。\n2. HEプロットで視覚的にパターンを確認する。Friendly [-@friendly2007] のHEプロットでは、H楕円がE楕円からはみ出す方向がDV軸と斜めになる場合、個別のDVでは検出できない「斜め方向」の群差が存在していることを示します。\n3. 論文には「多変量検定は有意であったが、単変量では個別に有意な変数は見られなかった。DDAにより、DVの組み合わせとして群分離が確認された」と報告する [@smith2020; @finch2013]。\n\n### 外れ値で結果が不安定になったときは?\n\n**症状**: マハラノビス距離がカットオフを大きく超える観測がある。外れ値の除外前後で結果が変わる。\n\n**原因**: データ入力ミス、異質な参加者（タスク不理解など）。\n\n**修正**:\n\n1. 外れ値の「含む/除く」の両方で分析し、結果の安定性を確認（感度分析）。\n2. 除外する場合は、理論的根拠（タスク不理解の記録など）を明記する。\n3. 「統計的にだけ外れ値」という理由での除外は避ける。\n\n### QDA が収束しない（rank deficiency）ときは?\n\n**症状**: `MASS::qda()` で \"some group is too small\" や \"rank deficiency\" エラー。\n\n**原因**: 群内の観測数がDV数以下、または群内共分散行列が特異（ランク落ち）。\n\n**修正**:\n\n1. 各群の $n >$ DV数 であることを確認する（最低でも $n > p + 1$）。\n2. LDAに切り替える（共通共分散を仮定するため、少数サンプルに対応しやすい）。\n3. DV数を減らすか、正則化判別分析を検討する。\n\n## 報告テンプレート（論文の結果節向け）\n\nこの節は、分析結果を論文の Method / Results に移すための最終確認である。MANOVA では「多変量検定が有意だった」だけでは情報が不足するため、**設計、前提、主検定、追跡法、分類精度、検定力**を一組で報告する。本節のテンプレートは APA 第 7 版と *Language Learning* の Open Methods ガイドライン [@norris2015] を主な参照枠としており、後者は記述統計、多変量および単変量効果量、CI、検定力、再現に必要な分析手続きの開示を必須項目に挙げています。\n\n| 報告要素 | 本章で確認した出力 | 本文での役割 |\n|:---|:---|:---|\n| 設計 | `Instruction × LearningMode`、1参加者1行 | between-subjects MANOVA であることを明示する |\n| 前提 | HZ検定、Box's M、外れ値診断 | Pillai を主報告にする根拠と、解釈上の制約を示す |\n| 主検定 | Pillai's trace | 多変量的な群差の有無を示す |\n| 多変量追跡 | DDA、構造係数、trace割合 | どのDVの組み合わせが群分離を作ったかを説明する |\n| 補助追跡 | Holm補正つき単変量ANOVA | 個別DVの方向を補足する |\n| 実務的分離 | LOOCV分類精度、チャンス水準 | 群がどの程度識別可能かを示す |\n| 設計評価 | 検定力、必要サンプルサイズ | 非有意結果や今後の研究計画を解釈する |\n\n::: {.panel-tabset}\n\n### Method\n\n以下は、本章のデータに基づいた Method セクションの記述例です。自分のデータに置き換えて使用してください。\n\n> We examined the effects of Instruction (Glossing vs. Writing) and LearningMode (Individual vs. Collaborative) on two vocabulary outcomes (Recall and Recognition) using a two-way multivariate analysis of variance (MANOVA). Assumptions of multivariate normality were evaluated using the Henze-Zirkler test (Korkmaz et al., 2014) applied group-wise, and homogeneity of covariance matrices was assessed with Box's M test. Pillai's trace was used as the primary test statistic due to its robustness to assumption violations (Olson, 1974). Descriptive discriminant analysis (DDA) was used to summarize the four-cell group separation, with univariate ANOVAs as supplementary analyses (Holm-adjusted). Classification accuracy was evaluated using leave-one-out cross-validation and a permutation check against chance. Analyses were conducted in R using the MASS, MVN, biotools, heplots, candisc, emmeans, effectsize, and WebPower packages.\n\n### Results（MANOVA + DDA）\n\nまず、Pillaiのトレースに基づく主検定をAPA形式で整理します。ここでは `pillai_focus` から自由度、F値、p値を取り出すため、固定値を手入力しません。\n\n\n::: {.cell}\n\n```{.r .cell-code}\napa_manova_tbl <- pillai_focus |>\n  mutate(\n    V = sub(\"^0\", \"\", sprintf(\"%.2f\", Statistic)),\n    F_value = sprintf(\"%.2f\", Approx_F),\n    p_APA = if_else(\n      p_value < .001,\n      \"< .001\",\n      paste0(\"= \", sub(\"^0\", \"\", sprintf(\"%.3f\", p_value)))\n    ),\n    APA_Result = paste0(\n      Effect,\n      \": *V* = \", V,\n      \", *F*(\", df1, \", \", df2, \") = \", F_value,\n      \", *p* \", p_APA\n    )\n  ) |>\n  dplyr::select(Effect, V, df1, df2, F_value, p_APA, Interpretation, APA_Result)\n\napa_manova_tbl |>\n  knitr::kable(caption = \"APA形式に整えたMANOVA結果（APA-ready MANOVA results）: Pillaiのトレース\")\n```\n\n::: {.cell-output-display}\n\n\nTable: APA形式に整えたMANOVA結果（APA-ready MANOVA results）: Pillaiのトレース\n\n|Effect                   |V   | df1| df2|F_value |p_APA  |Interpretation |APA_Result                                                          |\n|:------------------------|:---|---:|---:|:-------|:------|:--------------|:-------------------------------------------------------------------|\n|Instruction              |.41 |   2| 175|59.97   |< .001 |有意           |Instruction: *V* = .41, *F*(2, 175) = 59.97, *p* < .001             |\n|LearningMode             |.05 |   2| 175|4.22    |= .016 |有意           |LearningMode: *V* = .05, *F*(2, 175) = 4.22, *p* = .016             |\n|Instruction:LearningMode |.01 |   2| 175|0.69    |= .501 |非有意         |Instruction:LearningMode: *V* = .01, *F*(2, 175) = 0.69, *p* = .501 |\n\n\n:::\n:::\n\n\n次に、DDA（4セル全体の分離）と分類精度を報告用にまとめます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstructure_ld1_tbl <- structure_tbl |>\n  dplyr::select(Variable, LD1) |>\n  mutate(\n    r_s = gsub(\"^-0\\\\.\", \"-.\", sub(\"^0\\\\.\", \".\", sprintf(\"%.2f\", LD1))),\n    Report = paste0(Variable, \" *r_s* = \", r_s)\n  )\n\ndda_report_tbl <- tibble(\n  Item = c(\n    \"LD1 proportion of trace\",\n    \"LD1 structure coefficients\",\n    \"LOOCV overall accuracy\",\n    \"LOOCV balanced accuracy\",\n    \"Permutation check\"\n  ),\n  Value = c(\n    scales::percent(prop_trace_tbl$Proportion[1], accuracy = 0.1),\n    paste(structure_ld1_tbl$Report, collapse = \"; \"),\n    paste0(\n      scales::percent(lda_acc_ci$Accuracy[1], accuracy = 0.1),\n      \", 95% CI [\",\n      scales::percent(lda_acc_ci$CI_low[1], accuracy = 0.1),\n      \", \",\n      scales::percent(lda_acc_ci$CI_high[1], accuracy = 0.1),\n      \"]\"\n    ),\n    scales::percent(lda_balanced, accuracy = 0.1),\n    if_else(\n      lda_perm_p < .001,\n      \"p < .001\",\n      paste0(\"p = \", sub(\"^0\", \"\", sprintf(\"%.3f\", lda_perm_p)))\n    )\n  )\n)\n\ndda_report_tbl |>\n  knitr::kable(caption = \"APA形式に整えたDDA・分類性能の要約（APA-ready DDA and classification summary）\")\n```\n\n::: {.cell-output-display}\n\n\nTable: APA形式に整えたDDA・分類性能の要約（APA-ready DDA and classification summary）\n\n|Item                       |Value                                       |\n|:--------------------------|:-------------------------------------------|\n|LD1 proportion of trace    |98.8%                                       |\n|LD1 structure coefficients |Recall *r_s* = .87; Recognition *r_s* = .89 |\n|LOOCV overall accuracy     |38.9%, 95% CI [31.7%, 46.4%]                |\n|LOOCV balanced accuracy    |38.9%                                       |\n|Permutation check          |p = .005                                    |\n\n\n:::\n:::\n\n\n本文に移すと、次のようになります。\n\n\n```{.r .cell-code}\ncat(\"> Pillai's trace was used to evaluate the multivariate effects. \")\n```\n\n> Pillai's trace was used to evaluate the multivariate effects. \n\n```{.r .cell-code}\ncat(paste(apa_manova_tbl$APA_Result, collapse = \"; \"))\n```\n\nInstruction: *V* = .41, *F*(2, 175) = 59.97, *p* < .001; LearningMode: *V* = .05, *F*(2, 175) = 4.22, *p* = .016; Instruction:LearningMode: *V* = .01, *F*(2, 175) = 0.69, *p* = .501\n\n```{.r .cell-code}\ncat(\".\\n>\\n\")\n```\n\n.\n>\n\n```{.r .cell-code}\ncat(\n  \"> Descriptive discriminant analysis of the four-cell grouping showed that LD1 accounted for \",\n  scales::percent(prop_trace_tbl$Proportion[1], accuracy = 0.1),\n  \" of the between-group variance. Structure coefficients for LD1 were \",\n  paste(structure_ld1_tbl$Report, collapse = \"; \"),\n  \". Overall LOOCV classification accuracy was \",\n  scales::percent(lda_acc_ci$Accuracy[1], accuracy = 0.1),\n  \", 95% CI [\",\n  scales::percent(lda_acc_ci$CI_low[1], accuracy = 0.1),\n  \", \",\n  scales::percent(lda_acc_ci$CI_high[1], accuracy = 0.1),\n  \"], balanced accuracy was \",\n  scales::percent(lda_balanced, accuracy = 0.1),\n  \", and the permutation check yielded \",\n  if_else(lda_perm_p < .001, \"p < .001\", paste0(\"p = \", sub(\"^0\", \"\", sprintf(\"%.3f\", lda_perm_p)))),\n  \".\",\n  sep = \"\"\n)\n```\n\n> Descriptive discriminant analysis of the four-cell grouping showed that LD1 accounted for 98.8% of the between-group variance. Structure coefficients for LD1 were Recall *r_s* = .87; Recognition *r_s* = .89. Overall LOOCV classification accuracy was 38.9%, 95% CI [31.7%, 46.4%], balanced accuracy was 38.9%, and the permutation check yielded p = .005.\n\n### Results（単変量追跡）\n\n単変量追跡は補助的な位置づけです。Holm補正後のp値と偏η²の95% CIを併記します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\napa_univariate_tbl <- followup_tbl |>\n  mutate(\n    Residual_df = if_else(Outcome == \"Recall\", df.residual(aov_recall), df.residual(aov_recognition))\n  ) |>\n  left_join(\n    eta_tbl,\n    by = c(\"Outcome\", \"term\" = \"Parameter\")\n  ) |>\n  mutate(\n    F_value = sprintf(\"%.2f\", statistic),\n    p_Holm_APA = if_else(\n      p_holm < .001,\n      \"< .001\",\n      paste0(\"= \", sub(\"^0\", \"\", sprintf(\"%.3f\", p_holm)))\n    ),\n    eta_APA = sub(\"^0\", \"\", sprintf(\"%.3f\", Eta2_partial)),\n    CI_APA = paste0(\n      \"[\",\n      sub(\"^0\", \"\", sprintf(\"%.3f\", CI_low)),\n      \", \",\n      sub(\"^0\", \"\", sprintf(\"%.3f\", CI_high)),\n      \"]\"\n    ),\n    APA_Result = paste0(\n      Outcome, \" / \", term,\n      \": *F*(\", df, \", \", Residual_df, \") = \", F_value,\n      \", Holm-adjusted *p* \", p_Holm_APA,\n      \", eta_p2 = \", eta_APA,\n      \", 95% CI \", CI_APA\n    )\n  ) |>\n  dplyr::select(Outcome, term, df, Residual_df, F_value, p_Holm_APA, eta_APA, CI_APA, APA_Result)\n\napa_univariate_tbl |>\n  knitr::kable(caption = \"APA形式に整えた単変量追跡結果（APA-ready univariate follow-up results）\")\n```\n\n::: {.cell-output-display}\n\n\nTable: APA形式に整えた単変量追跡結果（APA-ready univariate follow-up results）\n\n|Outcome     |term                     | df| Residual_df|F_value |p_Holm_APA |eta_APA |CI_APA       |APA_Result                                                                                                               |\n|:-----------|:------------------------|--:|-----------:|:-------|:----------|:-------|:------------|:------------------------------------------------------------------------------------------------------------------------|\n|Recall      |Instruction              |  1|         176|76.45   |< .001     |.303    |[.197, .403] |Recall / Instruction: *F*(1, 176) = 76.45, Holm-adjusted *p* < .001, eta_p2 = .303, 95% CI [.197, .403]                  |\n|Recall      |LearningMode             |  1|         176|6.35    |= .051     |.035    |[.002, .103] |Recall / LearningMode: *F*(1, 176) = 6.35, Holm-adjusted *p* = .051, eta_p2 = .035, 95% CI [.002, .103]                  |\n|Recall      |Instruction:LearningMode |  1|         176|0.50    |= .962     |.003    |[.000, .039] |Recall / Instruction:LearningMode: *F*(1, 176) = 0.50, Holm-adjusted *p* = .962, eta_p2 = .003, 95% CI [.000, .039]      |\n|Recognition |Instruction              |  1|         176|85.20   |< .001     |.326    |[.220, .425] |Recognition / Instruction: *F*(1, 176) = 85.20, Holm-adjusted *p* < .001, eta_p2 = .326, 95% CI [.220, .425]             |\n|Recognition |LearningMode             |  1|         176|5.00    |= .080     |.028    |[.000, .091] |Recognition / LearningMode: *F*(1, 176) = 5.00, Holm-adjusted *p* = .080, eta_p2 = .028, 95% CI [.000, .091]             |\n|Recognition |Instruction:LearningMode |  1|         176|0.42    |= .962     |.002    |[.000, .037] |Recognition / Instruction:LearningMode: *F*(1, 176) = 0.42, Holm-adjusted *p* = .962, eta_p2 = .002, 95% CI [.000, .037] |\n\n\n:::\n:::\n\n\n### 査読者チェックリスト\n\n1. **前提チェックの報告**: MVN（HZ検定）と Box's M の結果を記載したか\n2. **検定統計量**: Pillai を主報告し、他の統計量は補足として併記したか\n3. **DDA の報告**: 判別関数の構造係数と分散説明割合を報告したか\n4. **分類精度**: LOOCV精度をチャンス水準と比較し、95% CI を付けたか\n5. **効果量**: 偏η² を 95% CI 付きで報告したか\n6. **多重性調整**: 追跡ANOVAに Holm 補正を適用し、補正前後の p 値を併記したか\n7. **HEプロット**: 視覚的に群分離を示したか\n8. **検定力**: 事前のサンプルサイズ計画、感度分析、または次回研究の必要Nを記載したか\n9. **ソフトウェア**: 使用したR パッケージとバージョンを明記したか\n\n:::\n\n### APA 7 最低限の表記ルール\n\n- 統計記号はイタリック: *V*, *F*, *p*, $\\eta^2_p$\n- Pillai's trace は *V* = .41 のように先頭ゼロなしで表記\n- *p* 値は `p = .032`、非常に小さい場合は `p < .001`\n- 効果量は $\\eta^2_p$ = .326, 95% CI [.220, .425] のようにCI付きで表記\n- 分類精度は % で報告し、チャンス水準と比較\n\n### コピペ用の実データ連動文\n\n**Method**: \"A two-way MANOVA was conducted with Instruction and LearningMode as independent variables and Recall and Recognition as dependent variables. Pillai's trace was the primary test statistic. DDA was used to summarize four-cell group separation.\"\n\n\n```{.r .cell-code}\ninstruction_sentence <- apa_manova_tbl |>\n  dplyr::filter(Effect == \"Instruction\") |>\n  dplyr::pull(APA_Result)\n\ncat(\n  '**Results**: \"',\n  instruction_sentence,\n  '. DDA structure coefficients indicated how each DV contributed to four-cell group separation (',\n  paste(structure_ld1_tbl$Report, collapse = \"; \"),\n  ').\"',\n  sep = \"\"\n)\n```\n\n**Results**: \"Instruction: *V* = .41, *F*(2, 175) = 59.97, *p* < .001. DDA structure coefficients indicated how each DV contributed to four-cell group separation (Recall *r_s* = .87; Recognition *r_s* = .89).\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlargest_eta <- eta_tbl |>\n  slice_max(Eta2_partial, n = 1, with_ties = FALSE)\n\nsummary_tbl <- tibble(\n  Component = c(\n    \"Primary multivariate test (Pillai)\",\n    \"Best univariate effect size\",\n    \"LD1 proportion of trace\",\n    \"LDA overall accuracy\",\n    \"QDA overall accuracy\",\n    \"Chance level\"\n  ),\n  Result = c(\n    {\n      tr_row <- pillai_focus |>\n        dplyr::filter(Effect == \"Instruction\")\n      if (nrow(tr_row) == 1) {\n        paste0(\"Instruction: F=\", round(tr_row$Approx_F, 2), \", \", tr_row$p_label)\n      } else {\n        \"Instruction row not found\"\n      }\n    },\n    paste0(\n      largest_eta$Outcome, \" / \", largest_eta$Parameter,\n      \": eta_p2 = \", round(largest_eta$Eta2_partial, 3)\n    ),\n    paste0(round(prop_trace_tbl$Proportion[1] * 100, 1), \"%\"),\n    paste0(round(lda_overall * 100, 1), \"%\"),\n    paste0(round(qda_overall * 100, 1), \"%\"),\n    paste0(round(chance_level * 100, 1), \"%\")\n  )\n)\n\nsummary_tbl |>\n    mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(caption = \"章の要約（chapter summary）: 報告に使う主要数値\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 章の要約（chapter summary）: 報告に使う主要数値\n\n|Component                          |Result                                    |\n|:----------------------------------|:-----------------------------------------|\n|Primary multivariate test (Pillai) |Instruction: F=59.97, p < .001            |\n|Best univariate effect size        |Recognition / Instruction: eta_p2 = 0.326 |\n|LD1 proportion of trace            |98.8%                                     |\n|LDA overall accuracy               |38.9%                                     |\n|QDA overall accuracy               |40.6%                                     |\n|Chance level                       |25%                                       |\n\n\n:::\n:::\n\n\n## まとめ\n\n\n1. **MANOVAは、複数DVを同時に扱う**ことで、単変量ANOVAの反復より整合的な推論を提供する [@warne2014]。DV間の相関構造を考慮できることが本質的な強みであり、.30-.70 程度は扱いやすい経験的範囲として考える [@tabachnick2019]。\n\n2. **H行列とE行列**がMANOVAの基盤であり、HEプロット [@friendly2007] によりその関係を直感的に把握できる。H楕円がE楕円を超える方向が、有意な群差の方向を示す（Royの最大根と幾何学的に対応）。\n\n3. **Pillai のトレース**を主報告とする。Olson [-@olson1974] のモンテカルロ研究で、正規性違反・共分散不等質性・群サイズ不均衡の全条件を通じて最も頑健であることが確認されている。\n\n4. **DDA（判別分析）はMANOVAの多変量構造を説明する追跡法**である。構造係数（$|r_s| \\geq .30$ を基準; @tabachnick2019; @sherry2005）により、各DVの群分離への寄与を安定的に評価できる。本章のLDAは4セル全体の分離を記述する分析であり、各主効果・交互作用の追跡とは区別する。\n\n5. **分類精度**（LOOCV; @psu505_lesson10）をチャンス水準や置換チェックと比較することで、「統計的に有意かどうか」だけでなく「実務的にどの程度群を分離できるか」を補助的に示す。\n\n6. **検定力分析** [@zhang2018] は、研究の事前計画、感度分析、次回研究の必要サンプルサイズを定量化するために使う。観測後の事後検定力を結論の根拠にしない。\n\n7. **報告では**、p値だけでなく Pillai のトレース、構造係数、分類精度（チャンス比較）、単変量効果量とその信頼区間、研究計画上の検定力を併記する。\n\n## 次に読む章\n\nここまでお疲れさまでした。本章では複数 DV を同時に扱う MANOVA、判別分析(LDA / QDA)、構造係数、HE プロット、検定力分析、報告テンプレートまで一通り辿ってきました。**「DV 間の共分散構造を考慮した群差推論」**という発想は、後続の混合効果モデル(第6章)・SEM(第9章)・予測モデル(第8章)にも繋がります。\n\n研究質問に応じて、次のステップとしては以下の章が候補になります。\n\n- **単一DVに戻して予測変数・交互作用を深く読む場合**: 第4章の重回帰分析と交互作用で、係数、単純傾斜、可視化を確認する。\n- **同じ参加者・同じ項目を繰り返し測っている場合**: 本章の between-subjects MANOVA ではなく、第6章の混合効果モデルで参加者・項目の依存性を明示する。\n- **複数DVの背後に潜在構成概念を想定する場合**: 第9章の因子分析・SEMで、観測変数のまとまりを測定モデルとして確認する。\n- **群差ではなく予測性能を主目的にする場合**: 第8章で ROC-AUC、PR-AUC、閾値、キャリブレーションを確認する。\n- **指導法の効果を因果的に主張したい場合**: 第18章で estimand、DAG、識別仮定、感度分析を整理する。\n\n## 参考Webリソース（再学習用）\n\n::: {.panel-tabset}\n\n### MANOVAの基礎\n\n- Warne (2014): MANOVAの設計と解釈の実務ガイド [@warne2014]\n- Penn State STAT 505 Lesson 8: One-Way MANOVA [@psu505_lesson08]\n- R Documentation: `manova` [@r_manova_doc]\n- R Documentation: `summary.manova` [@r_summary_manova]\n\n### DDA（判別分析）を深めたい\n\n- Smith et al. (2020): MANOVAの多変量追跡法としてのDDA [@smith2020]\n- Sherry & Henson (2005): 構造係数の解釈 [@sherry2005]\n- Penn State STAT 505 Lesson 10: Discriminant Analysis [@psu505_lesson10]\n- R Documentation: `MASS::lda` / `MASS::qda` [@mass_lda_doc; @mass_qda_doc]\n\n### HEプロット・可視化\n\n- Friendly (2007): HEプロットの理論と実装 [@friendly2007]\n- `heplots` パッケージ: MANOVA可視化\n- `candisc` パッケージ: 正準判別分析の可視化 [@friendly2021candisc]\n\n### 教科書的参照\n\n- Tabachnick & Fidell (2019): 多変量統計の標準的教科書 [@tabachnick2019]\n- Stevens (2009): 社会科学向け応用多変量統計 [@stevens2009]\n- Huberty & Olejnik (2006): Applied MANOVA and Discriminant Analysis [@huberty2006]\n\n:::\n\n## 参考文献 {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}