{
  "hash": "95023670b1ca918f3fe875e1154fd33e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MANOVA・判別分析\"\nauthor: \"小室竜也\"\ndate: today\nbibliography:\n  - references_manova_discriminant.bib\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    toc-title: \"目次\"\n    number-sections: true\n    code-fold: show\n    theme: journal\n    fontsize: 1.1em\n    linestretch: 1.8\n    mainfont: \"Noto Serif JP\"\nlang: ja\n---\n\n```{=html}\n<style>\n/* journalテーマ用のアカデミックなカスタムスタイル */\nbody {\n  font-family: 'Noto Serif JP', 'Times New Roman', serif;\n  color: #2c3e50;\n  line-height: 1.8;\n}\n\n/* タイトルブロックをジャーナル風に */\n.quarto-title-banner {\n  background: linear-gradient(180deg, #f8f9fa 0%, #e9ecef 100%);\n  border-bottom: 4px double #495057;\n  padding: 2.5em 2em;\n  text-align: center;\n}\n\n.quarto-title-banner .title {\n  color: #212529 !important;\n  font-size: 2.2em !important;\n  font-weight: 700;\n  letter-spacing: 0.02em;\n  text-transform: uppercase;\n  font-family: 'Noto Sans JP', sans-serif;\n}\n\n/* 見出しのアカデミックスタイル */\nh1 {\n  font-size: 1.8em;\n  font-weight: 700;\n  color: #1a1a1a;\n  border-bottom: 2px solid #212529;\n  padding-bottom: 0.5em;\n  margin-top: 2em;\n  margin-bottom: 1em;\n  text-transform: uppercase;\n  letter-spacing: 0.03em;\n}\n\nh2 {\n  font-size: 1.4em;\n  font-weight: 600;\n  color: #343a40;\n  margin-top: 1.5em;\n  margin-bottom: 0.8em;\n}\n\nh2:before {\n  content: \"§\";\n  margin-right: 0.5em;\n  color: #6c757d;\n  font-weight: 400;\n}\n\nh3 {\n  font-size: 1.2em;\n  font-weight: 600;\n  color: #495057;\n  font-style: italic;\n  margin-top: 1.2em;\n  margin-bottom: 0.6em;\n}\n\n/* テーブルを学術論文風に */\ntable {\n  margin: 2em auto;\n  border-collapse: collapse;\n  font-size: 0.95em;\n  width: 90%;\n  border-top: 2px solid #212529;\n  border-bottom: 2px solid #212529;\n}\n\nthead {\n  background: #f8f9fa;\n  border-bottom: 1px solid #212529;\n}\n\n/* コードブロックをシンプルに */\npre {\n  background: #f8f9fa !important;\n  border: 1px solid #dee2e6;\n  border-radius: 0;\n  padding: 1em;\n  font-size: 0.9em;\n}\n\n/* 数式を強調 */\n.math {\n  color: #212529;\n  font-size: 1.05em;\n  font-style: italic;\n}\n</style>\n```\n\n# パッケージの読み込み\n\nここでは、本章で必要なパッケージを一括で読み込みます。`heplots` はMANOVAのH行列とE行列を楕円として可視化するためのパッケージ、`candisc` は正準判別分析のプロットに使用します。`WebPower` はMANOVAの検定力分析に使います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) install.packages(\"pacman\")\n\npacman::p_load(\n  tidyverse,\n  MASS,\n  MVN,\n  biotools,\n  effectsize,\n  emmeans,\n  gt,\n  GGally,\n  broom,\n  patchwork,\n  heplots,\n  candisc,\n  WebPower\n)\n\nset.seed(123)\ntheme_set(theme_bw())\n```\n:::\n\n\n# はじめに\n\n本章は、**英語語彙学習研究**を想定して、2つの従属変数（`Recall`, `Recognition`）を同時に扱う **MANOVA（多変量分散分析）** と、群の分離構造を評価する **判別分析（DDA / LDA / QDA）** を、「実装できる」だけでなく「論文結果節として説明できる」水準まで整理します。\n\n回帰分析の既習者向けに、以下の対応関係を明示して進めます。\n\n- **単回帰・重回帰**: 1つの従属変数に対する線形モデル\n- **MANOVA**: 複数の従属変数を**同時に**扱う多変量線形モデル\n- **判別分析（DDA）**: MANOVAの追跡法として、群分離の方向と構造を明らかにする\n\n::: {.callout-tip}\n## この章の到達目標\n\n- MANOVAの前提を、設計上の論点と統計検定の論点に分けて説明できる。\n- H行列とE行列の意味を直感的に説明し、HEプロットを読むことができる。\n- Pillai / Wilks / Hotelling-Lawley / Roy の読み分けと選択根拠を説明できる。\n- DDA（判別分析）をMANOVAの主要追跡法として実装・解釈できる。\n- 構造係数（structure coefficients）を用いてDVの寄与を評価できる。\n- 有意性だけでなく、効果量・分類性能・検定力まで一貫して報告できる。\n- `WebPower` を用いた検定力分析でサンプルサイズ計画ができる。\n:::\n\n## なぜ個別ANOVAの繰り返しではだめなのか\n\n従属変数が複数ある場合、「DVごとにANOVAを繰り返す」アプローチをとりたくなるかもしれません。しかし、このアプローチには2つの根本的な問題があります。\n\n1. **Type Iエラーの膨張**: DV が $p$ 個あれば、各 $\\alpha = .05$ で検定を繰り返すと、族全体での偽陽性率は $1 - (1 - .05)^p$ に膨張します。$p = 2$ でも 9.75%、$p = 5$ なら 22.6% に達します。Smith et al. [-@smith2020] は英才教育研究の56本を体系的にレビューし、ほぼすべての論文がMANOVA後に単変量ANOVAのみで追跡しており、Type Iエラー率が最大76%に達しうるケースがあったと報告しています。\n\n2. **DV間の相関構造の無視**: 個別ANOVAは各DVを独立に扱うため、DV間の共変動パターンに埋め込まれた群差を検出できません。MANOVAが有意でも、すべてのANOVAが非有意になるケースは珍しくありません。Warne [-@warne2014] はMANOVAの58本の実証論文をレビューし、「MANOVAを実施しながらも追跡分析で多変量構造を適切に考慮した論文はほとんどない」と指摘しています。\n\n::: {.callout-important}\n### 「MANOVA = 同時ANOVA」という誤解\n\nMANOVAは単にANOVAを同時に実行するものではありません。MANOVAは**DV間の共分散構造を考慮した上で群差を検定**します。これは、H行列（群間変動）とE行列（群内変動）の相対的な大きさを多変量的に評価するものであり、個別ANOVAにはこの情報がありません [@warne2014; @huberty2006]。Huberty & Olejnik [-@huberty2006] は、MANOVAの本質を「DVの最適な重み付け線形結合に対する検定」と定義しており、これは個別ANOVAでは原理的にアクセスできない情報です。\n:::\n\nでは、MANOVAが常に最善かというと、DV間の相関の程度によって判断が変わります。\n\n| DV間相関の範囲 | MANOVAへの適合性 | 推奨 |\n|:---:|:---|:---|\n| .00 -- .30 | DVがほぼ独立。MANOVAの付加価値は小さい | 個別ANOVAでも可（Bonferroni補正付き） |\n| **.30 -- .70** | **理想的。MANOVAが最も有効に機能する** | **MANOVA推奨** |\n| .70 以上 | 多重共線性の懸念。推定が不安定になりうる | DVの統合・再検討を検討 |\n\n: DV間相関とMANOVAの適合性 {.striped}\n\n## 回帰分析との接続\n\n行列表記では、MANOVAは\n\n$$\n\\mathbf{Y} = \\mathbf{X}\\mathbf{B} + \\mathbf{E}\n$$\n\nと書けます。ここで、$\\mathbf{Y}$ は $n \\times p$ の従属変数行列（$p$ 個のDVを列に持つ）、$\\mathbf{X}$ は計画行列、$\\mathbf{B}$ は係数行列、$\\mathbf{E}$ は誤差行列です。つまり「回帰式を同時に推定し、**誤差の共分散構造も含めて**効果を検定する」という理解が、回帰既習者には最も自然です [@warne2014; @huberty2006]。\n\n## H行列とE行列: MANOVAの核心\n\nMANOVAを理解する鍵は、**H行列**（Hypothesis SSCP）と**E行列**（Error SSCP）の関係です [@huberty2006; @psu505_lesson08]。これは、単変量ANOVAにおける群間平方和（$SS_B$）と群内平方和（$SS_W$）の多変量版です。Warne [-@warne2014] はMANOVAの理解において「H行列とE行列の比が全統計量の基盤であることを把握することが最も重要」と述べています。\n\n| 単変量ANOVA | MANOVA | 意味 |\n|:---:|:---:|:---|\n| $SS_B$（群間平方和） | **H行列**（Hypothesis SSCP） | 群平均の散らばり（効果の大きさ） |\n| $SS_W$（群内平方和） | **E行列**（Error SSCP） | 群内のばらつき（ノイズ） |\n| $F = SS_B / SS_W$ | $\\mathbf{H}\\mathbf{E}^{-1}$ の固有値 | 効果がノイズに比べてどれだけ大きいか |\n\n: ANOVAとMANOVAの対応関係 {.striped}\n\n単変量ANOVAでは $F$ 値が1つだけですが、MANOVAでは $\\mathbf{H}\\mathbf{E}^{-1}$ の**固有値**が $s = \\min(p, k-1)$ 個（$p$ = DV数、$k$ = 群数）得られます。各固有値 $\\lambda_i$ は、多変量空間における群分離の「次元」ごとの大きさを表します。\n\n::: {.callout-note}\n### 固有値の直感的理解\n\n固有値 $\\lambda_i$ は「$i$ 番目に重要な群分離の方向で、群差がノイズの何倍あるか」を示します。\n\n- $\\lambda_1$ が大きく $\\lambda_2$ が小さければ、群分離はほぼ1次元で説明できます。\n- 複数の $\\lambda_i$ が大きければ、群分離は多次元的です。\n- 4つの検定統計量（Pillai, Wilks, Hotelling-Lawley, Roy）は、これらの固有値を**異なる方法で要約**したものです。\n:::\n\n## 4つの検定統計量の比較\n\n4つの検定統計量はいずれもH行列とE行列の関係を要約しますが、要約の仕方が異なります [@olson1974; @r_summary_manova; @psu505_lesson08]。\n\n| 統計量 | 数式の直感 | 有意の方向 | 頑健性 | 推奨場面 |\n|:---|:---|:---:|:---:|:---|\n| **Pillai's Trace** | $\\sum \\frac{\\lambda_i}{1 + \\lambda_i}$ | 大きい = 効果大 | **最も頑健** | **デフォルト推奨** |\n| Wilks' $\\Lambda$ | $\\prod \\frac{1}{1 + \\lambda_i}$ | 小さい = 効果大 | 中程度 | 等共分散・大標本 |\n| Hotelling-Lawley | $\\sum \\lambda_i$ | 大きい = 効果大 | 中程度 | 等共分散・大標本 |\n| Roy's Largest Root | $\\max(\\lambda_i)$ | 大きい = 効果大 | **最も脆弱** | **非推奨** |\n\n: 4つのMANOVA検定統計量の比較 [@olson1974; @psu505_lesson08] {.striped}\n\nOlson [-@olson1974] は6つの多変量検定統計量をモンテカルロ・シミュレーションで比較し、以下の実務的な結論を導いています。\n\n- **正規性違反のみ**の場合: すべての統計量が比較的頑健であり、結果は大きく変わらない。\n- **共分散行列の不等質性（等共分散の違反）**: Pillai のトレースが最も頑健。Wilks や Hotelling-Lawley は保守的になりすぎるか自由主義的になるリスクがある。\n- **不等質性 + サンプルサイズの不均衡**: 最も実務的に危険な条件。このとき、Pillai のみが名義 $\\alpha$ 水準を比較的よく維持する。\n- **Roy の最大根**: F近似が上界に過ぎないため、すべての条件で最も Type I エラー率が高く、群数が多い場合やDV数が多い場合に特に問題が大きい。\n\nPenn State STAT 505 [-@psu505_lesson08] も同様に、実務でまず確認すべきはPillaiであると明記しています。R の `summary.manova()` のデフォルトがPillaiであるのもこの根拠に基づいています [@r_summary_manova]。\n\n::: {.callout-important}\n### Roy's Largest Root は実務では非推奨\n\nRoy の最大根は最大の固有値のみに基づくため、多変量的な群差の全体像を反映しません。さらに、F近似が上界に過ぎないため、Type Iエラーが膨張しやすいことが知られています。Olson [-@olson1974] のモンテカルロ研究では、正規性・等共分散の両方が違反し、かつ群サイズが不均衡な条件で、Roy のType Iエラー率が名義水準の2倍以上に達する場合があることが示されています。本章では **Pillai を主報告**とし、他の統計量は一貫性確認のために併記します。\n:::\n\n## MANOVAとDDA（判別分析）の関係\n\nMANOVAと判別分析は、同じ数学的構造の「表と裏」です [@finch2013; @huberty2006]。\n\n- **MANOVA**: 「群間に多変量的な差があるか？」を検定する（有意性の判定）\n- **DDA（Descriptive Discriminant Analysis）**: 「どのDVが、どの方向に群分離に寄与しているか？」を明らかにする（効果の解釈）\n\n両者はともに $\\mathbf{H}\\mathbf{E}^{-1}$ の固有値分解に基づきますが、MANOVAは固有値の大きさを検定し、DDAは対応する固有ベクトル（＝判別関数の係数）を解釈します。このため、**DDAはMANOVAの最も自然な追跡法**であり、単変量ANOVAよりも理論的に一貫した追跡分析を提供します [@smith2020; @sherry2005]。\n\nにもかかわらず、実証研究の実態はDDAの使用率が極めて低いことを示しています。\n\n- **Warne [-@warne2014]** はMANOVAを用いた58本の実証論文をレビューし、DDAを追跡法として適切に使用した論文は**1本もなかった**と報告しています。ほぼすべてが単変量ANOVAのみで追跡しており、多変量構造の解釈が放棄されていました。\n- **Smith et al. [-@smith2020]** は英才教育研究の56本をレビューし、同様の傾向を確認しています。さらに、DDAを使用しないことでType Iエラーが深刻に膨張するリスクを定量的に示しました。\n- **Finch & French [-@finch2013]** は、DDAの判別関数がMANOVAの検定統計量と数学的に同一の情報源（$\\mathbf{H}\\mathbf{E}^{-1}$ の固有値・固有ベクトル）に基づくことを示し、追跡法としての理論的一貫性を強調しています。\n\n本章では、これらのレビューの知見を踏まえ、**DDAを主要追跡法として一貫して使用する**方針を採ります。\n\n::: {.callout-note}\n### 本章の分析デザイン上の前提\n\nここでは、**群間（between-subjects）設計**として説明します。同一参加者の反復測定や項目反復を主対象にする場合は、混合効果モデル（第6章）に接続する方が妥当です。\n:::\n\n::: {.callout-warning}\n### 重要: 本章は「反復測定データ」には適用しない\n\n- 本章のデータ構造は **1参加者1行** を前提にしています。\n- 同一参加者を複数時点で追跡したデータ（within-subjects）に、そのまま本章のMANOVA/判別分析を当てると、独立性仮定を損ねる可能性があります。\n- 反復測定デザインでは、反復測定MANOVAまたは混合効果モデルを優先してください。\n:::\n\n## 統計チュートリアル文献との接続\n\n::: {.callout-note collapse=\"true\"}\n### 主要ソースの要点（クリックで展開）\n\n本章は以下の文献を統合しています。\n\n**MANOVAの設計と解釈**\n\n- **Warne [-@warne2014]**: MANOVAの実証論文58本をレビュー。DDAを追跡に使った論文は0本。推奨手順は「(1) 前提確認 → (2) 多変量検定 → (3) 効果量 → (4) DDAによる追跡」の4段階。\n- **Penn State STAT 505 [-@psu505_lesson08]**: 4統計量はH行列とE行列の比を異なる視点で要約するもの。フローは「前提確認→MANOVA→追跡」。各統計量の数式的導出も掲載。\n\n**検定統計量の頑健性**\n\n- **Olson [-@olson1974]**: モンテカルロ・シミュレーションで6統計量を比較。正規性違反・共分散不等質性・群サイズ不均衡の3条件を組み合わせた結果、Pillaiが最も名義 $\\alpha$ 水準を維持。Royは全条件で最も脆弱。\n- **R公式ドキュメント [-@r_summary_manova]**: `summary.manova()` でPillaiがデフォルト。\n\n**前提チェック**\n\n- **Korkmaz et al. [-@korkmaz2014]**: MVNパッケージ。HZ検定はアフィン変換不変で、次元数と標本サイズに依存しにくい。Mardia の歪度・尖度検定やRoyston検定も提供。\n- **Tabachnick & Fidell [-@tabachnick2019]**: Box's M は過敏であるため $p < .001$ を実務基準とする。DV間相関が .90 を超える場合は多重共線性を疑い、DV の統合を検討。\n\n**判別分析（DDA）**\n\n- **Smith et al. [-@smith2020]**: 英才教育研究56本をレビュー。ほぼ全論文が単変量ANOVAのみで追跡。Type Iエラー率は最大76%に達しうることをシミュレーションで示す。DDAの使用を強く推奨。\n- **Sherry & Henson [-@sherry2005]**: 構造係数の解釈基準（$|r_s| \\geq .30$ で実質的寄与）。標準化係数は多重共線性に敏感であるため、構造係数を優先すべきことを具体例で示す。\n- **Finch & French [-@finch2013]**: DDAとMANOVAが数学的に同一の固有値分解に基づくことの厳密な証明。DVが5個以上の場合でもDDAが安定していることを示す。\n- **Penn State STAT 505 [-@psu505_lesson10]**: 7段階の判別分析手順を提示。(1) 前提確認 → (2) 判別関数推定 → (3) 有意性検定 → (4) 構造係数 → (5) 分類規則 → (6) LOOCV → (7) 結果の解釈。\n\n**HEプロット**\n\n- **Friendly [-@friendly2007]**: H行列とE行列を楕円として可視化する方法論。H楕円がE楕円からはみ出す方向が、Roy の最大根の検定で有意な方向と対応するという幾何学的解釈を提供。\n\n**教科書的参照**\n\n- **Tabachnick & Fidell [-@tabachnick2019]**: 各群のN > DV数が最低条件。構造係数 $|r_s| \\geq .30$ を実質的寄与の閾値とする。DV間相関の適正範囲は .30-.70。\n- **Stevens [-@stevens2009]**: 社会科学向け。検定力の観点から、各群20名以上を推奨。効果量小（$f = .10$）の検出には各群50名以上が必要。\n- **Hahs-Vaughn [-@hahs2017]**: MANOVA の前提条件を段階的に解説。初学者向けの判断フローチャートを提供。\n:::\n\n## 分析の全体像（フローチャート）\n\n本章の分析パイプラインは以下の順で進みます。\n\n```{mermaid}\nflowchart LR\n    A[\"1. 前提確認<br/>MVN・Box's M\"] --> B[\"2. MANOVA<br/>Pillai主報告\"]\n    B --> C[\"3. HEプロット<br/>H/E行列の可視化\"]\n    C --> D[\"4. DDA<br/>（主要追跡）\"]\n    D --> E[\"5. 単変量ANOVA<br/>（補助的追跡）\"]\n    E --> F[\"6. 効果量・分類精度<br/>検定力分析\"]\n    F --> G[\"7. 報告<br/>APA準拠\"]\n\n    style A fill:#e8f4fd\n    style B fill:#fff3cd\n    style C fill:#fff3cd\n    style D fill:#fff3cd\n    style G fill:#d4edda\n```\n\nまた、MANOVAを使うべきかどうかの判断は以下のフローで行います。\n\n```{mermaid}\nflowchart TD\n    A[\"研究の問い:<br/>複数DVに群差があるか?\"] --> B{\"DVは2つ以上か?\"}\n    B -->|\"No\"| C[\"ANOVA / t検定<br/>（1つのDVで十分）\"]\n    B -->|\"Yes\"| D{\"DV間に中程度の<br/>相関 (.30-.70)<br/>があるか?\"}\n    D -->|\"No (.00-.30)\"| E[\"個別ANOVAで十分<br/>MANOVAの付加価値は小さい\"]\n    D -->|\"Yes\"| F[\"MANOVAを実施\"]\n    D -->|\"高すぎる (>.70)\"| G[\"多重共線性の問題<br/>DVの再検討が必要\"]\n    F --> H{\"Pillai有意?\"}\n    H -->|\"Yes\"| I[\"追跡分析へ<br/>（DDA優先、ANOVA補助）\"]\n    H -->|\"No\"| J[\"検定力を確認<br/>N不足の可能性\"]\n\n    style A fill:#e8f4fd\n    style F fill:#fff3cd\n    style I fill:#d4edda\n    style J fill:#fff3cd\n```\n\n# 分析課題とフロー\n\n想定する研究課題は次の2点です。\n\n1. `Treatment`（Glossing vs Writing）と`Time`（Immediate vs Delayed）は、`Recall`と`Recognition`の**組**に影響するか。\n2. 4群（Treatment×Time）は、`Recall`と`Recognition`でどの程度判別できるか。\n\n分析フローは以下の順で進めます。\n\n1. データ設計と記述統計\n2. 前提チェック（独立性、多変量正規性、共分散等質性）\n3. MANOVA（4統計量を併記、主報告はPillai）\n4. HEプロット（H行列とE行列の可視化）\n5. DDA（判別分析を主要追跡法として）\n6. 単変量追跡分析（補助的、多重性調整つき）\n7. 検定力分析\n8. 論文結果節向けの要約\n\n::: {.callout-tip}\n## 初回読者向けの最短ルート（20分）\n\n1. HEプロットで群分離の全体像を視覚的に把握する。\n2. MANOVA統計量表のPillai列だけを読む。\n3. DDAの構造係数で、どのDVが群分離に寄与しているかを確認する。\n4. 最後の結果記述テンプレートを自分のデータに置き換える。\n:::\n\n# データ作成（語彙学習研究を想定）\n\nここでは、2（Treatment: Glossing vs Writing）× 2（Time: Immediate vs Delayed）の4群・各群45名のシミュレーションデータを作成します。`Recall` と `Recognition` には中程度の相関（$r \\approx .40$）を持たせます。この相関水準は、MANOVAが最も有効に機能する範囲（.30-.70）内です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_per_group <- 45\n\nmu_tbl <- tibble(\n  Group = c(\n    \"Glossing_Immediate\",\n    \"Glossing_Delayed\",\n    \"Writing_Immediate\",\n    \"Writing_Delayed\"\n  ),\n  Recall_mu = c(12, 10, 16, 14),\n  Recognition_mu = c(18, 16, 23, 21)\n)\n\n# 2つの従属変数の共分散（中程度の相関を想定）\nSigma <- matrix(\n  c(16, 6,\n    6, 20),\n  nrow = 2,\n  byrow = TRUE\n)\n\nsimulated <- mu_tbl |>\n  mutate(\n    sim = purrr::map2(\n      Recall_mu,\n      Recognition_mu,\n      ~ MASS::mvrnorm(\n          n = n_per_group,\n          mu = c(.x, .y),\n          Sigma = Sigma\n        ) |>\n        as_tibble(.name_repair = \"minimal\") |>\n        setNames(c(\"Recall\", \"Recognition\"))\n    )\n  ) |>\n  dplyr::select(Group, sim) |>\n  tidyr::unnest(sim) |>\n  mutate(\n    Treatment = if_else(str_detect(Group, \"^Glossing\"), \"Glossing\", \"Writing\"),\n    Time = if_else(str_detect(Group, \"Immediate$\"), \"Immediate\", \"Delayed\"),\n    ID = row_number(),\n    Recall = pmin(pmax(Recall, 0), 30),\n    Recognition = pmin(pmax(Recognition, 0), 30)\n  ) |>\n  mutate(across(c(Treatment, Time, Group), as.factor)) |>\n  dplyr::select(ID, Treatment, Time, Group, Recall, Recognition)\n\nsimulated |>\n  group_by(Treatment, Time) |>\n  summarise(\n    n = n(),\n    Recall_Mean = mean(Recall),\n    Recognition_Mean = mean(Recognition),\n    .groups = \"drop\"\n  ) |>\n  gt() |>\n  tab_header(\n    title = \"Simulated Design Overview\",\n    subtitle = \"Sample size and means by Treatment × Time\"\n  ) |>\n  fmt_number(columns = c(Recall_Mean, Recognition_Mean), decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Simulated Design Overview\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Sample size and means by Treatment × Time\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}ccrrr}\n\\toprule\nTreatment & Time & n & Recall\\_Mean & Recognition\\_Mean \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing & Delayed & 45 & 9.70 & 15.64 \\\\ \nGlossing & Immediate & 45 & 12.09 & 18.34 \\\\ \nWriting & Delayed & 45 & 14.38 & 21.71 \\\\ \nWriting & Immediate & 45 & 16.05 & 22.84 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**出力の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `n` | 各群のサンプルサイズ（45 = バランスド・デザイン） |\n| `Recall_Mean` | 再生テストの群平均。Writing 群が Glossing 群より高い傾向 |\n| `Recognition_Mean` | 再認テストの群平均。同様に Writing 群が高い傾向 |\n\n# 記述統計と可視化\n\nここでは、群ごとの記述統計量（平均・標準偏差）を算出し、プロファイルプロットで群パターンを視覚化します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndesc_tbl <- simulated |>\n  group_by(Treatment, Time) |>\n  summarise(\n    n = n(),\n    Recall_Mean = mean(Recall),\n    Recall_SD = sd(Recall),\n    Recognition_Mean = mean(Recognition),\n    Recognition_SD = sd(Recognition),\n    .groups = \"drop\"\n  )\n\ndesc_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Descriptive Statistics\",\n    subtitle = \"Dependent variables by group\"\n  ) |>\n  fmt_number(columns = c(Recall_Mean, Recall_SD, Recognition_Mean, Recognition_SD), decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Descriptive Statistics\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Dependent variables by group\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}ccrrrrr}\n\\toprule\nTreatment & Time & n & Recall\\_Mean & Recall\\_SD & Recognition\\_Mean & Recognition\\_SD \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing & Delayed & 45 & 9.70 & 4.26 & 15.64 & 3.92 \\\\ \nGlossing & Immediate & 45 & 12.09 & 3.71 & 18.34 & 4.05 \\\\ \nWriting & Delayed & 45 & 14.38 & 4.32 & 21.71 & 4.42 \\\\ \nWriting & Immediate & 45 & 16.05 & 4.07 & 22.84 & 3.68 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\np_recall <- ggplot(desc_tbl, aes(x = Time, y = Recall_Mean, group = Treatment, color = Treatment)) +\n  geom_line(linewidth = 1.1) +\n  geom_point(size = 2.8) +\n  labs(title = \"Recall\", y = \"Mean score\", x = \"Time\")\n\np_recog <- ggplot(desc_tbl, aes(x = Time, y = Recognition_Mean, group = Treatment, color = Treatment)) +\n  geom_line(linewidth = 1.1) +\n  geom_point(size = 2.8) +\n  labs(title = \"Recognition\", y = \"Mean score\", x = \"Time\")\n\np_recall + p_recog +\n  plot_annotation(\n    title = \"Profile of Group Means\",\n    subtitle = \"Treatment × Time patterns across two outcomes\"\n  )\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**プロファイルプロットの読み方**:\n\n- 2本の線（Treatment: Glossing vs Writing）がほぼ平行 → 交互作用は小さい\n- 線の上下差が大きい → Treatment 主効果が大きい\n- Immediate → Delayed の傾き → Time 主効果の方向\n\n## DV間相関の確認\n\nMANOVAを実施する前に、DV間の相関が適切な範囲（.30-.70）にあるかを確認します。Tabachnick & Fidell [-@tabachnick2019] は、DV間相関が .90 を超える場合は「深刻な多重共線性」と判断し、DVの統合または一方の除外を推奨しています。一方、相関が .30 未満の場合はDVがほぼ独立であるため、MANOVAの付加価値は小さく、個別ANOVAで十分な場合があります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_dvs <- cor(simulated[, c(\"Recall\", \"Recognition\")])\n\ntibble(\n  DV_Pair = \"Recall -- Recognition\",\n  Correlation = cor_dvs[1, 2],\n  Judgment = case_when(\n    abs(cor_dvs[1, 2]) < 0.30 ~ \"低い: 個別ANOVAでも可\",\n    abs(cor_dvs[1, 2]) <= 0.70 ~ \"適切: MANOVA推奨\",\n    TRUE ~ \"高すぎる: 多重共線性の懸念\"\n  )\n) |>\n  gt() |>\n  tab_header(\n    title = \"DV Correlation Check\",\n    subtitle = \"Confirming suitability for MANOVA\"\n  ) |>\n  fmt_number(columns = Correlation, decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  DV Correlation Check\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Confirming suitability for MANOVA\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrl}\n\\toprule\nDV\\_Pair & Correlation & Judgment \\\\ \n\\midrule\\addlinespace[2.5pt]\nRecall -- Recognition & 0.524 & 適切: MANOVA推奨 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGGally::ggpairs(\n  simulated,\n  columns = c(\"Recall\", \"Recognition\"),\n  mapping = aes(color = Group, alpha = 0.6),\n  title = \"Bivariate Structure by Group\"\n)\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# MANOVAの前提\n\n## 独立性（設計で担保する前提）\n\n独立性は、検定結果だけで担保するよりも、**研究計画段階（割り付け・測定手順）で保証する**ことが原則です。ここでは「1参加者1行」であることをデータ構造から確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_check <- simulated |>\n  count(ID, name = \"rows_per_id\")\n\ntable(id_check$rows_per_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1 \n180 \n```\n\n\n:::\n:::\n\n\n**出力の読み方**: すべてのIDに対して行数が1であれば、1参加者1行のデータ構造が確認できます。\n\n## 多変量正規性（群ごと）\n\nMANOVAで確認したいのは、**各群における従属変数ベクトルの多変量正規性**です。全体ではなく群ごとに検定することが重要です。なぜなら、MANOVAの仮定は「各群内の残差が多変量正規分布に従う」ことだからです。\n\n本章では Henze-Zirkler（HZ）検定を用います。HZ検定はアフィン変換に不変という望ましい性質を持ちます [@korkmaz2014]。\n\n### HZ検定をRで実施する最小コード\n\nまずは、全データを一括で検定する最小コードです（動作確認用）。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhz_overall <- MVN::mvn(\n  data = simulated |> dplyr::select(Recall, Recognition),\n  mvn_test = \"hz\",\n  tidy = TRUE\n)\n\nhz_overall$multivariate_normality |>\n  transmute(\n    Scope = \"All groups combined\",\n    Test,\n    Statistic,\n    p_value = p.value,\n    Decision = if_else(p.value < 0.05, \"MVNからの逸脱を示唆\", \"MVNを棄却せず\")\n  ) |>\n  gt() |>\n  tab_header(\n    title = \"Minimal HZ Test Example\",\n    subtitle = \"Single-step implementation in R\"\n  ) |>\n  fmt_number(columns = c(Statistic, p_value), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Minimal HZ Test Example\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Single-step implementation in R\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrl}\n\\toprule\nScope & Test & Statistic & p\\_value & Decision \\\\ \n\\midrule\\addlinespace[2.5pt]\nAll groups combined & Henze-Zirkler & 0.378 & 0.921 & MVNを棄却せず \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**`MVN::mvn()` の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Test` | 使用した検定名（Henze-Zirkler） |\n| `Statistic` | HZ検定統計量。大きいほど正規性からの逸脱が大きい |\n| `p_value` | $p < .05$ なら「MVNからの逸脱が示唆される」。ただし即中止ではない |\n\n### 群ごとのHZ検定を自動化する\n\n実務では「全体」より「群ごと」の確認が重要なので、再利用しやすい関数化を行います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_hz_test <- function(df, vars = c(\"Recall\", \"Recognition\"), alpha = 0.05) {\n  hz_out <- MVN::mvn(\n    data = df |> dplyr::select(all_of(vars)),\n    mvn_test = \"hz\",\n    tidy = TRUE\n  )\n\n  hz_out$multivariate_normality |>\n    transmute(\n      Test,\n      Statistic,\n      p_value = p.value,\n      alpha = alpha,\n      Decision = if_else(p.value < alpha, \"MVNからの逸脱を示唆\", \"MVNを棄却せず\")\n    )\n}\n\nalpha_level <- 0.05\n\nmvn_tbl <- simulated |>\n  group_by(Group) |>\n  group_modify(~ run_hz_test(.x, alpha = alpha_level)) |>\n  ungroup()\n\nmvn_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Multivariate Normality by Group\",\n    subtitle = \"Henze-Zirkler test\"\n  ) |>\n  fmt_number(columns = c(Statistic, p_value), decimals = 3) |>\n  fmt_number(columns = alpha, decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Multivariate Normality by Group\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Henze-Zirkler test\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}clrrrl}\n\\toprule\nGroup & Test & Statistic & p\\_value & alpha & Decision \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing\\_Delayed & Henze-Zirkler & 0.411 & 0.629 & 0.05 & MVNを棄却せず \\\\ \nGlossing\\_Immediate & Henze-Zirkler & 0.201 & 0.987 & 0.05 & MVNを棄却せず \\\\ \nWriting\\_Delayed & Henze-Zirkler & 0.508 & 0.407 & 0.05 & MVNを棄却せず \\\\ \nWriting\\_Immediate & Henze-Zirkler & 0.814 & 0.068 & 0.05 & MVNを棄却せず \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhz_action_tbl <- mvn_tbl |>\n  mutate(\n    Action = if_else(\n      p_value < alpha,\n      \"外れ値・分布形状を確認し、Pillai中心で慎重に解釈\",\n      \"正規性の観点では通常どおりMANOVAを実行可能\"\n    )\n  ) |>\n  dplyr::select(Group, Statistic, p_value, Decision, Action)\n\nhz_action_tbl |>\n  gt() |>\n  tab_header(\n    title = \"HZ Interpretation Guide\",\n    subtitle = \"Decision and recommended next action\"\n  ) |>\n  fmt_number(columns = c(Statistic, p_value), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  HZ Interpretation Guide\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Decision and recommended next action\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}crrll}\n\\toprule\nGroup & Statistic & p\\_value & Decision & Action \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing\\_Delayed & 0.411 & 0.629 & MVNを棄却せず & 正規性の観点では通常どおりMANOVAを実行可能 \\\\ \nGlossing\\_Immediate & 0.201 & 0.987 & MVNを棄却せず & 正規性の観点では通常どおりMANOVAを実行可能 \\\\ \nWriting\\_Delayed & 0.508 & 0.407 & MVNを棄却せず & 正規性の観点では通常どおりMANOVAを実行可能 \\\\ \nWriting\\_Immediate & 0.814 & 0.068 & MVNを棄却せず & 正規性の観点では通常どおりMANOVAを実行可能 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### HZ検定の補助: マハラノビス距離による外れ値診断\n\nHZ検定だけでは「どの群で逸脱が起きているか」が見えにくい場合があります。そこで、群ごとにマハラノビス距離を計算し、$\\chi^2_{0.975, p}$ を超える比率を確認します。マハラノビス距離は、多変量空間における「中心からの距離」であり、単変量の外れ値検出では見逃す多変量的な外れ値を検出できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise_mahal_outliers <- function(df, vars = c(\"Recall\", \"Recognition\"), cutoff_prob = 0.975) {\n  x <- df |> dplyr::select(all_of(vars)) |> as.matrix()\n  p <- ncol(x)\n  d2 <- mahalanobis(x, colMeans(x), cov(x))\n  cutoff <- qchisq(cutoff_prob, df = p)\n\n  tibble(\n    N = nrow(x),\n    p = p,\n    Cutoff = cutoff,\n    Outlier_N = sum(d2 > cutoff),\n    Outlier_Rate = mean(d2 > cutoff)\n  )\n}\n\nmahal_tbl <- simulated |>\n  group_by(Group) |>\n  group_modify(~ summarise_mahal_outliers(.x)) |>\n  ungroup()\n\nmahal_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Mahalanobis Outlier Screening\",\n    subtitle = \"Group-wise outlier rate with chi-square cutoff (97.5%)\"\n  ) |>\n  fmt_number(columns = c(Cutoff, Outlier_Rate), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Mahalanobis Outlier Screening\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Group-wise outlier rate with chi-square cutoff (97.5\\%)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}crrrrr}\n\\toprule\nGroup & N & p & Cutoff & Outlier\\_N & Outlier\\_Rate \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing\\_Delayed & 45 & 2 & 7.378 & 0 & 0.000 \\\\ \nGlossing\\_Immediate & 45 & 2 & 7.378 & 1 & 0.022 \\\\ \nWriting\\_Delayed & 45 & 2 & 7.378 & 1 & 0.022 \\\\ \nWriting\\_Immediate & 45 & 2 & 7.378 & 0 & 0.000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**マハラノビス距離の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Cutoff` | $\\chi^2_{0.975, p=2} \\approx 7.38$。これを超える観測が多変量的外れ値の候補 |\n| `Outlier_N` | カットオフを超えた観測数 |\n| `Outlier_Rate` | 外れ値率。正規分布なら約2.5%が期待値。10%を超えると要注意 |\n\n次に、$\\chi^2$ Q-Qプロットで多変量正規性を視覚的に確認します。点が対角線に沿っていれば、マハラノビス距離が $\\chi^2$ 分布に従っている（＝多変量正規性が妥当）ことを示します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmahal_qq_tbl <- simulated |>\n  group_by(Group) |>\n  group_modify(~ {\n    x <- .x |> dplyr::select(Recall, Recognition) |> as.matrix()\n    d2 <- sort(mahalanobis(x, colMeans(x), cov(x)))\n    tibble(\n      theoretical = qchisq(ppoints(length(d2)), df = ncol(x)),\n      observed = d2\n    )\n  }) |>\n  ungroup()\n\nggplot(mahal_qq_tbl, aes(x = theoretical, y = observed)) +\n  geom_point(alpha = 0.7, size = 1.5) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\") +\n  facet_wrap(~ Group, scales = \"free\") +\n  labs(\n    title = \"Chi-square Q-Q Plot by Group\",\n    subtitle = \"Mahalanobis distances vs theoretical quantiles\",\n    x = \"Theoretical quantile\",\n    y = \"Observed Mahalanobis distance\"\n  )\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**Q-Qプロットの読み方**:\n\n- 点が対角線（破線）に沿っていれば → 多変量正規性は妥当\n- 右上で対角線から上方に逸脱 → 裾が重い（外れ値が多い）\n- 系統的なS字カーブ → 歪度の問題\n\n::: {.callout-tip}\n## HZ検定の読み方（実務まとめ）\n\n- `p >= .05`: 「MVNを棄却しない」。通常どおりMANOVAへ進む。\n- `p < .05`: 「逸脱の示唆」。即中止ではなく、外れ値確認・図示・Pillai中心報告で対応する。\n- 群ごとに判定し、どの群で逸脱が強いかを先に把握すると解釈が安定する。\n- Pillai の Trace は MVN 逸脱に最も頑健な検定統計量である [@olson1974]。\n:::\n\n### 前提チェックを一括実行する関数\n\n以下の関数は他章でも再利用できます。`dv` と `group` を変えるだけで同じ流れを適用できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_manova_assumptions <- function(\n  data,\n  dv,\n  group,\n  id = NULL,\n  alpha = 0.05,\n  box_alpha = 0.001,\n  cutoff_prob = 0.975\n) {\n  group_sym <- rlang::sym(group)\n\n  hz <- data |>\n    group_by(!!group_sym) |>\n    group_modify(~ run_hz_test(.x, vars = dv, alpha = alpha)) |>\n    ungroup()\n\n  mahal <- data |>\n    group_by(!!group_sym) |>\n    group_modify(~ summarise_mahal_outliers(.x, vars = dv, cutoff_prob = cutoff_prob)) |>\n    ungroup()\n\n  box <- biotools::boxM(\n    data |> dplyr::select(all_of(dv)),\n    grouping = dplyr::pull(data, !!group_sym)\n  )\n\n  id_evidence <- if (!is.null(id) && id %in% names(data)) {\n    id_counts <- data |> count(.data[[id]], name = \"rows_per_id\")\n    if (all(id_counts$rows_per_id == 1)) {\n      \"One row per participant ID\"\n    } else {\n      paste0(\"Repeated IDs detected (max rows per ID = \", max(id_counts$rows_per_id), \")\")\n    }\n  } else {\n    \"No ID variable supplied (design-based judgment required)\"\n  }\n\n  summary <- tibble(\n    Assumption = c(\n      \"Independence\",\n      \"Multivariate normality (HZ)\",\n      \"Mahalanobis outlier burden\",\n      \"Homogeneity of covariance (Box's M)\"\n    ),\n    Evidence = c(\n      id_evidence,\n      paste0(sum(hz$p_value < alpha), \" / \", nrow(hz), \" groups flagged\"),\n      paste0(sum(mahal$Outlier_N), \" flagged obs across groups\"),\n      paste0(\"p = \", signif(box$p.value, 4))\n    ),\n    Practical_Decision = c(\n      if_else(str_detect(id_evidence, \"Repeated\"), \"Re-check design / consider mixed model\", \"Proceed\"),\n      if_else(any(hz$p_value < alpha), \"Proceed with caution (Pillai-priority)\", \"Proceed\"),\n      if_else(mean(mahal$Outlier_Rate) > 0.10, \"Inspect influential cases\", \"Proceed\"),\n      if_else(box$p.value < box_alpha, \"Proceed with caution (covariance mismatch)\", \"Proceed\")\n    )\n  )\n\n  list(hz = hz, mahal = mahal, box = box, summary = summary)\n}\n\nassump_obj <- check_manova_assumptions(\n  data = simulated,\n  dv = c(\"Recall\", \"Recognition\"),\n  group = \"Group\",\n  id = \"ID\"\n)\n\nassump_obj$summary |>\n  gt() |>\n  tab_header(\n    title = \"Reusable Assumption Pipeline\",\n    subtitle = \"Single-call diagnostic summary\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Reusable Assumption Pipeline\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Single-call diagnostic summary\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lll}\n\\toprule\nAssumption & Evidence & Practical\\_Decision \\\\ \n\\midrule\\addlinespace[2.5pt]\nIndependence & One row per participant ID & Proceed \\\\ \nMultivariate normality (HZ) & 0 / 4 groups flagged & Proceed \\\\ \nMahalanobis outlier burden & 2 flagged obs across groups & Proceed \\\\ \nHomogeneity of covariance (Box's M) & p = 0.8106 & Proceed \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**一括チェック結果の読み方**:\n\n| Assumption | Proceed の条件 | 要注意の対応 |\n|:---|:---|:---|\n| Independence | 1参加者1行 | 反復あり → 混合モデルを検討 |\n| MVN (HZ) | 全群で p > .05 | フラグ群あり → Pillai優先 |\n| Outlier burden | 外れ値率 < 10% | 高い → 感度分析 |\n| Box's M | p > .001 | p < .001 → Pillai優先、群サイズの均衡を確認 |\n\n## 共分散行列の等質性（Box's M）\n\nBox's M検定は「群間で共分散行列が等しい」という帰無仮説を検定します [@box1949]。MANOVAの検定統計量（特にWilks' $\\Lambda$）は等共分散を仮定するため、この前提の確認が必要です。\n\nただし、Box's M は標本サイズに対して過敏であり、大標本では実質的に無視できる程度の違いでも有意になることがあります。このため、Tabachnick & Fidell [-@tabachnick2019] および Huberty & Olejnik [-@huberty2006] は、$p < .05$ ではなく **$p < .001$ を実務的な基準**として採用することを推奨しています。\n\nさらに、Olson [-@olson1974] のモンテカルロ研究は、等共分散の違反があっても**群サイズが均衡していればPillaiのトレースは比較的頑健**であることを示しています。最も危険なのは「共分散不等質 + 群サイズ不均衡」の組み合わせであり、この条件ではすべての検定統計量が影響を受けますが、Pillaiが最も安定しています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbox_m <- biotools::boxM(\n  simulated |>\n    dplyr::select(Recall, Recognition),\n  grouping = simulated$Group\n)\n\nbox_tbl <- tibble(\n  Test = \"Box's M\",\n  Statistic = as.numeric(box_m$statistic),\n  df = as.numeric(box_m$parameter),\n  p_value = box_m$p.value,\n  Decision = if_else(box_m$p.value < 0.001, \"共分散等質性に注意\", \"重大な逸脱は示されず\")\n)\n\nbox_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Homogeneity of Covariance Matrices\",\n    subtitle = \"Box's M test\"\n  ) |>\n  fmt_number(columns = c(Statistic, p_value), decimals = 3) |>\n  fmt_number(columns = df, decimals = 0)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Homogeneity of Covariance Matrices\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Box's M test\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrl}\n\\toprule\nTest & Statistic & df & p\\_value & Decision \\\\ \n\\midrule\\addlinespace[2.5pt]\nBox's M & 5.265 & 9 & 0.811 & 重大な逸脱は示されず \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**`Box's M` の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Statistic` | Box の M 統計量。大きいほど群間の共分散行列の差が大きい |\n| `df` | 近似 $\\chi^2$ の自由度（群数とDV数に依存） |\n| `p_value` | $p < .001$ なら共分散等質性に注意。$p < .05$ でも即問題ではない |\n| `Decision` | 判定結果。注意の場合は Pillai を優先し、群サイズの均衡を確認 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nassumption_summary <- tibble(\n  Assumption = c(\n    \"Independence (between-subject design)\",\n    \"Multivariate normality (HZ by group)\",\n    \"Homogeneity of covariance (Box's M)\"\n  ),\n  Evidence = c(\n    \"One row per participant ID\",\n    paste0(sum(mvn_tbl$p_value < alpha_level), \" / \", nrow(mvn_tbl), \" groups flagged\"),\n    paste0(\"p = \", round(box_tbl$p_value[[1]], 4))\n  ),\n  Practical_Decision = c(\n    \"Proceed (design-based check)\",\n    if_else(any(mvn_tbl$p_value < alpha_level), \"Proceed with caution (Pillai-priority)\", \"Proceed\"),\n    if_else(box_tbl$p_value[[1]] < 0.001, \"Proceed with caution (covariance mismatch)\", \"Proceed\")\n  )\n)\n\nassumption_summary |>\n  gt() |>\n  tab_header(\n    title = \"Assumption Checklist (Practical Summary)\",\n    subtitle = \"What to check before running MANOVA\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Assumption Checklist (Practical Summary)\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  What to check before running MANOVA\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lll}\n\\toprule\nAssumption & Evidence & Practical\\_Decision \\\\ \n\\midrule\\addlinespace[2.5pt]\nIndependence (between-subject design) & One row per participant ID & Proceed (design-based check) \\\\ \nMultivariate normality (HZ by group) & 0 / 4 groups flagged & Proceed \\\\ \nHomogeneity of covariance (Box's M) & p = 0.8106 & Proceed \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n# MANOVAの実行\n\n## 4つの統計量を併記して確認\n\nここでは、`manova()` 関数を用いて多変量分散分析を実行します。`cbind(Recall, Recognition)` で2つの従属変数を同時に指定し、Treatment と Time の主効果および交互作用を検定します。4つの検定統計量を併記しますが、**Pillai のトレースを主報告**とします [@olson1974; @r_summary_manova]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_manova <- manova(\n  cbind(Recall, Recognition) ~ Treatment * Time,\n  data = simulated\n)\n\nextract_manova <- function(test_name) {\n  stats <- summary(fit_manova, test = test_name)$stats\n\n  tibble(\n    Test = test_name,\n    Effect = rownames(stats),\n    Statistic = stats[, 1],\n    Approx_F = stats[, 2],\n    df1 = stats[, 3],\n    df2 = stats[, 4],\n    p_value = stats[, 5]\n  ) |>\n    filter(Effect != \"Residuals\")\n}\n\nmanova_tbl <- purrr::map_dfr(\n  c(\"Pillai\", \"Wilks\", \"Hotelling-Lawley\", \"Roy\"),\n  extract_manova\n)\n\nmanova_tbl |>\n  gt() |>\n  tab_header(\n    title = \"MANOVA Test Statistics\",\n    subtitle = \"Treatment, Time, and interaction effects\"\n  ) |>\n  fmt_number(columns = c(Statistic, Approx_F, p_value), decimals = 3) |>\n  fmt_number(columns = c(df1, df2), decimals = 0) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_body(columns = p_value, rows = p_value < 0.05)\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  MANOVA Test Statistics\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Treatment, Time, and interaction effects\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrrr}\n\\toprule\nTest & Effect & Statistic & Approx\\_F & df1 & df2 & p\\_value \\\\ \n\\midrule\\addlinespace[2.5pt]\nPillai & Treatment & 1.000 & 0.356 & 48 & 2 & 175.000 \\\\ \nPillai & Time & 1.000 & 0.083 & 8 & 2 & 175.000 \\\\ \nPillai & Treatment:Time & 1.000 & 0.010 & 1 & 2 & 175.000 \\\\ \nWilks & Treatment & 1.000 & 0.644 & 48 & 2 & 175.000 \\\\ \nWilks & Time & 1.000 & 0.917 & 8 & 2 & 175.000 \\\\ \nWilks & Treatment:Time & 1.000 & 0.990 & 1 & 2 & 175.000 \\\\ \nHotelling-Lawley & Treatment & 1.000 & 0.553 & 48 & 2 & 175.000 \\\\ \nHotelling-Lawley & Time & 1.000 & 0.091 & 8 & 2 & 175.000 \\\\ \nHotelling-Lawley & Treatment:Time & 1.000 & 0.010 & 1 & 2 & 175.000 \\\\ \nRoy & Treatment & 1.000 & 0.553 & 48 & 2 & 175.000 \\\\ \nRoy & Time & 1.000 & 0.091 & 8 & 2 & 175.000 \\\\ \nRoy & Treatment:Time & 1.000 & 0.010 & 1 & 2 & 175.000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**MANOVA出力の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Test` | 使用した検定統計量（Pillai を主報告） |\n| `Effect` | Treatment（主効果）、Time（主効果）、Treatment:Time（交互作用） |\n| `Statistic` | 検定統計量の値。Pillai は 0-1 の範囲で、1 に近いほど効果が大きい |\n| `Approx_F` | F 近似値。大きいほど効果が強い |\n| `df1, df2` | 仮説自由度と誤差自由度 |\n| `p_value` | $p < .05$ なら多変量的に有意（太字で強調） |\n\n## 主報告（Pillai）を抽出\n\n\n::: {.cell}\n\n```{.r .cell-code}\npillai_focus <- manova_tbl |>\n  filter(Test == \"Pillai\") |>\n  mutate(\n    Interpretation = if_else(p_value < 0.05, \"有意\", \"非有意\")\n  )\n\npillai_focus |>\n  gt() |>\n  tab_header(\n    title = \"Primary Inference (Pillai)\",\n    subtitle = \"Recommended primary multivariate test\"\n  ) |>\n  fmt_number(columns = c(Statistic, Approx_F, p_value), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Primary Inference (Pillai)\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Recommended primary multivariate test\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrrrl}\n\\toprule\nTest & Effect & Statistic & Approx\\_F & df1 & df2 & p\\_value & Interpretation \\\\ \n\\midrule\\addlinespace[2.5pt]\nPillai & Treatment & 1.000 & 0.356 & 48.3464261 & 2 & 175.000 & 非有意 \\\\ \nPillai & Time & 1.000 & 0.083 & 7.9484532 & 2 & 175.000 & 非有意 \\\\ \nPillai & Treatment:Time & 1.000 & 0.010 & 0.8700856 & 2 & 175.000 & 非有意 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n## 多変量効果量（Pillai のトレースに基づく $\\eta^2$）\n\nPillai のトレース自体が 0-1 の範囲をとるため、多変量効果量の指標として直接的に解釈できます。ただし、Warne [-@warne2014] の4段階手順にならい、効果量を明示的に算出して報告します。多変量 $\\eta^2$ は $\\text{Pillai} / s$（$s = \\min(p, k-1)$）で近似できます [@tabachnick2019]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 多変量効果量の算出\np_dvs <- 2  # DV数\nk_groups <- 4  # 群数（Treatment × Time）\ns_value <- min(p_dvs, k_groups - 1)\n\nmultivariate_eta2 <- pillai_focus |>\n  mutate(\n    s = s_value,\n    Multivariate_eta2 = Statistic / s,\n    Size_label = case_when(\n      Multivariate_eta2 >= 0.14 ~ \"大きい\",\n      Multivariate_eta2 >= 0.06 ~ \"中程度\",\n      Multivariate_eta2 >= 0.01 ~ \"小さい\",\n      TRUE ~ \"ほぼゼロ\"\n    )\n  ) |>\n  dplyr::select(Effect, Statistic, s, Multivariate_eta2, Size_label)\n\nmultivariate_eta2 |>\n  gt() |>\n  tab_header(\n    title = \"Multivariate Effect Size\",\n    subtitle = \"Approximate multivariate eta-squared based on Pillai's trace\"\n  ) |>\n  fmt_number(columns = c(Statistic, Multivariate_eta2), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Multivariate Effect Size\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Approximate multivariate eta-squared based on Pillai's trace\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrl}\n\\toprule\nEffect & Statistic & s & Multivariate\\_eta2 & Size\\_label \\\\ \n\\midrule\\addlinespace[2.5pt]\nTreatment & 1.000 & 2 & 0.500 & 大きい \\\\ \nTime & 1.000 & 2 & 0.500 & 大きい \\\\ \nTreatment:Time & 1.000 & 2 & 0.500 & 大きい \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**多変量 $\\eta^2$ の解釈基準**（Cohen の基準を準用）:\n\n| $\\eta^2$ | 効果の大きさ |\n|:---:|:---|\n| .01 | 小さい |\n| .06 | 中程度 |\n| .14 | 大きい |\n\n::: {.callout-important}\n### MANOVAの有意性と追跡検定のType Iエラー\n\n「MANOVAが有意なら、追跡ANOVAのType Iエラーは制御されている」と書かれることがありますが、これは**誤り**です。MANOVAの有意性は多変量空間での検定結果であり、個々のDVに対する保護効果は提供しません。追跡分析では依然として多重性調整（Holm法など）が必要です [@huberty2006]。\n\nSmith et al. [-@smith2020] は56本のレビューにより、この誤解に基づく慣行が広く定着していることを実証しました。さらに重要なことに、単変量ANOVAによる追跡は**多変量パターンを見逃す**可能性があります。Warne [-@warne2014] は58本のレビューでDDAを使った論文がゼロであったことを示し、DDAこそがMANOVAの数学的構造と整合した追跡法であると強調しています。\n:::\n\n# HEプロット: H行列とE行列の可視化\n\nHEプロットは、MANOVA のH行列（群間変動）とE行列（群内変動）を**楕円として可視化**する手法です [@friendly2007]。Friendly [-@friendly2007] はこの手法を体系的に定式化し、多変量一般線形モデルの効果を2次元散布図上で幾何学的に解釈する方法を示しました。\n\nHEプロットの核心的な読み方は次のとおりです。\n\n- **E楕円**は群内変動（誤差）の大きさと方向を表す。E楕円は全効果で共通です。\n- **H楕円**は各効果の群間変動を表す。効果ごとに1つずつ描かれます。\n- **H楕円がE楕円からはみ出す方向**は、その効果が統計的に有意な方向を示す。Friendly [-@friendly2007] はこれが**Roy の最大根の検定で有意になる方向と幾何学的に対応する**ことを証明しています。\n- H楕円がE楕円に完全に収まる場合、その効果は（少なくともその2DV平面では）有意ではない。\n\nこの幾何学的対応は、数値だけでは把握しにくい多変量的な群差のパターンを直感的に読み取ることを可能にします。\n\n## H行列とE行列の確認\n\nまず、H行列とE行列を数値で確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Treatment × Time の2要因MANOVAフィット（再利用）\nH_matrices <- summary(fit_manova)$SS\nE_matrix <- H_matrices$Residuals\nH_treatment <- H_matrices$Treatment\nH_time <- H_matrices$Time\nH_interaction <- H_matrices$`Treatment:Time`\n\n# H行列の表示\ntibble(\n  Effect = c(\"Treatment\", \"Time\", \"Interaction\"),\n  H_Recall_Recall = c(H_treatment[1,1], H_time[1,1], H_interaction[1,1]),\n  H_Recall_Recog = c(H_treatment[1,2], H_time[1,2], H_interaction[1,2]),\n  H_Recog_Recog = c(H_treatment[2,2], H_time[2,2], H_interaction[2,2])\n) |>\n  gt() |>\n  tab_header(\n    title = \"Hypothesis SSCP Matrices (H)\",\n    subtitle = \"Between-group variation for each effect\"\n  ) |>\n  fmt_number(decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Hypothesis SSCP Matrices (H)\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Between-group variation for each effect\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrr}\n\\toprule\nEffect & H\\_Recall\\_Recall & H\\_Recall\\_Recog & H\\_Recog\\_Recog \\\\ \n\\midrule\\addlinespace[2.5pt]\nTreatment & 839.60 & 1,028.10 & 1,258.93 \\\\ \nTime & 184.93 & 174.98 & 165.58 \\\\ \nInteraction & 5.97 & 12.89 & 27.85 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**H行列の読み方**:\n\n| 要素 | 意味 |\n|:---|:---|\n| `H_Recall_Recall` | Recall における群間変動（対角要素 = 分散成分） |\n| `H_Recog_Recog` | Recognition における群間変動 |\n| `H_Recall_Recog` | Recall と Recognition の群間共変動（非対角要素）。正なら両DVが同方向に群差を持つ |\n\n## 2要因MANOVAのHEプロット\n\nここでは、`heplots::heplot()` を用いて各効果のH楕円とE楕円を重ねてプロットします。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lm() オブジェクトが必要（heplot は lm を受け付ける）\nfit_lm_mv <- lm(cbind(Recall, Recognition) ~ Treatment * Time, data = simulated)\n\nheplots::heplot(\n  fit_lm_mv,\n  fill = TRUE,\n  fill.alpha = 0.1,\n  main = \"HE Plot: Treatment × Time Effects on Recall and Recognition\",\n  xlab = \"Recall\",\n  ylab = \"Recognition\"\n)\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**HEプロットの読み方**:\n\n| プロット要素 | 意味 |\n|:---|:---|\n| **E楕円**（最も大きい楕円） | 群内のばらつき（誤差）の大きさと形状 |\n| **H楕円**（効果ごとの小さい楕円） | 各効果（Treatment, Time, 交互作用）の群間変動 |\n| H楕円がE楕円を**超える方向** | その方向で群差が統計的に有意 |\n| H楕円がE楕円に**収まる** | その効果はその方向では非有意 |\n| 楕円の**傾き** | DV間の相関の方向（正の相関なら右上がり） |\n\n::: {.callout-tip}\n### HEプロットの実務的な読み方\n\nHEプロットでは「H楕円がE楕円からはみ出す方向」に注目してください [@friendly2007]。\n\n1. **はみ出す方向**: H楕円がE楕円の外に出る方向が、統計的に有意な群差の方向です。これはRoyの最大根の検定方向と幾何学的に対応します。\n2. **楕円の大きさ**: H楕円が大きいほど群間変動が大きい。E楕円に完全に収まるH楕円は、その効果が（その平面では）小さいことを示します。\n3. **楕円の傾き**: DV間に正の相関がある場合、楕円は右上がりに傾きます。この傾きの方向は DV 間の共分散構造を反映しています。\n4. **複数の効果の比較**: Treatment のH楕円が大きく、Interaction のH楕円が小さければ、主効果が支配的で交互作用は弱いことが一目でわかります。\n\nFriendly [-@friendly2007] は、HEプロットの最大の利点を「数表だけでは見えない多変量的パターンを、研究者が直感的に把握できること」と述べています。特に、MANOVAが有意なのに全ANOVAが非有意なケース（DVの組み合わせが群差を担う場合）では、HEプロットが唯一の視覚的手がかりを提供します。\n:::\n\n## 1要因（Group）でのHEプロット\n\n4群をまとめた1要因モデルでのHEプロットも確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm_oneway <- lm(cbind(Recall, Recognition) ~ Group, data = simulated)\n\nheplots::heplot(\n  fit_lm_oneway,\n  fill = TRUE,\n  fill.alpha = 0.1,\n  main = \"HE Plot: Group Effect (One-way)\",\n  xlab = \"Recall\",\n  ylab = \"Recognition\"\n)\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## 正準判別プロット\n\n正準判別分析は、群分離を最大化する線形結合（正準判別関数）を求め、その空間にデータを射影します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncan_fit <- candisc::candisc(fit_lm_oneway)\nplot(can_fit,\n     main = \"Canonical Discriminant Plot\")\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**正準判別プロットの読み方**:\n\n| 要素 | 意味 |\n|:---|:---|\n| Can1（横軸） | 第1正準判別関数。群分離を最も多く説明する方向 |\n| Can2（縦軸） | 第2正準判別関数。Can1 に直交する方向での追加的な群分離 |\n| 各群の点と楕円 | 群の分布。楕円が離れているほど群分離が大きい |\n| 矢印（ベクトル） | 各DVが正準空間でどの方向に寄与しているか |\n\n# 判別分析による追跡（DDA）: 主要追跡法\n\nMANOVAは「群間に多変量的な差があるか？」を検定しますが、**どのDVが、どの方向に群分離に寄与しているか**は明らかにしません。DDA（Descriptive Discriminant Analysis）は、MANOVAと同じ固有値分解を逆方向から解釈することで、この問いに答えます [@smith2020; @finch2013; @sherry2005]。\n\nPenn State STAT 505 [-@psu505_lesson10] は、判別分析を以下の7段階で体系化しています。本章もこの流れに沿って進めます。\n\n1. **前提の確認**: 多変量正規性、共分散行列の等質性（Box's M）\n2. **判別関数の推定**: $\\mathbf{H}\\mathbf{E}^{-1}$ の固有値分解から判別関数を導出\n3. **有意性の検定**: 各判別関数のWilks' $\\Lambda$ 検定（MANOVAと等価）\n4. **構造係数の評価**: DVと判別関数の相関（$|r_s| \\geq .30$ が実質的寄与の基準; @tabachnick2019）\n5. **分類規則の構築**: 事前確率と誤分類コストに基づく判別境界\n6. **交差検証**: LOOCVによる分類精度の評価\n7. **結果の解釈**: 構造係数・分散説明割合・分類精度を統合的に報告\n\n::: {.callout-note}\n### DDAとANOVA追跡の比較\n\n| 追跡法 | 利点 | 限界 |\n|:---|:---|:---|\n| **DDA（判別分析）** | 多変量構造を保持し、DV間の相関を考慮。MANOVAと数学的に整合 [@finch2013] | 英語教育研究では馴染みが薄い場合がある |\n| 個別ANOVA | 直感的に理解しやすい。個々のDVの効果量が明確 | DV間の相関を無視。Type Iエラー膨張（最大76%; @smith2020）。多変量パターンを見逃す |\n\nWarne [-@warne2014] のレビューでは、MANOVAを使った58本中DDAを適切に使った論文は0本でした。本章では **DDAを主要追跡法**とし、個別ANOVAは補助的な追跡法として後に報告します。\n:::\n\n## LDAの推定と係数\n\nここでは、`MASS::lda()` を用いて線形判別分析を実行します [@venables2002; @mass_lda_doc]。DDAとして使う場合、分類精度よりも**判別関数の係数**と**構造係数**に注目します。\n\nFinch & French [-@finch2013] が示したように、LDAの判別関数は $\\mathbf{H}\\mathbf{E}^{-1}$ の固有ベクトルに対応しており、MANOVAの固有値と同一の情報源です。つまり、LDAの結果を解釈することは、MANOVAの結果を「群分離の方向と構造」という観点から補完することに相当します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_fit <- MASS::lda(\n  Group ~ Recall + Recognition,\n  data = simulated,\n  CV = FALSE\n)\n\nlda_coef <- as.data.frame(lda_fit$scaling) |>\n  rownames_to_column(\"Variable\")\n\nlda_coef |>\n  gt() |>\n  tab_header(\n    title = \"LDA Coefficients\",\n    subtitle = \"Linear discriminant function loadings\"\n  ) |>\n  fmt_number(columns = starts_with(\"LD\"), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA Coefficients\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Linear discriminant function loadings\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nVariable & LD1 & LD2 \\\\ \n\\midrule\\addlinespace[2.5pt]\nRecall & 0.120 & -0.229 \\\\ \nRecognition & 0.180 & 0.192 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\ncentroid_tbl <- as_tibble(lda_fit$means, rownames = \"Group\")\ncentroid_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Group Centroids\",\n    subtitle = \"Means of predictors by group\"\n  ) |>\n  fmt_number(columns = c(Recall, Recognition), decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Group Centroids\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Means of predictors by group\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nGroup & Recall & Recognition \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing\\_Delayed & 9.70 & 15.64 \\\\ \nGlossing\\_Immediate & 12.09 & 18.34 \\\\ \nWriting\\_Delayed & 14.38 & 21.71 \\\\ \nWriting\\_Immediate & 16.05 & 22.84 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**LDA係数の読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `LD1`, `LD2`, ... | 判別関数の係数。各DVにどの重みをかけて線形結合を作るか |\n| 群重心 | 各群がLD空間のどこに位置するか。重心が離れているほど群分離が良い |\n\n## 構造係数（Structure Coefficients）\n\n構造係数は、各DVと判別関数の相関であり、**各DVが判別関数にどれだけ寄与しているか**を示します。Sherry & Henson [-@sherry2005] は構造係数を「判別関数が捉える多変量的パターンの中で、各DVがどの程度そのパターンを共有しているか」と定義しています。\n\n標準化係数（LDA係数）は回帰分析の $\\beta$ 係数と同様に多重共線性の影響を受けますが、構造係数は**DV間の相関に対してより安定**しています。Tabachnick & Fidell [-@tabachnick2019] は、DV間相関が .40 を超える場合、標準化係数と構造係数の乖離が大きくなりうることを示しており、そのような場合に構造係数の優先使用を推奨しています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_pred <- predict(lda_fit, newdata = simulated)\n\n# 構造係数 = 各DVと判別関数スコアの相関\nstructure_coefs <- cor(\n  simulated[, c(\"Recall\", \"Recognition\")],\n  lda_pred$x\n)\n\nas.data.frame(structure_coefs) |>\n  rownames_to_column(\"Variable\") |>\n  gt() |>\n  tab_header(\n    title = \"Structure Coefficients\",\n    subtitle = \"Correlations between DVs and discriminant functions\"\n  ) |>\n  fmt_number(columns = starts_with(\"LD\"), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Structure Coefficients\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Correlations between DVs and discriminant functions\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nVariable & LD1 & LD2 \\\\ \n\\midrule\\addlinespace[2.5pt]\nRecall & 0.808 & -0.589 \\\\ \nRecognition & 0.925 & 0.380 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**構造係数の解釈基準** [@tabachnick2019]:\n\n| 構造係数の絶対値 | 解釈 |\n|:---:|:---|\n| $\\geq .30$ | **実質的な寄与**。その判別関数への重要な貢献 |\n| .15 -- .30 | 中程度の寄与。補助的に解釈 |\n| $< .15$ | 寄与はわずか。その判別関数には実質的に貢献していない |\n\n::: {.callout-important}\n### 標準化係数 vs 構造係数: どちらを報告すべきか\n\nLDA の標準化係数は回帰分析の $\\beta$ と同様に、多重共線性の影響を受けます。DV間の相関が高い場合、一方のDVの係数が不安定になったり、符号が反転したりすることがあります。\n\nSherry & Henson [-@sherry2005] は以下の指針を示しています。\n\n1. **構造係数を常に報告する**。標準化係数のみの報告は、多変量構造の解釈を歪める。\n2. **両者が一致する場合**: DV間の多重共線性が低い。標準化係数も信頼できる。\n3. **両者が乖離する場合**: DV間の多重共線性が高い。構造係数を優先し、標準化係数は参考として報告する。\n4. **構造係数の符号が逆転する場合**: そのDVは他のDVを通じて間接的に判別関数に関与している（抑圧効果の可能性）。\n\nTabachnick & Fidell [-@tabachnick2019] も同じ立場をとり、「構造係数 $\\geq .30$ を実質的寄与の閾値とする」という基準を広く普及させています。\n:::\n\n## 分散説明割合（Proportion of Trace）\n\n各判別関数が群間分散のどれだけを説明するかを確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_trace <- lda_fit$svd^2 / sum(lda_fit$svd^2)\n\ntibble(\n  Function = paste0(\"LD\", seq_along(prop_trace)),\n  Eigenvalue = lda_fit$svd^2,\n  Proportion = prop_trace,\n  Cumulative = cumsum(prop_trace)\n) |>\n  gt() |>\n  tab_header(\n    title = \"Proportion of Trace\",\n    subtitle = \"Variance explained by each discriminant function\"\n  ) |>\n  fmt_number(columns = Eigenvalue, decimals = 3) |>\n  fmt_percent(columns = c(Proportion, Cumulative), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Proportion of Trace\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Variance explained by each discriminant function\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrr}\n\\toprule\nFunction & Eigenvalue & Proportion & Cumulative \\\\ \n\\midrule\\addlinespace[2.5pt]\nLD1 & 38.111 & 99.4\\% & 99.4\\% \\\\ \nLD2 & 0.217 & 0.6\\% & 100.0\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**Proportion of Trace の読み方**:\n\n- LD1 の Proportion が 90% 以上 → 群分離はほぼ1次元で説明できる\n- 複数のLDが大きな割合を占める → 群分離は多次元的（DVの役割が異なる方向で発揮される）\n\n## LOOCVによる分類精度\n\nDDAの分類性能を Leave-One-Out Cross-Validation（LOOCV）で評価します [@psu505_lesson10]。LOOCVは各観測を1つずつ除外して残りで判別関数を推定し、除外した観測の群を予測します。これにより、過学習を軽減した分類精度が得られます。\n\nPenn State STAT 505 [-@psu505_lesson10] の7段階手順では、LOOCVは第6段階に位置づけられ、「判別関数の予測的妥当性を新データに対して検証する」ステップとして位置づけられています。再代入精度（学習データ自体での正解率）は過大評価されるため、LOOCVまたはk分割交差検証が標準的です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_cv <- MASS::lda(\n  Group ~ Recall + Recognition,\n  data = simulated,\n  CV = TRUE\n)\n\ncm_lda <- table(\n  Actual = simulated$Group,\n  Predicted = lda_cv$class\n)\n\nlda_overall <- sum(diag(cm_lda)) / sum(cm_lda)\nlda_balanced <- mean(diag(cm_lda) / rowSums(cm_lda))\nchance_level <- max(prop.table(table(simulated$Group)))\n\nlda_metric_tbl <- tibble(\n  Metric = c(\"Overall accuracy\", \"Balanced accuracy\", \"Chance level\"),\n  Value = c(lda_overall, lda_balanced, chance_level)\n)\n\nas.data.frame.matrix(cm_lda) |>\n  rownames_to_column(\"Actual\") |>\n  gt() |>\n  tab_header(\n    title = \"LDA Confusion Matrix (LOOCV)\",\n    subtitle = \"Rows = Actual, Columns = Predicted\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA Confusion Matrix (LOOCV)\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Rows = Actual, Columns = Predicted\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nActual & Glossing\\_Delayed & Glossing\\_Immediate & Writing\\_Delayed & Writing\\_Immediate \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing\\_Delayed & 32 & 7 & 2 & 4 \\\\ \nGlossing\\_Immediate & 18 & 11 & 9 & 7 \\\\ \nWriting\\_Delayed & 6 & 7 & 13 & 19 \\\\ \nWriting\\_Immediate & 0 & 10 & 14 & 21 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nlda_metric_tbl |>\n  gt() |>\n  tab_header(\n    title = \"LDA Classification Metrics\",\n    subtitle = \"LOOCV-based performance\"\n  ) |>\n  fmt_percent(columns = Value, decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA Classification Metrics\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  LOOCV-based performance\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nMetric & Value \\\\ \n\\midrule\\addlinespace[2.5pt]\nOverall accuracy & 42.8\\% \\\\ \nBalanced accuracy & 42.8\\% \\\\ \nChance level & 25.0\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**混同行列の読み方**:\n\n| 指標 | 意味 |\n|:---|:---|\n| 対角線 | 正しく分類された数。大きいほど良い |\n| 非対角線 | 誤分類。どの群がどの群に間違われやすいかを示す |\n| Overall accuracy | 全体正解率。チャンス水準（25.0%、4群均等の場合）を大きく上回るか確認 |\n| Balanced accuracy | 群サイズの不均衡を補正した正解率 |\n\n### 群別指標（Precision / Recall / F1）\n\n分類精度は全体正解率だけでなく、**群ごとの再現率と適合率**も確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalc_class_metrics <- function(cm) {\n  tp <- diag(cm)\n  support <- rowSums(cm)\n  predicted <- colSums(cm)\n\n  recall <- tp / support\n  precision <- tp / predicted\n  f1 <- ifelse(\n    (precision + recall) == 0,\n    NA_real_,\n    2 * precision * recall / (precision + recall)\n  )\n\n  tibble(\n    Group = rownames(cm),\n    Support = as.numeric(support),\n    Recall = as.numeric(recall),\n    Precision = as.numeric(precision),\n    F1 = as.numeric(f1)\n  )\n}\n\ncalc_accuracy_ci <- function(cm, conf_level = 0.95) {\n  correct <- sum(diag(cm))\n  total <- sum(cm)\n  ci <- binom.test(correct, total, conf.level = conf_level)$conf.int\n\n  tibble(\n    Correct = correct,\n    Total = total,\n    Accuracy = correct / total,\n    CI_low = ci[1],\n    CI_high = ci[2]\n  )\n}\n\nlda_class_tbl <- calc_class_metrics(cm_lda)\nlda_acc_ci <- calc_accuracy_ci(cm_lda)\n\nlda_class_tbl |>\n  gt() |>\n  tab_header(\n    title = \"LDA Class-wise Performance\",\n    subtitle = \"Recall, Precision, and F1 by group\"\n  ) |>\n  fmt_percent(columns = c(Recall, Precision, F1), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA Class-wise Performance\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Recall, Precision, and F1 by group\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nGroup & Support & Recall & Precision & F1 \\\\ \n\\midrule\\addlinespace[2.5pt]\nGlossing\\_Delayed & 45 & 71.1\\% & 57.1\\% & 63.4\\% \\\\ \nGlossing\\_Immediate & 45 & 24.4\\% & 31.4\\% & 27.5\\% \\\\ \nWriting\\_Delayed & 45 & 28.9\\% & 34.2\\% & 31.3\\% \\\\ \nWriting\\_Immediate & 45 & 46.7\\% & 41.2\\% & 43.7\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nlda_acc_ci |>\n  gt() |>\n  tab_header(\n    title = \"LDA Accuracy with 95% CI\",\n    subtitle = \"Exact binomial confidence interval\"\n  ) |>\n  fmt_percent(columns = c(Accuracy, CI_low, CI_high), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA Accuracy with 95\\% CI\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Exact binomial confidence interval\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\nCorrect & Total & Accuracy & CI\\_low & CI\\_high \\\\ \n\\midrule\\addlinespace[2.5pt]\n77 & 180 & 42.8\\% & 35.4\\% & 50.4\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n## LDA判別空間の可視化\n\n判別関数スコアの散布図で、4群がどの程度分離しているかを視覚的に確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_scores <- as_tibble(lda_pred$x) |>\n  mutate(Group = simulated$Group)\n\nif (!\"LD2\" %in% colnames(lda_scores)) {\n  lda_scores <- lda_scores |>\n    mutate(LD2 = 0)\n}\n\nggplot(lda_scores, aes(x = LD1, y = LD2, color = Group)) +\n  geom_point(alpha = 0.7, size = 2.5) +\n  stat_ellipse(level = 0.95, linewidth = 0.7, linetype = \"dashed\") +\n  labs(\n    title = \"Discriminant Space\",\n    subtitle = \"LDA scores by group\",\n    x = \"LD1\",\n    y = \"LD2\"\n  )\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-29-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**判別空間の読み方**:\n\n- 楕円が重なりが少ないほど → 群分離が良好\n- LD1 方向で分離 → 第1判別関数が支配的\n- LD2 方向でも分離 → 2次元的な群差がある\n\n## QDAとの比較\n\nLDAは**全群で共通の共分散行列を仮定**しますが、QDA（Quadratic Discriminant Analysis）は**群ごとに異なる共分散行列を許容**します [@venables2002; @mass_lda_doc; @mass_qda_doc]。Box's M検定が有意で、群間の共分散構造が異なる場合はQDAの方が適切な可能性があります。ただし、QDAはパラメータ数が多いため、各群に十分な標本サイズが必要です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqda_cv <- MASS::qda(\n  Group ~ Recall + Recognition,\n  data = simulated,\n  CV = TRUE\n)\n\ncm_qda <- table(\n  Actual = simulated$Group,\n  Predicted = qda_cv$class\n)\n\nqda_overall <- sum(diag(cm_qda)) / sum(cm_qda)\nqda_balanced <- mean(diag(cm_qda) / rowSums(cm_qda))\n\ncomparison_tbl <- tibble(\n  Method = c(\"LDA (LOOCV)\", \"QDA (LOOCV)\", \"Chance level\"),\n  Overall_Accuracy = c(lda_overall, qda_overall, chance_level),\n  Balanced_Accuracy = c(lda_balanced, qda_balanced, chance_level)\n)\n\ncomparison_tbl |>\n  gt() |>\n  tab_header(\n    title = \"LDA vs QDA\",\n    subtitle = \"Cross-validated classification performance\"\n  ) |>\n  fmt_percent(columns = c(Overall_Accuracy, Balanced_Accuracy), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA vs QDA\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Cross-validated classification performance\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nMethod & Overall\\_Accuracy & Balanced\\_Accuracy \\\\ \n\\midrule\\addlinespace[2.5pt]\nLDA (LOOCV) & 42.8\\% & 42.8\\% \\\\ \nQDA (LOOCV) & 43.9\\% & 43.9\\% \\\\ \nChance level & 25.0\\% & 25.0\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqda_class_tbl <- calc_class_metrics(cm_qda)\nqda_acc_ci <- calc_accuracy_ci(cm_qda)\n\nbind_rows(\n  lda_class_tbl |> mutate(Method = \"LDA\"),\n  qda_class_tbl |> mutate(Method = \"QDA\")\n) |>\n  dplyr::select(Method, Group, Support, Recall, Precision, F1) |>\n  gt() |>\n  tab_header(\n    title = \"LDA/QDA Class-wise Comparison\",\n    subtitle = \"Per-group classification quality\"\n  ) |>\n  fmt_percent(columns = c(Recall, Precision, F1), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA/QDA Class-wise Comparison\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Per-group classification quality\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrr}\n\\toprule\nMethod & Group & Support & Recall & Precision & F1 \\\\ \n\\midrule\\addlinespace[2.5pt]\nLDA & Glossing\\_Delayed & 45 & 71.1\\% & 57.1\\% & 63.4\\% \\\\ \nLDA & Glossing\\_Immediate & 45 & 24.4\\% & 31.4\\% & 27.5\\% \\\\ \nLDA & Writing\\_Delayed & 45 & 28.9\\% & 34.2\\% & 31.3\\% \\\\ \nLDA & Writing\\_Immediate & 45 & 46.7\\% & 41.2\\% & 43.7\\% \\\\ \nQDA & Glossing\\_Delayed & 45 & 68.9\\% & 57.4\\% & 62.6\\% \\\\ \nQDA & Glossing\\_Immediate & 45 & 35.6\\% & 41.0\\% & 38.1\\% \\\\ \nQDA & Writing\\_Delayed & 45 & 13.3\\% & 26.1\\% & 17.6\\% \\\\ \nQDA & Writing\\_Immediate & 45 & 57.8\\% & 40.6\\% & 47.7\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\nbind_rows(\n  lda_acc_ci |> mutate(Method = \"LDA\"),\n  qda_acc_ci |> mutate(Method = \"QDA\")\n) |>\n  dplyr::select(Method, Correct, Total, Accuracy, CI_low, CI_high) |>\n  gt() |>\n  tab_header(\n    title = \"LDA/QDA Accuracy with 95% CI\",\n    subtitle = \"Overall uncertainty of classification accuracy\"\n  ) |>\n  fmt_percent(columns = c(Accuracy, CI_low, CI_high), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  LDA/QDA Accuracy with 95\\% CI\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Overall uncertainty of classification accuracy\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrr}\n\\toprule\nMethod & Correct & Total & Accuracy & CI\\_low & CI\\_high \\\\ \n\\midrule\\addlinespace[2.5pt]\nLDA & 77 & 180 & 42.8\\% & 35.4\\% & 50.4\\% \\\\ \nQDA & 79 & 180 & 43.9\\% & 36.5\\% & 51.5\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**LDA vs QDA の選択基準**:\n\n| 条件 | 推奨 |\n|:---|:---|\n| Box's M が非有意（$p > .001$） | LDA（よりパーシモニアス） |\n| Box's M が有意（$p < .001$）かつ各群のN > DV数 + 1 | QDA を検討 |\n| LDA と QDA の精度がほぼ同じ | LDA を選択（より安定） |\n| QDA が明らかに優れる | QDA を報告（Box's M の有意性と合わせて根拠を明記） |\n\n### 判別分析を再利用する関数（汎用）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_discriminant_cv <- function(data, group, predictors, method = c(\"lda\", \"qda\"), priors = NULL) {\n  method <- match.arg(method)\n  fml <- as.formula(paste(group, \"~\", paste(predictors, collapse = \" + \")))\n\n  fit_args <- list(formula = fml, data = data, CV = TRUE)\n  if (!is.null(priors)) {\n    fit_args$prior <- priors\n  }\n\n  fit <- if (method == \"lda\") {\n    do.call(MASS::lda, fit_args)\n  } else {\n    do.call(MASS::qda, fit_args)\n  }\n\n  cm <- table(Actual = data[[group]], Predicted = fit$class)\n  overall <- sum(diag(cm)) / sum(cm)\n  balanced <- mean(diag(cm) / rowSums(cm))\n  chance <- max(prop.table(table(data[[group]])))\n\n  list(\n    fit = fit,\n    confusion = cm,\n    summary = tibble(\n      Method = toupper(method),\n      Overall_Accuracy = overall,\n      Balanced_Accuracy = balanced,\n      Chance_Level = chance\n    ),\n    class_metrics = calc_class_metrics(cm),\n    accuracy_ci = calc_accuracy_ci(cm)\n  )\n}\n\ndemo_lda <- run_discriminant_cv(\n  data = simulated,\n  group = \"Group\",\n  predictors = c(\"Recall\", \"Recognition\"),\n  method = \"lda\"\n)\n\ndemo_qda <- run_discriminant_cv(\n  data = simulated,\n  group = \"Group\",\n  predictors = c(\"Recall\", \"Recognition\"),\n  method = \"qda\"\n)\n\nbind_rows(demo_lda$summary, demo_qda$summary) |>\n  gt() |>\n  tab_header(\n    title = \"Reusable DA Function Demo\",\n    subtitle = \"Single-call LDA/QDA cross-validated summaries\"\n  ) |>\n  fmt_percent(columns = c(Overall_Accuracy, Balanced_Accuracy, Chance_Level), decimals = 1)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Reusable DA Function Demo\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Single-call LDA/QDA cross-validated summaries\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrr}\n\\toprule\nMethod & Overall\\_Accuracy & Balanced\\_Accuracy & Chance\\_Level \\\\ \n\\midrule\\addlinespace[2.5pt]\nLDA & 42.8\\% & 42.8\\% & 25.0\\% \\\\ \nQDA & 43.9\\% & 43.9\\% & 25.0\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n# 単変量追跡分析（Follow-up）: 補助的追跡法\n\n前節でDDAを主要追跡法として実施しました。ここでは、**補助的な追跡法**として単変量ANOVAを実行します。Warne [-@warne2014] の推奨手順に沿いつつも、個々のDVについて効果量を確認するために補助的に報告します。DV間の相関構造は考慮されない点に留意してください。\n\n::: {.callout-warning}\n### 単変量追跡の限界\n\n**注意**: 単変量ANOVAを追跡法として使う場合、以下の2つの問題があります [@smith2020; @finch2013]。\n\n1. **Type Iエラーの膨張**: 2 DV × 3 効果 = 6検定。Holm補正が必要。Smith et al. [-@smith2020] は、無補正の単変量追跡でType Iエラー率が最大76%に達しうることをシミュレーションで示しています。\n2. **多変量パターンの見逃し**: DV間の相関を無視するため、個々のANOVAでは非有意でもMANOVAでは有意になるケースを説明できない。Finch & French [-@finch2013] はこのケースをDDAでのみ解釈できることを示しています。\n\nWarne [-@warne2014] の58本レビューでは、ほぼすべてがANOVAのみで追跡しDDAを使っていませんでした。本章では**DDAを主要追跡法**とし、ANOVAは補助的に使います。\n:::\n\nMANOVAで有意な効果が見られた場合、どの従属変数が効果を担っているかを単変量で追跡します。ここでは6つの検定（2従属変数 × 3効果）に対して Holm 補正を適用します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_recall <- aov(Recall ~ Treatment * Time, data = simulated)\naov_recognition <- aov(Recognition ~ Treatment * Time, data = simulated)\n\nfollowup_tbl <- bind_rows(\n  broom::tidy(aov_recall) |>\n    mutate(Outcome = \"Recall\"),\n  broom::tidy(aov_recognition) |>\n    mutate(Outcome = \"Recognition\")\n) |>\n  filter(term != \"Residuals\") |>\n  mutate(\n    p_holm = p.adjust(p.value, method = \"holm\")\n  ) |>\n  dplyr::select(Outcome, term, df, statistic, p.value, p_holm)\n\nfollowup_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Univariate Follow-up Tests\",\n    subtitle = \"ANOVA with Holm-adjusted p-values\"\n  ) |>\n  fmt_number(columns = c(statistic, p.value, p_holm), decimals = 4) |>\n  fmt_number(columns = df, decimals = 0) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_body(columns = p_holm, rows = p_holm < 0.05)\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Univariate Follow-up Tests\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  ANOVA with Holm-adjusted p-values\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrr}\n\\toprule\nOutcome & term & df & statistic & p.value & p\\_holm \\\\ \n\\midrule\\addlinespace[2.5pt]\nRecall & Treatment & 1 & 50.0233 & 0.0000 & {\\bfseries 0.0000} \\\\ \nRecall & Time & 1 & 11.0180 & 0.0011 & {\\bfseries 0.0044} \\\\ \nRecall & Treatment:Time & 1 & 0.3556 & 0.5517 & 0.5517 \\\\ \nRecognition & Treatment & 1 & 77.7272 & 0.0000 & {\\bfseries 0.0000} \\\\ \nRecognition & Time & 1 & 10.2228 & 0.0016 & {\\bfseries 0.0049} \\\\ \nRecognition & Treatment:Time & 1 & 1.7196 & 0.1914 & 0.3829 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**追跡ANOVAの読み方**:\n\n| 出力項目 | 読み方 |\n|:---|:---|\n| `Outcome` | どのDVの結果か |\n| `term` | 効果名（Treatment, Time, 交互作用） |\n| `statistic` | F値 |\n| `p.value` | 補正前のp値 |\n| `p_holm` | Holm補正後のp値。**こちらを報告に使用する** |\n\n## 効果量（偏η²）\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_tbl <- bind_rows(\n  as.data.frame(effectsize::eta_squared(aov_recall, partial = TRUE)) |>\n    mutate(Outcome = \"Recall\"),\n  as.data.frame(effectsize::eta_squared(aov_recognition, partial = TRUE)) |>\n    mutate(Outcome = \"Recognition\")\n) |>\n  dplyr::select(Outcome, Parameter, Eta2_partial, CI_low, CI_high)\n\neta_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Effect Sizes\",\n    subtitle = \"Partial eta-squared for follow-up ANOVAs\"\n  ) |>\n  fmt_number(columns = c(Eta2_partial, CI_low, CI_high), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Effect Sizes\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Partial eta-squared for follow-up ANOVAs\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrr}\n\\toprule\nOutcome & Parameter & Eta2\\_partial & CI\\_low & CI\\_high \\\\ \n\\midrule\\addlinespace[2.5pt]\nRecall & Treatment & 0.221 & 0.138 & 1.000 \\\\ \nRecall & Time & 0.059 & 0.015 & 1.000 \\\\ \nRecall & Treatment:Time & 0.002 & 0.000 & 1.000 \\\\ \nRecognition & Treatment & 0.306 & 0.217 & 1.000 \\\\ \nRecognition & Time & 0.055 & 0.013 & 1.000 \\\\ \nRecognition & Treatment:Time & 0.010 & 0.000 & 1.000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**偏η²の解釈基準**:\n\n| 偏η² | 効果の大きさ |\n|:---:|:---|\n| .01 | 小さい効果 |\n| .06 | 中程度の効果 |\n| .14 | 大きい効果 |\n\n## 事後比較（セル平均の比較）\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_recall <- lm(Recall ~ Treatment * Time, data = simulated)\nlm_recognition <- lm(Recognition ~ Treatment * Time, data = simulated)\n\npairs_recall <- emmeans::emmeans(lm_recall, ~ Treatment * Time) |>\n  pairs(adjust = \"holm\") |>\n  as.data.frame() |>\n  mutate(Outcome = \"Recall\")\n\npairs_recognition <- emmeans::emmeans(lm_recognition, ~ Treatment * Time) |>\n  pairs(adjust = \"holm\") |>\n  as.data.frame() |>\n  mutate(Outcome = \"Recognition\")\n\nbind_rows(pairs_recall, pairs_recognition) |>\n  dplyr::select(Outcome, contrast, estimate, SE, df, t.ratio, p.value) |>\n  gt() |>\n  tab_header(\n    title = \"Post-hoc Pairwise Comparisons\",\n    subtitle = \"Estimated marginal means (Holm-adjusted)\"\n  ) |>\n  fmt_number(columns = c(estimate, SE, t.ratio, p.value), decimals = 4) |>\n  fmt_number(columns = df, decimals = 0)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Post-hoc Pairwise Comparisons\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Estimated marginal means (Holm-adjusted)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrrr}\n\\toprule\nOutcome & contrast & estimate & SE & df & t.ratio & p.value \\\\ \n\\midrule\\addlinespace[2.5pt]\nRecall & Glossing Delayed - Writing Delayed & -4.6836 & 0.8637 & 176 & -5.4228 & 0.0000 \\\\ \nRecall & Glossing Delayed - Glossing Immediate & -2.3914 & 0.8637 & 176 & -2.7688 & 0.0187 \\\\ \nRecall & Glossing Delayed - Writing Immediate & -6.3466 & 0.8637 & 176 & -7.3483 & 0.0000 \\\\ \nRecall & Writing Delayed - Glossing Immediate & 2.2923 & 0.8637 & 176 & 2.6540 & 0.0187 \\\\ \nRecall & Writing Delayed - Writing Immediate & -1.6630 & 0.8637 & 176 & -1.9255 & 0.0558 \\\\ \nRecall & Glossing Immediate - Writing Immediate & -3.9553 & 0.8637 & 176 & -4.5795 & 0.0000 \\\\ \nRecognition & Glossing Delayed - Writing Delayed & -6.0760 & 0.8484 & 176 & -7.1613 & 0.0000 \\\\ \nRecognition & Glossing Delayed - Glossing Immediate & -2.7049 & 0.8484 & 176 & -3.1881 & 0.0034 \\\\ \nRecognition & Glossing Delayed - Writing Immediate & -7.2075 & 0.8484 & 176 & -8.4949 & 0.0000 \\\\ \nRecognition & Writing Delayed - Glossing Immediate & 3.3711 & 0.8484 & 176 & 3.9732 & 0.0003 \\\\ \nRecognition & Writing Delayed - Writing Immediate & -1.1315 & 0.8484 & 176 & -1.3336 & 0.1841 \\\\ \nRecognition & Glossing Immediate - Writing Immediate & -4.5025 & 0.8484 & 176 & -5.3068 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n# 検定力分析\n\nMANOVAは多変量検定であるため、推定すべきパラメータが単変量ANOVAよりも多くなります。十分な検定力（通常 $\\geq .80$）を確保するには、サンプルサイズの事前計画が不可欠です。\n\nTabachnick & Fidell [-@tabachnick2019] は、MANOVAにおけるサンプルサイズの基本ルールとして以下を示しています。\n\n| ルール | 内容 | 根拠 |\n|:---|:---|:---|\n| **最低条件** | 各セルの $n >$ DV数 | 群内共分散行列が非特異であるために必要 |\n| **推奨条件** | 各セルの $n \\geq 20$ | 検定統計量のF近似が安定するために推奨 [@stevens2009] |\n| **DDA用の追加条件** | 各セルの $n \\geq$ DV数 + 1（QDA使用時は特に重要） | QDAの群別共分散推定に必要 |\n| **検定力の確保** | 総N に対して検定力計算で .80 以上 | 事前のパワー分析で確認 [@zhang2018] |\n\n: MANOVAのサンプルサイズに関する基本ルール {.striped}\n\nここでは `WebPower` パッケージの `wp.kanova()` を用いてMANOVA近似の検定力を計算します [@zhang2018]。MANOVAの場合、分子自由度は $\\text{ndf} = p \\times (k - 1)$（DV数 × 群の自由度）となります。4群・2DVの場合、$\\text{ndf} = 2 \\times 3 = 6$ です。\n\n## 本データの検定力\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MANOVA近似: ndf = p × (k-1) = 2 × 3 = 6\nwp_result <- WebPower::wp.kanova(\n  n = nrow(simulated),\n  ndf = 6,\n  f = 0.25,\n  ng = 4,\n  alpha = 0.05,\n  power = NULL\n)\n\ntibble(\n  Parameter = c(\"Total N\", \"Groups (ng)\", \"Numerator df (ndf)\", \"Effect size (f)\", \"Alpha\", \"Power\"),\n  Value = c(\n    wp_result$n,\n    wp_result$ng,\n    wp_result$ndf,\n    wp_result$f,\n    wp_result$alpha,\n    round(wp_result$power, 3)\n  )\n) |>\n  gt() |>\n  tab_header(\n    title = \"Power Analysis for Current Design\",\n    subtitle = \"WebPower::wp.kanova() — MANOVA approximation\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Power Analysis for Current Design\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  WebPower::wp.kanova() — MANOVA approximation\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nParameter & Value \\\\ \n\\midrule\\addlinespace[2.5pt]\nTotal N & 180.000 \\\\ \nGroups (ng) & 4.000 \\\\ \nNumerator df (ndf) & 6.000 \\\\ \nEffect size (f) & 0.250 \\\\ \nAlpha & 0.050 \\\\ \nPower & 0.687 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**検定力分析の読み方**:\n\n| パラメータ | 意味 |\n|:---|:---|\n| `n` | 総サンプルサイズ |\n| `ng` | 群数 |\n| `ndf` | 分子自由度（MANOVA: DV数 × 群の自由度） |\n| `f` | Cohen の f（中程度 = 0.25） |\n| `power` | 検定力。.80以上が望ましい |\n\n## サンプルサイズと検定力の関係\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_seq <- seq(40, 300, by = 20)\npower_curve <- purrr::map_dfr(n_seq, ~ {\n  res <- WebPower::wp.kanova(\n    n = .x, ndf = 6, f = 0.25,\n    ng = 4, alpha = 0.05, power = NULL\n  )\n  tibble(n = .x, power = res$power)\n})\n\nggplot(power_curve, aes(x = n, y = power)) +\n  geom_line(linewidth = 1.1, color = \"#2c3e50\") +\n  geom_hline(yintercept = 0.80, linetype = \"dashed\", color = \"red\") +\n  annotate(\"text\", x = 250, y = 0.82, label = \"Power = .80 threshold\", color = \"red\") +\n  labs(\n    title = \"Power Curve for MANOVA\",\n    subtitle = \"4 groups, 2 DVs, Cohen's f = 0.25 (ndf = 6)\",\n    x = \"Total sample size\",\n    y = \"Statistical power\"\n  )\n```\n\n::: {.cell-output-display}\n![](3_MANOVA_判別分析_files/figure-pdf/unnamed-chunk-37-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## 必要サンプルサイズの算出\n\n目標検定力 .80 に必要な総サンプルサイズを逆算します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwp_n <- WebPower::wp.kanova(\n  n = NULL,\n  ndf = 6,\n  f = 0.25,\n  ng = 4,\n  alpha = 0.05,\n  power = 0.80\n)\n\ntibble(\n  Target_Power = 0.80,\n  Required_N = ceiling(wp_n$n),\n  Per_Group = ceiling(wp_n$n / 4)\n) |>\n  gt() |>\n  tab_header(\n    title = \"Required Sample Size\",\n    subtitle = \"For 4 groups, 2 DVs, f = 0.25, power = .80\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Required Sample Size\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  For 4 groups, 2 DVs, f = 0.25, power = .80\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrr}\n\\toprule\nTarget\\_Power & Required\\_N & Per\\_Group \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.8 & 225 & 57 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-tip}\n### 英語教育研究における効果量の目安\n\n| 効果量 (f) | 英語教育研究での目安 | 必要N（4群, 2DV, power=.80） |\n|:---:|:---|:---:|\n| 0.10（小） | 語彙学習法間の微差 | 約800 |\n| 0.25（中） | 指導法間の一般的な差 | 約180 |\n| 0.40（大） | 介入の顕著な効果 | 約80 |\n\n先行研究の効果量を参照してサンプルサイズを計画することが重要です。英語教育研究では $f = 0.25$ 前後が現実的な目安となることが多いです [@stevens2009; @hahs2017]。\n\n**実務上のポイント**:\n\n- Stevens [-@stevens2009] は、効果量が小さい（$f = .10$）場合の検出には各群50名以上が必要であると指摘しており、教育研究で典型的な30名前後のクラスサイズでは検出が困難であることを示唆しています。\n- 英語教育研究では1クラス20-30名が現実的な制約であるため、**2-3クラスをまとめて1群40-60名**を確保するか、効果量が中程度以上の介入に焦点を絞る戦略が必要です。\n- Tabachnick & Fidell [-@tabachnick2019] は「各セルの $n >$ DV数」を最低条件としていますが、これはあくまり行列演算上の最低限であり、検定力の観点ではさらに大きなNが必要です。\n:::\n\n# よくある誤解\n\n::: {.callout-important}\n### 誤解1: 「MANOVAが有意なら追跡ANOVAのType Iエラーは制御される」\n\n**事実**: MANOVAの有意性は多変量空間全体での検定結果であり、個々のDVへの追跡ANOVAに対する「保護的ゲートキーパー」機能は限定的です。Huberty & Olejnik [-@huberty2006] はこの点を明確に指摘し、追跡ANOVAにはHolm法などの多重性補正が依然として必要であると述べています。\n\nSmith et al. [-@smith2020] は英才教育研究の56論文を体系的にレビューし、ほぼすべてがMANOVA後に無補正の単変量ANOVAのみで追跡していることを発見しました。シミュレーションにより、DV数が増えるとこの慣行のType Iエラー率が最大76%に達しうることを示しています。\n:::\n\n::: {.callout-important}\n### 誤解2: 「MANOVAが非有意なら群差はない」\n\n**事実**: 非有意の結果は「差がない」ことの証拠ではなく、「差を検出できなかった」可能性があります。検定力が不足している場合（N不足、効果量が小さい場合）、真の差があっても検出できません。必ず検定力分析で確認し、「power = XX であった」と報告してください [@stevens2009]。\n:::\n\n::: {.callout-important}\n### 誤解3: 「追跡ANOVAだけで十分」\n\n**事実**: 追跡ANOVAは各DVを個別に検定するため、DV間の相関構造を無視します。MANOVAが有意でも全てのANOVAが非有意になるケースがあります（DVの組み合わせが群差のパターンを担う場合）。\n\nWarne [-@warne2014] は58本のMANOVA論文をレビューし、DDAを適切に使った論文が**1本もなかった**ことを報告しています。このことは、追跡ANOVAのみに頼る慣行がいかに根深いかを示しています。Finch & French [-@finch2013] は、DDAがMANOVAと数学的に同一の情報源（$\\mathbf{H}\\mathbf{E}^{-1}$ の固有値分解）に基づくことを示し、追跡法としての理論的一貫性を強調しています。DDAを併用することで、単変量では見えない多変量的パターンを捉えることが可能になります。\n:::\n\n::: {.callout-important}\n### 誤解4: 「MANOVAは同時ANOVAにすぎない」\n\n**事実**: MANOVAはDV間の共分散構造を考慮した上で群差を検定します。H行列とE行列の比がMANOVAの検定統計量の基盤であり、DVを個別に検定するANOVAにはこの情報がありません。Huberty & Olejnik [-@huberty2006] はMANOVAの本質を「DVの最適な重み付け線形結合に対する検定」と定義しています。\n\nこの違いは、HEプロットで視覚的に確認できます。Friendly [-@friendly2007] のHEプロット手法では、H楕円がE楕円からはみ出す方向が多変量的な群差の方向を示しますが、この方向は個々のDV軸とは異なる場合があります。つまり、MANOVAは個別ANOVAでは原理的にアクセスできない「DV間の組み合わせに基づく群差」を検出する能力を持ちます。\n:::\n\n# トラブルシューティング（実務で詰まりやすい点）\n\n::: {.callout-warning}\n### 多変量正規性（MVN）の逸脱\n\n**症状**: HZ検定で $p < .05$。Q-Qプロットが対角線から乖離。\n\n**原因**: 外れ値、床効果・天井効果、本質的に非正規な変数。\n\n**修正**:\n\n1. マハラノビス距離で外れ値を特定し、感度分析（含む/除く）を行う。\n2. Pillai統計量を主報告にする。Olson [-@olson1974] のモンテカルロ研究で、正規性違反に最も頑健であることが確認されている。\n3. 逸脱が著しい場合、変数変換（log, sqrt）を検討。\n4. 大標本（各群 $n > 30$）であれば中心極限定理により頑健性が高まる [@tabachnick2019]。\n5. 論文には「HZ検定の結果と対応策」を明記する。\n:::\n\n::: {.callout-warning}\n### Box's M検定の有意\n\n**症状**: Box's M が $p < .001$。\n\n**原因**: 群間で共分散行列の構造が異なる。群サイズの不均衡があるとさらに影響が大きい。Box's M は標本サイズに過敏であるため、$p < .05$ ではなく $p < .001$ を実務基準とすることが推奨されます [@tabachnick2019; @huberty2006]。\n\n**修正**:\n\n1. 群サイズがバランスしていれば、Pillai統計量は比較的頑健。Olson [-@olson1974] はこの条件でPillaiが名義 $\\alpha$ 水準を維持することを示している。\n2. 群サイズが不均衡なら、最も危険な条件（共分散不等質 + 不均衡N）に該当するため、結果の解釈に特に慎重になる。\n3. 群ごとの共分散楕円を可視化し（HEプロットで確認可能）、逸脱の程度を確認する。\n4. QDAの使用を検討する（群別共分散を許容）。ただし各群の $n >$ DV数 + 1 が必要 [@tabachnick2019]。\n:::\n\n::: {.callout-warning}\n### DV間の多重共線性\n\n**症状**: DV間相関が .70 を超える。判別関数の係数が不安定。Tabachnick & Fidell [-@tabachnick2019] は .90 以上を「深刻な多重共線性」として警告している。\n\n**原因**: DVが測定している構成概念がほぼ同一。\n\n**修正**:\n\n1. 一方のDVを除外するか、複合スコアに統合することを検討。\n2. 構造係数を優先して解釈する。Sherry & Henson [-@sherry2005] は、DV間相関が高い場合に標準化係数が不安定になることを示しており、構造係数のみでの解釈を推奨している。\n3. 理論的にDVが異なる構成概念であることを再確認する。\n4. DV間相関が .30-.70 の「理想的な範囲」に収まるようDVの選択を見直す。\n:::\n\n::: {.callout-warning}\n### サンプルサイズの不足\n\n**症状**: MANOVAが非有意だが、記述統計では明らかな群差がある。\n\n**原因**: 検定力不足。MANOVAは推定パラメータが多いため、ANOVAより大きなNが必要。\n\n**修正**:\n\n1. `WebPower::wp.kanova()` で事後検定力を計算する。\n2. power < .80 の場合、「検定力不足の可能性」を明記する。\n3. 次回研究のために必要サンプルサイズを報告する。\n:::\n\n::: {.callout-warning}\n### MANOVAは有意だが全てのANOVAが非有意\n\n**症状**: Pillai が $p < .05$ だが、追跡ANOVAでは全DVが $p > .05$。\n\n**原因**: 群差がDV間の相関パターンに埋め込まれており、個々のDVでは表面化しない。これは「矛盾」ではなく、**MANOVAの利点が発揮された場面**です。Warne [-@warne2014] はこの状況を「MANOVAの存在意義を最もよく示すケース」と述べています。\n\n**修正**:\n\n1. DDA（判別分析）で多変量的な群分離パターンを確認する。構造係数を読むことで、DVの組み合わせがどの方向に群差を形成しているかがわかります。\n2. HEプロットで視覚的にパターンを確認する。Friendly [-@friendly2007] のHEプロットでは、H楕円がE楕円からはみ出す方向がDV軸と斜めになる場合、個別のDVでは検出できない「斜め方向」の群差が存在していることを示します。\n3. 論文には「多変量検定は有意であったが、単変量では個別に有意な変数は見られなかった。DDAにより、DVの組み合わせとして群分離が確認された」と報告する [@smith2020; @finch2013]。\n:::\n\n::: {.callout-warning}\n### 外れ値による結果の不安定化\n\n**症状**: マハラノビス距離がカットオフを大きく超える観測がある。外れ値の除外前後で結果が変わる。\n\n**原因**: データ入力ミス、異質な参加者（タスク不理解など）。\n\n**修正**:\n\n1. 外れ値の「含む/除く」の両方で分析し、結果の安定性を確認（感度分析）。\n2. 除外する場合は、理論的根拠（タスク不理解の記録など）を明記する。\n3. 「統計的にだけ外れ値」という理由での除外は避ける。\n:::\n\n::: {.callout-warning}\n### QDAが収束しない（rank deficiency）\n\n**症状**: `MASS::qda()` で \"some group is too small\" や \"rank deficiency\" エラー。\n\n**原因**: 群内の観測数がDV数以下、または群内共分散行列が特異（ランク落ち）。\n\n**修正**:\n\n1. 各群の $n >$ DV数 であることを確認する（最低でも $n > p + 1$）。\n2. LDAに切り替える（共通共分散を仮定するため、少数サンプルに対応しやすい）。\n3. DV数を減らすか、正則化判別分析を検討する。\n:::\n\n# 結果記述テンプレート（論文の結果節向け）\n\n::: {.panel-tabset}\n\n### Method\n\n以下は、本章のデータに基づいた Method セクションの記述例です。自分のデータに置き換えて使用してください。\n\n> We examined the effects of Treatment (Glossing vs. Writing) and Time (Immediate vs. Delayed) on two vocabulary outcomes (Recall and Recognition) using a two-way multivariate analysis of variance (MANOVA). Assumptions of multivariate normality were evaluated using the Henze-Zirkler test (Korkmaz et al., 2014) applied group-wise, and homogeneity of covariance matrices was assessed with Box's M test. Pillai's trace was used as the primary test statistic due to its robustness to assumption violations (Olson, 1974). Descriptive discriminant analysis (DDA) served as the primary multivariate follow-up, with univariate ANOVAs as supplementary analyses (Holm-adjusted). Classification accuracy was evaluated using leave-one-out cross-validation. Analyses were conducted in R using the MASS, heplots, MVN, and effectsize packages.\n\n### Results（MANOVA + DDA）\n\n> Pillai's trace indicated a significant main effect of Treatment, *V* = X.XX, *F*(2, 173) = XX.XX, *p* < .001. The Time main effect was also significant, *V* = X.XX, *F*(2, 173) = XX.XX, *p* = .0XX. The Treatment × Time interaction was non-significant, *V* = X.XX, *F*(2, 173) = X.XX, *p* = .XXX.\n>\n> Descriptive discriminant analysis revealed that the first discriminant function (LD1) accounted for XX% of the between-group variance. Structure coefficients indicated that both Recall ($r_s$ = .XX) and Recognition ($r_s$ = .XX) contributed substantially to group separation (criterion: $|r_s| \\geq .30$; Tabachnick & Fidell, 2019). LOOCV classification accuracy was XX.X% (balanced = XX.X%), exceeding the chance level of 25.0%, 95% CI [XX.X%, XX.X%].\n\n### Results（単変量追跡）\n\n> Supplementary univariate ANOVAs (Holm-adjusted) indicated that the Treatment effect was significant for both Recall, *F*(1, 176) = XX.XX, *p* < .001, $\\eta^2_p$ = .XXX, and Recognition, *F*(1, 176) = XX.XX, *p* < .001, $\\eta^2_p$ = .XXX.\n\n### 査読者チェックリスト\n\n1. **前提チェックの報告**: MVN（HZ検定）と Box's M の結果を記載したか\n2. **検定統計量**: Pillai を主報告し、他の統計量は補足として併記したか\n3. **DDA の報告**: 判別関数の構造係数と分散説明割合を報告したか\n4. **分類精度**: LOOCV精度をチャンス水準と比較し、95% CI を付けたか\n5. **効果量**: 偏η² を 95% CI 付きで報告したか\n6. **多重性調整**: 追跡ANOVAに Holm 補正を適用し、補正前後の p 値を併記したか\n7. **HEプロット**: 視覚的に群分離を示したか（推奨）\n8. **検定力**: 事後検定力または事前のサンプルサイズ計画を記載したか\n9. **ソフトウェア**: 使用したR パッケージとバージョンを明記したか\n\n:::\n\n::: {.callout-tip}\n### APA 7 最低限の表記ルール\n\n- 統計記号はイタリック: *V*, *F*, *p*, $\\eta^2_p$\n- Pillai's trace は *V* = .XXX と表記\n- *p* 値は `p = .032`、非常に小さい場合は `p < .001`\n- 効果量は $\\eta^2_p$ = .XXX, 95% CI [LL, UL]\n- 分類精度は % で報告し、チャンス水準と比較\n:::\n\n::: {.callout-tip}\n### コピペ用 1 文テンプレート\n\n**Method**: \"A two-way MANOVA was conducted with Treatment and Time as independent variables and Recall and Recognition as dependent variables. Pillai's trace was the primary test statistic. DDA served as the multivariate follow-up.\"\n\n**Results**: \"Pillai's trace indicated a significant Treatment effect, *V* = .XX, *F*(2, 173) = XX.XX, *p* < .001. DDA structure coefficients indicated both DVs contributed to group separation (Recall $r_s$ = .XX; Recognition $r_s$ = .XX).\"\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlargest_eta <- eta_tbl |>\n  slice_max(Eta2_partial, n = 1, with_ties = FALSE)\n\nsummary_tbl <- tibble(\n  Component = c(\n    \"Primary multivariate test (Pillai)\",\n    \"Best univariate effect size\",\n    \"LD1 proportion of trace\",\n    \"LDA overall accuracy\",\n    \"QDA overall accuracy\",\n    \"Chance level\"\n  ),\n  Result = c(\n    {\n      tr_row <- pillai_focus |>\n        filter(Effect == \"Treatment\")\n      if (nrow(tr_row) == 1) {\n        paste0(\"Treatment: F=\", round(tr_row$Approx_F, 2), \", p=\", round(tr_row$p_value, 4))\n      } else {\n        \"Treatment row not found\"\n      }\n    },\n    paste0(\n      largest_eta$Outcome, \" / \", largest_eta$Parameter,\n      \": eta_p2 = \", round(largest_eta$Eta2_partial, 3)\n    ),\n    paste0(round(prop_trace[1] * 100, 1), \"%\"),\n    paste0(round(lda_overall * 100, 1), \"%\"),\n    paste0(round(qda_overall * 100, 1), \"%\"),\n    paste0(round(chance_level * 100, 1), \"%\")\n  )\n)\n\nsummary_tbl |>\n  gt() |>\n  tab_header(\n    title = \"Chapter Summary\",\n    subtitle = \"Key numbers to report\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Chapter Summary\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Key numbers to report\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}ll}\n\\toprule\nComponent & Result \\\\ \n\\midrule\\addlinespace[2.5pt]\nPrimary multivariate test (Pillai) & Treatment: F=0.36, p=175 \\\\ \nBest univariate effect size & Recognition / Treatment: eta\\_p2 = 0.306 \\\\ \nLD1 proportion of trace & 99.4\\% \\\\ \nLDA overall accuracy & 42.8\\% \\\\ \nQDA overall accuracy & 43.9\\% \\\\ \nChance level & 25\\% \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n# まとめ\n\n本章では、MANOVA と判別分析（DDA）を用いた多変量解析の一連のワークフローを整理しました。先行研究のチュートリアル論文の知見を統合し、以下の主要なポイントを実装しています。\n\n1. **MANOVAは、複数DVを同時に扱う**ことで、単変量ANOVAの反復より整合的な推論を提供する [@warne2014]。DV間の相関構造（理想的には .30-.70 の範囲; @tabachnick2019）を考慮できることが本質的な強みである。\n\n2. **H行列とE行列**がMANOVAの基盤であり、HEプロット [@friendly2007] によりその関係を直感的に把握できる。H楕円がE楕円を超える方向が、有意な群差の方向を示す（Royの最大根と幾何学的に対応）。\n\n3. **Pillai のトレース**を主報告とする。Olson [-@olson1974] のモンテカルロ研究で、正規性違反・共分散不等質性・群サイズ不均衡の全条件を通じて最も頑健であることが確認されている。\n\n4. **DDA（判別分析）はMANOVAの主要追跡法**である。構造係数（$|r_s| \\geq .30$ を基準; @tabachnick2019; @sherry2005）により、各DVの群分離への寄与を安定的に評価できる。Warne [-@warne2014] の58本レビューおよびSmith et al. [-@smith2020] の56本レビューが示すように、DDAの使用率は極めて低いのが現状であるが、理論的にはMANOVAの最も自然な追跡法である [@finch2013]。\n\n5. **分類精度**（LOOCV; @psu505_lesson10）をチャンス水準と比較することで、「統計的に有意かどうか」だけでなく「実務的にどの程度群を分離できるか」を示す。\n\n6. **検定力分析** [@zhang2018] により、研究の事前計画（必要サンプルサイズ）および事後評価（実際の検定力）を定量化する。Tabachnick & Fidell [-@tabachnick2019] の「各セルの $n >$ DV数」を最低条件とし、Stevens [-@stevens2009] の「各群20名以上」を推奨条件とする。\n\n7. **報告では**、p値だけでなく多変量効果量（Pillai のトレースに基づく $\\eta^2$）・構造係数・分類精度（チャンス比較）・検定力を併記する。\n\n# 参考Webリソース（再学習用）\n\n::: {.panel-tabset}\n\n### MANOVAの基礎\n\n- Warne (2014): MANOVAの設計と解釈の実務ガイド [@warne2014]\n- Penn State STAT 505 Lesson 8: One-Way MANOVA [@psu505_lesson08]\n- R Documentation: `summary.manova` [@r_summary_manova]\n\n### DDA（判別分析）を深めたい\n\n- Smith et al. (2020): MANOVAの多変量追跡法としてのDDA [@smith2020]\n- Sherry & Henson (2005): 構造係数の解釈 [@sherry2005]\n- Penn State STAT 505 Lesson 10: Discriminant Analysis [@psu505_lesson10]\n- R Documentation: `MASS::lda` / `MASS::qda` [@mass_lda_doc; @mass_qda_doc]\n\n### HEプロット・可視化\n\n- Friendly (2007): HEプロットの理論と実装 [@friendly2007]\n- `heplots` パッケージ: MANOVA可視化\n- `candisc` パッケージ: 正準判別分析の可視化 [@friendly2021candisc]\n\n### 教科書的参照\n\n- Tabachnick & Fidell (2019): 多変量統計の標準的教科書 [@tabachnick2019]\n- Stevens (2009): 社会科学向け応用多変量統計 [@stevens2009]\n- Huberty & Olejnik (2006): Applied MANOVA and Discriminant Analysis [@huberty2006]\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"unnamed-chunk-19\",\"unnamed-chunk-19\",\"unnamed-chunk-19\",\"unnamed-chunk-19\",\"unnamed-chunk-19\",\"unnamed-chunk-19\",\"unnamed-chunk-19\",\"unnamed-chunk-20\",\"unnamed-chunk-20\",\"unnamed-chunk-20\",\"unnamed-chunk-20\",\"unnamed-chunk-20\",\"unnamed-chunk-20\",\"unnamed-chunk-20\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-24\",\"unnamed-chunk-25\",\"unnamed-chunk-25\",\"unnamed-chunk-25\",\"unnamed-chunk-25\",\"unnamed-chunk-25\",\"unnamed-chunk-25\",\"unnamed-chunk-25\",\"unnamed-chunk-26\",\"unnamed-chunk-26\",\"unnamed-chunk-26\",\"unnamed-chunk-26\",\"unnamed-chunk-26\",\"unnamed-chunk-26\",\"unnamed-chunk-26\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-27\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-28\",\"unnamed-chunk-30\",\"unnamed-chunk-30\",\"unnamed-chunk-30\",\"unnamed-chunk-30\",\"unnamed-chunk-30\",\"unnamed-chunk-30\",\"unnamed-chunk-30\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-31\",\"unnamed-chunk-32\",\"unnamed-chunk-32\",\"unnamed-chunk-32\",\"unnamed-chunk-32\",\"unnamed-chunk-32\",\"unnamed-chunk-32\",\"unnamed-chunk-32\",\"unnamed-chunk-33\",\"unnamed-chunk-33\",\"unnamed-chunk-33\",\"unnamed-chunk-33\",\"unnamed-chunk-33\",\"unnamed-chunk-33\",\"unnamed-chunk-33\",\"unnamed-chunk-34\",\"unnamed-chunk-34\",\"unnamed-chunk-34\",\"unnamed-chunk-34\",\"unnamed-chunk-34\",\"unnamed-chunk-34\",\"unnamed-chunk-34\",\"unnamed-chunk-35\",\"unnamed-chunk-35\",\"unnamed-chunk-35\",\"unnamed-chunk-35\",\"unnamed-chunk-35\",\"unnamed-chunk-35\",\"unnamed-chunk-35\",\"unnamed-chunk-36\",\"unnamed-chunk-36\",\"unnamed-chunk-36\",\"unnamed-chunk-36\",\"unnamed-chunk-36\",\"unnamed-chunk-36\",\"unnamed-chunk-36\",\"unnamed-chunk-38\",\"unnamed-chunk-38\",\"unnamed-chunk-38\",\"unnamed-chunk-38\",\"unnamed-chunk-38\",\"unnamed-chunk-38\",\"unnamed-chunk-38\",\"unnamed-chunk-39\",\"unnamed-chunk-39\",\"unnamed-chunk-39\",\"unnamed-chunk-39\",\"unnamed-chunk-39\",\"unnamed-chunk-39\",\"unnamed-chunk-39\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}