{
  "hash": "c7c5b406772fc5b4e6fe1f221418c676",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"混合効果モデル：2値ロジスティック回帰分析\"\nauthor: \"小室竜也\"\ndate: today\nbibliography:\n  - references_glm_gam.bib\n  - references_glmm.bib\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    toc-title: \"目次\"\n    number-sections: true\n    code-fold: show\n    theme: journal\n    fontsize: 1.1em\n    linestretch: 1.8\n    mainfont: \"Noto Serif JP\"\nlang: ja\n---\n\n```{=html}\n<style>\n/* journalテーマ用のアカデミックなカスタムスタイル */\nbody {\n  font-family: 'Noto Serif JP', 'Times New Roman', serif;\n  color: #2c3e50;\n  line-height: 1.8;\n}\n\n/* タイトルブロックをジャーナル風に */\n.quarto-title-banner {\n  background: linear-gradient(180deg, #f8f9fa 0%, #e9ecef 100%);\n  border-bottom: 4px double #495057;\n  padding: 2.5em 2em;\n  text-align: center;\n}\n\n.quarto-title-banner .title {\n  color: #212529 !important;\n  font-size: 2.2em !important;\n  font-weight: 700;\n  letter-spacing: 0.02em;\n  text-transform: uppercase;\n  font-family: 'Noto Sans JP', sans-serif;\n}\n\n/* 見出しのアカデミックスタイル */\nh1 {\n  font-size: 1.8em;\n  font-weight: 700;\n  color: #1a1a1a;\n  border-bottom: 2px solid #212529;\n  padding-bottom: 0.5em;\n  margin-top: 2em;\n  margin-bottom: 1em;\n  text-transform: uppercase;\n  letter-spacing: 0.03em;\n}\n\nh2 {\n  font-size: 1.4em;\n  font-weight: 600;\n  color: #343a40;\n  margin-top: 1.5em;\n  margin-bottom: 0.8em;\n}\n\nh2:before {\n  content: \"§\";\n  margin-right: 0.5em;\n  color: #6c757d;\n  font-weight: 400;\n}\n\nh3 {\n  font-size: 1.2em;\n  font-weight: 600;\n  color: #495057;\n  font-style: italic;\n  margin-top: 1.2em;\n  margin-bottom: 0.6em;\n}\n\n/* テーブルを学術論文風に */\ntable {\n  margin: 2em auto;\n  border-collapse: collapse;\n  font-size: 0.95em;\n  width: 90%;\n  border-top: 2px solid #212529;\n  border-bottom: 2px solid #212529;\n}\n\nthead {\n  background: #f8f9fa;\n  border-bottom: 1px solid #212529;\n}\n\n/* コードブロックをシンプルに */\npre {\n  background: #f8f9fa !important;\n  border: 1px solid #dee2e6;\n  border-radius: 0;\n  padding: 1em;\n  font-size: 0.9em;\n}\n\n/* 数式を強調 */\n.math {\n  color: #212529;\n  font-size: 1.05em;\n  font-style: italic;\n}\n</style>\n```\n\n# はじめに\n\n5章では GLM/GAM の使い分けを扱いました。次の実務課題は、\n**データの独立性が崩れる場面**です。\n\n英語教育データでは「同じ学習者が複数のペアに登場する」「同じテスト項目に複数の学習者が回答する」\nといった**繰り返し構造**がほぼ必ず存在します。\nこのとき GLM を使うと、実際には独立でない観測を独立と見なすことになり、\n標準誤差が過小評価され、p 値が楽観的に出てしまいます[@baayen2008; @meteyard2020]。\n\nこの問題に対する標準解が\n**一般化線形混合効果モデル（GLMM）**です。\nGLMM は、報告したい効果（固定効果）と個人差・項目差（ランダム効果）を\n同時にモデル化することで、標準誤差を**正直に**推定します[@bates2015]。\nSLA（第二言語習得）分野でも GLMM は標準ツールとなっており、\n@cunnings2012 と @linck2015 が分野に特化したチュートリアルを提供しています。\n2値言語データに対するロジット混合モデルの有効性も、\n複数の方法論研究で一貫して示されてきました[@jaeger2008; @quene2008]。\n\n本章では、実データを用いて 2値ロジスティック GLMM を\n「最小モデルから診断・報告まで」一気通貫で実装します。\n\n::: {.callout-tip}\n## この章の到達目標\n\n- GLM と GLMM を同一データで比較し、ランダム効果の必要性を説明できる。\n- 交差分類ランダム効果（sender / receiver）を実装できる。\n- ICC とデザインエフェクトを用いて、独立性仮定の破れを説明できる。\n- OR と予測確率を併記して、読み手に伝わる結果提示ができる。\n- 特異適合・過分散・残差の点検を、最小限の手順で実行できる。\n:::\n\n::: {.callout-note}\n## Conventions\n\n- Figure labels/titles are in English to avoid mojibake across environments.\n- All code chunks are R (```{r}). HTML/CSS is used only for chapter styling.\n- モデル比較は「解釈可能性」を優先し、必要最小限の複雑さを採用する。\n:::\n\n# GLMM が必要になる理由（最短版）\n\n::: {.callout-important}\n### GLM と GLMM の核心的な違い\n\nGLM は**推定値そのもの**（β）を大きく変えるわけではありません。GLMM の本質は**標準誤差を正直にする**ことにあります。\n\n- **GLM**: 全ペアが独立と仮定 → SE が過小 → p 値が楽観的\n- **GLMM**: sender/receiver の繰り返しを考慮 → SE が適切 → p 値が正直\n\nつまり、GLMM は「効果を見つける」ためではなく、「効果の不確かさを正しく評価する」ために使います。\n:::\n\n## GLMM の数学的表現\n\n2値 GLMM は次で表されます[@nelder1972; @bates2015]。\n\n$$\ng(p_{ij}) = \\mathbf{x}_{ij}^\\top\\beta + \\mathbf{z}_{ij}^\\top b,\n\\quad b \\sim \\mathcal{N}(0, \\Sigma)\n$$\n\nこの式を日本語で読み下すと：\n\n> **ペア $ij$ の助言確率 $p_{ij}$ をリンク関数 $g()$ で変換した値は、「固定効果（全員に共通の平均的効果 $\\beta$）」と「ランダム効果（個人ごとの偏り $b$）」の和で表される。ランダム効果 $b$ は平均ゼロの正規分布から生成される。**\n\nもう少し直感的に言えば：\n\n- **固定効果 $\\beta$**（報告したい効果）: 「同クラスだと助言しやすい」「スコアが高いと助言しやすい」など、研究で検証したい平均的な効果\n- **ランダム効果 $b$**（統制したいばらつき）: 「田中さんは全般に助言をよくする」「鈴木さんは助言をあまり受けない」など、個人ごとの偏り\n\n::: {.callout-tip}\n### この式がピンとこない場合\n\n数式よりもコードで理解したいタイプの方には、以下の入門チュートリアルを先に読むことをお勧めします。\n\n1. @winter2013 — 言語学データの例で、線形モデルから混合モデルへの拡張を段階的に解説。\n2. @brown2021 — 心理学データを使い、`lme4` での実装を一から追える R チュートリアル。\n3. @debruine2021 — 「自分でデータを生成して、ランダム効果が何をしているか体感する」という独自のアプローチ。数式の意味が腑に落ちます。\n\nいずれも本章の前提知識として有用ですが、**本章だけでも完結する設計**になっています。\n:::\n\n::: {.callout-note}\n### 交差分類 vs 入れ子\n\n- **入れ子（nested）**: 生徒がクラスにのみ属する形（例：生徒 1-10 はクラス A、11-20 はクラス B）。`(1 | class/student)` で実装。\n- **交差分類（crossed）**: 本データでは sender と receiver が同じ 30 人のプールから出ている。sender 1 は receiver 2, 3, ... 29 と全員のペアを作る。`(1 | sender) + (1 | receiver)` で実装。\n\n英語教育では「学習者差」「項目差」が同時に入る交差分類が多いです[@baayen2008; @barr2013; @quene2008]。\n:::\n\n## GLMM でもリンク関数は選べる\n\n本章の主モデルは `logit` ですが、GLMM でも `probit` や `cloglog` を選択できます。\n実装上は `glmer(..., family = binomial(link = \\\"...\\\"))` を変えるだけです。\n\n- `logit`: OR 解釈が可能（実務上もっとも扱いやすい）\n- `probit`: 潜在正規尺度での解釈（確率予測は logit と近いことが多い）\n- `cloglog`: 非対称リンク。離散時間ハザードの文脈と整合的[@prentice1978]\n\nリンクの候補は `stats::family` / `stats::make.link` を参照してください\n[@rstatsfamily; @rmakelink]。また、`log-log` は `cloglog` の反転関係として扱えます\n[@vgamcloglog]。\n\n# 実行前ガイド（実務フロー）\n\n以下のフローチャートが本章全体の分析手順です。\n\n```{mermaid}\n%%| fig-width: 8\nflowchart TD\n    A[GLM で基準線を作成] --> B[ICC / DEFF で依存性を確認]\n    B --> C{ICC が無視できる?}\n    C -->|Yes| D[GLM で報告]\n    C -->|No| E[GLMM ランダム切片を追加]\n    E --> F{isSingular = FALSE?}\n    F -->|Yes| G[ランダム傾きを試行]\n    F -->|No| H[ランダム構造を簡素化]\n    G --> I{isSingular = FALSE?}\n    I -->|Yes| J[ランダム傾きモデルを候補に]\n    I -->|No| K[ランダム切片モデルに戻す]\n    J --> L[AIC / LRT でモデル比較]\n    K --> L\n    H --> L\n    L --> M[OR 表 + 応答スケール予測]\n    M --> N[DHARMa + 過分散テストで最終診断]\n    N --> O[結果報告]\n\n    style A fill:#e8f4fd\n    style O fill:#d4edda\n    style C fill:#fff3cd\n    style I fill:#fff3cd\n```\n\n## モデル前提チェックリスト（GLMM）\n\nGLMM の前提は「正規残差」ではなく、次の**構造的条件**を確認することです\n[@bolker2009; @meteyard2020; @glmmfaq]。\n\n1. `outcome` と `family/link` が整合しているか（本章は 2値 + logit）。\n2. 群化構造（sender/receiver）が研究設計に一致しているか。\n3. ランダム効果構造が過剰でないか（`isSingular()`, `rePCA()`）。\n4. 過分散・残差の大きな破綻がないか（`DHARMa`, `check_overdispersion()`）。\n5. 固定効果の推定が不安定でないか（`check_collinearity()`）。\n\n::: {.callout-important}\n### よくある誤解：「残差が正規分布でないからダメ」\n\nGLM/GLMM では **アウトカムの正規性は仮定していません**。family（本章では `binomial`）がアウトカムの型と整合していれば、残差の正規性はそもそも問題になりません。上の 5 項目が GLMM の本当のチェックポイントです。\n\nなお、混合モデルは分布仮定からの軽度な逸脱に対して比較的頑健であることが、大規模シミュレーション研究で確認されています[@schielzeth2020]。\n:::\n\n::: {.callout-tip}\n### 本章での対応関数\n\n- 構造比較: `compare_performance()`, `anova(..., test=\"Chisq\")`\n- 特異適合: `isSingular()`, `performance::check_singularity()`, `rePCA()`\n- 残差診断: `DHARMa::simulateResiduals()`, `testDispersion()`, `testUniformity()`\n- 補助診断: `check_overdispersion()`, `check_collinearity()`, `check_model()`\n:::\n\n# パッケージと共通関数\n\nGLMM 分析に必要なパッケージを読み込みます。主要パッケージの役割：\n\n| パッケージ | 役割 |\n|-----------|------|\n| `lme4` | GLMM の推定（`glmer()`）|\n| `performance` | モデル比較、ICC、R²、診断（`compare_performance()`, `icc()`, `r2_nakagawa()`）|\n| `emmeans` | 推定周辺平均と事後比較 |\n| `DHARMa` | シミュレーションベースの残差診断 |\n| `sjPlot` | モデル比較表と予測プロット |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- パッケージ読み込み ---\n# pacman::p_load() は未インストールのパッケージを自動でインストールしてから読み込む\npacman::p_load(\n  tidyverse,   # データ操作・可視化（dplyr, ggplot2 等）\n\n  lme4,        # GLMM の推定（glmer）\n  performance, # ICC, R², モデル比較, 診断\n  emmeans,     # 推定周辺平均（事後比較）\n  DHARMa,      # シミュレーション残差診断\n  sjPlot,      # モデル比較表・予測プロット\n  gt           # きれいな表の作成\n)\n\n# --- 共通設定 ---\ntheme_set(theme_bw())   # ggplot2 のデフォルトテーマ\nset.seed(20260220)      # 乱数の再現性を確保\n\n# --- 自作ヘルパー関数 ---\n# 複数モデルの AIC/BIC を一覧表にまとめる関数\n# 使い方: make_ic_table(\"モデル名1\" = model1, \"モデル名2\" = model2)\nmake_ic_table <- function(...) {\n  models <- list(...)\n  names(models) |>\n    purrr::map_dfr(function(nm) {\n      m <- models[[nm]]\n      tibble(\n        model = nm,\n        AIC = suppressWarnings(AIC(m)),\n        BIC = suppressWarnings(BIC(m)),\n        logLik = as.numeric(logLik(m))\n      )\n    }) |>\n    arrange(AIC)  # AIC が小さい順に並べる\n}\n```\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n### `make_ic_table()` とは？（クリックで展開）\n\n`make_ic_table()` は本章で繰り返し使うヘルパー関数です。複数のモデルを渡すと、AIC・BIC・対数尤度を一覧表にして AIC の小さい順に並べます。`performance::compare_performance()` と似た機能ですが、軽量で出力がシンプルなため、ランダム効果構造の候補比較に使います。\n:::\n\n# データ準備（実データ）\n\n本章は `data/network` の実データを使います。\n\n- `nodes.csv`: 助言ネットワークの学習者属性（`id`, `class`, `proficiency`）\n- `edges_directed_advice.csv`: 有向助言関係（from → to）\n- `nodes_collaboration.csv`: ベースライン得点（共変量に使用）\n\n以下のコードでは、ノード属性と助言エッジを読み込み、`proficiency` を順序つきファクター（A2 < B1 < B2）に変換し、ベースラインスコアを標準化（z スコア）します。`factor()` への変換は、後に `glmer()` がグループ変数を正しく認識するために必要です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── CSV ファイルの読み込み ──\nnodes_advice <- readr::read_csv(\"data/network/nodes.csv\",\n                                show_col_types = FALSE)\n\nnodes_collab <- readr::read_csv(\"data/network/nodes_collaboration.csv\",\n                                show_col_types = FALSE) |>\n  dplyr::select(id, baseline_score)  # 必要な列だけ選択\n\nedges_advice <- readr::read_csv(\"data/network/edges_directed_advice.csv\",\n                                show_col_types = FALSE)\n\n# ── 変数の前処理 ──\nprof_levels <- c(\"A2\", \"B1\", \"B2\")          # 順序を定義\nprof_map    <- c(A2 = 1, B1 = 2, B2 = 3)   # 数値に変換するマップ\n\nnodes <- nodes_advice |>\n  left_join(nodes_collab, by = \"id\") |>     # ベースラインスコアを結合\n  mutate(\n    class = factor(class),                                        # ファクター化\n    proficiency = factor(proficiency, levels = prof_levels),       # 順序付きファクター\n    prof_num = unname(prof_map[as.character(proficiency)]),        # 数値化（差の計算用）\n    baseline_score_sc = as.numeric(scale(baseline_score))          # z 標準化\n  )\n\nsummary(nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      id            class  proficiency baseline_score     prof_num  \n Length:30          A:10   A2: 9       Min.   :50.10   Min.   :1.0  \n Class :character   B:10   B1:15       1st Qu.:53.00   1st Qu.:1.0  \n Mode  :character   C:10   B2: 6       Median :58.25   Median :2.0  \n                                       Mean   :58.82   Mean   :1.9  \n                                       3rd Qu.:63.55   3rd Qu.:2.0  \n                                       Max.   :71.30   Max.   :3.0  \n baseline_score_sc \n Min.   :-1.40416  \n 1st Qu.:-0.93700  \n Median :-0.09128  \n Mean   : 0.00000  \n 3rd Qu.: 0.76249  \n Max.   : 2.01093  \n```\n\n\n:::\n:::\n\n\n`summary()` の出力で確認すべき点：\n\n- **class**: 各クラスの人数バランス。極端な偏りがあるとランダム効果の推定が不安定になる。\n- **proficiency**: A2/B1/B2 の分布。3水準が揃っているか。\n- **baseline_score_sc**: 平均≈0、SD≈1 になっていれば標準化は正常。\n\n# 分析データ作成（有向ペア単位）\n\n`sender != receiver` の全有向ペアを作り、\n各ペアが実際に助言エッジとして観測されたか（`tie`）を 0/1 で定義します。\n\n**変数名のポイント**: `sender`/`receiver` という命名にしておくと、後の `glmer()` 式で `(1 | sender) + (1 | receiver)` と書くだけで交差分類ランダム効果が実装でき、コードの可読性が上がります。また、`factor()` への変換は `lme4` がランダム効果のグループ変数を正しく認識するために必須です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── 全有向ペアを生成（自分自身は除外）──\ndat_bin <- tidyr::crossing(\n  sender   = nodes$id,\n  receiver = nodes$id\n) |>\n  filter(sender != receiver) |>\n\n  # sender 側の属性を結合\n  left_join(\n    nodes |>\n      dplyr::select(sender = id, class_sender = class,\n                    prof_sender = proficiency, prof_sender_num = prof_num,\n                    score_sender_sc = baseline_score_sc),\n    by = \"sender\"\n  ) |>\n\n  # receiver 側の属性を結合\n  left_join(\n    nodes |>\n      dplyr::select(receiver = id, class_receiver = class,\n                    prof_receiver = proficiency, prof_receiver_num = prof_num,\n                    score_receiver_sc = baseline_score_sc),\n    by = \"receiver\"\n  ) |>\n\n  mutate(\n    # ── 予測子の作成 ──\n    same_class = as.integer(class_sender == class_receiver),  # 同クラスなら 1\n    prof_gap   = abs(prof_sender_num - prof_receiver_num),    # 熟達度差（0, 1, 2）\n    score_gap  = abs(score_sender_sc - score_receiver_sc),    # スコア差（連続量）\n\n    # ── アウトカム：助言エッジがあるか ──\n    tie = as.integer(\n      paste(sender, receiver) %in% paste(edges_advice$from, edges_advice$to)\n    ),\n\n    # ── glmer のランダム効果に必要なファクター化 ──\n    sender   = factor(sender),\n    receiver = factor(receiver)\n  )\n\n# ── データの概要を確認 ──\ntibble(\n  `全ペア数`     = nrow(dat_bin),\n  `助言あり`     = sum(dat_bin$tie),\n  `ベースレート` = mean(dat_bin$tie) |> round(3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  全ペア数 助言あり ベースレート\n     <int>    <int>        <dbl>\n1      870      154        0.177\n```\n\n\n:::\n:::\n\n\n出力の読み方：\n\n| 指標 | 確認ポイント |\n|------|------------|\n| `全ペア数` | 全有向ペア数 = $n \\times (n-1)$（n は学習者数）。30人なら 870 行 |\n| `助言あり` | 実際に助言関係があったペア数 |\n| `ベースレート` | 助言関係の割合。**極端に低い**（< 0.05）場合は完全分離のリスクあり |\n\n::: {.callout-important}\n### ベースレートと依存構造\n\n`tie_rate` が低いということは、大半のペアで `tie = 0` であることを意味します。このようなスパースなデータでは、各学習者が複数のペアに繰り返し出現するという依存構造（sender が 29 回、receiver が 29 回出現）が推定に大きく影響します。GLM はこの依存を無視するため、標準誤差が過小評価される典型的な場面です。\n:::\n\n# 階層性の確認: ICC とデザインエフェクト\n\nこのデータは「有向ペア」が観測単位ですが、観測は sender / receiver に跨って\n繰り返し出現します。したがって独立性仮定は破れやすく、GLM 単独では\n標準誤差が過小になる可能性があります[@snijders2012; @hox2018]。\n\n## 交差分類データ構造（本章データ）\n\n- Level 1: 有向ペア（sender → receiver）\n- 高次構造: sender と receiver の**交差分類ランダム効果**\n- 重要点: 厳密な単純階層（生徒がクラスにのみ入る形）ではないため、\n  ICC/DEFF は「構造把握の近似指標」として使う\n\n## null GLMM で ICC を推定\n\nICC（級内相関係数）を推定するために、まず固定効果を含まない**空モデル（null model）**を当てはめます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── Step 1: 空モデルを当てはめる ──\n# tie ~ 1 は「切片だけ」（固定効果なし）\n# (1 | sender) + (1 | receiver) は交差分類ランダム切片\nm_null <- glmer(\n  tie ~ 1 + (1 | sender) + (1 | receiver),\n  family = binomial(link = \"logit\"),\n  data = dat_bin,\n  control = glmerControl(\n    optimizer = \"bobyqa\",           # 収束しやすい最適化手法\n    optCtrl = list(maxfun = 2e5)    # 最大反復回数を増やす\n  )\n)\n```\n:::\n\n\n### 方法 A: `performance::icc()` で一発計算（実務向け）\n\n実務では `performance::icc()` を使うのが最もシンプルです。\n内部でロジスティック分布の残差分散（$\\pi^2/3$）を自動的に考慮してくれます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::icc(m_null)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.122\n  Unadjusted ICC: 0.122\n```\n\n\n:::\n:::\n\n\n`performance::icc()` は adjusted ICC（条件付き）と unadjusted ICC（周辺）を返します[@performance_icc]。\nnull モデルでは固定効果がないため両者は実質同じ値です。\n\n### 方法 B: 手計算で原理を理解する\n\n`performance::icc()` の中身を理解するために、ICC を手計算してみましょう。\nロジスティック GLMM では、Level 1 の残差分散を $\\pi^2/3 \\approx 3.29$ と近似する\n「潜在変数法」が標準的です[@snijders2012; @hox2018]。\n\n$$\n\\mathrm{ICC}_{\\mathrm{sender}}\n= \\frac{\\sigma^2_{\\mathrm{sender}}}\n       {\\sigma^2_{\\mathrm{sender}} + \\sigma^2_{\\mathrm{receiver}} + \\pi^2/3}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ランダム効果の分散を取り出す\nvc <- as.data.frame(VarCorr(m_null))\nvar_sender   <- vc |> filter(grp == \"sender\")   |> pull(vcov)\nvar_receiver <- vc |> filter(grp == \"receiver\") |> pull(vcov)\nvar_logistic <- (pi^2) / 3   # ≈ 3.29（ロジスティック分布の残差分散）\n\n# ICC を手計算\nicc_sender   <- var_sender   / (var_sender + var_receiver + var_logistic)\nicc_receiver <- var_receiver / (var_sender + var_receiver + var_logistic)\nicc_total    <- (var_sender + var_receiver) /\n                (var_sender + var_receiver + var_logistic)\n\ntibble(\n  component = c(\"sender ICC\", \"receiver ICC\", \"total clustered share\"),\n  estimate  = c(icc_sender, icc_receiver, icc_total)\n) |>\n  gt() |>\n  fmt_number(columns = estimate, decimals = 3) |>\n  tab_header(title = \"ICC（手計算：潜在変数近似）\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ICC（手計算：潜在変数近似）\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\ncomponent & estimate \\\\ \n\\midrule\\addlinespace[2.5pt]\nsender ICC & 0.039 \\\\ \nreceiver ICC & 0.082 \\\\ \ntotal clustered share & 0.122 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-tip}\n### ICC の読み方\n\n| 値 | 意味 |\n|----|------|\n| **sender ICC** | 助言行動のばらつきのうち、「誰が送り手か」で説明される割合 |\n| **receiver ICC** | 「誰が受け手か」で説明される割合 |\n| **total** | 両方を合わせた群内相関。GLM → GLMM の必要性の主要な根拠 |\n\n方法 A と方法 B の値がほぼ一致することを確認してください。一致していれば、`performance::icc()` が正しく潜在変数近似を使っていることがわかります。\n:::\n\n## デザインエフェクト（DEFF）の近似\n\nDEFF（デザインエフェクト）は、「独立性仮定が破れることで、実効サンプルサイズがどれだけ縮小するか」を示す指標です。DEFF = 2 なら、見かけのサンプルサイズの半分しか情報がないことを意味します。以下では ICC と平均クラスターサイズから DEFF を近似計算します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 各 sender / receiver が何ペアに登場するか（= 平均クラスターサイズ）\nm_sender   <- dat_bin |> count(sender)   |> summarise(mean_n = mean(n)) |> pull()\nm_receiver <- dat_bin |> count(receiver) |> summarise(mean_n = mean(n)) |> pull()\n\n# DEFF = 1 + (クラスターサイズ - 1) × ICC\ndeff_sender   <- 1 + (m_sender - 1)   * icc_sender\ndeff_receiver <- 1 + (m_receiver - 1) * icc_receiver\ndeff_total    <- 1 + (mean(c(m_sender, m_receiver)) - 1) * icc_total\n\n# 実効サンプルサイズ = 観測数 / DEFF\nn_obs       <- nrow(dat_bin)\nn_effective <- n_obs / deff_total\n\ntibble(\n  quantity = c(\n    \"観測数（ペア数）\",\n    \"平均クラスターサイズ（sender）\",\n    \"平均クラスターサイズ（receiver）\",\n    \"DEFF sender\", \"DEFF receiver\", \"DEFF total\",\n    \"実効サンプルサイズ ≈ 観測数 / DEFF total\"\n  ),\n  value = c(n_obs, m_sender, m_receiver,\n            deff_sender, deff_receiver, deff_total,\n            n_effective)\n) |>\n  gt() |>\n  fmt_number(columns = value, decimals = 1) |>\n  tab_header(title = \"Design Effect（DEFF）の近似計算\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Design Effect（DEFF）の近似計算\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nquantity & value \\\\ \n\\midrule\\addlinespace[2.5pt]\n観測数（ペア数） & 870.0 \\\\ \n平均クラスターサイズ（sender） & 29.0 \\\\ \n平均クラスターサイズ（receiver） & 29.0 \\\\ \nDEFF sender & 2.1 \\\\ \nDEFF receiver & 3.3 \\\\ \nDEFF total & 4.4 \\\\ \n実効サンプルサイズ ≈ 観測数 / DEFF total & 197.4 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**DEFF 表の読み方**：\n\n| 指標 | 解釈 |\n|------|------|\n| 平均クラスターサイズ | 各 sender/receiver が関与するペア数の平均（n-1 に近い）|\n| DEFF sender / receiver | 繰り返し構造による情報の目減り。**1 なら独立と同等**、大きいほど深刻 |\n| DEFF total | 両方を合わせた概算 |\n| 実効サンプルサイズ | **表の最終行が実効 N** です。観測数との差が大きいほど、GLM の SE は楽観的すぎる |\n\n単純階層データでは $\\mathrm{DEFF}=1+(m-1)\\mathrm{ICC}$ が標準式です[@kish1965]。\n本章は交差分類なので厳密適用ではありませんが、**独立性違反の強さを概観する**\n目的には有用です。DEFF が 1 から離れるほど、GLM の独立性仮定は危うくなります。\n\n::: {.callout-note}\n### 実務での読み方（ICC/DEFF）\n\n- ICC が 0 に近い: 群内相関は小さく、GLM と GLMM の差は小さいことが多い。\n- ICC が中程度以上: GLMM を優先し、標準誤差の過小評価を避ける。\n- DEFF が 1 を大きく超える: 独立性仮定の破れが大きい可能性がある。\n- 交差分類では ICC/DEFF は「採用判断の補助」であり、最終判断は\n  `compare_performance()` と診断を併用する。\n:::\n\n# ステップ1: GLM（基準モデル）\n\nまずランダム効果なしのロジスティック回帰で基準線を作ります。この GLM は「全ペアが独立」と仮定しており、sender/receiver の繰り返し構造を無視しています。**目的は GLMM との比較基準を作ること**であり、このモデル自体を最終モデルとして採用するわけではありません。\n\n固定効果の意味：\n\n| 予測子 | 意味 |\n|--------|------|\n| `same_class` | 同じクラスに所属するペアか（0/1）|\n| `prof_gap` | 熟達度水準の差の絶対値（0, 1, 2）|\n| `score_sender_sc` | 送り手のベースラインスコア（z 標準化）|\n| `score_receiver_sc` | 受け手のベースラインスコア（z 標準化）|\n| `score_gap` | スコア差の絶対値 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ランダム効果なしの標準ロジスティック回帰（比較基準）\nm_glm <- glm(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap,\n  family = binomial(link = \"logit\"),  # 2値 → ロジスティック\n  data = dat_bin\n)\n\nsummary(m_glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = tie ~ same_class + prof_gap + score_sender_sc + \n    score_receiver_sc + score_gap, family = binomial(link = \"logit\"), \n    data = dat_bin)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)       -2.25795    0.22894  -9.862  < 2e-16 ***\nsame_class         1.30664    0.18604   7.023 2.16e-12 ***\nprof_gap           0.39316    0.14193   2.770   0.0056 ** \nscore_sender_sc    0.02408    0.09461   0.255   0.7991    \nscore_receiver_sc  0.05150    0.09462   0.544   0.5862    \nscore_gap         -0.10573    0.11750  -0.900   0.3682    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 812.29  on 869  degrees of freedom\nResidual deviance: 755.20  on 864  degrees of freedom\nAIC: 767.2\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n**`summary(m_glm)` の読み方**：\n\n| 出力項目 | 読み方 |\n|---------|--------|\n| `Estimate` | logit スケールでの係数。正なら助言関係の **オッズが増加** する方向 |\n| `Std. Error` | 係数の標準誤差。**GLM はペアの独立性を仮定しているため、この SE は過小評価の可能性が高い** |\n| `z value` | Estimate / SE。Wald 検定統計量 |\n| `Pr(>\\|z\\|)` | 帰無仮説（係数 = 0）の p 値 |\n| `AIC` | モデルの相対的な当てはまり。後で GLMM の AIC と比較する |\n\n::: {.callout-warning}\n### この GLM の SE をそのまま信用しない\n\nICC/DEFF の分析で見たとおり、このデータには sender/receiver による依存構造があります。GLM はこの構造を無視するため、標準誤差が過小に見積もられ、**p 値が本来より小さく出ている可能性**があります。次のステップで GLMM に移行した際に、SE がどのように変化するか（通常は大きくなる）を確認してください。\n:::\n\n# ステップ2: GLMM（ランダム切片）\n\n次に sender / receiver のランダム切片を追加します。`(1 | sender) + (1 | receiver)` は「各送り手と各受け手が、全体平均からどれだけ偏るか」を推定する項です。\n\n- `(1 | sender)`: 「助言をしやすい人/しにくい人」の個人差\n- `(1 | receiver)`: 「助言を受けやすい人/受けにくい人」の個人差\n- この 2 つは **交差分類**（同じ 30 人のプールから sender と receiver が出ている）\n\n`control = glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e5))` は、デフォルトの最適化アルゴリズムでは収束しにくい場合の標準対処です。`bobyqa`（制約付き最適化）と最大反復回数の増加を組み合わせています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GLMM: 交差分類ランダム切片（sender + receiver）\nm_glmm_ri <- glmer(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap +\n    (1 | sender) +    # sender のランダム切片（助言をしやすい/しにくい個人差）\n    (1 | receiver),   # receiver のランダム切片（助言を受けやすい/受けにくい個人差）\n  family = binomial(link = \"logit\"),\n  data = dat_bin,\n  control = glmerControl(\n    optimizer = \"bobyqa\",         # 収束しやすい最適化手法\n    optCtrl = list(maxfun = 2e5)  # 最大反復回数\n  )\n)\n\nsummary(m_glmm_ri)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc +  \n    score_gap + (1 | sender) + (1 | receiver)\n   Data: dat_bin\nControl: glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e+05))\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n    753.7     791.8    -368.8     737.7       862 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.3073 -0.4590 -0.3101 -0.2473  4.0508 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n sender   (Intercept) 0.1810   0.4254  \n receiver (Intercept) 0.3246   0.5697  \nNumber of obs: 870, groups:  sender, 30; receiver, 30\n\nFixed effects:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)       -2.38262    0.27974  -8.517  < 2e-16 ***\nsame_class         1.40516    0.19496   7.208  5.7e-13 ***\nprof_gap           0.35095    0.16248   2.160   0.0308 *  \nscore_sender_sc    0.04818    0.12557   0.384   0.7012    \nscore_receiver_sc  0.03917    0.14555   0.269   0.7878    \nscore_gap         -0.12725    0.12783  -0.995   0.3195    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) sm_cls prf_gp scr_s_ scr_r_\nsame_class  -0.427                            \nprof_gap    -0.504  0.105                     \nscr_sndr_sc  0.043  0.023 -0.076              \nscr_rcvr_sc  0.054 -0.007 -0.064 -0.012       \nscore_gap   -0.525  0.037  0.023 -0.057 -0.043\n```\n\n\n:::\n:::\n\n\n**`summary(m_glmm_ri)` の読み方**：\n\nGLMM の出力は GLM と構造が似ていますが、**ランダム効果の分散成分**が追加されています。\n\n**ランダム効果セクション**：\n\n| 出力項目 | 読み方 |\n|---------|--------|\n| `Groups` / `Name` | ランダム効果のグループ変数と項（ここでは sender と receiver の切片）|\n| `Variance` | そのグループの分散。**大きいほど個人差が大きい** |\n| `Std.Dev.` | 分散の平方根（logit スケール）。0.5 以上なら実質的な個人差がある |\n| `Number of obs` / `groups` | 観測数とグループ数 |\n\n**固定効果セクション**：GLM と同じ列構成ですが、**SE が GLM より大きくなっている**はずです。これが GLMM の本質的な効果——依存構造を考慮することで SE が「正直に」なるのです。\n\n::: {.callout-important}\n### GLM と GLMM の SE を比較する\n\n`summary(m_glm)` と `summary(m_glmm_ri)` の SE を並べて見てください。GLMM の SE が GLM より大きくなっていれば、GLM が独立性仮定のもとで SE を過小評価していた証拠です。**推定値（Estimate）自体はそれほど変わらないが、SE が変わる**——これが GLMM の核心です。「GLMM は推定値を変えるのではなく、精度の主張を正直にする」と理解してください。\n:::\n\n分散成分の大きさを直感的に解釈するには、ロジスティック分布の残差分散 $\\pi^2/3 \\approx 3.29$ と比較します。sender 分散が 0.5、receiver 分散が 0.3 なら、残差（$\\pi^2/3$）に対する比率はそれぞれ約 15%、9% であり、sender 側の個人差がより大きいことがわかります。\n\n# ステップ3: ランダム傾き候補と特異適合\n\nランダム切片モデルは「全体平均からの偏り」だけを推定しますが、**ランダム傾きモデル**は「固定効果の強さ自体が個人ごとに異なるか」を検討します。\n\nここでは `(1 + same_class | sender)` を試します。これは「same_class の効果が sender ごとに異なるか」——つまり「同クラスを好む傾向に送り手間の個人差があるか」を意味します。ただし、ランダム構造が過剰だとモデルが **特異適合（singular fit）** を起こし、分散成分が 0 に張り付くことがあります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GLMM: ランダム傾き追加（same_class の効果が sender ごとに異なるか？）\nm_glmm_rs <- glmer(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap +\n    (1 + same_class | sender) +  # 切片 + same_class の傾きを sender ごとに推定\n    (1 | receiver),\n  family = binomial(link = \"logit\"),\n  data = dat_bin,\n  control = glmerControl(\n    optimizer = \"bobyqa\",\n    optCtrl = list(maxfun = 2e5)\n  )\n)\n\n# 特異適合の確認：FALSE なら安全、TRUE なら過剰パラメータ化\nisSingular(m_glmm_ri)  # ランダム切片モデル\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nisSingular(m_glmm_rs)  # ランダム傾き追加モデル\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n**`isSingular()` の読み方**：\n\n- `FALSE` → 特異適合ではない。ランダム効果構造は推定可能。\n- `TRUE` → **特異適合が発生**。分散成分の一部が 0 に張り付いている。\n\n::: {.callout-warning}\n### 特異適合が起きたときの対処法\n\n1. **無視しない**: 特異適合はモデルの過剰パラメータ化の徴候であり、推定結果の信頼性に影響する。\n2. **ランダム構造を簡素化**: ランダム傾きを落とし、ランダム切片モデルに戻す。\n3. **試みたことを報告**: 論文では「ランダム傾きを試みたが特異適合が生じたため、ランダム切片モデルを採用した」と書くことが推奨される[@bates2015parsimonious; @matuschek2017]。SLA 分野での具体的な判断例は @linck2015 を参照。\n\n本データでは、`m_glmm_ri`（ランダム切片のみ）が `FALSE` であれば安全に使用でき、`m_glmm_rs`（ランダム傾き追加）が `TRUE` であれば、ランダム切片モデルに留めるのが実務上の正解です。\n:::\n\n# モデル比較ワークフロー\n\nステップ 1–3 でモデルの候補がそろいました。ここからはモデル比較に入ります。GLMM のモデル比較は **3 段階**で進めるのが定石です[@bolker2009; @barr2013; @bates2015parsimonious; @matuschek2017; @meteyard2020; @glmmfaq]。\n\n```{mermaid}\n%%| fig-cap: \"GLMM モデル比較の全体フロー\"\nflowchart TD\n    A[\"① ランダム効果構造の比較\\n（固定効果は固定のまま）\"] --> B[\"② リンク関数の選択\\n（logit / probit / cloglog）\"]\n    B --> C[\"③ 固定効果の比較\\n（ランダム構造は固定のまま）\"]\n    C --> D[\"最終モデル確定 → 解釈・診断へ\"]\n    style A fill:#4682b4,color:#fff\n    style B fill:#5f9ea0,color:#fff\n    style C fill:#6b8e23,color:#fff\n    style D fill:#cd853f,color:#fff\n```\n\n**ΔAIC の目安**（全ステップ共通）：\n\n| ΔAIC | 解釈 |\n|------|------|\n| 0–2 | ほぼ同等。パラメータの少ないモデルを選ぶのが倹約的 |\n| 4–7 | 中程度の証拠。ΔAIC が大きい側のモデルは劣る可能性 |\n| 10+ | 強い証拠。ΔAIC が大きい側のモデルは実質的に支持されない |\n\n## ① ランダム効果構造の比較\n\n::: {.callout-important}\n### モデル比較の鉄則：一度に動かすのは一つだけ\n\nランダム効果構造と固定効果を同時に変えると、何が改善に寄与したか分からなくなります。手順は：\n\n1. **固定効果を固定** → ランダム効果構造を比較（①）\n2. **ランダム構造を固定** → リンク関数を比較（②）\n3. **ランダム構造・リンクを固定** → 固定効果を比較（③）\n:::\n\nまず sender / receiver の組み合わせを変えた候補を推定し、GLM（ランダム効果なし）とステップ 2–3 で推定済みの `m_glmm_ri`・`m_glmm_rs` を含めて一括比較します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 候補1: sender のランダム切片のみ\nm_glmm_sender <- glmer(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap +\n    (1 | sender),\n  family = binomial(link = \"logit\"),\n  data = dat_bin,\n  control = glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e5))\n)\n\n# 候補2: receiver のランダム切片のみ\nm_glmm_receiver <- glmer(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap +\n    (1 | receiver),\n  family = binomial(link = \"logit\"),\n  data = dat_bin,\n  control = glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e5))\n)\n# 候補3: m_glmm_ri（sender + receiver）と候補4: m_glmm_rs（ランダム傾き追加）は既に推定済み\n\n# ── 全候補の AIC/BIC を一括比較 ──\nmake_ic_table(\n  \"GLM（ランダム効果なし）\"       = m_glm,\n  \"RI: sender のみ\"              = m_glmm_sender,\n  \"RI: receiver のみ\"            = m_glmm_receiver,\n  \"RI: sender + receiver\"        = m_glmm_ri,\n  \"RS: sender 傾き + receiver RI\" = m_glmm_rs\n) |>\n  gt() |>\n  tab_header(title = \"① ランダム効果構造の候補比較\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ① ランダム効果構造の候補比較\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrr}\n\\toprule\nmodel & AIC & BIC & logLik \\\\ \n\\midrule\\addlinespace[2.5pt]\nRI: sender + receiver & 753.6577 & 791.8057 & -368.8289 \\\\ \nRI: receiver のみ & 756.2256 & 789.6051 & -371.1128 \\\\ \nRS: sender 傾き + receiver RI & 757.6217 & 805.3066 & -368.8108 \\\\ \nRI: sender のみ & 763.9478 & 797.3273 & -374.9739 \\\\ \nGLM（ランダム効果なし） & 767.2034 & 795.8143 & -377.6017 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n**この表の読み方**：\n\n1. **GLM vs GLMM**: ΔAIC が 10 以上なら、ランダム効果の追加が適合を大幅に改善している証拠。\n2. **sender のみ vs receiver のみ vs 両方**: 両方入れることで AIC が改善しているかを確認。\n3. **ランダム傾き**: AIC が改善していても特異適合（`isSingular = TRUE`）ならば採用は避ける。\n\n`compare_performance()` で AIC/BIC/R² を同時に確認することもできます[@performance_compare]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AIC/BIC/R² を一括比較（conditional R² が marginal を大きく上回るほどランダム効果が重要）\nperformance::compare_performance(\n  m_glm, m_glmm_sender, m_glmm_receiver, m_glmm_ri, m_glmm_rs\n) |>\n  gt() |>\n  tab_header(title = \"compare_performance(): ランダム効果構造の比較\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom effect variances not available. Returned R2 does not account for random effects.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  compare\\_performance(): ランダム効果構造の比較\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrrrrrrrrrrrrrr}\n\\toprule\nName & Model & AIC & AIC\\_wt & AICc & AICc\\_wt & BIC & BIC\\_wt & RMSE & Sigma & Log\\_loss & Score\\_log & Score\\_spherical & R2\\_conditional & R2\\_marginal & ICC & R2\\_Tjur & PCP \\\\ \n\\midrule\\addlinespace[2.5pt]\nm\\_glm & glm & 767.2034 & 0.0008049832 & 767.3007 & 0.000833985 & 795.8143 & 0.0320509471 & 0.3678414 & 1 & 0.4340249 & -30.62943 & 0.008078869 & NA & NA & NA & 0.0707262 & 0.7292497 \\\\ \nm\\_glmm\\_sender & glmerMod & 763.9478 & 0.0040994387 & 764.0777 & 0.004178475 & 797.3273 & 0.0150422671 & 0.3583169 & 1 & 0.4146014 & -30.45482 & 0.007789862 & 0.1663998 & 0.1190070 & 0.05379472 & NA & NA \\\\ \nm\\_glmm\\_receiver & glmerMod & 756.2256 & 0.1947958339 & 756.3555 & 0.198551451 & 789.6051 & 0.7147737049 & 0.3540599 & 1 & 0.4038261 & -30.83709 & 0.004133575 & 0.1912066 & 0.1117708 & 0.08943163 & NA & NA \\\\ \nm\\_glmm\\_ri & glmerMod & 753.6577 & 0.7033767382 & 753.8250 & 0.703684718 & 791.8057 & 0.2378547123 & 0.3454336 & 1 & 0.3862866 & -31.02272 & 0.005517479 & 0.2305488 & 0.1123040 & 0.13320422 & NA & NA \\\\ \nm\\_glmm\\_rs & glmerMod & 757.6217 & 0.0969230061 & 757.8778 & 0.092751372 & 805.3066 & 0.0002783687 & 0.3452250 & 1 & 0.3861714 & -31.03739 & 0.005299541 & NA & 0.1262437 & NA & NA & NA \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n次に LRT（尤度比検定）でランダム効果構造を正式に比較します。LRT は **入れ子関係にあるモデル同士** でのみ有効です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 同一固定効果でのランダム構造比較（LRT）\nanova(m_glmm_sender, m_glmm_ri, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat_bin\nModels:\nm_glmm_sender: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap + (1 | sender)\nm_glmm_ri: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap + (1 | sender) + (1 | receiver)\n              npar    AIC    BIC  logLik -2*log(L) Chisq Df Pr(>Chisq)    \nm_glmm_sender    7 763.95 797.33 -374.97    749.95                        \nm_glmm_ri        8 753.66 791.81 -368.83    737.66 12.29  1  0.0004554 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(m_glmm_receiver, m_glmm_ri, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat_bin\nModels:\nm_glmm_receiver: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap + (1 | receiver)\nm_glmm_ri: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap + (1 | sender) + (1 | receiver)\n                npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)  \nm_glmm_receiver    7 756.23 789.61 -371.11    742.23                       \nm_glmm_ri          8 753.66 791.81 -368.83    737.66 4.5679  1    0.03258 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(m_glmm_ri, m_glmm_rs, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat_bin\nModels:\nm_glmm_ri: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap + (1 | sender) + (1 | receiver)\nm_glmm_rs: tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap + (1 + same_class | sender) + (1 | receiver)\n          npar    AIC    BIC  logLik -2*log(L) Chisq Df Pr(>Chisq)\nm_glmm_ri    8 753.66 791.81 -368.83    737.66                    \nm_glmm_rs   10 757.62 805.31 -368.81    737.62 0.036  2     0.9821\n```\n\n\n:::\n:::\n\n\n**LRT 出力の読み方**：\n\n| 出力項目 | 読み方 |\n|---------|--------|\n| `Chisq` | カイ二乗検定統計量。大きいほど 2 モデル間の適合差が大きい |\n| `Df` | パラメータ数の差（追加されたランダム効果の数）|\n| `Pr(>Chisq)` | p 値。有意なら、より複雑なモデルが有意に適合を改善 |\n\n::: {.callout-note}\n### 境界問題に注意\n\nランダム効果の分散はゼロ以上の制約があるため、帰無仮説（分散 = 0）はパラメータ空間の境界に位置します。このため LRT の p 値は**保守的**（やや大きめ）になる傾向があります[@self1987; @stram1994]。実務的には、LRT が有意でなくても AIC/BIC が改善していれば、ランダム効果の追加を検討する余地があります。\n:::\n\n次に特異適合の正式チェックと、ランダム効果の主成分分析（`rePCA()`）を行います。`rePCA()` はランダム効果の分散共分散行列を主成分分解し、各成分がどれだけ情報を持つかを示します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 特異適合チェック（FALSE = 安全、TRUE = 過剰パラメータ化）\nisSingular(m_glmm_ri)  # ランダム切片モデル\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nisSingular(m_glmm_rs)  # ランダム傾きモデル\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n# ランダム効果の分散共分散構造を確認（分散が 0 に近い項があれば過剰）\nVarCorr(m_glmm_rs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Std.Dev. Corr \n sender   (Intercept) 0.404061      \n          same_class  0.045834 1.000\n receiver (Intercept) 0.570698      \n```\n\n\n:::\n\n```{.r .cell-code}\n# ランダム効果の主成分分析（各成分がどれだけ情報を持つか）\n# → 1成分で 99%+ なら、ランダム傾きは実質不要\nrePCA(m_glmm_rs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sender\nStandard deviations (1, .., p=2):\n[1] 0.4066525 0.0000000\n\nRotation (n x k) = (2 x 2):\n           [,1]       [,2]\n[1,] -0.9936278 -0.1127111\n[2,] -0.1127111  0.9936278\n\n$receiver\nStandard deviations (1, .., p=1):\n[1] 0.5706983\n\nRotation (n x k) = (1 x 1):\n     [,1]\n[1,]    1\n\nattr(,\"class\")\n[1] \"prcomplist\"\n```\n\n\n:::\n:::\n\n\n`isSingular()` と `rePCA()` は、ランダム効果が過剰でないかを点検する定番です[@lme4issingular; @lme4repca]。\n\n**出力の読み方**：\n\n| 関数 | 結果 | 意味 |\n|------|------|------|\n| `isSingular()` | `FALSE` | 安全。ランダム効果構造は推定可能 |\n| `isSingular()` | `TRUE` | 特異適合。分散成分の一部が 0 に収束 |\n| `VarCorr()` | 分散 ≈ 0 の項あり | その項のランダム効果は過剰 |\n| `rePCA()` | 1成分で 99%+ | ランダム傾きは実質的に不要 |\n\n`m_glmm_rs` が特異適合かつ適合改善が小さい場合は、\nランダム切片モデルを採用するのが実務上の安全策です。\n\n### ランダム効果の可視化\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ランダム効果の個人ごとの推定値を可視化\n# → 各点が 1 人の sender（または receiver）\nsjPlot::plot_model(m_glmm_ri, type = \"re\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/sjplot-random-effects-1.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/sjplot-random-effects-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n`plot_model(type = \"re\")` で sender / receiver のランダム効果分布を可視化します。\n\n**図の読み方**：\n\n- 各点が 1 人の sender（または receiver）のランダム効果推定値。\n- **信頼区間が 0 をまたぐ**個人は、全体平均と有意に異ならない。\n- 信頼区間が 0 をまたがない個人は、特に助言をしやすい（正）または しにくい（負）。\n- sender と receiver のプロットを比べ、**どちらの個人差が大きいか**を視覚的に判断できる。散布の幅が大きいほど個人差が大きい。\n\n## ② リンク関数の選択\n\nランダム効果構造が決まったら、次はリンク関数を選択します。5 章で学んだように、ロジスティック GLMM でも `logit`（標準）、`probit`（潜在正規尺度）、`cloglog`（非対称）の 3 つを選べます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# リンク関数だけ変えて比較（固定効果・ランダム構造は同一）\nm_glmm_probit <- glmer(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap +\n    (1 | sender) + (1 | receiver),\n  family = binomial(link = \"probit\"),   # 潜在正規尺度\n  data = dat_bin,\n  control = glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e5))\n)\n\nm_glmm_cloglog <- glmer(\n  tie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + score_gap +\n    (1 | sender) + (1 | receiver),\n  family = binomial(link = \"cloglog\"),  # 非対称リンク\n  data = dat_bin,\n  control = glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e5))\n)\n\n# 3 リンク関数を AIC/BIC で比較\nperformance::compare_performance(m_glmm_ri, m_glmm_probit, m_glmm_cloglog) |>\n  gt() |>\n  tab_header(title = \"② リンク関数の比較: logit vs probit vs cloglog\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ② リンク関数の比較: logit vs probit vs cloglog\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrrrrrrrrrrrr}\n\\toprule\nName & Model & AIC & AIC\\_wt & AICc & AICc\\_wt & BIC & BIC\\_wt & R2\\_conditional & R2\\_marginal & ICC & RMSE & Sigma & Log\\_loss & Score\\_log & Score\\_spherical \\\\ \n\\midrule\\addlinespace[2.5pt]\nm\\_glmm\\_ri & glmerMod & 753.6577 & 0.3297061 & 753.8250 & 0.3297061 & 791.8057 & 0.3297061 & 0.2305488 & 0.1123040 & 0.1332042 & 0.3454336 & 1 & 0.3862866 & -31.02272 & 0.005517479 \\\\ \nm\\_glmm\\_probit & glmerMod & 754.6713 & 0.1986232 & 754.8386 & 0.1986232 & 792.8193 & 0.1986232 & 0.2381935 & 0.1174680 & 0.1367944 & 0.3466072 & 1 & 0.3868415 & -30.51503 & 0.004732942 \\\\ \nm\\_glmm\\_cloglog & glmerMod & 752.9416 & 0.4716707 & 753.1088 & 0.4716707 & 791.0895 & 0.4716707 & 0.3121056 & 0.1559786 & 0.1849799 & 0.3442231 & 1 & 0.3855758 & -31.96507 & 0.005897812 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nAIC がほぼ同等であれば、**logit を採用するのが実務上の推奨**です。理由は（1）OR（オッズ比）として解釈可能、（2）読者が最も慣れている、（3）先行研究との比較が容易、の 3 点です。\n\n### GLM vs GLMM の係数比較（中間確認）\n\nここまでの選択を確認するため、`sjPlot::tab_model()` で GLM と GLMM の係数を並べて表示します。**SE の変化**に注目してください。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# GLM と GLMM の係数を並べて比較する表\n# → SE の変化と有意性の変化に注目\nsjPlot::tab_model(\n  m_glm, m_glmm_ri,\n  show.aic = TRUE,   # AIC を表示\n  show.ci  = TRUE,   # 95% CI を表示\n  show.se  = TRUE,   # 標準誤差を表示\n  dv.labels = c(\"GLM（基準）\", \"GLMM（ランダム切片）\")\n)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"4\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">GLM（基準）</th>\n<th colspan=\"4\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">GLMM（ランダム切片）</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">std. Error</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7\">std. Error</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col8\">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col9\">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.10</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.09</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\">0.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8\">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">same class</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.69</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">4.08</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\">0.79</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8\">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9\"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">prof gap</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.48</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.21</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.006</strong></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.42</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\">0.23</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8\">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9\"><strong>0.031</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">score sender sc</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.10</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.799</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\">0.13</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8\">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9\">0.701</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">score receiver sc</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.10</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.586</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.04</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\">0.15</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8\">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9\">0.788</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">score gap</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.90</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.11</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.368</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7\">0.11</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8\">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col9\">0.320</td>\n</tr>\n<tr>\n<td colspan=\"9\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">&nbsp;</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">3.29</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">&nbsp;</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.18 <sub>sender</sub></td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">&nbsp;</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.32 <sub>receiver</sub></td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">&nbsp;</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.13</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">&nbsp;</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">30 <sub>sender</sub></td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\"></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">&nbsp;</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">30 <sub>receiver</sub></td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"4\">870</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"4\">870</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> Tjur</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.071</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">0.112 / 0.231</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">AIC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">767.203</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"4\">753.658</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n**注目すべき点**：\n\n- **SE の変化**: GLMM の SE が GLM より大きくなっていれば、GLM が SE を過小評価していた証拠。\n- **有意性の変化**: GLM では有意だった予測子が GLMM では非有意になることがある。これは「見かけの有意性」が依存構造の無視によるものだったことを示す。\n- **ICC / R²**: 表の下部に表示される。conditional R² が marginal R² より大きければ、ランダム効果が重要。\n\n## ③ 固定効果の比較（ランダム構造は固定）\n\n最後に、採用したランダム構造（ここでは `m_glmm_ri`）を固定したまま、固定効果を比較します[@lme4pvalues; @meteyard2020]。\n\n以下では `update()` を使い、`m_glmm_ri` から各予測子を 1 つずつ落としたモデルを作成します。これにより「その予測子を入れることで適合がどれだけ改善するか」を個別に検証できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# update() で「フルモデルから 1 予測子だけ落としたモデル」を作成\n# → 各予測子の寄与を個別に検証するため\n# 注: score_gap は score_sender_sc と score_receiver_sc から算出した派生変数なので、\n#     ここでは主要な 4 予測子のみを個別に検証する\nm_glmm_drop_same     <- update(m_glmm_ri, . ~ . - same_class)\nm_glmm_drop_prof     <- update(m_glmm_ri, . ~ . - prof_gap)\nm_glmm_drop_sender   <- update(m_glmm_ri, . ~ . - score_sender_sc)\nm_glmm_drop_receiver <- update(m_glmm_ri, . ~ . - score_receiver_sc)\n```\n:::\n\n\n次に LRT で各予測子の寄与を正式に検定します。`drop1()` は「フルモデルから各予測子を 1 つずつ落とし、適合が有意に悪化するかを一括検定する」便利関数です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# drop1(): 各予測子の LRT を一括実行\n# → 「この予測子を落とすと適合がどれだけ悪化するか」を検定\ndrop1(m_glmm_ri, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions\n\nModel:\ntie ~ same_class + prof_gap + score_sender_sc + score_receiver_sc + \n    score_gap + (1 | sender) + (1 | receiver)\n                  npar    AIC    LRT  Pr(Chi)    \n<none>                 753.66                    \nsame_class           1 804.35 52.688 3.91e-13 ***\nprof_gap             1 756.21  4.553  0.03286 *  \nscore_sender_sc      1 751.80  0.145  0.70337    \nscore_receiver_sc    1 751.73  0.071  0.78946    \nscore_gap            1 752.63  0.975  0.32334    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**`drop1()` 出力の読み方**：\n\n| 出力項目 | 読み方 |\n|---------|--------|\n| `Df` | その予測子のパラメータ数（通常 1）|\n| `AIC` | その予測子を落とした場合の AIC。フルモデルより大きければ、落とすと悪化する |\n| `LRT` | 尤度比統計量。大きいほど、その予測子の寄与が大きい |\n| `Pr(Chi)` | p 値。p < .05 なら、その予測子はモデルの適合に有意に寄与 |\n\n- **非有意な予測子**については、理論的根拠がなければ除外を検討できるが、統制変数として投入した場合は残すのが一般的。\n\n::: {.callout-tip collapse=\"true\"}\n### 個別に `anova()` で確認したい場合（クリックで展開）\n\n`drop1()` の結果をより詳細に確認したい場合は、個別の `anova()` で 2 モデル比較ができます：\n\n```r\n# 例：same_class の寄与を個別に検定\nanova(m_glmm_drop_same, m_glmm_ri, test = \"Chisq\")\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::compare_performance(\n  m_glmm_drop_same,\n  m_glmm_drop_prof,\n  m_glmm_drop_sender,\n  m_glmm_drop_receiver,\n  m_glmm_ri\n) |>\n  gt() |>\n  tab_header(title = \"③ 固定効果候補の比較\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  ③ 固定効果候補の比較\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llrrrrrrrrrrrrrr}\n\\toprule\nName & Model & AIC & AIC\\_wt & AICc & AICc\\_wt & BIC & BIC\\_wt & R2\\_conditional & R2\\_marginal & ICC & RMSE & Sigma & Log\\_loss & Score\\_log & Score\\_spherical \\\\ \n\\midrule\\addlinespace[2.5pt]\nm\\_glmm\\_drop\\_same & glmerMod & 804.3455 & 1.531261e-12 & 804.4755 & 1.535675e-12 & 837.7250 & 1.782985e-12 & 0.1237950 & 0.01391457 & 0.1114310 & 0.3611491 & 1 & 0.4195921 & -29.43770 & 0.004000913 \\\\ \nm\\_glmm\\_drop\\_prof & glmerMod & 756.2105 & 4.339413e-02 & 756.3405 & 4.351924e-02 & 789.5900 & 5.052770e-02 & 0.2353454 & 0.10001810 & 0.1503667 & 0.3456035 & 1 & 0.3855054 & -30.88978 & 0.005864494 \\\\ \nm\\_glmm\\_drop\\_sender & glmerMod & 751.8027 & 3.931678e-01 & 751.9326 & 3.943013e-01 & 785.1822 & 4.578007e-01 & 0.2299031 & 0.11161770 & 0.1331469 & 0.3454358 & 1 & 0.3863348 & -31.02264 & 0.005909265 \\\\ \nm\\_glmm\\_drop\\_receiver & glmerMod & 751.7290 & 4.079249e-01 & 751.8589 & 4.091010e-01 & 785.1085 & 4.749837e-01 & 0.2307843 & 0.11190204 & 0.1338616 & 0.3453859 & 1 & 0.3862094 & -31.01882 & 0.005251547 \\\\ \nm\\_glmm\\_ri & glmerMod & 753.6577 & 1.555132e-01 & 753.8250 & 1.530785e-01 & 791.8057 & 1.668786e-02 & 0.2305488 & 0.11230398 & 0.1332042 & 0.3454336 & 1 & 0.3862866 & -31.02272 & 0.005517479 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-note}\n### ①②③ の結果を踏まえた最終判断\n\n- **①** ランダム効果構造: AIC が改善し、かつ特異適合でないモデルを優先。本データでは `m_glmm_ri`（sender + receiver のランダム切片）を採用。\n- **②** リンク関数: AIC が同等なら logit を採用（OR で解釈可能なため）。\n- **③** 固定効果: LRT・AIC/BIC・理論整合性を総合的に判断。統制変数として投入した予測子は、非有意でも残すのが一般的。\n- 境界問題を含む比較では p 値は近似なので、`compare_performance()` と診断を併用する。\n:::\n\n# 固定効果の解釈（OR）\n\nlogit スケールの係数（β）はそのままでは解釈しにくいため、**オッズ比（OR = exp(β)）** に変換して報告します。OR は「その予測子が 1 単位増加したとき、イベント（助言関係）のオッズが何倍になるか」を示します。\n\n### 方法 A: `sjPlot::tab_model()` で OR を表示（実務向け）\n\n`tab_model()` は係数を自動的に OR に変換し、95% CI 付きの表を生成します。\n**論文やレポートに使う表はこちらで十分**です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsjPlot::tab_model(\n  m_glmm_ri,\n  show.ci = TRUE,      # 95% CI を表示\n  show.se = TRUE,      # 標準誤差を表示\n  show.stat = TRUE,    # z 値を表示\n  dv.labels = \"GLMM (Random Intercepts)\",\n  title = \"Fixed Effects as Odds Ratios\"\n)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<caption style=\"font-weight: bold; text-align:left;\">Fixed Effects as Odds Ratios</caption>\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"5\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">GLMM (Random Intercepts)</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Odds Ratios</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">std. Error</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Statistic</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.09</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;8.52</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">same class</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">4.08</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.79</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">7.21</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">prof gap</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.42</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.23</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.16</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.031</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">score sender sc</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.13</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.38</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.701</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">score receiver sc</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.04</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.15</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.788</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">score gap</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.11</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00&nbsp;&ndash;&nbsp;Inf</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;1.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.320</td>\n</tr>\n<tr>\n<td colspan=\"6\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">3.29</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>sender</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">0.18</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>receiver</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">0.32</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">0.13</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>sender</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">30</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>receiver</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">30</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"5\">870</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">0.112 / 0.231</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n### 方法 B: 手計算で OR 表を作る（原理理解のため）\n\n`sjPlot::tab_model()` の裏側では `exp(β)` の計算が行われています。\n以下のコードでこれを手動で再現します。**OR = exp(logit 係数)**、**CI = exp(係数 ± 1.96 × SE)** です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_mat <- summary(m_glmm_ri)$coefficients\n\nor_tbl <- tibble(\n  term           = rownames(coef_mat),\n  estimate_logit = coef_mat[, \"Estimate\"],\n  std_error      = coef_mat[, \"Std. Error\"],\n  z_value        = coef_mat[, \"z value\"],\n  p_value        = coef_mat[, \"Pr(>|z|)\"],\n  OR      = exp(estimate_logit),                       # exp(β)\n  OR_low  = exp(estimate_logit - 1.96 * std_error),    # 95% CI 下限\n  OR_high = exp(estimate_logit + 1.96 * std_error)     # 95% CI 上限\n)\n\nor_tbl |>\n  gt() |>\n  tab_header(title = \"Fixed Effects as Odds Ratios（手計算版）\") |>\n  fmt_number(columns = c(estimate_logit, std_error, z_value, OR, OR_low, OR_high), decimals = 3) |>\n  fmt_scientific(columns = p_value, decimals = 2) |>\n  cols_label(\n    term = \"Term\", estimate_logit = \"β (logit)\", std_error = \"SE\",\n    z_value = \"z\", p_value = \"p\", OR = \"OR\",\n    OR_low = \"OR 2.5%\", OR_high = \"OR 97.5%\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Fixed Effects as Odds Ratios（手計算版）\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrrr}\n\\toprule\nTerm & β (logit) & SE & z & p & OR & OR 2.5\\% & OR 97.5\\% \\\\ \n\\midrule\\addlinespace[2.5pt]\n(Intercept) & -2.383 & 0.280 & -8.517 & 1.63 $\\times$ 10\\textsuperscript{-17} & 0.092 & 0.053 & 0.160 \\\\ \nsame\\_class & 1.405 & 0.195 & 7.208 & 5.70 $\\times$ 10\\textsuperscript{-13} & 4.076 & 2.782 & 5.973 \\\\ \nprof\\_gap & 0.351 & 0.162 & 2.160 & 3.08 $\\times$ 10\\textsuperscript{-2} & 1.420 & 1.033 & 1.953 \\\\ \nscore\\_sender\\_sc & 0.048 & 0.126 & 0.384 & 7.01 $\\times$ 10\\textsuperscript{-1} & 1.049 & 0.820 & 1.342 \\\\ \nscore\\_receiver\\_sc & 0.039 & 0.146 & 0.269 & 7.88 $\\times$ 10\\textsuperscript{-1} & 1.040 & 0.782 & 1.383 \\\\ \nscore\\_gap & -0.127 & 0.128 & -0.995 & 3.20 $\\times$ 10\\textsuperscript{-1} & 0.881 & 0.685 & 1.131 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n方法 A と方法 B の OR 値が一致することを確認してください。\n\n**OR 表の全予測子の解釈**（以下は出力例に基づく解釈パターンです。実際の数値で読み替えてください）：\n\n| 予測子 | 解釈の読み方 |\n|--------|-------------|\n| `(Intercept)` | 基準条件（same_class=0, prof_gap=0, 全スコア=0）でのオッズ。OR < 1 ならベースラインで助言関係は少ない |\n| `same_class` | **同クラスのペアは異クラスに比べて OR 倍のオッズで助言関係をもつ**。OR > 1 なら同クラスが助言を促進 |\n| `prof_gap` | 熟達度差が 1 段階広がるごとに、助言のオッズが OR 倍に変化。OR < 1 なら差が大きいほど助言が減る |\n| `score_sender_sc` | 送り手のスコアが 1 SD 高いごとに、助言のオッズが OR 倍に変化 |\n| `score_receiver_sc` | 受け手のスコアが 1 SD 高いごとに、助言のオッズが OR 倍に変化 |\n| `score_gap` | スコア差が 1 SD 広がるごとに、助言のオッズが OR 倍に変化 |\n\n::: {.callout-tip}\n### OR 報告の 4 点セット\n\n1. **方向**: OR > 1（促進）か OR < 1（抑制）か\n2. **OR と 95% CI**: OR = X.XX, 95% CI [LL, UL]\n3. **p 値**: 統計的有意性\n4. **確率差への変換**（応答スケール）: 次のセクションで `emmeans` を使って報告\n\n::: {.callout-note}\nOR は**確率差そのもの**ではありません。例えば OR = 2.0 は「オッズが 2 倍」であり、確率が 2 倍になるわけではありません。確率差を知るには、次のセクションの応答スケール予測が必要です。\n:::\n:::\n\n# 応答スケールでの報告（予測確率）\n\n## 群比較（same class）\n\n`emmeans()` は、他の予測子を平均的な値に固定したうえで、特定の条件における推定周辺平均（EMMs）を算出します。`type = \"response\"` を指定すると、logit スケールではなく**確率スケール**で結果を返します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# same_class の各水準での推定確率（他の予測子は平均値に固定）\nemm_class <- emmeans(m_glmm_ri, ~ same_class, type = \"response\")\n\n# 確率スケールでの結果表\nas.data.frame(emm_class) |>\n  gt() |>\n  tab_header(title = \"Predicted Probability by Same-Class Condition\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Predicted Probability by Same-Class Condition\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrrrr}\n\\toprule\nsame\\_class & prob & SE & df & asymp.LCL & asymp.UCL \\\\ \n\\midrule\\addlinespace[2.5pt]\n0 & 0.0943280 & 0.01665206 & Inf & 0.06636379 & 0.1324046 \\\\ \n1 & 0.2980206 & 0.04005491 & Inf & 0.22583113 & 0.3819025 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n\n```{.r .cell-code}\n# ペアワイズ比較（OR と p 値）\npairs(emm_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                  odds.ratio     SE  df null z.ratio p.value\n same_class0 / same_class1      0.245 0.0478 Inf    1  -7.208 <0.0001\n\nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n**EMMs 表の読み方**：\n\n- `prob`: 各条件での推定確率。same_class = 0（異クラス）vs same_class = 1（同クラス）の確率を比較。\n- `asymp.LCL` / `asymp.UCL`: 確率の 95% 信頼区間。\n- **確率差**: 2 つの `prob` の差が、same_class の実質的効果を示す。例えば 0.15 vs 0.25 なら、同クラスは約 10 ポイント高い。\n\n**`pairs()` の読み方**：\n\n- `odds.ratio`: 2 条件間の OR（OR 表の same_class の OR と一致するはず）。\n- `p.value`: ペアワイズ比較の p 値。\n\n## 下位検定の可視化（Case: same class）\n\nEMMs をプロットで可視化します。エラーバーが重ならないほど、条件間の差が明確です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm_class_df <- as.data.frame(emm_class) |>\n  mutate(\n    same_class = factor(\n      same_class,\n      levels = c(0, 1),\n      labels = c(\"Different class\", \"Same class\")\n    )\n  )\n\nggplot(emm_class_df, aes(x = same_class, y = prob, ymin = asymp.LCL, ymax = asymp.UCL)) +\n  geom_pointrange(size = 0.8) +\n  labs(\n    x = \"Dyad Class Relation\",\n    y = \"Predicted Probability of Advice Tie\",\n    title = \"Post-hoc EMMs with 95% CI\"\n  )\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/emmeans-class-plot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**図の読み方**: 点が推定確率、縦線が 95% CI。2 条件の CI が重なっていなければ、差は統計的に有意と視覚的に判断できます（ただし正式な検定は `pairs()` の p 値で行う）。\n\n次に `sjPlot::plot_model()` で連続予測子の効果を可視化します。`pred.type = \"fe\"` は固定効果のみによる予測（母平均的予測）です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# score_sender_sc を連続的に動かし、same_class 別に予測確率をプロット\n# pred.type = \"fe\" → 固定効果のみの母平均的予測\nsjPlot::plot_model(\n  m_glmm_ri,\n  type = \"pred\",\n  terms = c(\"score_sender_sc\", \"same_class [0,1]\"),\n  pred.type = \"fe\",\n  show.data = FALSE\n)\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/sjplot-glmm-pred-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**図の読み方**: 線が予測確率、帯が 95% CI。2 つの線（same_class = 0 vs 1）の差が same_class の効果を確率スケールで示します。次のチャンクでは、この予測をより細かく制御する方法を示します。\n\n## 連続予測子を動かした確率曲線\n\n以下では、送り手のスコア（`score_sender_sc`）を -2 〜 +2 SD の範囲で変化させ、`same_class` ごとに予測確率をプロットします。`re.form = NA` を指定することで、**ランダム効果を含まない母平均的な予測**（population-level prediction）を算出しています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ── 予測用の新しいデータフレームを作成 ──\n# score_sender_sc を -2 〜 +2 SD で動かし、他は代表値で固定\nnew_pred <- tidyr::expand_grid(\n  same_class        = c(0L, 1L),                   # 異クラス vs 同クラス\n  prof_gap          = median(dat_bin$prof_gap),     # 熟達度差は中央値で固定\n  score_sender_sc   = seq(-2, 2, length.out = 120), # 送り手スコアを変化\n  score_receiver_sc = 0                             # 受け手は平均（z = 0）\n)\n\nnew_pred$score_gap <- abs(new_pred$score_sender_sc - new_pred$score_receiver_sc)\n\n# re.form = NA → ランダム効果を含まない母平均的な予測\nnew_pred$pred_prob <- predict(\n  m_glmm_ri,\n  newdata = new_pred,\n  type = \"response\",   # 確率スケールで予測\n  re.form = NA         # 母平均的予測（論文の主要結果図に使用）\n)\n\nplot_pred <- new_pred |>\n  mutate(\n    same_class = factor(\n      same_class,\n      levels = c(0, 1),\n      labels = c(\"Different class\", \"Same class\")\n    )\n  )\n\nggplot(plot_pred, aes(x = score_sender_sc, y = pred_prob, color = same_class)) +\n  geom_line(linewidth = 1) +\n  labs(\n    x = \"Sender Baseline Score (z)\",\n    y = \"Predicted Probability of Advice Tie\",\n    title = \"Response-Scale Prediction from GLMM\"\n  )\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/prediction-curve-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n**図の読み方**：\n\n- **横軸**: 送り手のベースラインスコア（z スコア）。0 が平均、+1 が 1 SD 上。\n- **縦軸**: 助言関係の予測確率。\n- **2 本の曲線**: Same class（同クラス）と Different class（異クラス）。\n- **曲線の間隔**: same_class の効果の大きさを確率スケールで示す。間隔が広いほど効果が大きい。\n- **曲線の傾き**: score_sender_sc の効果。右上がりなら、スコアが高い送り手ほど助言を出しやすい。\n- ロジスティック曲線のため、確率の中央付近（≈0.5）で効果が最も大きく、端（≈0 や ≈1）では効果が小さくなる（S 字カーブの性質）。\n\n::: {.callout-note}\n### `re.form = NA` vs `re.form = NULL`\n\n- `re.form = NA`: ランダム効果を**含まない**予測。母平均的な効果（「典型的な」送り手・受け手）を表す。**論文の主要な結果図にはこちらを使用**。\n- `re.form = NULL`: ランダム効果を**含む**予測。特定の個人の条件付き予測。個人レベルの予測が必要な場合に使用。\n:::\n\n# 診断（必須セット）\n\n## marginal R² と conditional R²（GLMMで必須）\n\n混合効果モデルの $R^2$ は、単一の値ではなく\n**marginal / conditional** を分けて報告するのが標準です\n[@nakagawa2013; @johnson2014; @nakagawa2017]。\n\n$$\nR^2_{\\mathrm{marginal}}\n=\n\\frac{\\mathrm{Var}(X\\beta)}\n{\\mathrm{Var}(X\\beta)+\\mathrm{Var}(Zu)+\\mathrm{Var}_{\\mathrm{dist}}}\n$$\n\n$$\nR^2_{\\mathrm{conditional}}\n=\n\\frac{\\mathrm{Var}(X\\beta)+\\mathrm{Var}(Zu)}\n{\\mathrm{Var}(X\\beta)+\\mathrm{Var}(Zu)+\\mathrm{Var}_{\\mathrm{dist}}}\n$$\n\n- `marginal R²`: 固定効果だけで説明される割合\n- `conditional R²`: 固定 + ランダム効果で説明される割合\n- 差分 `conditional - marginal`: ランダム効果が担う説明分の目安\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Nakagawa の R² を計算（GLMM 専用の分散分解）\nr2_glmm <- performance::r2_nakagawa(m_glmm_ri)\nr2_df   <- as.data.frame(r2_glmm)\n\n# 見やすい表にまとめる\nr2_tbl <- tibble(\n  metric = c(\n    \"Marginal R²（固定効果のみ）\",\n    \"Conditional R²（固定 + ランダム効果）\",\n    \"ランダム効果の寄与（差分）\"\n  ),\n  value = c(\n    r2_df$R2_marginal[1],\n    r2_df$R2_conditional[1],\n    r2_df$R2_conditional[1] - r2_df$R2_marginal[1]  # この差がランダム効果の説明分\n  )\n)\n\nr2_tbl |>\n  gt() |>\n  fmt_number(columns = value, decimals = 3) |>\n  tab_header(title = \"R² 分解（Nakagawa's R²）\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  R² 分解（Nakagawa's R²）\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lr}\n\\toprule\nmetric & value \\\\ \n\\midrule\\addlinespace[2.5pt]\nMarginal R²（固定効果のみ） & 0.112 \\\\ \nConditional R²（固定 + ランダム効果） & 0.231 \\\\ \nランダム効果の寄与（差分） & 0.118 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n`performance::r2_nakagawa()` は、GLMM の分散分解に基づく\nR²（Nakagawa系）を実装した関数です[@performance_r2; @performancepkg]。\n\n::: {.callout-note}\n### 読み方（実務）\n\n- marginal R²が小さく、conditional R²が大きい:\n  個体差・項目差などのランダム効果が主要因になっている可能性。\n- 両者が近い:\n  固定効果だけで大部分が説明され、ランダム効果の追加利得は小さい。\n- R²の大小だけで採否を決めず、`compare_performance()` と残差診断を併用する。\n:::\n\n::: {.panel-tabset}\n\n### DHARMa 残差診断\n\nDHARMa はシミュレーションベースの残差を生成し、モデルの仮定が満たされているかを視覚的・統計的に検証します。`n = 250` はシミュレーション回数です（推奨は 250–1000）。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# シミュレーション残差を生成（n = 250 回のシミュレーション）\nres_glmm <- DHARMa::simulateResiduals(m_glmm_ri, n = 250)\n\nplot(res_glmm)                      # QQ プロット + 残差 vs 予測値\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/diag-dharma-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nDHARMa::testDispersion(res_glmm)    # 過分散テスト（p > .05 なら OK）\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/diag-dharma-2.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDHARMa nonparametric dispersion test via sd of residuals fitted vs.\n\tsimulated\n\ndata:  simulationOutput\ndispersion = 0.99766, p-value = 0.968\nalternative hypothesis: two.sided\n```\n\n\n:::\n\n```{.r .cell-code}\nDHARMa::testUniformity(res_glmm)    # 残差分布テスト（p > .05 なら OK）\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/diag-dharma-3.pdf){fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  simulationOutput$scaledResiduals\nD = 0.027244, p-value = 0.5383\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n**読み方**：\n\n- **QQ プロット（左）**: 点が対角線に沿っていれば残差分布は適切。大きく外れていればモデルのミスフィット。\n- **残差 vs 予測値（右）**: パターン（U 字、扇形など）がなければ OK。系統的パターンがあればモデル構造の問題。\n- `testDispersion`: **p > .05 なら過分散の問題なし**。有意なら過分散（観測データの分散がモデルの想定より大きい）。\n- `testUniformity`: **p > .05 なら残差分布に大きな問題なし**。有意なら分布の仮定に懸念。\n\n::: {.callout-important}\n### DHARMa 診断の合格基準\n\n以下の 3 条件がすべて満たされていれば、モデルの当てはまりは実務上問題ない：\n\n1. `testDispersion` が非有意（p > .05）\n2. `testUniformity` が非有意（p > .05）\n3. QQ プロットと残差プロットに系統的パターンがない\n:::\n\n### 過分散チェック\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 過分散チェック（dispersion ratio ≈ 1.0 なら問題なし）\nperformance::check_overdispersion(m_glmm_ri)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n dispersion ratio = 0.998\n          p-value = 0.968\n```\n\n\n:::\n:::\n\n\n**読み方**：\n\n- `Dispersion ratio` ≈ 1.0 なら過分散なし。1.0 から大きく離れるほど過分散の懸念。\n- p > .05 なら過分散は統計的に有意ではない。\n\n::: {.callout-note}\n### 2値 GLMM での過分散について\n\n厳密には、2値アウトカム（0/1）のロジスティックモデルでは過分散は定義上生じません（各観測の分散は $p(1-p)$ で固定）。ただし、**群レベルでの集計データ**や**観測レベルのランダム効果がない場合**は「見かけの過分散」が起こりえます。DHARMa の検定結果と合わせて総合的に判断してください。\n:::\n\n### 共線性チェック\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# VIF（分散拡大因子）: < 3 なら安全、> 5 なら要注意\nperformance::check_collinearity(m_glm)      # GLM 版\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n              Term  VIF    VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n        same_class 1.02 [1.00,  1.71]     1.01      0.98     [0.59, 1.00]\n          prof_gap 1.03 [1.00,  1.28]     1.02      0.97     [0.78, 1.00]\n   score_sender_sc 1.01 [1.00,  4.77]     1.01      0.99     [0.21, 1.00]\n score_receiver_sc 1.01 [1.00,  2.84]     1.01      0.99     [0.35, 1.00]\n         score_gap 1.01 [1.00, 10.32]     1.00      0.99     [0.10, 1.00]\n```\n\n\n:::\n\n```{.r .cell-code}\nperformance::check_collinearity(m_glmm_ri)  # GLMM 版（両方で確認）\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n              Term  VIF     VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n        same_class 1.01 [1.00,   3.02]     1.01      0.99     [0.33, 1.00]\n          prof_gap 1.02 [1.00,   1.50]     1.01      0.98     [0.67, 1.00]\n   score_sender_sc 1.01 [1.00,   7.45]     1.01      0.99     [0.13, 1.00]\n score_receiver_sc 1.01 [1.00, 261.45]     1.00      0.99     [0.00, 1.00]\n         score_gap 1.01 [1.00, 126.10]     1.00      0.99     [0.01, 1.00]\n```\n\n\n:::\n:::\n\n\n**VIF（分散拡大因子）の判断基準**：\n\n| VIF | 判断 |\n|-----|------|\n| < 3 | 問題なし |\n| 3–5 | 注意。解釈に影響がないか確認 |\n| > 5 | 共線性の懸念。予測子の除外や合成を検討 |\n| > 10 | 深刻な共線性。推定が不安定な可能性が高い |\n\nGLM と GLMM の両方で VIF を確認しているのは、ランダム効果の追加で共線性パターンが変化しないことを確認するためです。\n\n### check_model（総合診断）\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 総合的な視覚診断（複数パネルを一括表示）\nperformance::check_model(m_glm)      # GLM 版\n```\n\n::: {.cell-output-display}\n![](6_混合効果モデル_2値ロジスティック回帰_files/figure-pdf/diag-checkmodel-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nperformance::check_model(m_glmm_ri)  # GLMM 版\n```\n:::\n\n\n`check_model()` はモデル仮定の可視化を一括で確認できるため、\n最終モデルの報告前チェックとして有用です[@performance_checkmodel]。\n\n**パネルの読み方**：\n\n- **Posterior predictive check**: 実データ（黒線）とモデルからのシミュレーション（青線）が近いか\n- **Linearity**: 残差の平均が 0 付近を推移しているか\n- **Homogeneity of variance**: 残差の散布が予測値に依存していないか\n- **Influential observations**: Cook の距離が極端に大きい観測がないか\n- **VIF**: 共線性の視覚的確認\n\n:::\n\n::: {.callout-tip}\n### 診断結果の 1 文報告テンプレート\n\nすべての診断が合格した場合、論文には以下の 1 文を記載すれば十分です：\n\n> Diagnostic checks indicated no major violations: DHARMa simulation-based tests for dispersion and uniformity were non-significant, VIF values were below 3, and visual inspection of residual plots revealed no systematic patterns.\n:::\n\n# 5章からの接続: GLMM と GAMM の使い分け\n\n- **GLMM**: 非線形よりも、階層・反復構造の扱いが主課題のとき。\n- **GAMM**: 階層構造に加えて連続予測子の非線形も重要なとき[@wood2017; @wood2020; @pedersen2019]。\n\n次の判断が有効です。\n\n1. まず GLMM（線形効果）\n2. 残差/理論から非線形が必要なら GAMM へ拡張\n3. 複雑化で解釈が落ちる場合は GLMM に戻して報告\n\n::: {.callout-note}\n### アウトカムが 2 値以外の場合\n\n本章は 2 値（binomial）ですが、`glmer()` の `family` 引数を変えるだけで同じ枠組みを他のデータ型に適用できます。\n\n| データ型 | family 指定 | 変わる点 | 参考 |\n|----------|-----------|---------|------|\n| **反応時間**（正の連続量）| `Gamma(link = \"log\")` | 係数は乗法的（倍率）解釈。変換の問題を回避できる[@lo2015] | 5 章ケース 3 |\n| **カウント** | `poisson` or `MASS::negative.binomial` | IRR（発生率比）で報告 | 5 章ケース 2 |\n| **多値カテゴリカル** | `mclogit` or `brms` で多項ロジット | 3 値以上の選択データ[@gudmestad2025] | — |\n| **学習者コーパス** | データ型に応じて上記を選択 | @gries2021 が完全なワークフローを提示 | — |\n\nランダム効果の考え方（`(1 | sender) + (1 | receiver)` など）は family が変わっても**まったく同じ**です。\n:::\n\n# 報告テンプレート（実践向け）\n\n::: {.panel-tabset}\n\n### Method\n\n以下は本データの変数名を使った worked example です。自身の分析に合わせて変数名と数値を置き換えてください。\n\n::: {.callout-tip}\n### Method 欄での引用のコツ\n\nSLA 分野の論文では、`lme4` の技術論文[@bates2015]だけでなく、\n**分野内のチュートリアル論文**[@cunnings2012; @linck2015]も併せて引用すると、\n「なぜこの手法を選んだか」の正当化が査読者に伝わりやすくなります。\n:::\n\n```text\nWe analyzed directed advice ties among 30 EFL learners using a\nbinomial generalized linear mixed-effects model (GLMM; Bates et al.,\n2015) implemented in R (lme4 package, version 1.1-x). The binary\noutcome was whether a given sender–receiver pair had an advice tie\n(1) or not (0). Fixed effects included same-class membership\n(binary), proficiency gap (ordinal), standardized sender baseline\nscore, standardized receiver baseline score, and absolute score gap.\nTo account for the non-independence of dyadic observations, we\nspecified crossed random intercepts for sender and receiver.\n\nModel selection proceeded in two stages: (a) random-effect structure\nwas compared via AIC, BIC, and likelihood-ratio tests, with\nsingularity checks (isSingular; Bates et al., 2015); (b) fixed\neffects were evaluated via backward elimination (drop1) with the\nrandom structure held constant. The optimizer was set to bobyqa\n(maxfun = 200,000). Diagnostics included DHARMa simulation-based\nresidual tests (Hartig, 2022), overdispersion checks, and VIF-based\ncollinearity assessment (performance package; Lüdecke et al., 2021).\n```\n\n### Results\n\n**固定効果（worked example）**:\n\n```text\nSame-class membership positively predicted advice tie formation,\nβ = 0.XX, SE = 0.XX, z = X.XX, p < .001, OR = X.XX,\n95% CI [X.XX, X.XX]. Learners in the same class were approximately\nX.XX times more likely to form an advice tie than those in\ndifferent classes. On the response scale, predicted probability\nwas .XX for same-class dyads and .XX for different-class dyads.\n\nProficiency gap negatively predicted advice tie formation,\nβ = −0.XX, SE = 0.XX, z = −X.XX, p = .0XX, OR = 0.XX,\n95% CI [0.XX, 0.XX], suggesting that dyads with greater\nproficiency differences were less likely to share advice.\n```\n\n**ランダム効果・分散説明**:\n\n```text\nRandom intercept variance was estimated for both sender\n(σ² = X.XX) and receiver (σ² = X.XX), confirming clustered\ndependence in dyadic observations. ICC estimates from the null\nGLMM indicated that approximately X% of the total variance in\nadvice ties was attributable to sender-level differences and\nX% to receiver-level differences.\n\nModel-level explained variance was R²_marginal = .XXX (fixed\neffects only) and R²_conditional = .XXX (fixed + random effects),\nindicating that individual differences in advice-seeking and\nadvice-giving accounted for a substantial portion of explained\nvariance beyond the fixed effects.\n```\n\n**モデル比較**:\n\n```text\nThe GLMM with crossed random intercepts (sender and receiver)\nshowed substantially improved fit over the fixed-effects-only\nGLM (ΔAIC = XX.X). A random-slope model for same_class was\nalso tested but exhibited singular fit, so the random-intercept\nmodel was retained as the final model.\n```\n\n**診断**:\n\n```text\nDiagnostic checks indicated no major violations: DHARMa\nsimulation-based tests for dispersion (p = .XX) and uniformity\n(p = .XX) were non-significant, VIF values were below X.X for\nall predictors, and visual inspection of residual plots\nrevealed no systematic patterns.\n```\n\n### 査読者チェックリスト\n\n論文投稿前に以下の 7 項目を確認してください：\n\n1. **GLM vs GLMM の根拠**: ICC/DEFF またはモデル比較（ΔAIC）で GLMM の必要性を示したか\n2. **ランダム効果構造の選択**: ランダム傾きを試み、特異適合が生じたためランダム切片に留めた、等の経緯を記載したか\n3. **特異適合チェック**: `isSingular()` の結果を報告したか（特に RS モデルを試みた場合）\n4. **OR + 確率スケール**: 固定効果を OR（95% CI 付き）と応答スケール予測の両方で報告したか\n5. **R² の併記**: marginal R² と conditional R² の両方を報告したか\n6. **診断結果**: DHARMa（dispersion + uniformity）、VIF、残差プロットの結果を記載したか\n7. **オプティマイザ設定**: `bobyqa`、`maxfun` の値を記載したか（再現性のため）\n\n:::\n\n::: {.callout-tip}\n### APA 7 最低限の表記ルール\n\n- 統計記号はイタリック: *β*, *SE*, *z*, *p*, OR, *R*^2^\n- *p* 値は `p = .032`、非常に小さい場合は `p < .001`\n- 区間推定は `95% CI [LL, UL]`\n- GLMM では ICC と *R*^2^ (marginal / conditional) を併記\n:::\n\n::: {.callout-tip}\n### コピペ用 1 文テンプレート\n\n**Method（最短版）**: \"We fitted a binomial GLMM with crossed random intercepts for sender and receiver (lme4; Bates et al., 2015), using bobyqa optimization.\"\n\n**固定効果 1 予測子**: \"[Predictor] significantly predicted [outcome], *β* = X.XX, *SE* = X.XX, *z* = X.XX, *p* < .001, OR = X.XX, 95% CI [X.XX, X.XX].\"\n\n**ランダム効果**: \"Random intercept variances were σ²~sender~ = X.XX and σ²~receiver~ = X.XX; *R*^2^~marginal~ = .XXX, *R*^2^~conditional~ = .XXX.\"\n\n**診断**: \"DHARMa residual tests and VIF diagnostics indicated no major model violations.\"\n:::\n\n# トラブルシューティング（よくあるつまずき）\n\n::: {.callout-warning}\n### 収束警告（convergence warning）が出る\n\n**症状**: `Model failed to converge` や `max|grad| = ...` といった警告メッセージ。\n\n**原因**: 最適化アルゴリズムが最大反復回数内に収束しなかった。変数のスケールが大きく異なる場合や、ランダム効果構造が複雑すぎる場合に起こりやすい。\n\n**段階的な修正手順**:\n\n1. **変数の標準化**: 連続予測子を z スコア化する（`scale()`）。これが最も効果的。\n2. **オプティマイザ変更**: `glmerControl(optimizer = \"bobyqa\")` に変更。\n3. **反復回数増加**: `optCtrl = list(maxfun = 2e5)` または `5e5`。\n4. **別のオプティマイザ**: `nloptwrap` や `optimx` パッケージの `nlminb` を試す。\n5. **ランダム構造簡素化**: ランダム傾きを落とす。\n\n```r\n# 段階的対処の実装例\ncontrol_step1 <- glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 2e5))\ncontrol_step2 <- glmerControl(optimizer = \"bobyqa\", optCtrl = list(maxfun = 5e5))\n```\n:::\n\n::: {.callout-warning}\n### 特異適合（singular fit）\n\n**症状**: `isSingular(model)` が `TRUE` を返す。`boundary (singular) fit` という警告。\n\n**原因**: ランダム効果の分散成分が 0（またはその境界）に推定された。モデルの複雑さに対してデータが不足している。\n\n**修正手順**:\n\n1. `VarCorr(model)` で分散が 0 に近い項を特定。\n2. その項を含むランダム効果を除外してモデルを再推定。\n3. 論文には「ランダム傾きを試みたが特異適合が生じたため、ランダム切片モデルを採用した」と記載。\n:::\n\n::: {.callout-warning}\n### OR の誤解\n\n**症状**: OR = 2.0 を「確率が 2 倍」と誤って解釈。\n\n**原因**: OR（オッズ比）と確率比（リスク比）の混同。\n\n**正しい理解**: OR = 2.0 は「オッズが 2 倍」。ベースライン確率が低い場合（例：p = .05）は確率もほぼ 2 倍に近いが、ベースラインが高い場合（例：p = .50）はオッズ 2 倍でも確率は .50 → .67 程度の変化にとどまる。\n\n**対処**: OR だけでなく、`emmeans()` による応答スケール予測（確率差）を必ず併記する。\n:::\n\n::: {.callout-warning}\n### `re.form` の混同\n\n**症状**: 予測値が観測値と大きくずれる、または個人ごとの予測が全員同じになる。\n\n**原因**: `predict()` の `re.form` 引数の誤用。\n\n**正しい使い分け**:\n\n| 引数 | 意味 | 用途 |\n|------|------|------|\n| `re.form = NA` | ランダム効果を含まない（母平均的予測）| 論文の主要結果図、一般的な効果の報告 |\n| `re.form = NULL` | ランダム効果を含む（条件付き予測）| 個人レベルの予測、モデルの適合度確認 |\n| `re.form = ~0` | `NA` と同じ | 同上 |\n:::\n\n::: {.callout-warning}\n### DHARMa の警告が出た\n\n**症状**: `testDispersion` や `testUniformity` が有意（p < .05）。\n\n**原因と対処**:\n\n- **testDispersion が有意**: 過分散の可能性。2値データでは観測レベルのランダム効果（`(1 | obs_id)`）を追加するか、`MASS::glmmPQL` を検討。ただし、2値単独観測では過分散は定義上起こらないため、群レベルの集計をしていないか確認。\n- **testUniformity が有意**: モデル構造のミスフィット。非線形効果の追加（GAMM への拡張）や、外れ値の確認を検討。\n- **有意だが視覚的に問題がない場合**: サンプルサイズが大きいと微小な逸脱でも有意になることがあります。QQ プロットと残差プロットを視覚的に確認し、系統的パターンがなければ実務上は問題ないと判断できます。混合モデルは軽度の分布仮定の逸脱に対して頑健であることがシミュレーションで確認されているため[@schielzeth2020]、検定が有意でも**視覚的に問題がなければ過度に心配する必要はありません**。\n:::\n\n::: {.callout-warning}\n### 完全分離（complete separation）\n\n**症状**: `glmer` が収束しない、または係数が極端に大きい（|β| > 10）。\n\n**原因**: ある予測子の値によってアウトカムが完全に予測される（例：same_class = 1 のとき tie が常に 1）。\n\n**修正手順**:\n\n1. クロス表で完全分離の有無を確認: `table(dat_bin$same_class, dat_bin$tie)`\n2. 完全分離がある場合、`blme::bglmer()` で弱い事前分布を追加するか、Firth 補正を検討。\n3. カテゴリの統合や、問題のある予測子の除外も選択肢。\n:::\n\n::: {.callout-warning}\n### グループ数が少ない\n\n**症状**: ランダム効果の分散推定が不安定。推定値が極端に大きいまたは小さい。\n\n**原因**: ランダム効果のグループ数（例：sender 数）が少ない（目安として < 10）と、分散の推定に十分な情報がない。\n\n**対処**:\n\n- グループ数が 5 未満の場合、ランダム効果ではなく固定効果として投入することを検討。\n- グループ数が 10–20 の場合、ランダム切片のみに留め、ランダム傾きは避ける。\n- ベイズ推定（`brms` パッケージ）は少グループでもより安定した推定を行える。\n:::\n\n# 発展学習\n\n本章の内容をさらに深めたい場合、**あなたの次の一歩**に合わせて文献を選んでください。\n\n::: {.panel-tabset}\n\n### 基礎を固めたい\n\n本章を読んで「ランダム効果って何をしているの？」がまだ曖昧な場合は、以下の順で読み進めると効率的です。\n\n1. @winter2013 — 言語学の例題で、線形モデルから混合モデルへの拡張を段階的に解説。数式よりコードで理解したい人向け。\n2. @brown2021 — `lme4` で線形混合モデルを一から実装する R チュートリアル。心理学データを使用。\n3. @debruine2021 — 「自分でデータを生成して、ランダム効果が何をしているか体感する」アプローチ。式の意味が腑に落ちます。\n\n### SLA の文脈で学びたい\n\nSLA・応用言語学に特化した GLMM ガイドです。論文の方法欄を書くときにも引用として役立ちます。\n\n- @cunnings2012 — SLA 研究者を対象に、混合モデルの基礎と利点を体系的に解説した先駆的論文。「なぜ ANOVA ではダメか」の議論も含む。\n- @linck2015 — ランダム効果構造の選択やモデル比較の手順を SLA データで実演。本章のステップ 2-3 と直接対応する内容。\n- @gries2021 — 学習者コーパスデータで GLMM の完全なワークフローを提示。カテゴリカル応答変数の扱いに重点を置いた実践例。\n- @gudmestad2025 — 3 値以上のカテゴリカル従属変数（例：正用・誤用・無反応）を扱う多項ロジスティック混合モデルの実装ガイド。\n\n### アウトカムが 2 値以外のとき\n\n本章は 2 値（binomial）でしたが、同じ GLMM の枠組みを他のデータ型にも拡張できます。\n\n- @jaeger2008; @quene2008 — 2 値データでの GLMM の基礎。本章の理論的背景。\n- @lo2015 — **反応時間データ**に対する「変換してから LMM」vs「GLMM（Gamma/逆ガウス）で直接扱う」を比較。変換の問題点を具体的に示した重要論文。\n- @brysbaert2018 — 混合モデルでのエフェクトサイズとパワー分析。サンプルサイズ計画に不可欠。\n\n### ランダム効果構造で悩んだら\n\n「最大構造にすべき」vs「節約的にすべき」という論争は、GLMM の最も実務的な難所です。\n\n- @barr2013 — 「Keep it maximal」：確認的仮説検定ではランダム効果構造を最大にすべきという主張。\n- @bates2015parsimonious; @matuschek2017 — 「節約的モデリング」：過剰パラメータ化を避け、データが支持する範囲に留めるべきという反論。\n- @schielzeth2020 — 混合モデルが分布仮定の逸脱にどこまで耐えるかを大規模シミュレーションで検証。「多少の違反は大丈夫」の根拠。\n\n実務的な判断基準は @meteyard2020 が最もバランスよくまとめています。\n\n### 困ったときのリファレンス\n\n- **GLMM FAQ**: @glmmfaq — 実務で遭遇するほぼすべての疑問に回答。ブックマーク推奨。\n- **p 値の取得**: @lme4pvalues — `lme4` で p 値を得る複数の方法を比較。\n- **特異適合の対処**: @lme4issingular; @lme4repca — `isSingular()` と `rePCA()` の公式ドキュメント。\n- **モデル診断ツール**: @performance_compare; @performance_checkmodel; @performancepkg — `performance` パッケージの各関数リファレンス。\n- **混合モデルの教科書**: @baayen2008; @bates2015; @snijders2012; @hox2018; @bolker2009\n\n### 5 章との接続（GAM/GAMM）\n\n連続予測子に非線形関係が疑われる場合は、GLMM から GAMM へ拡張できます。\n\n- @wood2017; @wood2020; @pedersen2019\n\n:::\n\n# 参考文献\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"icc-manual\",\"icc-manual\",\"icc-manual\",\"icc-manual\",\"icc-manual\",\"icc-manual\",\"icc-manual\",\"design-effect-approx\",\"design-effect-approx\",\"design-effect-approx\",\"design-effect-approx\",\"design-effect-approx\",\"design-effect-approx\",\"design-effect-approx\",\"fit-random-structure-candidates\",\"fit-random-structure-candidates\",\"fit-random-structure-candidates\",\"fit-random-structure-candidates\",\"fit-random-structure-candidates\",\"fit-random-structure-candidates\",\"fit-random-structure-candidates\",\"compare-random-structure-performance\",\"compare-random-structure-performance\",\"compare-random-structure-performance\",\"compare-random-structure-performance\",\"compare-random-structure-performance\",\"compare-random-structure-performance\",\"compare-random-structure-performance\",\"link-compare-glmm\",\"link-compare-glmm\",\"link-compare-glmm\",\"link-compare-glmm\",\"link-compare-glmm\",\"link-compare-glmm\",\"link-compare-glmm\",\"compare-fixed-performance\",\"compare-fixed-performance\",\"compare-fixed-performance\",\"compare-fixed-performance\",\"compare-fixed-performance\",\"compare-fixed-performance\",\"compare-fixed-performance\",\"or-table\",\"or-table\",\"or-table\",\"or-table\",\"or-table\",\"or-table\",\"or-table\",\"emmeans-class\",\"emmeans-class\",\"emmeans-class\",\"emmeans-class\",\"emmeans-class\",\"emmeans-class\",\"emmeans-class\",\"r2-glmm\",\"r2-glmm\",\"r2-glmm\",\"r2-glmm\",\"r2-glmm\",\"r2-glmm\",\"r2-glmm\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}