{
  "hash": "9ff9f6b89ad4c25280c563687cec8125",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"T検定と効果量\"\nprefer-html: true\nalways_allow_html: true\nbibliography: references_ttest.bib\nnocite: |\n  @cohen1988, @mcgraw1992, @delacre2017, @effectsize, @lakens2013,\n  @hoenig2001, @cumming2009, @cumming2014, @rstatsformula,\n  @rstatsttest, @rstatslm, @rstatsshapiro, @rstatswilcox,\n  @rstatspowerttest, @lakens2018equiv\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequired_packages <- c(\n  \"brunnermunzel\",\n  \"car\",\n  \"compute.es\",\n  \"effectsize\",\n  \"forcats\",\n  \"knitr\",\n  \"pacman\",\n  \"purrr\",\n  \"scales\",\n  \"tibble\",\n  \"tidyr\",\n  \"tidyverse\"\n)\n\nmissing_packages <- setdiff(required_packages, rownames(installed.packages()))\nif (length(missing_packages) > 0) {\n  install.packages(missing_packages, repos = \"https://cloud.r-project.org\")\n}\n```\n:::\n\n\n\n## はじめに\n\n本章では、2群比較のための基本的な統計手法である t 検定 (t-test) と、その実質的な差の大きさを示す効果量 (effect size) を扱います。\n\nt 検定は、2つのグループの平均値を比べ、その差が偶然のばらつきだけでは説明しにくいかどうかを調べる方法です。たとえば、「Writing 群の平均点は Glossing 群より本当に高いのか、それとも今回たまたま高く見えただけなのか」を判断したいときに使います。\n\nこの章では、まず「連続量の平均差」をどう読むかに集中します。正解・不正解のような 2 値データや回数データ、より一般的な線型モデルについては、後続章で改めて扱います。\n\n### この章の到達目標\n\n- t 検定の前提条件を確認し、Welch の t 検定を中心に適切な手法を選べるようになる。\n- 効果量（Cohen's d, Hedges g, Glass's Δ, 対応あり d）を計算し、p 値と分けて解釈できるようになる。\n- サンプルサイズと検定力の関係を理解し、研究計画に必要な人数を見積もれるようになる。\n- t 検定の結果を APA 第 7 版に沿って報告できるようになる。\n\n本章は本書の出発点であり、最も基本的な 2 群比較を扱います。まずは t 検定そのものを理解し、そのあとで回帰分析とのつながりも確認します。\n\n## データの作成\n\n架空のデータセットを作成します。この研究では、50 人の参加者を 2 種類の語彙学習方法（注釈付き読解 [Glossing] vs. 文章作成 [Writing]）のいずれかにランダムに割り当てます。各群 25 人ずつで、各参加者は自分に割り当てられた方法だけで 15 語の目標語を学びます。学習後には、再生テスト (recall) と再認テスト (recognition) を学習直後 (Immediate) と 1 週間後 (Delayed) に受けます。\n\nつまり、この章で中心的に扱う Treatment は **参加者間要因**（between-subjects）です。したがって、Immediate の Recall における Glossing 群と Writing 群の比較は、独立 2 群の t 検定として説明できます。\n\n最終的なデータは、次のような列をもつ「縦長データ」になります。\n\n| Participant | Treatment | Test | Time | Item | Score |\n|---|---|---|---|---|---|\n| 1 | Writing | Recall | Immediate | 1 | 1 |\n| 1 | Writing | Recall | Immediate | 2 | 0 |\n| 1 | Writing | Recognition | Delayed | 1 | 1 |\n| 26 | Glossing | Recall | Immediate | 1 | 0 |\n\n以下の setup では、必要なパッケージを読み込み、図のテーマと乱数種を設定します。なお、本書全体の HTML テーマは `_quarto.yml` の `format: html: theme: journal` で定義されています。ここでの `theme_set()` は ggplot の図だけに作用する設定で、Quarto のページテーマとは役割が異なります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"pacman\", quietly = TRUE)) install.packages(\"pacman\", repos = \"https://cloud.r-project.org\")\n\nsuppressPackageStartupMessages(\n  pacman::p_load(tidyverse, effectsize)\n)\n\ntheme_set(theme_bw(base_size = 12, base_family = \"HiraginoSans-W3\") +\n  theme(\n    plot.title.position = \"plot\",\n    plot.title = element_text(\n      face = \"bold\",\n      size = rel(1.0),\n      lineheight = 1.04,\n      margin = margin(b = 6)\n    ),\n    plot.subtitle = element_text(\n      size = rel(0.92),\n      lineheight = 1.04,\n      margin = margin(b = 8)\n    ),\n    plot.margin = margin(t = 10, r = 14, b = 10, l = 10)\n  ))\ntheme_update(legend.position = \"bottom\")\nset.seed(2024)\n```\n:::\n\n\n### 主なパッケージの役割\n\n- `tidyverse`: データ生成、整形、可視化、本章全体のパイプラインの共通基盤。\n- `effectsize`: Cohen's *d*、Hedges' *g* などの効果量を一貫して算出する。\n- `car` / `brunnermunzel`: 前提確認やロバストな 2 群比較で補助的に使う。\n- `compute.es` / `forcats` / `purrr` / `scales`: 効果量の補助計算、因子処理、反復処理、図表整形に使う。\n\n本書では R 4.1 以降のネイティブパイプ演算子 `|>` を使います。`x |> f()` は `f(x)` と同じ意味で、左側の結果を右側の関数へ順に渡します。\n\n```r\n# パイプなし\nround(mean(x), 2)\n\n# パイプあり\nx |> mean() |> round(2)\n```\n\nシミュレーションデータは、最初に「誰がどの群か」を決め、そのあとで各参加者の項目反応を作る 2 段階で生成します。こうすると、between-subjects の設計がコード上でも見えやすくなります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_participants <- 50\nn_items <- 15\ntreatments <- c(\"Glossing\", \"Writing\")\ntests <- c(\"Recall\", \"Recognition\")\ntimes <- c(\"Immediate\", \"Delayed\")\n\nparticipant_tbl <- tibble(\n  Participant = factor(1:n_participants),\n  Treatment = factor(\n    sample(rep(treatments, each = n_participants / 2)),\n    levels = treatments\n  )\n)\n\nknitr::kable(\n  participant_tbl |>\n    count(Treatment),\n  caption = \"各群の参加者数\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: 各群の参加者数\n\n|Treatment |  n|\n|:---------|--:|\n|Glossing  | 25|\n|Writing   | 25|\n\n\n:::\n:::\n\n\nこの時点では、各参加者に Treatment が 1 つだけ割り当てられています。次に、その割り当てに基づいて各項目の得点を作ります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- tidyr::expand_grid(\n  Participant = participant_tbl$Participant,\n  Item = 1:n_items,\n  Test = tests,\n  Time = times\n) |>\n  left_join(participant_tbl, by = \"Participant\") |>\n  mutate(\n    base_prob = case_when(\n      Treatment == \"Glossing\" & Test == \"Recognition\" ~ 0.50,\n      Treatment == \"Glossing\" & Test == \"Recall\" ~ 0.20,\n      Treatment == \"Writing\" & Test == \"Recognition\" ~ 0.90,\n      TRUE ~ 0.50\n    ),\n    immediate_bonus = if_else(\n      Time == \"Immediate\",\n      sample(0:1, size = n(), replace = TRUE),\n      0L\n    ),\n    Score = pmin(\n      rbinom(n(), size = 1, prob = base_prob) + immediate_bonus,\n      1L\n    )\n  ) |>\n  dplyr::select(-base_prob, -immediate_bonus)\n```\n:::\n\n\n`Score` 列はアイテムごとの正誤（1 = 正答、0 = 誤答）を表す 2 値データです。生データ全体は行数が多いので、まずは先頭 12 行だけを見て、各行が「1人 × 1項目 × 1種類のテスト × 1時点」を表していることを確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(\n  dat |>\n    slice_head(n = 12),\n  caption = \"生データの先頭 12 行\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: 生データの先頭 12 行\n\n|Participant | Item|Test        |Time      |Treatment | Score|\n|:-----------|----:|:-----------|:---------|:---------|-----:|\n|1           |    1|Recall      |Immediate |Glossing  |     1|\n|1           |    1|Recall      |Delayed   |Glossing  |     1|\n|1           |    1|Recognition |Immediate |Glossing  |     1|\n|1           |    1|Recognition |Delayed   |Glossing  |     1|\n|1           |    2|Recall      |Immediate |Glossing  |     1|\n|1           |    2|Recall      |Delayed   |Glossing  |     0|\n|1           |    2|Recognition |Immediate |Glossing  |     0|\n|1           |    2|Recognition |Delayed   |Glossing  |     0|\n|1           |    3|Recall      |Immediate |Glossing  |     1|\n|1           |    3|Recall      |Delayed   |Glossing  |     0|\n|1           |    3|Recognition |Immediate |Glossing  |     0|\n|1           |    3|Recognition |Delayed   |Glossing  |     0|\n\n\n:::\n:::\n\n\nt 検定や ANOVA では、目的変数は連続値として扱える形になっている必要があります。そこで、参加者ごと・条件ごとにスコアを合計し、15 点満点の得点に変換します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_summarized <- dat |>\n  mutate(\n    Participant = factor(Participant),\n    Item = factor(Item),\n    Treatment = factor(Treatment, levels = treatments),\n    Test = factor(Test, levels = tests),\n    Time = factor(Time, levels = times)\n  ) |>\n  group_by(Participant, Treatment, Test, Time) |>\n  summarise(Score = sum(Score), .groups = \"drop\")\n\ndesc_stats <- dat_summarized |>\n  group_by(Treatment, Test, Time) |>\n  summarise(\n    Mean = mean(Score),\n    SD = sd(Score),\n    N = n(),\n    SE = SD / sqrt(N),\n    CI_lower = Mean - qt(0.975, df = N - 1) * SE,\n    CI_upper = Mean + qt(0.975, df = N - 1) * SE,\n    .groups = \"drop\"\n  ) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 2)))\n\nknitr::kable(\n  desc_stats,\n  caption = \"Treatment × Test × Time の記述統計\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Treatment × Test × Time の記述統計\n\n|Treatment |Test        |Time      |  Mean|   SD|  N|   SE| CI_lower| CI_upper|\n|:---------|:-----------|:---------|-----:|----:|--:|----:|--------:|--------:|\n|Glossing  |Recall      |Immediate |  9.24| 1.67| 25| 0.33|     8.55|     9.93|\n|Glossing  |Recall      |Delayed   |  2.92| 1.15| 25| 0.23|     2.44|     3.40|\n|Glossing  |Recognition |Immediate | 11.48| 1.64| 25| 0.33|    10.80|    12.16|\n|Glossing  |Recognition |Delayed   |  7.68| 2.08| 25| 0.42|     6.82|     8.54|\n|Writing   |Recall      |Immediate | 11.40| 1.68| 25| 0.34|    10.71|    12.09|\n|Writing   |Recall      |Delayed   |  7.52| 1.81| 25| 0.36|     6.77|     8.27|\n|Writing   |Recognition |Immediate | 13.88| 0.88| 25| 0.18|    13.52|    14.24|\n|Writing   |Recognition |Delayed   | 13.76| 1.05| 25| 0.21|    13.33|    14.19|\n\n\n:::\n:::\n\n\n記述統計を見ると、Writing の平均値が Glossing より高く、Immediate の方が Delayed より高い傾向が確認できます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat_summarized, aes(x = Treatment, y = Score, fill = Time)) +\n  geom_boxplot() +\n  facet_wrap(~ Test) +\n  labs(x = \"Treatment\", y = \"Score\")\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/plot-descriptive-1.png){width=2400}\n:::\n:::\n\n\n## T検定\n\nR の統計関数では、`Score ~ Treatment` のようなフォーミュラ構文をよく使います。公式ドキュメントでは、左辺が目的変数、右辺が説明項を表すと整理されています [@rstatsformula]。本章ではこれを「得点を学習条件で説明する」と読みます。\n\n### 分析フロー\n\n以下のフローチャートは、2 群比較における判断の流れを示したものです。まず確認すべきなのは、目的変数の型と研究デザインです。\n\n```{mermaid}\n%%| label: fig-analysis-flow\n%%| fig-cap: \"2群比較の分析フローチャート\"\nflowchart TD\n    A[\"<b>Two-group comparison</b><br>Predictor: 2 levels\"] --> Z{\"<b>Outcome type</b>\"}\n    Z -->|\"Continuous<br>(e.g., test scores)\"| B{\"<b>Check normality</b><br>Shapiro-Wilk test<br>QQ plot\"}\n    Z -->|\"Binary<br>(correct / incorrect)\"| GLM1[\"<b>Logistic regression</b><br>→ Chapter 5\"]\n    Z -->|\"Count<br>(frequency)\"| GLM2[\"<b>Poisson regression</b><br>→ Chapter 5\"]\n    Z -->|\"Ordinal<br>(Likert-type)\"| GLM3[\"<b>Ordinal regression / CLM</b><br>→ Chapter 7\"]\n    B -->|\"Approximately normal<br>or n ≥ 30\"| C{\"<b>Check variance and outliers</b><br>Levene's test\"}\n    B -->|\"Strong skewness<br>and n < 30\"| D[\"<b>Nonparametric tests</b>\"]\n    C --> E[\"Welch's t-test<br>var.equal = FALSE\"]\n    D --> G[\"Wilcoxon test<br>Brunner-Munzel test\"]\n    E --> H[\"Effect size<br>Cohen's d / Hedges g\"]\n    G --> I[\"Effect size<br>Probabilistic superiority, etc.\"]\n    H --> J[\"Power analysis\"]\n    I --> J\n    J --> K[\"Report results\"]\n```\n\n### t検定を適用できるデータ\n\nt 検定の目的変数は、平均値と分散を意味のある形で扱える連続量である必要があります。したがって、次のようなデータには t 検定をそのまま適用しません。\n\n- 2 値データ（正答/誤答、合格/不合格）: ロジスティック回帰\n- 頻度データ（エラー回数、発話回数）: ポアソン回帰や負の二項回帰\n- 順序データ（5 段階尺度など）: 順序ロジスティック回帰\n\n本章では、アイテムごとの 0/1 を参加者単位で合計し、15 点満点のスコアに変換したうえで t 検定を使います。集約前のアイテムレベルデータを分析したい場合は、一般化線型混合モデルの方が自然です。\n\nこのデータ全体は、Treatment が参加者間要因、Time と Test が参加者内要因の混合デザインです。厳密には混合分散分析や混合効果モデルで一度に扱う方が自然ですが、本章では t 検定の考え方を学ぶことを優先し、Immediate の Recall だけを取り出して 2 群比較を行います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_imm <- dat_summarized |>\n  dplyr::filter(Time == \"Immediate\", Test == \"Recall\") |>\n  mutate(Treatment = forcats::fct_relevel(Treatment, \"Writing\", \"Glossing\"))\n\ndat_del <- dat_summarized |>\n  dplyr::filter(Time == \"Delayed\", Test == \"Recall\") |>\n  mutate(Treatment = forcats::fct_relevel(Treatment, \"Writing\", \"Glossing\"))\n```\n:::\n\n\n以降の検定では、`Writing - Glossing` が正になるように水準順を `Writing`, `Glossing` に揃えています。こうしておくと、t 値、平均差、効果量の符号が一貫して解釈しやすくなります。\n\n### 統計的検定とは何か\n\n統計的検定は、「見えている差が、偶然のばらつきだけでも起こりうる範囲なのか」を調べる手続きです。t 検定では、まず帰無仮説 $H_0$ として「母平均に差はない」を置きます。そのうえで、もし本当に差がないなら、今回観測された平均値差がどれくらい珍しいかを確かめます。\n\n直感的には、次の 3 ステップで考えると理解しやすくなります。\n\n1. まず「差はない」という出発点を置く。\n2. その世界で偶然だけによってどの程度の差が出るかを考える。\n3. 今回の差がその分布の端にあれば、「偶然だけでは説明しにくい」と判断する。\n\n用語だけ先に整理すると、次の表のようになります。\n\n| 用語 | この章での意味 |\n|---|---|\n| 帰無仮説 $H_0$ | Glossing 群と Writing 群の母平均に差はない |\n| 対立仮説 $H_1$ | 2群の母平均に差がある |\n| 検定統計量 | 今回の差が標準誤差の何倍かを表す値 |\n| p 値 | $H_0$ のもとで今回以上に極端な結果が出る割合 |\n| 効果量 | 差の大きさそのもの |\n\n以下では、Immediate の Recall データを使って、「もし群の違いが本当はなかったら」という世界を置換（ラベルの入れ替え）で再現します。赤い部分が「今回以上に極端な差」に相当します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_diff <- dat_imm |>\n  summarise(\n    diff = mean(Score[Treatment == \"Writing\"]) -\n      mean(Score[Treatment == \"Glossing\"])\n  ) |>\n  pull(diff)\n\nperm_diffs <- replicate(3000, {\n  permuted_treatment <- sample(dat_imm$Treatment)\n  mean(dat_imm$Score[permuted_treatment == \"Writing\"]) -\n    mean(dat_imm$Score[permuted_treatment == \"Glossing\"])\n})\n\nperm_p <- mean(abs(perm_diffs) >= abs(observed_diff))\n\nperm_tbl <- tibble(\n  Difference = perm_diffs,\n  Extreme = abs(perm_diffs) >= abs(observed_diff)\n)\n\nggplot(perm_tbl, aes(x = Difference, fill = Extreme)) +\n  geom_histogram(bins = 50, color = \"white\") +\n  geom_vline(\n    xintercept = c(-abs(observed_diff), abs(observed_diff)),\n    color = \"firebrick\",\n    linetype = \"dashed\",\n    linewidth = 0.9\n  ) +\n  scale_fill_manual(\n    values = c(\"FALSE\" = \"grey80\", \"TRUE\" = \"#F4A6A6\"),\n    guide = \"none\"\n  ) +\n  labs(\n    x = \"Mean difference under the null hypothesis\",\n    y = \"Count\",\n    title = \"Mean differences under the null hypothesis\",\n    subtitle = paste0(\n      \"Observed difference = \",\n      round(observed_diff, 2),\n      \", permutation p = \",\n      format.pval(perm_p, digits = 3)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/permutation-null-1.png){width=2100}\n:::\n:::\n\n\nこの図では、中央付近にある差は「偶然でもよく起こる差」、両端の赤い部分は「かなり珍しい差」です。今回のデータでは、観測された平均値差は帰無仮説のもとではあまり起こりにくく、その割合が p 値に対応します。t 検定は、こうした発想を理論的な t 分布を使って効率よく計算する方法だと考えると理解しやすくなります。\n\nここで大事なのは、**p 値は「帰無仮説が正しい確率」ではない**という点です。p 値はあくまで、「差がないと仮定したときに今回以上の結果がどれくらい出るか」を表しています。\n\nチュートリアル論文でも、p 値だけで結論を二分するのではなく、「差はどれくらい大きいか」「その推定にはどれくらい不確実性があるか」を同時に見ることが強く勧められています [@lakens2013; @cumming2014]。\n\n### 前提条件の確認\n\n実務上の確認ポイントは、次の 3 つです。\n\n| 前提 | 主な確認方法 | 実務上の判断 |\n|---|---|---|\n| 正規性 | `shapiro.test()`, QQ プロット, ヒストグラム | 大標本では図も重視する |\n| 等分散性 | 群ごとの散らばり, `leveneTest()` | 主報告は Welch を使う |\n| 独立性 | 研究デザイン | 統計関数だけでは補えない |\n\nこのうち **独立性** は特に重要です。独立性とは、「ある参加者の得点が、別の参加者の得点に引きずられていない」という前提です。たとえば同じペアで学習した、同じクラス内で強い相互作用がある、同じ教員のクラスが複数まとまっている、という状況では、観測値どうしが似やすくなります。\n\nここで重要なのは、独立性は Shapiro-Wilk 検定のように後から 1 つの関数で簡単に確認するものではなく、**研究計画の段階で確保するもの**だという点です。独立性が怪しい場合は、t 検定よりもクラスや教員を考慮できる混合効果モデルの方が適切です。\n\nまた、群差が見つかったとしても、それだけで直ちに「介入の因果効果が証明された」と言えるわけではありません。ランダム割り当てが適切に行われていれば因果解釈に近づけますが、観察データや準実験デザインでは、事前差や交絡の可能性を考える必要があります。\n\n#### Shapiro-Wilk 検定\n\n`shapiro.test()` の帰無仮説は「データは正規分布に従う」です [@rstatsshapiro]。したがって、p 値が大きいときは「正規性からの有意な逸脱は検出されない」と解釈します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro_tbl <- tibble(\n  Treatment = c(\"Writing\", \"Glossing\"),\n  W = c(\n    shapiro.test(dat_imm$Score[dat_imm$Treatment == \"Writing\"])$statistic,\n    shapiro.test(dat_imm$Score[dat_imm$Treatment == \"Glossing\"])$statistic\n  ),\n  p_value = c(\n    shapiro.test(dat_imm$Score[dat_imm$Treatment == \"Writing\"])$p.value,\n    shapiro.test(dat_imm$Score[dat_imm$Treatment == \"Glossing\"])$p.value\n  )\n) |>\n  mutate(\n    Decision = if_else(\n      p_value > 0.05,\n      \"有意な逸脱は検出されない\",\n      \"正規性からの逸脱が示唆される\"\n    ),\n    across(c(W, p_value), \\(x) round(x, 4))\n  )\n\nknitr::kable(\n  shapiro_tbl,\n  caption = \"Immediate recall に対する Shapiro-Wilk 検定\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Immediate recall に対する Shapiro-Wilk 検定\n\n|Treatment |      W| p_value|Decision                 |\n|:---------|------:|-------:|:------------------------|\n|Writing   | 0.9300|  0.0871|有意な逸脱は検出されない |\n|Glossing  | 0.9573|  0.3629|有意な逸脱は検出されない |\n\n\n:::\n:::\n\n\nShapiro-Wilk 検定は便利ですが、p 値だけで正規性を機械的に判定しない方が安全です。サンプルサイズが大きいと小さな逸脱でも有意になりやすく、逆に小さいと明らかな歪みを見逃すことがあります。だからこそ、QQ プロットとヒストグラムを併記します。\n\n外れ値の扱いやロバストな代替手法については、第20章「欠測データ解析とロバスト統計」で詳しく扱います。本章では、まず通常の t 検定の考え方を固めることを優先します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat_imm, aes(sample = Score)) +\n  stat_qq() +\n  stat_qq_line(color = \"steelblue\") +\n  facet_wrap(~ Treatment) +\n  labs(\n    title = \"Normal Q-Q Plot by Treatment\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/qq-plot-1.png){width=2400}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat_imm, aes(x = Score)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 8,\n    fill = \"steelblue\",\n    alpha = 0.5,\n    color = \"white\"\n  ) +\n  geom_density(color = \"darkblue\", linewidth = 1) +\n  facet_wrap(~ Treatment, scales = \"free_y\") +\n  labs(\n    x = \"Score\",\n    y = \"Density\",\n    title = \"Score Distribution by Treatment\"\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/histogram-density-1.png){width=2400}\n:::\n:::\n\n\n#### 等分散性\n\n等分散性の確認には Levene 検定を使います。分散の完全な一致をここで厳密に証明したいわけではなく、「群ごとの散らばりがどの程度違うか」を把握するための補助診断として使います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevene_tbl <- car::leveneTest(Score ~ Treatment, data = dat_imm) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Term\") |>\n  slice(1) |>\n  transmute(\n    Term = \"Treatment\",\n    Df = Df,\n    F_value = round(`F value`, 3),\n    p_value = round(`Pr(>F)`, 4)\n  )\n\nknitr::kable(\n  levene_tbl,\n  caption = \"Immediate recall に対する Levene 検定\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Immediate recall に対する Levene 検定\n\n|Term      | Df| F_value| p_value|\n|:---------|--:|-------:|-------:|\n|Treatment |  1|   0.014|  0.9076|\n\n\n:::\n:::\n\n\nR の `t.test()` はデフォルトで `var.equal = FALSE`、つまり Welch の t 検定を実行します [@rstatsttest]。そのため、Levene 検定は「Student と Welch のどちらに分岐するか」を決める関門というより、データの散らばりを理解するための補助情報と考える方が実務的です。Welch を標準とする考え方は、近年の推奨とも整合的です [@delacre2017]。\n\n### 検定の実施\n\nt 統計量は、平均値差をその標準誤差で割った値です。言い換えると、「群間差が、ばらつきを踏まえてどれだけ大きいか」を表しています。p 値はその t 値と自由度から計算されますが、p 値そのものは効果の大きさを示しません。したがって、平均値差の信頼区間と効果量をセットで読むことが重要です。\n\nここで、最初に理解すべき数量は 3 つあります。\n\n- **平均値差**: 実際に何点違うのか\n- **95%信頼区間**: その差をどの程度の幅で見積もるべきか\n- **p 値**: 差が 0 だと仮定したときに、今回以上の結果がどれくらい珍しいか\n\nこの 3 つのうち、実際の教育研究で最も直感的なのは平均値差です。たとえば「平均で 2 点高い」はそのまま読み取れます。一方、効果量はその差を標準偏差で割った“比較しやすい尺度”、p 値はその差が偶然でも起こるかをみる尺度です。それぞれ役割が違います。\n\nまず **Welch の t 検定だけを確実に理解すれば十分** です。Student の t 検定やノンパラメトリック検定は、「前提やデータの性質が違うときにどうするか」を知るための発展事項として読むと整理しやすくなります。\n\n::: panel-tabset\n#### Welch の t 検定\n\n公式ドキュメントどおり、まずはデフォルトの Welch の t 検定を使います [@rstatsttest]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwelch_result <- t.test(Score ~ Treatment, data = dat_imm)\nwelch_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Score by Treatment\nt = 4.5611, df = 47.995, p-value = 3.53e-05\nalternative hypothesis: true difference in means between group Writing and group Glossing is not equal to 0\n95 percent confidence interval:\n 1.207825 3.112175\nsample estimates:\n mean in group Writing mean in group Glossing \n                 11.40                   9.24 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_diff_tbl <- tibble(\n  Quantity = c(\"Writing 群平均\", \"Glossing 群平均\", \"平均値差\", \"差の95%信頼区間\"),\n  Value = c(\n    round(unname(welch_result$estimate[[\"mean in group Writing\"]]), 2),\n    round(unname(welch_result$estimate[[\"mean in group Glossing\"]]), 2),\n    round(diff(rev(unname(welch_result$estimate))), 2),\n    paste0(\n      \"[\",\n      round(welch_result$conf.int[1], 2),\n      \", \",\n      round(welch_result$conf.int[2], 2),\n      \"]\"\n    )\n  )\n)\n\nknitr::kable(\n  mean_diff_tbl,\n  caption = \"平均値差と95%信頼区間の要約\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: 平均値差と95%信頼区間の要約\n\n|Quantity        |Value        |\n|:---------------|:------------|\n|Writing 群平均  |11.4         |\n|Glossing 群平均 |9.24         |\n|平均値差        |2.16         |\n|差の95%信頼区間 |[1.21, 3.11] |\n\n\n:::\n:::\n\n\nWelch 検定では自由度が小数になることがあります。これは Welch-Satterthwaite 近似によって自由度を調整しているためで、等分散を仮定しない代わりにその不確実性を自由度側へ反映していると考えると理解しやすくなります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_obs <- unname(welch_result$statistic)\ndf_obs <- unname(welch_result$parameter)\n\nt_curve <- tibble(\n  t_value = seq(-5, 5, length.out = 600)\n) |>\n  mutate(\n    density = dt(t_value, df = df_obs),\n    Extreme = abs(t_value) >= abs(t_obs)\n  )\n\nggplot(t_curve, aes(x = t_value, y = density)) +\n  geom_line(linewidth = 1, color = \"steelblue4\") +\n  geom_area(\n    data = subset(t_curve, Extreme),\n    fill = \"#F4A6A6\",\n    alpha = 0.8\n  ) +\n  geom_vline(\n    xintercept = c(-abs(t_obs), abs(t_obs)),\n    color = \"firebrick\",\n    linetype = \"dashed\",\n    linewidth = 0.9\n  ) +\n  labs(\n    x = \"t value\",\n    y = \"Density\",\n    title = \"t distribution and the two-sided p-value\",\n    subtitle = paste0(\n      \"Observed t = \",\n      round(t_obs, 2),\n      \", df = \",\n      round(df_obs, 2),\n      \", p = \",\n      format.pval(welch_result$p.value, digits = 3)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/t-distribution-visual-1.png){width=2100}\n:::\n:::\n\n\n赤く塗られた両端の面積が、両側検定の p 値です。つまり p 値とは、「差がないと仮定したときに、今回の t 値以上に極端な値がどれくらいの割合で起こるか」を表した面積だと考えられます。\n\nこの例を一文で言うと、**Writing 群は Glossing 群より平均で 2.16 点高く、その差は Welch の t 検定でも偶然だけでは説明しにくい**、ということです。\n\n:::\n\n### 95%信頼区間をどう読むか\n\n95%信頼区間は、「もっともらしい差の範囲」を表す区間です。今回の例では、平均値差の95%信頼区間はおよそ 1.21 点から 3.11 点です。つまり、Writing 群の優位性は 0 点差付近ではなく、少なくとも 1 点程度はありそうだ、と読みます。\n\nただし、95%信頼区間を「真の値が95%の確率でこの中にある」とそのまま言い換えるのは、頻度主義統計の厳密な言い方ではありません。正確には、「同じ手続きを何度も繰り返したとき、そのたびに作られる区間の 95% が真の値を含む」という意味です。それでも実務上は、「どれくらいの差がもっともらしいかを見る幅」と理解しておけば十分役に立ちます。\n\n特に意識するとよいのは次の 2 点です。\n\n- **区間が狭いほど** 推定は精密\n- **区間が広いほど** 推定には不確実性が大きい\n\n今回の章では p 値だけでなく、この信頼区間を必ず併記する方針をとっています。これは Cumming が強調する “new statistics” の考え方とも一致します [@cumming2014]。\n\nこの「95%」という言い方を直感的に理解するには、同じ条件で研究を何度も繰り返す場面を思い浮かべると役立ちます。下の図では、同じ母集団から 80 回研究を繰り返し、そのたびに平均値差の 95% 信頼区間を作っています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrue_p_glossing <- 0.54\ntrue_p_writing <- 0.68\ntrue_diff_ci <- 15 * (true_p_writing - true_p_glossing)\nn_ci_demo <- 25\nn_rep_ci <- 80\n\nci_demo <- purrr::map_dfr(1:n_rep_ci, \\(i) {\n  writing_scores <- rbinom(n_ci_demo, size = 15, prob = true_p_writing)\n  glossing_scores <- rbinom(n_ci_demo, size = 15, prob = true_p_glossing)\n  ci_result <- t.test(writing_scores, glossing_scores, var.equal = TRUE)\n\n  tibble(\n    Study = i,\n    Estimate = mean(writing_scores) - mean(glossing_scores),\n    CI_low = ci_result$conf.int[1],\n    CI_high = ci_result$conf.int[2],\n    Covers = ci_result$conf.int[1] <= true_diff_ci &\n      ci_result$conf.int[2] >= true_diff_ci\n  )\n}) |>\n  mutate(Study = factor(Study, levels = rev(unique(Study))))\n\nggplot(ci_demo, aes(x = Estimate, y = Study, color = Covers)) +\n  geom_vline(xintercept = true_diff_ci, linetype = \"dashed\", color = \"grey40\") +\n  geom_segment(\n    aes(x = CI_low, xend = CI_high, yend = Study),\n    linewidth = 0.8\n  ) +\n  geom_point(size = 1.8) +\n  scale_color_manual(\n    values = c(`TRUE` = \"steelblue4\", `FALSE` = \"firebrick\"),\n    labels = c(`TRUE` = \"Covers the true difference\", `FALSE` = \"Does not cover the true difference\")\n  ) +\n  labs(\n    x = \"Mean difference\",\n    y = \"Repeated study\",\n    color = \"\",\n    title = \"What a 95% confidence interval means\",\n    subtitle = paste0(\n      \"True mean difference = \",\n      round(true_diff_ci, 1),\n      \". Over repeated studies, most 95% CIs include the true difference\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/ci-coverage-visual-1.png){width=2100}\n:::\n:::\n\n\nこの図で青い区間は真の差を含んでおり、赤い区間は含んでいません。95% 信頼区間とは、「今作った 1 本の区間に 95% の確率で真の値が入る」という意味ではなく、**同じ手続きを何度も繰り返したとき、作られる区間の約 95% が真の値を含む**という長期的な性質を表しています。この例でも、80 本中 74 本の区間が真の差を含んでいます。\n\n#### サンプルサイズが増えると CI はどう変わるか\n\n信頼区間の幅は、ばらつきだけでなくサンプルサイズにも強く依存します。簡単のため、各群のばらつきが同程度である状況を仮定すると、各群の人数が増えるほど平均値差の標準誤差が小さくなり、信頼区間は狭くなります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npooled_sd_demo <- dat_imm |>\n  group_by(Treatment) |>\n  summarise(\n    n = n(),\n    variance = var(Score),\n    .groups = \"drop\"\n  ) |>\n  summarise(\n    pooled_sd = sqrt(sum((n - 1) * variance) / sum(n - 1))\n  ) |>\n  pull(pooled_sd)\n\nci_width_data <- tibble(n = seq(10, 120, by = 5)) |>\n  mutate(\n    t_crit = qt(0.975, df = 2 * n - 2),\n    se_diff = pooled_sd_demo * sqrt(2 / n),\n    ci_width = 2 * t_crit * se_diff\n  )\n\nci_width_current <- ci_width_data |>\n  dplyr::filter(n == 25) |>\n  pull(ci_width)\n\nggplot(ci_width_data, aes(x = n, y = ci_width)) +\n  geom_line(linewidth = 1, color = \"steelblue4\") +\n  geom_point(\n    data = dplyr::filter(ci_width_data, n == 25),\n    color = \"firebrick\",\n    size = 3\n  ) +\n  annotate(\n    \"text\",\n    x = 27,\n    y = ci_width_current + 0.15,\n    label = \"Current example: n = 25 per group\",\n    hjust = 0,\n    size = 3\n  ) +\n  labs(\n    x = \"Sample size per group\",\n    y = \"Approximate width of 95% CI\",\n    title = \"Larger samples produce narrower confidence intervals\",\n    subtitle = \"Approximation assuming similar variability across groups\"\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/ci-width-by-n-1.png){width=2100}\n:::\n:::\n\n\nこの図が伝えているのは、サンプルサイズが増えると「有意になりやすくなる」だけでなく、**平均値差をより狭い範囲で見積もれる**ということです。検定力と信頼区間の幅は、同じ不確実性を別の角度から見たものだと考えると整理しやすくなります [@cumming2014]。\n\n### Student の t 検定\n\nStudent の t 検定は `var.equal = TRUE` を明示した場合に実行されます。等分散が強く妥当だと判断できるときには使えますが、教育データでは Welch を主報告にしておけば十分なことが多いです。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudent_result <- t.test(Score ~ Treatment, data = dat_imm, var.equal = TRUE)\nstudent_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Score by Treatment\nt = 4.5611, df = 48, p-value = 3.529e-05\nalternative hypothesis: true difference in means between group Writing and group Glossing is not equal to 0\n95 percent confidence interval:\n 1.207828 3.112172\nsample estimates:\n mean in group Writing mean in group Glossing \n                 11.40                   9.24 \n```\n\n\n:::\n:::\n\n\n### ノンパラメトリック検定\n\n`wilcox.test()` は順位に基づく比較であり、正規性を仮定しません [@rstatswilcox]。ただし、これを「中央値差」として解釈したいなら、2 群の分布の形が大きく違わないことを確認した方がよいです。分散や形状の違いが気になるときは、Brunner-Munzel 検定も併記すると判断材料が増えます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_result <- wilcox.test(Score ~ Treatment, data = dat_imm, exact = FALSE)\nwilcox_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  Score by Treatment\nW = 514, p-value = 7.851e-05\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_result <- brunnermunzel::brunnermunzel.test(Score ~ Treatment, data = dat_imm)\nbm_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBrunner-Munzel Test\n\ndata:  Score by Treatment\nBrunner-Munzel Test Statistic = -5.347, df = 46.727, p-value =\n2.616e-06\n95 percent confidence interval:\n 0.05628286 0.29891714\nsample estimates:\nP(X<Y)+.5*P(X=Y) \n          0.1776 \n```\n\n\n:::\n:::\n\n\n参考として、遅延テスト (Delayed) の結果も確認しておきます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndelayed_result <- t.test(Score ~ Treatment, data = dat_del)\ndelayed_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Score by Treatment\nt = 10.739, df = 40.758, p-value = 1.87e-13\nalternative hypothesis: true difference in means between group Writing and group Glossing is not equal to 0\n95 percent confidence interval:\n 3.734814 5.465186\nsample estimates:\n mean in group Writing mean in group Glossing \n                  7.52                   2.92 \n```\n\n\n:::\n:::\n\n\n### 結果の可視化\n\n統計量の符号や群差の方向を取り違えないためにも、最終的には図で確認しておく方が安全です。以下の図では、箱ひげ図で分布の広がりを示し、白丸と誤差棒で群平均と 95% 信頼区間を重ねています。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_summary <- dat_imm |>\n  group_by(Treatment) |>\n  summarise(\n    mean = mean(Score),\n    sd = sd(Score),\n    n = n(),\n    se = sd / sqrt(n),\n    ci = qt(0.975, df = n - 1) * se,\n    .groups = \"drop\"\n  )\n\nggplot(dat_imm, aes(x = Treatment, y = Score, fill = Treatment)) +\n  geom_boxplot(width = 0.5, alpha = 0.45, outlier.shape = NA) +\n  geom_jitter(width = 0.08, alpha = 0.25, size = 1.4) +\n  geom_point(\n    data = dat_summary,\n    aes(x = Treatment, y = mean),\n    inherit.aes = FALSE,\n    size = 3,\n    shape = 21,\n    fill = \"white\",\n    color = \"black\"\n  ) +\n  geom_errorbar(\n    data = dat_summary,\n    aes(x = Treatment, ymin = mean - ci, ymax = mean + ci),\n    inherit.aes = FALSE,\n    width = 0.1,\n    linewidth = 0.8\n  ) +\n  scale_x_discrete(limits = c(\"Glossing\", \"Writing\")) +\n  labs(x = \"Treatment\", y = \"Immediate recall score\")\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/plot-result-1.png){width=1800}\n:::\n:::\n\n\nここで見るべきなのは、Writing の分布全体が Glossing より上にずれているか、外れ値が結果を支配していないか、そして平均差の方向が t 検定の符号と一致しているか、の 3 点です。群平均の信頼区間の重なりだけで有意性を判定するのではなく、平均値差の信頼区間と t 検定の結果を主に読みます。95% 信頼区間どうしの重なりと有意差判定の関係は直感的に見えても、単純な「重なれば有意差なし、重ならなければ有意差あり」という規則にはなりません [@cumming2009]。\n\n## t検定と回帰分析のつながり\n\nここまで t 検定を 2 群比較として見てきました。ここで一度、t 検定が単回帰分析とどうつながるかを確認しておきます。\n\n回帰分析は、一般に\n\n$$\nY = b_0 + b_1 X + \\varepsilon\n$$\n\nという形で表されます。`lm()` もこの形のモデルを当てはめる関数です [@rstatslm]。\n\n- $X$ が連続変数なら、回帰直線は傾きをもつ通常の単回帰になります。\n- $X$ が 0/1 の 2 値変数なら、$b_0$ は 0 群の平均、$b_1$ は 1 群と 0 群の平均値差になります。\n\nつまり、**2 群の平均値差を調べる t 検定は、「説明変数が 2 水準だけの回帰分析」として書き直すことができます**。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_demo <- bind_rows(\n  tibble(\n    Demo = \"Simple regression with continuous X\",\n    x = seq(0, 10, length.out = 50),\n    y = 3 + 0.8 * x + rnorm(50, sd = 1.3)\n  ),\n  dat_imm |>\n    transmute(\n      Demo = \"t-test as regression with binary X\",\n      x = if_else(Treatment == \"Glossing\", 0, 1),\n      y = Score\n    )\n)\n\nggplot(regression_demo, aes(x = x, y = y)) +\n  geom_jitter(width = 0.05, height = 0, alpha = 0.45, color = \"grey35\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"steelblue\", linewidth = 1) +\n  facet_wrap(~ Demo, scales = \"free_x\") +\n  labs(x = \"X\", y = \"Y\")\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/regression-connection-plot-1.png){width=2400}\n:::\n:::\n\n\n左の図は、普通の単回帰です。右の図では、`Glossing = 0`, `Writing = 1` と符号化すると、回帰直線は「2 群の平均を結ぶ線」になります。0 の位置の予測値が Glossing 群の平均、1 の位置の予測値が Writing 群の平均です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_df <- dat_imm |>\n  mutate(Treatment01 = if_else(Treatment == \"Writing\", 1, 0))\n\nlm_result <- lm(Score ~ Treatment01, data = lm_df)\nlm_coef <- summary(lm_result)$coefficients[\"Treatment01\", ]\n\nmean_diff <- with(\n  lm_df,\n  mean(Score[Treatment01 == 1]) - mean(Score[Treatment01 == 0])\n)\n\ncomparison_tbl <- tibble(\n  Quantity = c(\"平均値差\", \"t 値\", \"p 値\"),\n  `Student's t-test` = c(\n    round(mean_diff, 4),\n    round(unname(student_result$statistic), 4),\n    round(student_result$p.value, 4)\n  ),\n  `lm(Score ~ Treatment01)` = c(\n    round(unname(coef(lm_result)[\"Treatment01\"]), 4),\n    round(unname(lm_coef[\"t value\"]), 4),\n    round(unname(lm_coef[\"Pr(>|t|)\"]), 4)\n  )\n)\n\nknitr::kable(\n  comparison_tbl,\n  caption = \"Student の t 検定と単回帰分析の一致\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Student の t 検定と単回帰分析の一致\n\n|Quantity | Student's t-test| lm(Score ~ Treatment01)|\n|:--------|----------------:|-----------------------:|\n|平均値差 |           2.1600|                  2.1600|\n|t 値     |           4.5611|                  4.5611|\n|p 値     |           0.0000|                  0.0000|\n\n\n:::\n:::\n\n\nこの表から、**Student の t 検定と、0/1 に符号化した説明変数をもつ `lm()` は同じ平均値差・同じ t 値・同じ p 値を返す**ことがわかります。厳密に一致するのは等分散を仮定する Student の t 検定です。Welch の t 検定は、その考え方を保ったまま等分散を仮定しないように拡張したものです。\n\nこの見方をもっておくと、t 検定、ANOVA、回帰分析が別々の道具に見えにくくなります。チュートリアル論文が強調する「推定量と不確実性を一貫して考える」という発想にもつながります [@cumming2014]。\n\n## 効果量\n\np 値は「差があるか」を問う指標であり、「差がどれくらい大きいか」を直接は教えてくれません。t 検定の結果を報告するときは、効果量を合わせて示すことで、実質的な意味を読み取りやすくなります [@lakens2013]。\n\n### 標準化効果量の種類\n\n- Cohen's d: 平均値差をプールした標準偏差で割った値。最も基本的な標準化平均差です。\n- Hedges g: Cohen's d に小標本補正を加えたもの。サンプルサイズが小さい研究やメタ分析でよく使われます。\n- Glass's Δ: 対照群の標準偏差だけで標準化する指標。介入によって分散が変わる可能性があるときに有用です。\n\n代表的な目安として、Cohen は $d = 0.2, 0.5, 0.8$ を small, medium, large と整理しました [@cohen1988]。ただし、これはあくまで便宜的な基準であり、文脈依存の解釈を置き換えるものではありません [@lakens2013]。\n\n| Cohen's d | 効果の大きさ |\n|---|---|\n| 0.2 | 小 |\n| 0.5 | 中 |\n| 0.8 | 大 |\n| 1.2 以上 | 非常に大 |\n\n### 効果量の計算\n\n`effectsize` パッケージは、Cohen's d, Hedges g, Glass's Δ を同じ記法で計算でき、95% 信頼区間も併せて出力します [@effectsize]。ここでは `reference = \"Glossing\"` を明示し、正の値が「Writing 有利」を意味するように符号を固定します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_result <- cohens_d(\n  Score ~ Treatment,\n  data = dat_imm,\n  reference = \"Glossing\"\n)\nhedges_result <- hedges_g(\n  Score ~ Treatment,\n  data = dat_imm,\n  reference = \"Glossing\"\n)\nglass_result <- glass_delta(\n  Score ~ Treatment,\n  data = dat_imm,\n  reference = \"Glossing\"\n)\n\ntab_es_plot <- tibble(\n  Measure = c(\"Cohen's d\", \"Hedges g\", \"Glass's Δ\"),\n  Estimate = c(\n    cohens_result$Cohens_d,\n    hedges_result$Hedges_g,\n    glass_result$Glass_delta\n  ),\n  CI_lower = c(\n    cohens_result$CI_low,\n    hedges_result$CI_low,\n    glass_result$CI_low\n  ),\n  CI_upper = c(\n    cohens_result$CI_high,\n    hedges_result$CI_high,\n    glass_result$CI_high\n  )\n)\n\ntab_es <- tab_es_plot |>\n  mutate(across(where(is.numeric), \\(x) round(x, 2)))\n\nknitr::kable(\n  tab_es,\n  caption = \"Immediate recall の効果量比較\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Immediate recall の効果量比較\n\n|Measure    | Estimate| CI_lower| CI_upper|\n|:----------|--------:|--------:|--------:|\n|Cohen's d  |     1.29|     0.67|     1.90|\n|Hedges g   |     1.27|     0.66|     1.87|\n|Glass's Δ |     1.26|     0.60|     1.89|\n\n\n:::\n:::\n\n\nHedges g が Cohen's d よりわずかに小さくなるのは、小標本補正が入るためです。サンプルサイズが十分大きければ、両者はほぼ同じ値になります。\n\nこの例を一文で言うと、**この差は統計的に有意なだけでなく、Cohen's d = 1.29 と、実質的にも無視しにくい大きさ**です。\n\n### 平均値差の CI と効果量の CI をどう使い分けるか\n\nここまでで、平均値差にも Cohen's d にも信頼区間が付くことを見てきました。両者はどちらも大切ですが、答えている問いが少し違います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_comparison_tbl <- tibble(\n  指標 = c(\"平均値差\", \"Cohen's d\"),\n  単位 = c(\"得点\", \"標準偏差単位\"),\n  推定値 = c(\n    round(observed_diff, 2),\n    round(cohens_result$Cohens_d, 2)\n  ),\n  `95% CI` = c(\n    paste0(\n      \"[\",\n      round(welch_result$conf.int[1], 2),\n      \", \",\n      round(welch_result$conf.int[2], 2),\n      \"]\"\n    ),\n    paste0(\n      \"[\",\n      round(cohens_result$CI_low, 2),\n      \", \",\n      round(cohens_result$CI_high, 2),\n      \"]\"\n    )\n  ),\n  主な使いどころ = c(\n    \"実際に何点違うかを述べる\",\n    \"研究間で差の大きさを比較する\"\n  )\n)\n\nknitr::kable(\n  estimate_comparison_tbl,\n  caption = \"平均値差と効果量の信頼区間の役割分担\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: 平均値差と効果量の信頼区間の役割分担\n\n|指標      |単位         | 推定値|95% CI       |主な使いどころ               |\n|:---------|:------------|------:|:------------|:----------------------------|\n|平均値差  |得点         |   2.16|[1.21, 3.11] |実際に何点違うかを述べる     |\n|Cohen's d |標準偏差単位 |   1.29|[0.67, 1.9]  |研究間で差の大きさを比較する |\n\n\n:::\n:::\n\n\n平均値差の 95% 信頼区間は、「教育的に見て何点くらいの差がありそうか」を直接示します。一方、Cohen's d の 95% 信頼区間は、「その差が標準偏差何個分くらいか」を表し、別のテストや別研究との比較に向いています [@lakens2013]。\n\nしたがって、教育研究では **平均値差の CI を主に読み、効果量の CI でその差の相対的な大きさを補う**、という順番で解釈するとわかりやすくなります。\n\n### 対応ありデザインの効果量\n\nここまでは独立 2 群の効果量でした。もし同じ参加者を前後比較するなら、独立 2 群の d ではなく対応あり d を使います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaired_df <- dat_summarized |>\n  dplyr::filter(Treatment == \"Writing\", Test == \"Recall\") |>\n  dplyr::select(Participant, Time, Score) |>\n  pivot_wider(names_from = Time, values_from = Score)\n\ncohens_d(paired_df$Immediate, paired_df$Delayed, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI\n------------------------\n1.78      | [1.13, 2.40]\n```\n\n\n:::\n:::\n\n\n対応ありか対応なしかは、統計手法の選択でも効果量の選択でも最重要です。同じ参加者 ID が複数条件に現れるなら対応あり、各条件に別の参加者が割り当てられているなら対応なしと判断します。\n\n記述統計しか手元にない先行研究から効果量を復元したいときは、`compute.es::mes()` が便利です。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompute.es::mes(\n  m.1 = 10, m.2 = 12,\n  sd.1 = 1, sd.2 = 1.3,\n  n.1 = 30, n.2 = 30\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Differences ES: \n \n d [ 95 %CI] = -1.72 [ -2.32 , -1.13 ] \n  var(d) = 0.09 \n  p-value(d) = 0 \n  U3(d) = 4.23 % \n  CLES(d) = 11.13 % \n  Cliff's Delta = -0.78 \n \n g [ 95 %CI] = -1.7 [ -2.29 , -1.12 ] \n  var(g) = 0.09 \n  p-value(g) = 0 \n  U3(g) = 4.44 % \n  CLES(g) = 11.44 % \n \n Correlation ES: \n \n r [ 95 %CI] = -0.66 [ -0.78 , -0.49 ] \n  var(r) = 0 \n  p-value(r) = 0 \n \n z [ 95 %CI] = -0.79 [ -1.05 , -0.53 ] \n  var(z) = 0.02 \n  p-value(z) = 0 \n \n Odds Ratio ES: \n \n OR [ 95 %CI] = 0.04 [ 0.01 , 0.13 ] \n  p-value(OR) = 0 \n \n Log OR [ 95 %CI] = -3.13 [ -4.2 , -2.05 ] \n  var(lOR) = 0.3 \n  p-value(Log OR) = 0 \n \n Other: \n \n NNT = -5.13 \n Total N = 60\n```\n\n\n:::\n:::\n\n\n`compute.es::mes()` は d や g に加えて、相関係数 $r$、オッズ比、CLES (common language effect size) なども返します。CLES は、ランダムに取り出した 2 人を比べたときに、一方が他方を上回る確率として解釈できるため、実務家に説明しやすい指標です [@mcgraw1992]。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tab_es_plot, aes(x = Estimate, y = reorder(Measure, Estimate))) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_segment(\n    aes(x = CI_lower, xend = CI_upper, yend = Measure),\n    linewidth = 0.8\n  ) +\n  geom_point(size = 3, color = \"steelblue\") +\n  labs(\n    x = \"Effect size estimate\",\n    y = \"\",\n    title = \"Effect Size Comparison with 95% CI\",\n    subtitle = \"Immediate recall: Writing vs Glossing\"\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/forest-plot-es-1.png){width=2100}\n:::\n:::\n\n\n### 効果量の変換\n\nCohen's d から相関係数 $r$ への変換は、次の式で表せます。\n\n$$\nr = \\frac{d}{\\sqrt{d^2 + a}}\n$$\n\nここで $a = \\frac{(n_1 + n_2)^2}{n_1 n_2}$ です。メタ分析のように研究間で指標をそろえたいときには、こうした変換式が役立ちます。研究統合では Hedges g を報告しておくと再利用しやすくなります。\n\n## 「有意差がない」と「等価である」は違う\n\n通常の有意差検定では、帰無仮説は「差が 0」です。したがって、`p > .05` だったときに言えるのは、**帰無仮説を棄却できなかった**ということだけです。ここで「帰無仮説を採択した」「差がないことが証明された」とまでは言えません。\n\nもし本当に主張したいことが「条件間に意味のある差はない」であれば、通常の t 検定ではなく **等価性検定**（equivalence testing）を使う必要があります [@lakens2018equiv]。\n\n等価性検定では、発想が逆になります。\n\n- 通常の有意差検定: 「差は 0」を出発点にして、それを棄却できるかを調べる。\n- 等価性検定: 「差は無視できるほど小さくはない」を出発点にして、それを棄却できるかを調べる。\n\n実務では、まず「どの程度までの差なら実質的に同じとみなすか」を **等価性境界**（equivalence bounds, SESOI: smallest effect size of interest）として事前に決めます。たとえば 15 点満点の再生テストなら、「平均差が 1 点未満なら実務上は同じとみなす」という境界を置くことが考えられます。\n\nTOST（two one-sided tests）では、90% 信頼区間がこの等価性境界の内側に完全に収まれば、「実質的に等価」と判断できます。次の図は、その考え方を概念的に示したものです。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequiv_cases <- tibble(\n  Scenario = factor(\n    c(\"Statistically significant\", \"Inconclusive\", \"Practically equivalent\"),\n    levels = rev(c(\"Statistically significant\", \"Inconclusive\", \"Practically equivalent\"))\n  ),\n  Estimate = c(1.6, 0.2, 0.1),\n  CI_low = c(0.9, -0.7, -0.45),\n  CI_high = c(2.3, 1.1, 0.55)\n)\n\nggplot(equiv_cases, aes(x = Estimate, y = Scenario)) +\n  geom_vline(xintercept = c(-1, 0, 1), linetype = c(\"dashed\", \"solid\", \"dashed\"),\n             color = c(\"firebrick\", \"grey40\", \"firebrick\")) +\n  geom_segment(aes(x = CI_low, xend = CI_high, yend = Scenario), linewidth = 1) +\n  geom_point(size = 3, color = \"steelblue\") +\n  annotate(\"text\", x = -1, y = 3.35, label = \"-Δ\", color = \"firebrick\", vjust = 0) +\n  annotate(\"text\", x = 1, y = 3.35, label = \"+Δ\", color = \"firebrick\", vjust = 0) +\n  labs(\n    x = \"Mean difference with 90% CI\",\n    y = \"\",\n    title = \"How equivalence testing works\",\n    subtitle = \"If the 90% CI falls entirely inside [-Δ, +Δ], the groups are practically equivalent\"\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/equivalence-visual-1.png){width=2400}\n:::\n:::\n\n\nこの図の読み方は次のとおりです。\n\n- **有意差あり**: 信頼区間が 0 から十分離れており、境界の外側にある。\n- **結論保留**: 0 をまたいでいて、なおかつ等価性境界にも収まっていない。差があるとも、十分小さいとも言えない。\n- **実質的に等価**: 90% 信頼区間が等価性境界の内側に完全に収まっている。差があっても、事前に決めた基準より小さいといえる。\n\n要するに、**通常の t 検定で p > .05 だったからといって「差がない」とは言えません**。その主張をしたいなら、事前に「どれくらい小さければ同じとみなすか」を定め、等価性検定を別途行う必要があります。\n\n## チュートリアル論文からの実務的なまとめ\n\nこの章で採用している方針は、近年のチュートリアル論文の勧めと整合するように組んでいます。\n\n1. **p 値だけで終わらせず、効果量と信頼区間を必ず見る**。Lakens の実践的レビューや Cumming の “new statistics” は、この点を強く勧めています [@lakens2013; @cumming2014]。\n2. **独立 2 群比較では Welch を標準とする**。Student の t 検定は等分散が強く妥当なときに限れば使えますが、実務上は Welch を主に使う方が安全です [@delacre2017]。\n3. **p > .05 を「差がない」と読み替えない**。その主張には、等価性境界を事前に定めた等価性検定が必要です [@lakens2018equiv]。\n4. **検定力は事後より事前に使う**。観測後の “observed power” より、計画段階での a priori power analysis の方が研究設計に役立ちます [@hoenig2001]。\n\nこの 4 点を理解しておくと、t 検定を単なる「p 値を出す手順」としてではなく、推定・不確実性・実質的重要性を含めた分析の入口として理解しやすくなります。\n\n## サンプルサイズと検定力分析\n\n研究計画の段階では、期待する効果量に対して何人必要かを見積もる必要があります。R の公式ドキュメントにある `power.t.test()` は、平均値差 `delta` と標準偏差 `sd` を使って検定力計算を行います [@rstatspowerttest]。ここでは標準化効果量 $d$ を使いたいので、`sd = 1` と置き、`delta = d` として扱います。\n\n先ほど見たように、サンプルサイズが大きいほど信頼区間は狭くなります。検定力分析は、その同じ事実を「差を検出できる確率」という観点から見直したものです。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_from_d <- function(d, n = NULL, power = NULL, sig.level = 0.05,\n                         type = \"two.sample\", alternative = \"two.sided\") {\n  stats::power.t.test(\n    n = n,\n    delta = d,\n    sd = 1,\n    sig.level = sig.level,\n    power = power,\n    type = type,\n    alternative = alternative\n  )\n}\n```\n:::\n\n\n事前の計画には有用ですが、観測された効果量をそのまま代入した「事後検定力」は新しい情報をほとんど増やしません [@hoenig2001]。そのため、ここでは a priori の検定力分析に絞ります。\n\nここも一文で言うと、**研究を始める前に「何人いれば差を見つけやすいか」を決めるのが検定力分析**です。\n\n### 代表的な事前検定力分析\n\n::: panel-tabset\n#### 必要サンプルサイズの計算\n\n中程度の効果量 ($d = 0.5$) を 80% の検出力で検出するには、各群に何名必要かを計算します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_from_d(\n  d = 0.5,\n  power = 0.80,\n  type = \"two.sample\",\n  alternative = \"two.sided\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 63.76576\n          delta = 0.5\n             sd = 1\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n#### 効果量ごとの必要サンプルサイズ\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_tbl <- tibble(\n  Effect_Size = c(\"Small\", \"Medium\", \"Large\"),\n  d = c(0.2, 0.5, 0.8),\n  n_for_80 = c(\n    ceiling(power_from_d(d = 0.2, power = 0.80)$n),\n    ceiling(power_from_d(d = 0.5, power = 0.80)$n),\n    ceiling(power_from_d(d = 0.8, power = 0.80)$n)\n  ),\n  n_for_90 = c(\n    ceiling(power_from_d(d = 0.2, power = 0.90)$n),\n    ceiling(power_from_d(d = 0.5, power = 0.90)$n),\n    ceiling(power_from_d(d = 0.8, power = 0.90)$n)\n  ),\n  power_n50 = c(\n    power_from_d(n = 50, d = 0.2)$power,\n    power_from_d(n = 50, d = 0.5)$power,\n    power_from_d(n = 50, d = 0.8)$power\n  )\n) |>\n  mutate(\n    power_n50 = scales::percent(power_n50, accuracy = 0.1)\n  )\n\nknitr::kable(\n  power_tbl,\n  caption = \"効果量別の必要サンプルサイズと n = 50 の検定力\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: 効果量別の必要サンプルサイズと n = 50 の検定力\n\n|Effect_Size |   d| n_for_80| n_for_90|power_n50 |\n|:-----------|---:|--------:|--------:|:---------|\n|Small       | 0.2|      394|      527|16.6%     |\n|Medium      | 0.5|       64|       86|69.7%     |\n|Large       | 0.8|       26|       34|97.7%     |\n\n\n:::\n:::\n\n\n中程度の効果量 ($d = 0.5$) を 80% の検出力で捉えたいなら、各群におよそ 64 名必要です。\n\n#### 検定力カーブ\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_range <- seq(10, 200, by = 5)\nd_values <- c(0.2, 0.5, 0.8, 1.2)\n\npower_data <- tidyr::expand_grid(n = n_range, d = d_values) |>\n  mutate(\n    power = purrr::map2_dbl(n, d, \\(n, d) power_from_d(n = n, d = d)$power),\n    d_label = factor(\n      d,\n      levels = d_values,\n      labels = c(\n        \"d = 0.2 (Small)\",\n        \"d = 0.5 (Medium)\",\n        \"d = 0.8 (Large)\",\n        \"d = 1.2 (Very large)\"\n      )\n    )\n  )\n\nggplot(power_data, aes(x = n, y = power, color = d_label)) +\n  geom_line(linewidth = 1) +\n  geom_hline(yintercept = 0.8, linetype = \"dashed\", color = \"grey50\") +\n  geom_vline(xintercept = 50, linetype = \"dotted\", color = \"grey50\") +\n  annotate(\"text\", x = 195, y = 0.82, label = \"Power = 0.80\", size = 3, vjust = -0.5) +\n  annotate(\"text\", x = 52, y = 0.05, label = \"n = 50\", size = 3, hjust = -0.1) +\n  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +\n  labs(\n    x = \"Sample size (per group)\",\n    y = \"Power\",\n    color = \"Effect size\",\n    title = \"Power Curve by Effect Size\",\n    subtitle = \"Two-sample t-test, alpha = 0.05, two-sided\"\n  )\n```\n\n::: {.cell-output-display}\n![](1_T検定と効果量_files/figure-html/power-curve-1.png){width=2400}\n:::\n:::\n\n:::\n\n## 報告テンプレート（英語教育研究向け）\n\nt 検定の結果を論文に報告する際のテンプレートを以下に示します。\n\n### 方法セクション\n\n> Prior to analysis, normality was assessed using Shapiro-Wilk tests and QQ plots for each group. Homogeneity of variance was examined using Levene's test, but the main analysis used Welch's two-sample t-test because it does not require equal variances. Effect sizes were reported as Cohen's d with 95% confidence intervals. Sample size planning was based on an a priori power analysis conducted in R.\n\n### 結果セクション\n\n> The Writing group (*M* = X.XX, *SD* = X.XX) scored significantly higher than the Glossing group (*M* = X.XX, *SD* = X.XX) on the immediate recall test, Welch's *t*(XX.XX) = X.XX, *p* < .001, 95% CI [X.XX, X.XX]. The standardized mean difference was large, Cohen's *d* = X.XX, 95% CI [X.XX, X.XX].\n\n### 3 文テンプレート\n\n1. 統計量の報告: \"A Welch two-sample t-test revealed a significant difference between the Writing and Glossing conditions, *t*(df) = X.XX, *p* < .001, 95% CI [X.XX, X.XX].\"\n2. 効果量の報告: \"The effect size was large, Cohen's *d* = X.XX, 95% CI [X.XX, X.XX].\"\n3. 実質的解釈: \"This finding suggests that sentence-writing tasks promote deeper vocabulary processing than glossed reading.\"\n\n### 報告チェックリスト\n\n| Level | Report items | Typical use |\n|---|---|---|\n| Minimal | t 値, df, p 値, 群平均, 効果量 | 短報, 学会発表 |\n| Recommended | + 平均値差の 95% CI, 効果量の 95% CI, 前提確認の要約 | 通常の論文 |\n| Detailed | + 検定力分析, ノンパラメトリック比較, 分布図, 代替指標 | 事前登録研究, 再現研究 |\n\n## トラブルシューティング\n\n### p 値は有意だが効果量が小さい\n\nサンプルサイズが大きいと、実質的に小さな差でも p 値は小さくなります。p 値だけで結論を書かず、効果量とその信頼区間を併記してください。\n\n### p 値が有意でないので「差がない」と言ってしまう\n\n`p > .05` は「差がないことの証明」ではなく、「差があるとは言い切れなかった」という意味です。もし「条件間に意味のある差はない」と主張したいなら、通常の t 検定ではなく、等価性境界を事前に定めた等価性検定を使ってください。\n\n### 対応ありと対応なしを混同した\n\n同一参加者の前後比較に独立 2 群の t 検定を使うと、標準誤差の扱いが崩れます。`t.test(..., paired = TRUE)` や `cohens_d(..., paired = TRUE)` を使うべき場面かどうかを、参加者 ID の構造で確認してください。\n\n### 効果量や t 値の符号が逆に見える\n\n群の並び順が曖昧だと、符号の解釈がぶれます。本章では `Writing - Glossing` が正になるように水準順と `reference` を明示しました。報告時にも、どちらを基準に差をとったかを書き添えると安全です。\n\n### 同じデータに複数の t 検定をかけてしまった\n\n比較が複数あるなら、ANOVA や混合モデルで一度に扱う方が自然です。やむを得ず複数の t 検定を行う場合は、Holm 法や Bonferroni 補正を検討してください。\n\n## 参考文献\n\n::: {#refs}\n:::\n\n## セッション情報\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.1 (2025-06-13 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=Japanese_Japan.utf8  LC_CTYPE=Japanese_Japan.utf8   \n[3] LC_MONETARY=Japanese_Japan.utf8 LC_NUMERIC=C                   \n[5] LC_TIME=Japanese_Japan.utf8    \n\ntime zone: Etc/GMT-9\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] brunnermunzel_2.0 pwr_1.3-0         compute.es_0.2-6  car_3.1-5        \n [5] carData_3.0-6     effectsize_1.0.2  DT_0.34.0         gt_1.3.0         \n [9] lubridate_1.9.5   forcats_1.0.1     stringr_1.6.0     dplyr_1.2.0      \n[13] purrr_1.2.1       readr_2.2.0       tidyr_1.3.2       tibble_3.3.1     \n[17] ggplot2_4.0.2     tidyverse_2.0.0  \n\nloaded via a namespace (and not attached):\n [1] gtable_0.3.6       xfun_0.57          bayestestR_0.17.0  htmlwidgets_1.6.4 \n [5] insight_1.4.6      lattice_0.22-9     tzdb_0.5.0         vctrs_0.7.2       \n [9] tools_4.5.1        generics_0.1.4     datawizard_1.3.0   sandwich_3.1-1    \n[13] pacman_0.5.1       pkgconfig_2.0.3    Matrix_1.7-5       RColorBrewer_1.1-3\n[17] S7_0.2.1           lifecycle_1.0.5    compiler_4.5.1     farver_2.1.2      \n[21] textshaping_1.0.5  codetools_0.2-20   htmltools_0.5.9    yaml_2.3.12       \n[25] Formula_1.2-5      pillar_1.11.1      MASS_7.3-65        abind_1.4-8       \n[29] multcomp_1.4-30    nlme_3.1-168       tidyselect_1.2.1   digest_0.6.39     \n[33] mvtnorm_1.3-6      stringi_1.8.7      labeling_0.4.3     splines_4.5.1     \n[37] fastmap_1.2.0      grid_4.5.1         cli_3.6.5          magrittr_2.0.4    \n[41] survival_3.8-6     TH.data_1.1-5      withr_3.0.2        scales_1.4.0      \n[45] estimability_1.5.1 timechange_0.4.0   rmarkdown_2.31     emmeans_2.0.2     \n[49] otel_0.2.0         ragg_1.5.2         zoo_1.8-15         hms_1.1.4         \n[53] coda_0.19-4.1      evaluate_1.0.5     knitr_1.51         parameters_0.28.3 \n[57] mgcv_1.9-4         rlang_1.1.7        xtable_1.8-8       glue_1.8.0        \n[61] xml2_1.5.2         jsonlite_2.0.0     R6_2.6.1           systemfonts_1.3.2 \n[65] fs_2.0.1          \n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}